### DISCUSSION TITLE
AWS Skill Builder CDK Primer: TypeScript compile error TS2345 in sample code

### DISCUSSION THREAD

**Discussion by owenblacker** [aws/aws-cdk#20043] [Q&A]
### Describe the bug

Following the instructions in the [AWS CDK Demonstration code-along](https://explore.skillbuilder.aws/learn/course/1475/play/4999/aws-cloud-development-kit-primer;lp=85) in AWS Skill Builder and the first time I'm asked to `cdk synth` I get a compilation error, unlike the demonstration video.

### Expected Behavior

I expected the `cdk synth` to execute correctly, outputting a non-error response that ends
```yaml
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```
like on-screen.

### Current Behavior

I get an error response, with the error occurring in one of the files I have not changed. (The instructions have only asked me to change the file `lib/cdk_primer-stack.ts` so far; I have not edited `bin/cdk-primer.ts`.)
```
/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/cdk-primer.ts:7:20 - error TS2345: Argument of type 'App' is not assignable to parameter of type 'Construct'.
  Type 'App' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesize, validate, and 2 more.

7 new CdkPrimerStack(app, 'CdkPrimerStack', {
                     ~~~

    at createTSError (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Subprocess exited with error 1
```

### Reproduction Steps

Following the instructions in the video, I have done the following:

1. On a computer where I had newly installed the CDK with `sudo npm i -g aws-cdk`
2. Open VS Code
3. Using the terminal, create and enter an empty folder (in my case `/Users/owen.blacker/Projects/other/cdk-primer/`)
4. Run `cdk init --language typescript`
5. Install modules: `npm i @aws-cdk/aws-ec2 @aws-cdk/aws-ecs @aws-cdk/aws-ecs-patterns`
6. Edit the file `lib/cdk_primer-stack.ts` to contain the TypeScript as below
7. Run `cdk synth`

The contents of `lib/cdk_primer-stack.ts` once edited are:

```typescript
import * as cdk from '@aws-cdk/core';
import * as ec2 from "@aws-cdk/aws-ec2";
import * as ecs from "@aws-cdk/aws-ecs";
import * as ecs_patterns from "@aws-cdk/aws-ecs-patterns";

export class CdkPrimerStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "MyVpc", {maxAzs: 2});
    const cluster = new ecs.Cluster(this, "MyCluster", {vpc: vpc});
    new ecs_patterns.ApplicationLoadBalancedFargateService(this, "MyFargateService", {
      cluster: cluster,
      taskImageOptions: { image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample") },
      publicLoadBalancer: true
    });
  }
}
```
Other than the video having an extra tab at the start of line 12 (`new ecs_patterns.ApplicationLoadBalancedFargateService(...)`) and an extra linebreak after that `new` statement, this is identical to the code on-screen.

### CDK CLI Version

2.21.0 (build 3f74a81)

### Node.js Version

v16.14.2

### OS

MacOS Monterey version 12.3.1 (21E258)

### Language

Typescript

### Language Version

TypeScript 3.9.10

**Comment by peterwoodworth** [comment]
Migrating this to a discussion @owenblacker 🙂

**Comment by peterwoodworth** [comment]
Edit: Apps extend Construct, so you can use construct here. should've known that

We don't have any ownership over the skill builder courses as far as I'm aware. So, I will suggest looking at our official documentation and guides instead 🙂 
Check out the [CDK Workshop](https://cdkworkshop.com/) to walk through setting up an app, building tests, and even a pipeline in any of our supported languages
And be sure to check out our [developer guide](https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html) as well.

Let me know if you have any more questions or concerns I can help you with!

**Reply by owenblacker** [reply]
Making that change gives me a slightly different error message:
```
/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/cdk-primer.ts:7:20 - error TS2345: Argument of type 'import("/Users/owen.blacker/Projects/other/cdk-primer/node_modules/aws-cdk-lib/core/lib/app").App' is not assignable to parameter of type 'import("/Users/owen.blacker/Projects/other/cdk-primer/node_modules/@aws-cdk/core/lib/app").App'.
  Type 'App' is missing the following properties from type 'App': onValidate, onPrepare, onSynthesize, validate, and 2 more.

7 new CdkPrimerStack(app, 'CdkPrimerStack', {
                     ~~~

    at createTSError (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
****************************************************
*** Newer version of CDK is available [2.21.1]   ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

Subprocess exited with error 1
```

(And upgrading to CDK 2.21.1 doesn't make a difference here.)

If I `import * as lib from "aws-cdk-lib/core";` and change line 8 to `constructor(scope: lib.App, id: string, props?: cdk.StackProps)` to match the module it seems to be comparing with here, then intellisense warns me on line 9 that `super(score, id, props);` that

> Argument of type 'App' is not assignable to parameter of type 'Construct'.
>  Type 'App' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesizets(2345)

which makes sense.

Either way, there's definitely an error in the sample code in the video. But the video is the thing I need to complete in the AWS Certification process. Do you know where I should report the error to?

![AWS CDK Primer video screenshot](https://user-images.githubusercontent.com/376642/165052293-169ffe41-74ce-4314-8f9d-ee74ded69166.png)

**Reply by owenblacker** [reply]
Also, having just tried, if I skip step 6, and just run with the default content of that TypeScript file (which also defines `scope` as type `Construct`, as below), then I get a valid output.

Default contents of `lib/cdk-primer2-stack.ts`:
```typescript
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
// import * as sqs from 'aws-cdk-lib/aws-sqs';

export class CdkPrimer2Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here

    // example resource
    // const queue = new sqs.Queue(this, 'CdkPrimer2Queue', {
    //   visibilityTimeout: cdk.Duration.seconds(300)
    // });
  }
}
```

Output of `cdk synth` (with the base64‘d `Analytics` value shortened):
```yaml
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/z...DNZAAAA
    Metadata:
      aws:cdk:path: CdkPrimer2Stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```
