### DISCUSSION TITLE
CDK Associate OIDC identity provider

### DISCUSSION THREAD

**Discussion by dborysenko** [aws/aws-cdk#20277] [Q&A] [answered]
Hello,
I am trying to get an idea how to Associate OIDC identity provider with EKS cluster built using CDK. Is it supported? If so, could you please share hight level example?

eksctl example:
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: your-region-code

identityProviders:
  - name: my-provider
    type: oidc
    issuerUrl: https://example.com
    clientId: kubernetes
    usernameClaim: email
    usernamePrefix: my-username-prefix
    groupsClaim: my-claim
    groupsPrefix: my-groups-prefix
    requiredClaims:
      string: string
    tags:
      env: dev
```
Console example:
<img width="1436" alt="Screen Shot 2022-05-10 at 3 01 16 PM" src="https://user-images.githubusercontent.com/14313734/167713318-e7289344-1cfb-4bb9-8101-c06a8991c987.png">
