### DISCUSSION TITLE
How to get CDK version used to deploy a stack?

### DISCUSSION THREAD

**Discussion by pmezard** [aws/aws-cdk#20591] [Q&A] [answered]
Hello,

I have received an AWS notification telling me:

> You are receiving this notification because you currently have at least one CloudFormation Stack deployed using version 1 of the AWS Cloud Development Kit (CDK).

which surprised me, I thought all the stacks were migrated to 2.x already. Unfortunately, it does not tell me which ones are still on version 1, or any way to get them.

How can I find the stacks still deployed with version 1?

I could not find anything relevant in AWS console or playing with cdk cli.

Thank!

**Comment by pepdekpd** [comment]
Indeed, am having the same question. In our cloudformation templates I find something like this:
```
"CDKMetadata": {
   "Type": "AWS::CDK::Metadata",
   "Properties": {
    "Analytics": "**v2**:deflate64:< --cut away some hashes here -- > "
   },

``` 
In the [documentation](https://docs.aws.amazon.com/cdk/v2/guide/cli.html) there is written about the analytics property:
By default, the AWS CDK reports the use of constructs in the following NPM modules that are used in the stack:

AWS CDK core module
AWS Construct Library modules
AWS Solutions Constructs module
AWS Render Farm Deployment Kit module

And indeed :
```
echo "H4sIAAAAAAAA/1WQwQ6CMAyGn8X7mIpRz+rBiwcD3k0dlVTGRraCB7J3d4hGPLV//69N21SmW7mYwdMnqqgSTTfZ5wyqEoe7OYODGhmdyNDb1ikUEbz2qMEzKW2huIEGo8iUXSr7XdNoUsBkzSl6+7cXu+OoPz3lyDOaD/PNJ/4FXIl8dLZtBmQig4ijmO4DiDUYKNHJ/vCrDfxEBhG7GNeruGeGyrpiAMYsRw5hlOOdQRhboHz4ebfcyOU6vujhiRLXGqYaZTbGF1Gm95I+AQAA" | base64 -di | zcat
2.27.0!aws-cdk-lib.{Stack,CfnParameter,Resource,aws_{elasticloadbalancingv2.{ApplicationLoadBalancer,CfnLoadBalancer,ApplicationListener,CfnListener,ApplicationTargetGroup,CfnTargetGroup},certificatemanager.{Certificate,CfnCertificate},route53.{ARecord,CfnRecordSet}},CfnResource},node.js/v16.15.0!jsii-runtime.Runtime
````

In the [cdk workshop](https://cdkworkshop.com/20-typescript/20-create-project/400-synth.html) there is CDKMetadata of an older version:

  CDKMetadata:
```
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.21.1,@aws-cdk/aws-cloudwatch=1.21.1,@aws-cdk/aws-iam=1.21.1,@aws-cdk/aws-kms=1.21.1,@aws-cdk/aws-sns=1.21.1,@aws-cdk/aws-sns-subscriptions=1.21.1,@aws-cdk/aws-sqs=1.21.1,@aws-cdk/core=1.21.1,@aws-cdk/cx-api=1.21.1,@aws-cdk/region-info=1.21.1,jsii-runtime=node.js/v13.6.0
    Condition: CDKMetadataAvailable
```
Apparently in CDKv2 there is no Modules: property anymore.

So based on the assumption that version-reporting was enabled would it work to retreive al cfn templates and check if there is CDKMetadata.Modules property to determine a CDK v1 cloudformation stack?
