### DISCUSSION TITLE
having  index error while creating Vpc

### DISCUSSION THREAD

**Discussion by rsarili** [aws/aws-cdk#22827] [Q&A]
For this basic vpc definition below I got following error,

```
    const vpc = new ec2.Vpc(this, 'my-cdk-vpc', {
      cidr: '10.0.0.0/16',
    });
```

09:40:46 | CREATE_FAILED        | AWS::EC2::Subnet                      | my-cdk-vpc/PublicSubnet2/Subnet
Template error: Fn::Select  cannot select nonexistent value at index 1.
This is the part auto generated in cloudformation template
```
  mycdkvpcPublicSubnet2Subnet33F973F6:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: mycdkvpc037DA4AF
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
```

It seems error related to resources will be created by default. I just want to create a vpc without any explicit configuration(default ones are fine). Do you have any idea how can I achieve that? cdk version 2.50.0
