### DISCUSSION TITLE
KMS: Passing in `admins` when creating key allows actions = kms:* for account root

### DISCUSSION THREAD

**Discussion by ecs-jnguyen** [aws/aws-cdk#24624] [General]
### Describe the bug

When I am passing in the `admins` parameter to the kms key, I still see the default key policy that allows `Action: kms:*` for the account root.

### Expected Behavior

I expect for there to only be 1 statement that only allows my specified role (`TheRole`) to have access to the kms key

```yaml
Resources:
  TheKeyName5734F6E4:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action:
              - kms:CancelKeyDeletion
              - kms:Create*
              - kms:Delete*
              - kms:Describe*
              - kms:Disable*
              - kms:Enable*
              - kms:Get*
              - kms:List*
              - kms:Put*
              - kms:Revoke*
              - kms:ScheduleKeyDeletion
              - kms:TagResource
              - kms:UntagResource
              - kms:Update*
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::123456789012:role/TheRole
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: DebugCdkStack/TheKeyName/Resource
```

### Current Behavior

Currently this is the cloudformation template that is generated. You can see the first statement allows `kms:*` for the account root. The second admin policy is redundant because the first one allows everything for the root.

```yaml
Resources:
  TheKeyName5734F6E4:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
          - Action:
              - kms:CancelKeyDeletion
              - kms:Create*
              - kms:Delete*
              - kms:Describe*
              - kms:Disable*
              - kms:Enable*
              - kms:Get*
              - kms:List*
              - kms:Put*
              - kms:Revoke*
              - kms:ScheduleKeyDeletion
              - kms:TagResource
              - kms:UntagResource
              - kms:Update*
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::123456789012:role/TheRole
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: DebugCdkStack/TheKeyName/Resource
```

### Reproduction Steps

```python
        role = ArnPrincipal("arn:aws:iam::123456789012:role/TheRole")
        aws_kms.Key(
            self, id="TheKeyName", admins=[role]
        )
```

### Possible Solution

When we specify `admins` during the kms key creation we should remove the default policy.

### CDK CLI Version

2.67.0

### Node.js Version

v19.1.0

### OS

mac

### Language

Python

### Language Version

python (3.10)

### Other information

Another thing I noticed is that if I use `ArnPrincipal("my role arn")` it add "my role arn" into the key policy. However if I use `aws_iam.Role.from_role_name(..., "my role name")`, it will create an `AWS::IAM::Policy` and associate it to the role. I wasn't sure if this behavior should have its own issue or not.
