### DISCUSSION TITLE
how to parameterize IAM resources in AWS CDK

### DISCUSSION THREAD

**Discussion by jhansisarva1** [aws/aws-cdk#24831] [Q&A]
I am creating separate policies, I wanted to parameterize the resources we are defining in the policy statements so that when I do cdk synth it has to look something like below especially Resource section
   ```
 Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sns:ListSubscriptionsByTopic
              - sns:ListTagsForResource
            Effect: Allow
            Resource: 
            - !Sub 'arn:aws:sns:*:${AWS::AccountId}:${ResourcePrefix}'
```

> The issue is when I am trying to parameterize in the json especially for the Resource section to have the  - !Sub 'arn:aws:sns:*:${AWS::AccountId}:${ResourcePrefix}' I am not able to define Fn::Sub or any other way.Look at my json file below.

```
{
    "Version": "2012-10-17",    
    "Parameters": {
        "ResourcePrefix":{
            "Type" : "String",
            "Description" : "Environment Variables"
        }
    },
    "Statement": [
        {
            "Action": [
                "sns:ListTagsForResource",
                "sns:ListSubscriptionsByTopic"
            ],
            "Resource":"arn:aws:sns:*:${AWS::AccountId}:${ResourcePrefix}",
            "Effect": "Allow",
            "Sid": "testsid"
        },
```
