### DISCUSSION TITLE
Where is Amazon.CDK.AWS.Apigatewayv2.Alpha WebSocket AWS integration type?

### DISCUSSION THREAD

**Discussion by JobaDiniz** [aws/aws-cdk#27073] [Q&A]
**UPDATE** to better explain what I'm trying to accomplish

This is my CDK code:
```csharp
var api = new WebSocketApi(this, $"{nameof(BrokerRobotStack)}Api", new WebSocketApiProps
{
    RouteSelectionExpression = "$request.body.action",
    DefaultRouteOptions = new WebSocketRouteOptions 
    { 
        Integration = //TODO: which class to instantiate here to create => IntegrationType: AWS
    }
});
```

Which class do I instantiate in the `Integration`  property of `WebSocketRouteOptions` to create a `AWS` [IntegrationType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationtype)? Look at the documentation

>**AWS**: for integrating the route or method request with an AWS service action, [...]. With any other AWS service action, this is known as AWS integration. **Supported only for WebSocket APIs**.

 Like the following CloudFormation yaml:
```yaml
ApiAuthenticateRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BrokerRobotSocketApi
      IntegrationType: AWS
      IntegrationMethod: POST
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:states:action/StartExecution"
     ...
```

**Comment by peterwoodworth** [comment]
@github-actions proposed answer You need to install alpha modules separately, see the docs [here](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-csharp.html#csharp-managemodules) for more info. Note that there are multiple alpha modules for ApiGatewayV2, so you can find [`WebSocketLambdaIntegration` in the `ApiGatewayV2Integrations` module](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.Apigatewayv2.Integrations.Alpha.WebSocketLambdaIntegration.html).

As for converting CloudFormation to CDK, if you want to do that explicitly you can drop to the L1 Cfn resources found [here](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.Apigatewayv2.html), since our L1 resources are identical to the CloudFormation ones. Or depending on your exact requirements, you could also use the [`cloudformation-include` module.](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.CloudFormation.Include.html)

**Reply by JobaDiniz** [reply]
I'm looking to rewrite using L2 L3 constructs.
The mentioned module is okay for lambda, but what about WebSocket AWS integration type? I didn't find that module/nuget

**Reply by peterwoodworth** [reply]
I'm not sure I understand your exact requirements, or what code you already have in place and where exactly you're getting stuck. Could you please go into some more detail regarding these things?

**Reply by JobaDiniz** [reply]
this is my CDK code:
```csharp
var api = new WebSocketApi(this, $"{nameof(BrokerRobotStack)}Api", new WebSocketApiProps
{
    RouteSelectionExpression = "$request.body.action",
    DefaultRouteOptions = new WebSocketRouteOptions 
    { 
        Integration = //TODO: which class to instantiate here to create => IntegrationType: AWS
    }
});
```

Which class do I instantiate in the `Integration`  property of `WebSocketRouteOptions` to create a `AWS` [IntegrationType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationtype)? Look at the documentation

>**AWS**: for integrating the route or method request with an AWS service action, [...]. With any other AWS service action, this is known as AWS integration. **Supported only for WebSocket APIs**.

 Like the following CloudFormation yaml:
```yaml
ApiAuthenticateRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BrokerRobotSocketApi
      IntegrationType: AWS
      IntegrationMethod: POST
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:states:action/StartExecution"
     ...
```
