### DISCUSSION TITLE
Create aws-auth ConfigMap in EKS Cluster as YAML, not JSON

### DISCUSSION THREAD

**Discussion by HarishMavila** [aws/aws-cdk#28006] [Q&A]
The following CDK Python code updates the `aws-auth` ConfigMap:

```python
from aws_cdk import aws_eks as eks, aws_iam as iam
cluster = eks.Cluster(...)

cluster.aws_auth.add_user_mapping(
  username='eks', groups='system:masters',
  user=iam.User.from_user_arn(self, 'eks',
    'arn:aws:iam::111122223333:user/eks')
)
```

After the above code has run, the `aws-auth` ConfigMap in the EKS cluster looks like this:

```yaml
spec:
  mapUsers: >-
    [{"username":"eks","groups":["system:masters"],"userarn":"arn:aws:iam::111122223333:user/eks"}]
```

Is there a way to get CDK to generate the `aws-auth` ConfigMap as YAML (below) instead of JSON (above)?

```yaml
spec:
  mapUsers:
  - username: eks
    groups: [system:masters]
    userarn: arn:aws:iam::111122223333:user/eks
```
