### DISCUSSION TITLE
Invoking an existing Lambda Function using AWSCustomResource

### DISCUSSION THREAD

**Discussion by houdinisparks** [aws/aws-cdk#28240] [Q&A] [answered]
I am trying to invoke an existing lambda function using AWSCustomResource with the code below:

```typescript
  const existingLambda = cdk.aws_lambda.Function.fromFunctionName(
    stack,
    `TriggerExistingLambda`,
    'existing-function-name'
  );
  return new cdk.custom_resources.AwsCustomResource(stack, 'TriggerExistingLambdaCustomResource', {
    policy: cdk.custom_resources.AwsCustomResourcePolicy.fromStatements([
      new cdk.aws_iam.PolicyStatement({
        actions: ['lambda:InvokeFunction'],
        effect: cdk.aws_iam.Effect.ALLOW,
        resources: [existingLambda.functionArn],
      }),
    ]),

   // I presume AWS will generate another lambda internall to execute the onCreate API call?
    onCreate: {
      service: 'Lambda',
      action: 'invoke',
      parameters: {
        FunctionName: existingLambda.functionName,
        InvocationType: 'RequestResponse',
        Payload: 'some-payload',
      },
      physicalResourceId: cdk.custom_resources.PhysicalResourceId.of(`${resourceName}LambdaPhysicalResourceId`),
    },
    installLatestAwsSdk: false,
  });
```

Here is the generated cloudformation manifest.yml 

```yaml
  LambdaTriggerSetupRDSIAMEE3AB6F1:
    Type: Custom::AWS
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
       Create: ....

  AWS679f53fac002430cb0da5b7982bd22872D164C4C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-020653668000-ap-southeast-1
        S3Key: d62cd506a0f4ef6a29d7a97e2a02d80bc8248142ce428543cfbf0d84b3c116a2.zip
      Role:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
          - Arn
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 900
    DependsOn:
      - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: Stack/AWS679f53fac002430cb0da5b7982bd2287/Resource
      aws:asset:path: asset.d62cd506a0f4ef6a29d7a97e2a02d80bc8248142ce428543cfbf0d84b3c116a2
      aws:asset:is-bundled: false
      aws:asset:property: Code
```

The error: For resource `AWS679f53fac002430cb0da5b7982bd22872D164C4C`, I am facing `Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.` for the lambda function that I presume will be internally generated by AWS when using `AWSCustomResource` to make the AWS API call to invoke the existing lambda.

and when I checked the S3 console, `S3Key: d62cd506a0f4ef6a29d7a97e2a02d80bc8248142ce428543cfbf0d84b3c116a2.zip` does not exist in the bucket. I thought `cdk bootstrap` should help me create the internal lambda but I guess im wrong.

Am I understanding AWSCustomResource wrongly? I presumed the CDK should handle the onCreate event handling to call the `lambda:Invoke` action for me.

fyi: I am also using AWS's `copilot`  cdk overrides for this.
