### DISCUSSION TITLE
AWS Lambda Authorizer returns BadRequestException

### DISCUSSION THREAD

**Discussion by pmigliore** [aws/aws-cdk#29077] [Q&A]
I'm using an AWS Lambda to authorize a GraphQL query, I want to use the authorization token to get the client information from Cognito, and use the sub in the user attributes to check if the user purchased a phone in my Record Table, but every time I call the method it returns `BadRequestException: Unknown error at buildRestApiServiceError`.

Schema:

    type Phone
      @model
      @auth(rules: [{ allow: owner }, { allow: custom, operations: [read] }]) {
      id: ID!
      title: String!
      description: AWSJSON!
      rating: Float
    }

AWS Lambda:

    exports.handler = async (event) => {
      const {
        authorizationToken,
        requestContext: { queryString },
      } = event;
    
      try {
        const cognitoClient = new CognitoIdentityProviderClient({});
        const cognitoInput = {
          AccessToken: authorizationToken,
        };
    
        const cognitoCommand = new GetUserCommand(cognitoInput);
        const user = await cognitoClient.send(cognitoCommand);
    
        const dynamoClient = new DynamoDBClient({});
        const dynamoInput = {
          Key: {
            id: {
              S: user.Username,
            },
          },
          TableName: "RecordTable",
        };
    
        const dynamoCommand = new GetItemCommand(dynamoInput);
        const response = await dynamoClient.send(dynamoCommand);
    
        let isPurchased = false;

        for (let index = 0; index < purchasedPhones.length; index++) {
          const phoneID = purchasedPhones[index];
    
          if (queryString.includes(phoneID)) {
            isPurchased = true;
            break;
          }
        }

    
        return {
          isAuthorized: isPurchased ,
          resolverContext: {
            userid: userId,
            info: user,
            more_info: response,
          },
          ttlOverride: 10,
        };
      } catch (error) {
        return error;
      }
    };

GraphQL method:

     const phone = await client.graphql<GraphQLQuery<GetPhoneQuery>>({
            query: getPhone,
            authMode: "lambda",
            authToken: "xxxxxxx...xxx",
            variables: {
              id,
            },
          });

Function overview:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  graphQlLambdaAuthorizer8c87c0ddbeta:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 25
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          ENV: beta
          REGION: us-east-2
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - arn:aws:lambda:us-east-2:580247275435:layer:LambdaInsightsExtension:45
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: >-
                arn:aws:lambda:us-east-2:062633224221:function:graphQlLambdaAuthorizer8c87c0dd-beta
            - Effect: Allow
              Action:
                - appsync:GraphQL
                - appsync:GetGraphqlApi
                - appsync:ListGraphqlApis
                - appsync:ListApiKeys
              Resource: '*'
            - Effect: Allow
              Action:
                - cognito-identity:Describe*
                - cognito-identity:Get*
                - cognito-identity:List*
                - cognito-idp:Describe*
                - cognito-idp:AdminGet*
                - cognito-idp:AdminList*
                - cognito-idp:List*
                - cognito-idp:Get*
                - cognito-sync:Describe*
                - cognito-sync:Get*
                - cognito-sync:List*
                - iam:ListOpenIdConnectProviders
                - iam:ListRoles
                - sns:ListPlatformApplications
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
              Resource:
                - '*'
            - Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:BatchGetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource:
                - arn:aws:dynamodb:us-east-2:062633224221:table/RecordTable
              Effect: Allow
              Sid: AllowDynamoDB
      SnapStart:
        ApplyOn: None
      Tags:
        user:Application: XXXXX
        user:Stack: beta
      Tracing: Active
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
```

I'm not quite sure what I'm missing here.
