### DISCUSSION TITLE
Debug a s3 deployment issue

### DISCUSSION THREAD

**Discussion by crivi30** [aws/aws-cdk#30765] [Q&A]
Hello everyone!

I'm new to CDK and I'm trying to store a file in S3 using CDK in Python. I've been stuck on this problem for a week and would appreciate some help from someone more experienced to find the issue. The code I'm using is as follows:

```
self.trusted_store_deployment = aws_s3_deployment.BucketDeployment(
    self, f"TrustedStoreDeployment{self.cnstrct_id}",
    destination_bucket=self.service_s3,
    destination_key_prefix=self.mtlsapi_truststoreprefix,
    sources=[aws_s3_deployment.Source.asset(str(self.mtlsapi_truststore_local_folder))],
    log_retention=aws_logs.RetentionDays.ONE_WEEK,
    prune=False
)
```

However, after deploying, the generated CloudFormation syntax for this CDK file creates the following:

yaml
```

TrustedStoreDeploymentIotDIYeucentral1CustomResource23D02C00:
  Type: Custom::CDKBucketDeployment
  Properties:
    ServiceToken:
      Fn::GetAtt:
        - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
        - Arn
    SourceBucketNames:
      - cdk-hnb659fds-assets-590183820794-eu-central-1
    SourceObjectKeys:
      - 0aab58b5231cf9517a894381a0a4d63b0ce5df6d8d6f102992ef0dc035b5ca9b.zip
    DestinationBucketName:
      Ref: IotDIYeucentral1ServiceBucket521E98CE
    DestinationBucketKeyPrefix: mtlstruststore
    Prune: false
  UpdateReplacePolicy: Delete
  DeletionPolicy: Delete
  Metadata:
    aws:cdk:path: IotDIYeucentral1/TrustedStoreDeploymentIotDIYeucentral1/CustomResource/Default
```

The issue I'm facing is that after deployment, I can't find the file 0aab58b5231cf9517a894381a0a4d63b0ce5df6d8d6f102992ef0dc035b5ca9b.zip in the source bucket cdk-hnb659fds-assets-590183820794-eu-central-1. Consequently, the destination bucket IotDIYeucentral1ServiceBucket521E98CE remains empty. I've verified the local directory path and everything seems correct. I've also checked the Lambda function logs responsible for copying the object from the CDK bucket to the destination bucket, but I haven't found any errors, only information about another .zip file that was copied correctly to its destination bucket.

Could someone please advise on additional steps I can take to debug this issue?
