### ISSUE TITLE
[cognito] can't add cognito trigger after UserPool.fromUserPoolId

### ISSUE THREAD

**Issue by Albert-Gao** [aws/aws-cdk#10002]
## version:
`"@aws-cdk/aws-cognito": "^1.60.0",`

## Code
```javascript
    const amplifyUserPool = cognito.UserPool.fromUserPoolId(
      this,
      "amplifyUserPool",
      "us-east-1_ABCDE"
    );

    console.log("addTrigger" in amplifyUserPool);
```

## Expect
`true`

## Receive
`false`

## Documentation
[Importing User Pools](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html#importing-user-pools)
[addTrigger](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPool.html#add-wbr-triggeroperation-fn-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span)

## More
The documentation indeed mentions:

> However, imported user pools have limited configurability. As a rule of thumb, none of the properties that is are part of the AWS::Cognito::UserPool CloudFormation resource can be configured.

But I am when I am using `serverless framework`, it works like a charm.
Just wonder any workarounds against this? I want to move my full serverless stack to CDK, it is such a beautiful tech.

- There is a stackoverflow question against this: https://stackoverflow.com/questions/61816264/add-lambda-trigger-to-imported-cognito-user-pool-with-aws-cdk

**Comment by NGL321** [comment]
Hey @Albert-Gao,

Unfortunately, at the moment, we are limited by Cloudformation's ability to utilize existing resources, and in the case of Cognito, we are unable to configure internal properties (including adding a trigger).
As far as I am aware, there is no workaround for this at the moment 😞. @nija-at do you have any information otherwise?

Please let me know if you have further questions!

😸 😷

**Comment by Albert-Gao** [comment]
Thanks, understood.

However, it is totally doable via serverless framework.

The below yaml can add a `postConfirmation` cognito trigger

```yaml
functions:
  postConfirmation:
    handler: dist/trigger/postConfirmation.handler
    events:
      - cognitoUserPool:
          pool: tcUserPool-${self:custom.stage}
          trigger: PostConfirmation
          existing: true
```

interesting here, how could they do that? 😳
