### ISSUE TITLE
[cloudformation-include] Resource used in GetAtt not found when using single quotes in template

### ISSUE THREAD

**Issue by fongie** [aws/aws-cdk#10177]
When the imported template uses single quotes like `!GetAtt 'MYID.Arn'` cdk synth fails with `Resource used in GetAtt expression with logical ID: ''MYID' not found` (note the double single quotes in the error message)

### Reproduction Steps

In my case:
```
NATIP:
        DependsOn: VPCGatewayAttachment
        Type: 'AWS::EC2::EIP'
        Properties:
            Domain: vpc

NATGateway:
        Type: 'AWS::EC2::NatGateway'
        Properties:
            AllocationId: !GetAtt 'NATIP.AllocationId'
            SubnetId: !Ref Subnet1
```

### What did you expect to happen?

I was trying to cdk synth having imported my (already working in and deployed) yaml template using this code in a new stack
```
    const templateFile = path.join(__dirname, '../templates/template.yml');
    const include = new CfnInclude(this, 'Template', {
      templateFile
    });
```

### What actually happened?

```
Resource used in GetAtt expression with logical ID: ''NATIP' not found
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.62.0 (build 8c2d7fc)
  - **Framework Version:** 1.62.0
  - **Node.js Version:**  v14.3.0
  - **OS               :** mac Mojave 10.14.6
  - **Language (Version):**  Typescript ~4.0.2

### Other

Judging from the error message it seems an extra ' is making its way into the resource name somehow.

--- 

This is :bug: Bug Report
