### ISSUE TITLE
[aws-greengrass] Missing property when CF is generated 

### ISSUE THREAD

**Issue by nicgoth** [aws/aws-cdk#10178]
When creating a Greengrass Device Definition in CDK:
```
       greengrass_device_def = greengrass.CfnDeviceDefinition(self, 'GreengrassDeviceDefinition,
            name="GreengrassDevices",
            initial_version={
                'devices': [{
                    'id': '1',
                    'certificateArn': cert_arn,
                    'thingArn': thing_arn,
                    'syncShadow': True
            }]
            }
        )
```

In the generated CF template the "ShadowSync" property is missing:
```
GreengrassDeviceDefinitiontestgroup:
    Type: AWS::Greengrass::DeviceDefinition
    Properties:
      Name: GreengrassDevices
      InitialVersion:
        Devices:
          - CertificateArn:
              Fn::GetAtt:
                - CertCustResource
                - certificateArn
            Id: "1"
            ThingArn: arn:aws:iot:us-east-1:856990477240:thing/test
```

### Environment

  - CLI Version : 2.0.5
  - Framework Version: 1.59.0
  - Language (Version) Python (3.7.7)

--- 

This is :bug: Bug Report
