### ISSUE TITLE
[aws-wafv2] Missing property when CF is generated (ExcludedRules)

### ISSUE THREAD

**Issue by carolinux** [aws/aws-cdk#10180]
The [ExcludedRules ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-excludedrule.html)property does not get generated by `cdk synth`.

## Steps to reproduce

 The python code:

```
from aws_cdk import core, aws_wafv2


class HelloCdkStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        web_acl = aws_wafv2.CfnWebACL(
            self,
            'WebACL',
            default_action={'allow': {}},
            rules=[{
                'name': 'AWS-AWSManagedRulesCommonRuleSet',
                'overrideAction': {'none': {}},
                'priority': 0,
                'statement': {
                    'managedRuleGroupStatement': {
                        'name': 'AWSManagedRulesCommonRuleSet',
                        'vendorName': 'AWS',
                        'ExcludedRules': [{"Name": "GenericRFI_BODY"}]}},
                'visibilityConfig': {
                    'cloudWatchMetricsEnabled': True,
                    'metricName': 'AWSManagedRulesCommonRuleSet',
                    'sampledRequestsEnabled': True}}],
            scope='CLOUDFRONT',
            visibility_config={
                'cloudWatchMetricsEnabled': True,
                'metricName': 'WAF',
                'sampledRequestsEnabled': True})`
```
The resulting CF template:
```
Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: WAF
        SampledRequestsEnabled: true
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          Priority: 0
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesCommonRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: true
```

### Environment

  - CLI Version: aws-cli/2.0.35 Python/3.7.3 Linux/5.4.0-45-generic botocore/2.0.0dev39
  - Framework Version: aws-cdk.aws-wafv2==1.62.0 , aws-cdk.core==1.62.0
  - Node.js Version: v10.19.0
  - OS :Ubuntu
  - Language (Version): Python (3.7.3)
--- 

This is :bug: Bug Report
