### ISSUE TITLE
[cloudfront] generates "Comment" automatically which can be too long.

### ISSUE THREAD

**Issue by laimonassutkus** [aws/aws-cdk#10211]
When creating a distribution with **Distribution** (**from aws_cdk.aws_cloudfront import Distribution**) an Origin access identity is being created with a **Comment** attribute which can be to long (in fact - for me it is too long and I can not deploy the distribution). I get the following error from CloudFormation: 

`The parameter Comment is too big. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidArgument; Request ID: 138149ac-0858-4ecb-abf7-17d90f671ce1)`

### Reproduction Steps

1. Create a stack.
2. Create another stack inside the stack.
3. Repeat for few times so the cdk would start generating ridiculously long names.
4. Create distribution.
5. `cdk deploy`

### What did you expect to happen?

Distribution created.

### What actually happened?

`The parameter Comment is too big. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidArgument; Request ID: 138149ac-0858-4ecb-abf7-17d90f671ce1)`

### Environment

  - **CLI Version      : aws-cli/1.18.49 Python/3.6.0 Windows/10 botocore/1.15.49**
  - **Framework Version: ?**
  - **Node.js Version: v12.16.2**
  - **OS               : Windows 10**
  - **Language (Version): Python3.6**

### Other

The cdk generates the following template (snippet):

```
BlaBlaContactCenterCloudFrontDistributionOrigin1S3OriginE9E0DBAE:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access identity for BlaBlaCoreMainStackBlaBlaContactCenterUiMainStackBlaBlaContactCenterUiCloudFrontStackBlaBlaContactCenterCloudFrontDistributionOrigin19B3E38BF
```

--- 

This is :bug: Bug Report
