### ISSUE TITLE
[aws-elasticloadbalancingv2] fromNetworkLoadBalancerAttributes is creating new NLB

### ISSUE THREAD

**Issue by xrl** [aws/aws-cdk#10323]
I want to reference an existing network load balancer and instead the script is trying to create a new network load balancer.

### Reproduction Steps

```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';
import * as cloudfront from '@aws-cdk/aws-cloudfront';
import * as origins from '@aws-cdk/aws-cloudfront-origins';

export class CloudformationCloudfrontStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = ec2.Vpc.fromLookup(this, 'vpc', {isDefault: false, vpcId: 'vpc-ffffffff'});
    // Create an application load balancer in a VPC. 'internetFacing' must be 'true'
    // for CloudFront to access the load balancer and use it as an origin.
    new elbv2.ApplicationLoadBalancer(this, 'LB', {
      vpc,
      internetFacing: true
    });

    const nginxLb = elbv2.NetworkLoadBalancer.fromNetworkLoadBalancerAttributes(this,'k3elb', {
      loadBalancerArn: "arn:aws:elasticloadbalancing:eu-central-1:123:loadbalancer/net/456/789",
      loadBalancerDnsName: "abc-def.elb.eu-central-1.amazonaws.com"
    });

    const defaultBehavior = { origin: new origins.LoadBalancerV2Origin(nginxLb, {}) };

    new cloudfront.Distribution(this, 'wildcard-mysite-com', {
      enabled: true,
      defaultBehavior
    });

  }
}
```

which synthesizes this:

```
% cdk synth
[[[ SNIP ]]]
Resources:
  LB8A12904C:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: "false"
      Scheme: internet-facing
      SecurityGroups:
        - Fn::GetAtt:
            - LBSecurityGroup8A41EA2B
            - GroupId
      Subnets: # these valid subnets, looked up from the existing NLB
        - subnet-1
        - subnet-2
        - subnet-3
      Type: application
    Metadata:
      aws:cdk:path: CloudformationCloudfrontStack/LB/Resource
[[[[ SNIP ]]]]
```

### What did you expect to happen?

I should have a NLB reference, not a new one.

### What actually happened?

The stack created a new NLB

### Environment

  - **CLI Version      1.62.0 (build 8c2d7fc):**
  - **Framework Version: 1.62.0**
  - **Node.js Version: v14.9.0**
  - **OS               :* OS X*
  - **Language (Version): tsc 4.0.2 ** 

### Other

--- 

This is :bug: Bug Report
