### ISSUE TITLE
[Events] How to associate a rule to a role 

### ISSUE THREAD

**Issue by furstenheim** [aws/aws-cdk#10590]
When using cfn an AWS:Events:Rule is defined as :

```
Properties:
  Description: ...
  EventPattern: ...
  RoleArn: ...
  Targets:
           -Id ...
           Arn: ...
          RoleArn: ...

```
However in cdk we have 

```
import * as events from '@aws-cdk/aws-events';

const someRule = new events.Rule(this, 'someRule', {
   description: ...
   evenPattern: ...
})
```

Neither roleArn nor targets are allowed. Targets is easy, we defined separately and then we do `someRule.addTarget...`. However, it is not clear how to link a role and an events rule, since role has no addRule.

Maybe I'm missing a way to do it, in that case maybe consider documenting it.

Thanks
