### ISSUE TITLE
[codebuild] Default IAM role created by codebuild does not add codebuild:BatchPutCodeCoverages

### ISSUE THREAD

**Issue by karthikns16** [aws/aws-cdk#10750]
### The Question
IAM role created by the codebuild.PipelineProject doesn't automatically add codebuild:BatchPutCodeCoverages while it does add the codebuild:BatchPutTestCases. Any reason why CodeCoverage was left out? 

https://github.com/aws/aws-cdk/blob/c58127bd1b7215468df0f2bd584fed1a344ac7a5/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L795

### Environment

  - **CDK CLI Version:** 1.66.0 (build 459488d)
  - **Module Version:** 1.66.0
  - **Node.js Version:** v12.16.1
  - **OS:**  OSX Catalina
  - **Language (Version):** Python 3.7.4

**Comment by skinny85** [comment]
Hey @karthikns16 ,

no particular reason, probably just the docs never mentioned `codebuild:BatchPutCodeCoverages`, and so we never added them.

Can you show me some docs that show when is `codebuild:BatchPutCodeCoverages` needed?

Thanks,
Adam

**Comment by markusl** [comment]
Including `codebuild:BatchPutCodeCoverages` by default would make sense in our use case as well. It is needed for example when the buildspec uploads code coverage reports in addition to the usual unit test results.

```yaml
reports:
  JUnitReports:
    files:
      - 'junit.xml'
    base-directory: '.'
  CoverageReports:
    files:
      - 'coverage/clover.xml'
    file-format: CloverXml
    base-directory: '.'
```

**Comment by karthikns16** [comment]
@skinny85 here is document that describes the need of the BatchPutCodeCoverages for publishing code coverage reports

https://docs.aws.amazon.com/codebuild/latest/userguide/test-permissions.html

Wondering if these kinds of changes can be contributed :)

**Comment by skinny85** [comment]
@karthikns16 absolutely! See here for details: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md 

I wonder whether there's more we need to do than just the `codebuild:BatchPutCodeCoverages` permission though to support code coverage reports - we only support the JUnit type today...

**Comment by karthikns16** [comment]
@skinny85 , I am not sure what you mean when you say we support Junit type today. I was working on a project yesterday and I was able to use cdk's codebuild.PipelineProject in combination with buildspec.yml similar to what @markusl  has pasted above and was able to publish a COBERTURAXML formatted coverage report to codebuild report group. Am I missing something?


example buildspec I used
```
version: 0.2
env:
  shell: /bin/bash

phases:
  install:
    commands:
      - pipeline/bin/setup.sh

  build:
    commands:
      - mkdir -p tests/output
      - python -m coverage run --omit=.env/*.* -m pytest tests/*.py -v --junit-xml=tests/output/test_report.xml
      - python -m coverage report
      - python -m coverage xml

reports:
  tests:
    files:
      - tests/output/test_report.xml
    file-format: JUNITXML
  coverage:
    files:
      - coverage.xml
    file-format: COBERTURAXML
```
