### ISSUE TITLE
[ec2] Issue when creating multiple addIngressRule in an imported SGR

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#10851]
When adding Ingress Rules in a Security Group imported from another Stack, only 1 Rule is created.

### Reproduction Steps
The code :
```
    const SecurityGroup = ec2.SecurityGroup.fromSecurityGroupId(this, 'SecurityGroup', SecurityGroupId);

    SecurityGroup.addIngressRule(ec2.Peer.ipv4(PrivateSubnet1Cidr), ec2.Port.tcp(5555), 'Allow Main access');
    SecurityGroup.addIngressRule(ec2.Peer.ipv4(PrivateSubnet2Cidr), ec2.Port.tcp(5555), 'Allow Main access');
    SecurityGroup.addIngressRule(ec2.Peer.ipv4(PrivateSubnet3Cidr), ec2.Port.tcp(5555), 'Allow Main access');
```
### What did you expect to happen?
I expect to have 3 Rules, 1 for each Subnets CIDRs.

### What actually happened?
Only the first Rule is created, not 3.
When I change the port, it's working and creating a new Rule.

### Environment

  - **CLI Version      :** 1.66.0
  - **Framework Version:** 6.14.8
  - **Node.js Version:** v12.15.0
  - **OS               :** Linux
  - **Language (Version):** TypeScript

### Other

A synth or the created Template show us indeed only 1 Rule : 
   ```
 Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: SsmParameterValuecdkglobalvpcSecretsManagerarnC96584B6F00A464EAD1953AFF4B05118Parameter
            - :SecretString:PrivateSubnet1Cidr::}}
      Description: Allow Main access
      FromPort: 5555
```

--- 

This is :bug: Bug Report
