### ISSUE TITLE
[Core] Fn.ConditionIf doesn't capitalise properties name.

### ISSUE THREAD

**Issue by pivstone** [aws/aws-cdk#10895]
When we put the nested resource properties in the Fn.ConditionIf, the output template doesn't capitalise those fields name.  For NodeJs, we can change the name to Capital one, but for Typescript, we can't do it. The type check force us to use lower case.

### Reproduction Steps

Here is the demo code
```javascript

const cdk = require('@aws-cdk/core');
const dynamodb = require('@aws-cdk/aws-dynamodb');
const YAML = require('yamljs');

class HelloCdkStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    new dynamodb.CfnTable(this, 'items', {
      keySchema: [
        {
          attributeName: 'itemId',
          keyType: dynamodb.AttributeType.STRING,
        },
      ],
      tableName: 'items',
      provisionedThroughput: {
        readCapacityUnits: 10,
        writeCapacityUnits: 10,
      },
      globalSecondaryIndexes: [
        cdk.Fn.conditionIf(
          'HasGlobalSecondaryIndex1',
          {
            IndexName: cdk.Fn.ref('IndexName'),
            KeySchema: [
              {
                AttributeName: cdk.Fn.ref('HashKeyName'),
                KeyType: 'HASH',
              },
            ],
            Projection: {
              ProjectionType: 'ALL',
            },
            ProvisionedThroughput: {
              readCapacityUnits: cdk.Fn.ref('readCapacityUnits'),
              writeCapacityUnits: cdk.Fn.ref('writeCapacityUnits'),
            },
          },
          cdk.Aws.NO_VALUE
        ),
      ],
    });
  }
}

const stackName = 'stack';
const app = new cdk.App();
new HelloCdkStack(app, stackName);
app.synth();
const { template } = app.synth().getStackByName(stackName);
console.log(YAML.stringify(template, 20, 2));

```

The output:
```yaml
Resources:
  items:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        -
          AttributeName: itemId
          KeyType: S
      GlobalSecondaryIndexes:
        -
          'Fn::If':
            - HasGlobalSecondaryIndex1
            -
              IndexName:
                Ref: IndexName
              KeySchema:
                -
                  AttributeName:
                    Ref: HashKeyName
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                readCapacityUnits:   // Here is problem
                  Ref: readCapacityUnits
                writeCapacityUnits:
                  Ref: writeCapacityUnits
            -
              Ref: 'AWS::NoValue'
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: items
```

### What did you expect to happen?

Capitalise the parameter name in the ConditionIf

### Environment

  - **CLI Version      :** 
  - **Framework Version:** 1.67.0
  - **Node.js Version:** v12.13.1
  - **OS               :** macOS
  - **Language (Version):** TypeScript 

### Other

--- 

This is :bug: Bug Report
