### ISSUE TITLE
[aws-ecs]  EcrSourceAction with ECR as a source does not trigger pipeline change when the source is updated

### ISSUE THREAD

**Issue by jpSimkins** [aws/aws-cdk#10901]
When creating a code pipeline and using `EcrSourceAction`, I would expect when the `latest` tag is updated, for this to update the pipeline that is using this as a source. This is how it works when I create this manually but I cannot get the CDK to do this.

I am thinking this is a bug because this is not what happens when I build the pipeline manually.

### Reproduction Steps

I have a pretty large construct to build our pipeline so I will only post the part I think is relevant to the issue.

This is how  I define the source action for the pipeline to use the Repository as a source:
```typescript
new EcrSourceAction({
  actionName: 'BaseImage',
  repository: this._props.projectSourceEcrRepo, // This is a Repository
  imageTag: 'latest',
  output: this._artifactProjectBaseECR,
}),
```

Whenever I update the ECR repo, this does not trigger the pipeline to update at all. Basically, adding this as a source is pointless as the entire purpose is to allow this to update the pipeline when this is changed. Otherwise, I can simple pull the image when the project code is update.

To give a better idea of what I am doing:

- I have 2 sources (ECR, and BitBucket)
   -  When ECR is updated, nothing happens
   -  When BitBucket is updated, the pipeline works as expected (pulling the latest ECR image)
- Build, just builds a new image using the ECR source `latest` and the code from the BitBucket branch
- Deploy, since blue/green is not working, I have a rolling update in place currently.

The only part of the pipeline not working is the ECR source does not trigger the pipeline to build when it is updated.

### What did you expect to happen?

I expected that when I update the ECR source, for it to trigger the pipeline to build as this is what it does when I build this manually.

### What actually happened?

When the ECR source is updated, nothing happens. No errors that I could find, simply nothing. Like it is not aware of the connection to the repo.

### Environment

  - **CLI Version      :** 1.67.0 (build 2b4dd71)
  - **Framework Version:** 1.67.0 (build 2b4dd71)
  - **Node.js Version:** v12.18.3
  - **OS               :** Linux Zeus 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - **Language (Version):** TypeScript (3.9.7)

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @jpSimkins ,

thanks for reporting the issue. Can you tell me whether you see a `AWS::Events::Rule` resource in your template, and show its content if you do?

Thanks,
Adam

**Comment by jpSimkins** [comment]
Hello @skinny85,

This is the resource with `AWS::Events::Rule`:

```yaml
CDKTestBaseRepositoryPipelineTestCDKTestProjectPipeline3CAA437FSourceEventRuleC4D400A3:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.ecr
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          requestParameters:
            repositoryName:
              - Ref: CDKTestBaseRepository90CAC7C5
            imageTag:
              - latest
          eventName:
            - PutImage
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":codepipeline:us-east-1:311209486165:"
                - Ref: CDKTestProjectPipeline664B0BF2
          Id: Target0
          RoleArn:
            Fn::GetAtt:
              - CDKTestProjectPipelineEventsRoleEBA1D6BA
              - Arn
    Metadata:
      aws:cdk:path: PipelineTest/CDKTestBase/Repository/PipelineTestCDKTestProjectPipeline3CAA437FSourceEventRule/Resource
```
