### ISSUE TITLE
[aws-kms] Key.fromKeyArn with full arn results alias key arn when used inside the key creation account

### ISSUE THREAD

**Issue by heikkis** [aws/aws-cdk#10979]
Key.fromKeyArn with full arn results alias key arn when using **the kms key in same account that it has been created**.

### Reproduction Steps

```
      const vault = new BackupVault(this, 'Vault', {
            encryptionKey: Key.fromKeyArn(
                this,
                'KmsKey',
                'arn:aws:kms:eu-west-1:nnnnnnn:key/nnnnnn-nnnnn-nnnnn-nnnnn'
            )
        })
```
==> 
```
Vault23237E5B:
    Type: AWS::Backup::BackupVault
    Properties:
      EncryptionKeyArn: arn:aws:kms:eu-west-1:nnnnnnn::**alias**/kms-crossaccount-xxxxxxxxxx
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```

### What did you expect to happen?

Full key Arn was expected to be used.

### What actually happened?

Alias key Arn was used (maybe got the match from cdk.context.json). It is not supported eg. by AWS Backup:

KMS key Alias is not supported by AWS Backup (Service: AWSBackup; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: dfe13b6c-d1d7-459c-a162-xxxxxxxx)

### Environment

  - **CLI Version      :** 1.69.0
  - **Framework Version:** 1.69.0
  - **Node.js Version:** 13.10.1
  - **OS               :** MACOS
  - **Language (Version):** Typescript

--- 

This is :bug: Bug Report
