### ISSUE TITLE
[aws-cognito] CfnIdentityPool: "Invalid Cognito Identity Provider"  

### ISSUE THREAD

**Issue by phelucko** [aws/aws-cdk#11054]
I was trying to create an identity pool using the following code:

```javascript
    // create userPool
    // create userPoolClient
    const identityPool = new cognito.CfnIdentityPool(this, 'CognitoServerlessDemoIdentityPool', {
      allowUnauthenticatedIdentities: true,
      cognitoIdentityProviders: [
        {
          clientId: userPoolClient.clientId,
          providerName: userPool.userPoolProviderName,
        },
      ],
    });
```
I got the error below.

```
CognitoServerlessDemoIdentityPool Invalid Cognito Identity Provider (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidParameterException; Request ID: 8c85c42d-0188-42ef-948f-5f7842c8e2a9; Proxy: null)
  new CognitoServerlessDemoStack (/src/aws/cognito-serverless-demo/cdk/lib/cognito-serverless-demo-stack.js:204:26)
  \_ Object.<anonymous> (/src/aws/cognito-serverless-demo/cdk/bin/cognito-serverless-demo.js:7:1)
  \_ Module._compile (internal/modules/cjs/loader.js:1076:30)
  \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
  \_ Module.load (internal/modules/cjs/loader.js:941:32)
  \_ Function.Module._load (internal/modules/cjs/loader.js:782:14)
  \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  \_ internal/main/run_main_module.js:17:47
```

The generated CloudFormation is below. For some reason, the `ClientId` attribute was missing:

```
  CognitoServerlessDemoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ProviderName:
            Fn::GetAtt:
              - CognitoServerlessDemoUserPool74CA82F1
              - ProviderName
```

### Environment

  - **CLI Version      :** aws-cli/1.18.155 Python/3.8.6 Linux/5.8.10-arch1-1 botocore/1.18.14
  - **Framework Version:** 1.69.0 (build 2b474b9)
  - **Node.js Version:** v14.12.0
  - **OS               :** Arch Linux

--- 

This is :bug: Bug Report
