### ISSUE TITLE
[aws-iam] Role.addManagedPolicy not filtering duplicates 

### ISSUE THREAD

**Issue by IvanKraljevic** [aws/aws-cdk#11073]
Hi,
I have some custom ASG configuration for my EKS cluster, and when I connect the ASG to the cluster, CDK adds 3 managed policies. Which is reasonable.
The problem occurs when I try to use a single IAM role for multiple ASGs. In that case, when I connect the ASGs to the cluster, the role ends up with **N** duplicates of each managed policy. When I try to deploy it, CloudFormation throws an error since duplicate managed policies are not allowed.

### Reproduction Steps

```
function buildAsg(scope, vpc, subnets, role) {
  return new AutoScalingGroup(scope, 'id', {...});
}

function buildAndConnectAsgs(scope, cluster, vpc, subnets) {
  let role = new Role(scope, "my-role", {...});
  let asgOptions = {...};
  let asgs: AutoScalingGroup[] = buildAsgs(scope, role, vpc, subnets);
  
  for (let i = 0; i < subnets.length; i++) {
    cluster.connectAutoScalingGroupCapacity(buildAsg(scope, role, vpc, subnet[i]), asgOptions);
  }
}

```

### What did you expect to happen?

I expected the IAM role will contain only 3 managed policies.

### What actually happened?

I got N duplicates of each managed policy (N = num. of ASGs).

```
MyRole94EB9947:
    Type: AWS::IAM::Role
    Properties:
      ...
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonEKSWorkerNodePolicy"
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonEKS_CNI_Policy"
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonEKSWorkerNodePolicy"
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonEKS_CNI_Policy"
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      ...
```

On deployment, CloudFormation throws an error on duplicate managed policies.

### Environment

  - **CLI Version      :** 1.69 (reporduced in 1.47 and 1.45 as well)
  - **Framework Version:** 1.69 (reporduced in 1.47 and 1.45 as well)
  - **Node.js Version:** v10.21.0
  - **OS               :**  MacOs
  - **Language (Version):** Typescript, but probably affects other languages as well

### Other

My current workaround is to extend the `Role` class, do nothing on `addManagedPolicy` and configure the policies manually:

```
class RoleWithIgnoredManagedPolicies extends Role {
  constructor(scope: Construct, id: string, props: RoleProps) {
    super(scope, id, props);
  }

  addManagedPolicy(policy: IManagedPolicy): void {
    console.debug("nope");
  }

  // gives us the ability to manually add the necessary policies
  internalAddManagedPolicy(policy: IManagedPolicy): void {
    super.addManagedPolicy(policy);
  }
}
```

Looking at the source code, Role has basic filtering, but it doesn't help because at synth time each managed policy gets a unique token, so nothing gets filtered:
https://github.com/aws/aws-cdk/blob/a76428bd8559e497cd631d17ff9af2a01792b4c2/packages/%40aws-cdk/aws-iam/lib/role.ts#L384 

--- 

This is :bug: Bug Report
