### ISSUE TITLE
[route53] CfhHealthCheck in @aws-cdk/aws-route53 has regressed to having properties as lowercase

### ISSUE THREAD

**Issue by brianfoody** [aws/aws-cdk#11096]
CfnHealthCheck has regressed to have Cloudformation properties as lower case.

### Reproduction Steps

```
new CfnHealthCheck(this, "SensiveApiHealthCheck", {
      healthCheckConfig: {
        Port: 443,
        Type: "HTTPS",
        ResourcePath: "/prod/system/health/check",
        FullyQualifiedDomainName: `${this.api.restApiId}.execute-api.${props.region}.amazonaws.com`,
        RequestInterval: 30,
        FailureThreshold: 2
      }
});
```

### What did you expect to happen?

```
Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Port: 443
        Type: HTTPS
        ResourcePath: /prod/system/health/check
        FullyQualifiedDomainName:
          Fn::Join:
            - ""
            - - Ref: sensiveRootSensiveRegionalApiF65332A1
              - .execute-api.ap-southeast-2.amazonaws.com
        RequestInterval: 30
        FailureThreshold: 2
```

### What actually happened?
```
Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        port: 443
        type: HTTPS
        resourcePath: /prod/system/health/check
        fullyQualifiedDomainName:
          Fn::Join:
            - ""
            - - Ref: sensiveRootSensiveRegionalApiF65332A1
              - .execute-api.ap-southeast-2.amazonaws.com
        requestInterval: 30
        failureThreshold: 2
```

### Environment
```
  - **CLI Version  1.70.0  :**
  - **Framework Version: ~1.70.0**
  - **Node.js Version:** 14.5.0 / 12 on CI-->
  - **OS               : Mac / Linux**
  - **Language (Version):** TypeScript (3.8.3)
```

### Other

Nothing else

--- 

This is :bug: Bug Report
