### ISSUE TITLE
[aws-wafv2] NotStatement isn't recognized when setting up rule 

### ISSUE THREAD

**Issue by newcomer** [aws/aws-cdk#11153]
### Reproduction Steps
```
new CfnWebACL(this, 'APIWebAcl', {
                defaultAction: { allow: {} },
                name: 'API',
                scope: 'CLOUDFRONT',
                visibilityConfig: {
                    cloudWatchMetricsEnabled: true,
                    metricName: 'API',
                    sampledRequestsEnabled: false,
                },
                rules: [
                    {
                        name: 'DoS',
                        priority: 3,
                        statement: {
                            rateBasedStatement: {
                                limit: 1000,
                                aggregateKeyType: 'IP',
                                scopeDownStatement: {
                                    andStatement: {
                                        statements: [
                                            {
                                                notStatement: {
                                                    statement: {
                                                        byteMatchStatement: {
                                                            searchString: 'Prober/1.0',
                                                            fieldToMatch: {
                                                                singleHeader: {
                                                                    name: 'user-agent',
                                                                },
                                                            },
                                                            textTransformations: [{ priority: 0, type: 'NONE' }],
                                                            positionalConstraint: 'CONTAINS',
                                                        },
                                                    },
                                                },
                                            },
                                        ],
                                    },
                                },
                            },
                        },
                        visibilityConfig: {
                            cloudWatchMetricsEnabled: true,
                            metricName: 'DoS',
                            sampledRequestsEnabled: true,
                        },
                        overrideAction: {
                            block: {},
                        },
                    },
                ],
            });
```
Produces
```
  APIWebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: API
        SampledRequestsEnabled: false
      Name: API
      Rules:
        - Name: DoS
          OverrideAction: {}
          Priority: 3
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 1000
              ScopeDownStatement:
                AndStatement:
                  Statements:
                    - {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: DoS
            SampledRequestsEnabled: true
```
### What did you expect to happen?
All statements defined in the construct are synthesized

### Environment

  - **CLI Version      :**  1.69.0
  - **Framework Version: ** 1.69.0
  - **Node.js Version:**  v12.15.0
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** JavaScripts
This is :bug: Bug Report

**Comment by shivlaks** [comment]
@newcomer - I'm trying to understand this a little better... is this a problem specifically with `NotStatement`?
from the rendered template, it appears that your `AndStatement` is also empty. specifically

```yaml
 ScopeDownStatement:
                AndStatement:
                  Statements:
                    - {}
```

do you happen to have an example of a valid CloudFormation template that leverages the property you're trying to use?
I'll have to do a little digging to investigate, but it might be handy to know what the generated template *should* look like
