### ISSUE TITLE
S3 SqsDestination and SnsDestination creates a cyclic reference 

### ISSUE THREAD

**Issue by mickog** [aws/aws-cdk#11245]
### Reproduction Steps
```
const app1= new cdk.App();
const stack1 = new cdk.Stack(app, "stack1");
const stack2 = new cdk.Stack(app, "stack2");

const topic = new Topic(stack2, 'Topic');

const bucket = new s3.Bucket(stack1, "bucket");
bucket.addEventNotification(      EventType.OBJECT_CREATED_PUT, new s3n.SnsDestination(topic));
```

```
$ cdk synth
```
### What actually happened?
```
Error: 'stack1' depends on 'stack2' ("stack1/bucket/Notifications/Resource" depends on "stack2/Topic/Resource", "stack1/bucket/Notifications/Resource" depends on "stack2/Topic/Policy/Resource", stack1 -> stack2/Topic/Resource.Ref). Adding this dependency (stack2 -> stack1/bucket/Resource.Arn) would create a cyclic reference.
```

**Comment by mickog** [comment]
For reference https://github.com/aws/aws-cdk/issues/5760, the fix may be similar

**Comment by dreamitsk** [comment]
Apparently there is some kind of what-was-first-chicken-or-egg situation and topic's stack can't leave without the bucket's Custom::S3BucketNotifications resource for some reason.
Does anyone know any obvious workaround (except for placing both the bucket and the notification target in the same node) for this or any estimate on a fix (if it is even possible)?

**Comment by ezeev** [comment]
+1

**Comment by jmfiola** [comment]
+1

**Comment by pulkit83** [comment]
+1

**Comment by jaspotter** [comment]
+1

**Comment by sekhavati** [comment]
I'm hitting this, any workaround or movement on this issue?

**Comment by sekhavati** [comment]
So thought I’d share the workaround I’ve put in place as it may help someone else who comes across this thread. 

In my situation I was setting up a fan-out pattern described below but essentially to fix it I had to create the resources that resulted in a cyclical dependency within the same stack. 

**Before (broken):**

- shared resources stack
  - creates an s3 bucket
  - exposes s3 bucket as property of stack
- stack 1
  - accepts s3 bucket as a prop (ie: from shared resources)
  - adds s3 event notification with SNS topic as a destination*
  - add a lambda subscription to the SNS topic above


**After (working):**

 - shared resources stack
	- creates an s3 bucket
        - add s3 event notification with SNS topic as a destination
        - expose SNS topics as prop
 - stack 2
        - accepts SNS topic as a prop (ie: from shared resources)
        - add a lambda subscription to the SNS topic above

This works but makes the code CDK code untidy and clouds the separations of concerns for each of the stacks in question in my case. 

Do you think this issue is worthy of bumping to a P1 given it’s Lambda counterpart was also a P1?

**Comment by sekhavati** [comment]
So thought I’d share the workaround I’ve put in place as it may help someone else who comes across this thread. 

In my situation I was configuring a basic fan-out pattern shown below but essentially to fix it I had to create the resources that resulted in a cyclic reference within the _same_ stack. 

#### Before (broken):

- Shared resources stack
  - creates an s3 bucket
  - exposes s3 bucket as property of stack
- Stack 1
  - accepts s3 bucket as a prop (ie: from shared resources)
  - adds s3 event notification with SNS topic as a destination   **_<--- *** cyclic reference error ***_**
  - add a lambda subscription to the SNS topic above


#### After (working):

- Shared resources stack
  - creates an s3 bucket
  - add s3 event notification with SNS topic as a destination   **_<--- *** cyclic reference fix ***_**
  - expose SNS topics as prop
- Stack 1
  - accepts SNS topic as a prop (ie: from shared resources)
  - add a lambda subscription to the SNS topic above

This works but clouds the separations of concerns for each of the stacks in question in my case. 

@SomayaB Do you think this issue is worthy of bumping to a P1 given it’s [Lambda counterpart](https://github.com/aws/aws-cdk/issues/5760) was also a P1?

**Comment by larsskaug** [comment]
+1

**Comment by laguna-rotem** [comment]
Same issue, a fix would be great!

**Comment by owengage** [comment]
Low effort fix: rather than accept the `IBucket` as a property, accept the bucket name and use `Bucket.fromBucketName` in the stack requiring the S3 notification. This breaks the cycle.

**Comment by IsaiahJTurner** [comment]
I solved this by creating an SNS topic that serves as an intermediary. S3 delivers notifications to SNS and then SNS delivers them to my SQS queue. The problem that's causing all this mess is that the `addObjectCreatedNotification` is trying to modify the policy document of the destination to allow access. Ideally, it would accept a parameter that allows me to explicitly say I do NOT want the policy updated. Since that is not possible currently, I did something along these lines:


```ts
// SQS stack
    const sqsQueue = new sqs.Queue(this, 'Queue', {
      retentionPeriod: Duration.days(14),
      receiveMessageWaitTime: Duration.seconds(20),
      visibilityTimeout: Duration.hours(1),
    })
    sqsQueue.addToResourcePolicy(new iam.PolicyStatement({
      actions: ['sqs:SendMessage'],
      effect: Effect.ALLOW,
      principals: [new ServicePrincipal('s3.amazonaws.com')],
      conditions: {
        StringEquals: {
          "aws:SourceAccount": this.account,
        },
        ArnLike: {
           // Allows all buckets to send notifications since we haven't created the bucket yet.
          "aws:SourceArn": "arn:aws:s3:*:*:*"
        }
      }
    }))
    sqsQueue.addToResourcePolicy(new iam.PolicyStatement({
      actions: ['sqs:SendMessage'],
      effect: Effect.ALLOW,
      principals: [new ServicePrincipal('sns.amazonaws.com')],
      conditions: {
        StringEquals: {
          "aws:SourceAccount": this.account,
        },
        ArnLike: {
           // Allows all sns topics to send notifications since we haven't created the bucket yet.
          "aws:SourceArn": "arn:aws:sns:*:*:*"
        }
      }
    }))
  
    this.sqsQueue = sqsQueue
```
```ts
// S3 stack
    const topic = new sns.Topic(this, 'Topic', {
      fifo: false,
    })
    this.topic = topic
    const bucket = new s3.Bucket(this, 'Bucket', {
      versioned: true,
    })
    bucket.addToResourcePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['s3:GetObject'],
      resources: [bucket.arnForObjects('*')],
      principals: [originAccessIdentity.grantPrincipal],
    }))
    bucket.addObjectCreatedNotification(new s3n.SnsDestination(topic))
    new sns.Subscription(this, `Subscription`, {
      rawMessageDelivery: true,
      endpoint: props.beanstalkPrepStack.sqsQueue.queueArn,
      protocol: SubscriptionProtocol.SQS,
      topic: this.topic,
    })
```

Notice I do not use `topic.addSubscription` as this would also create a cyclical dependency as CDK attempts to modify the SQS Queue's policy document when you do this.

**Comment by gfteix** [comment]
Other possible workaround is to use AwsCustomResource:
https://docs.aws.amazon.com/cdk/api/v1/docs/custom-resources-readme.html
PS: this always override the current configuration


```typescript 
queue.addPermission(`AllowS3Invocation`, {
    action: 'sqs:SendMessage',
    principal: new ServicePrincipal('s3.amazonaws.com'),
    sourceArn: bucket.bucketArn
  })

  const notificationResource = new AwsCustomResource(this, `NotificationCustomResource`, {
    logRetention: RetentionDays.THREE_DAYS,
    policy: AwsCustomResourcePolicy.fromStatements([
      new PolicyStatement({
        effect: Effect.ALLOW,
        actions: ['s3:PutBucketNotification'],
        resources: [bucket.bucketArn, `${ bucket.bucketArn }/*`],
      })
    ]),
    onCreate: {
      service: 'S3',
      action: 'putBucketNotificationConfiguration',
      parameters: {
        Bucket: bucket.bucketName,
        NotificationConfiguration: {
          QueueConfigurations: [
            {
              Events:['s3:ObjectCreated:*'],
              QueueArn: queue.queueArn,
            }
          ]
        }
      },
      physicalResourceId: PhysicalResourceId.of(`${ id + Date.now().toString() }`),
    },
  })

  notificationResource.node.addDependency(queue.permissionsNode.findChild('AllowS3Invocation'))
```

**Comment by MatthewMSaucedo** [comment]
+1 to this, as [https://github.com/aws/aws-cdk/issues/5760|issue 5760] has been erroneously closed.

**Comment by knziiy** [comment]
+1

**Comment by awmcc90** [comment]
Any update on this? It's still an issue in the latest CDK version.

**Comment by scorbiere** [comment]
The usual way to deal with the cross Stack cyclic references issue is to use the "export attribute and import resources" mechanism (see CloudFormation `Output` and `Fn::ImportValue`). For now the L2 constructs of Bucket, Topic and so on, don't support this cross Stack setup.  
So as a workaround, and to extend the [comment](https://github.com/aws/aws-cdk/issues/11245#issuecomment-1030597769) from @owengage, here is what I would recommend for now:
```ts
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as cdk from 'aws-cdk-lib';
import * as s3n from 'aws-cdk-lib/aws-s3-notifications';

import { Construct } from 'constructs';

class BucketStack extends cdk.Stack {
  private readonly bucket: s3.Bucket;
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.bucket = new s3.Bucket(this, 'my-bucket');
  }

  /**
   * 
   * @param scope Construct which will interact with the bucket. If the scope's Stack is not the same as the BucketStack,
   * a cross stack reference will be created using the `Stack.exportValue()` method.
   * 
   * @returns the bucket that was created with this stack.
   */
  public getBucket(scope?: Construct): s3.IBucket {
    // return this.bucket; // --> does not support cross stacks scenario

    if (scope === undefined || cdk.Stack.of(scope) === this) {
      return this.bucket;
    } else {
      const exportedBucketName = this.exportValue(this.bucket.bucketName);
      return s3.Bucket.fromBucketName(scope, 'my-imported-bucket', exportedBucketName);
    }
  }
}

class TopicStack extends cdk.Stack {
  private readonly topic: sns.Topic;
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.topic = new sns.Topic(this, 'my-topic');
  }

  /**
   * 
   * @param scope Construct which will interact with the topic. If the scope's Stack is not the same as the TopicStack,
   * a cross stack reference will be created using the `Stack.exportValue()` method.
   * 
   * @returns the topic that was created with this stack.
   */
  public getTopic(scope?: Construct): sns.ITopic {
    // return this.topic; // --> does not support cross stack scenario

    if (scope === undefined || cdk.Stack.of(scope) === this) {
      return this.topic;
    } else {
      const exportedTopicArn = this.exportValue(this.topic.topicArn);
      return sns.Topic.fromTopicArn(scope, 'my-imported-topic', exportedTopicArn);
    }
  }
}

export class S3EventNotifications {
  private readonly bucket: s3.IBucket;
  private readonly topic: sns.ITopic;

  constructor(app: cdk.App) {

    const bucketStack = new BucketStack(app, 'MyBucketStack');
    const topicStack = new TopicStack(app, 'MyTopicStack');

    this.bucket = bucketStack.getBucket(topicStack);
    this.topic = topicStack.getTopic();

    this.bucket.addEventNotification(s3.EventType.OBJECT_CREATED_PUT, new s3n.SnsDestination(this.topic));
  }
}
```

In this example the responsibility of creating an export/import resource is handled by the stack which own the resource.

Another option would be to move this logic into the `S3EventNotifications` (from my example) as you may want to keep the control of which resource attribute is exported and independently decide of its usage (with a `<RESOURCE>.from<ATTRIBUTE>(...)` method). Which will make your code easier to change in the case of a future architecture change/migration (see this discussion for more context: https://github.com/aws/aws-cdk/issues/27420)

Here is the result of the 2 stacks synthesize:
```sh
cdk synth MyBucketStack
```
```yaml
Resources:
  mybucket15E130AF:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
Outputs:
  ExportsOutputRefmybucket15E130AFA0000000:
    Value:
      Ref: mybucket15E130AF
    Export:
      Name: MyBucketStack:ExportsOutputRefmybucket15E130AFA0000000
```

```sh
cdk synth MyTopicStack
```
```yaml
Resources:
  mytopicA51900AA:
    Type: AWS::SNS::Topic
  mytopicPolicy0AEB5F49:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sns:Publish
            Condition:
              ArnLike:
                aws:SourceArn:
                  Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":s3:::"
                      - Fn::ImportValue: MyBucketStack:ExportsOutputRefmybucket15E130AFA0000000
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Resource:
              Ref: mytopicA51900AA
            Sid: "0"
        Version: "2012-10-17"
      Topics:
        - Ref: mytopicA51900AA
  myimportedbucketNotificationsAC5303A0:
    Type: Custom::S3BucketNotifications
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - BucketNotificationsHandler000a0087b7544547bf325f094a3db8347ECC3691
          - Arn
      BucketName:
        Fn::ImportValue: MyBucketStack:ExportsOutputRefmybucket15E130AFA0000000
      NotificationConfiguration:
        TopicConfigurations:
          - Events:
              - s3:ObjectCreated:Put
            TopicArn:
              Ref: mytopicA51900AA
      Managed: false
    DependsOn:
      - mytopicPolicy0AEB5F49
      - mytopicA51900AA
  BucketNotificationsHandler000a0087b7544547bf325f094a3db834RoleB6FB88EC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  BucketNotificationsHandler000a0087b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucketNotification
              - s3:PutBucketNotification
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: BucketNotificationsHandler000a0087b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36
      Roles:
        - Ref: BucketNotificationsHandler000a0087b7544547bf325f094a3db834RoleB6FB88EC
  BucketNotificationsHandler000a0087b7544547bf325f094a3db8347ECC3691:
    Type: AWS::Lambda::Function
    Properties:
      Description: AWS CloudFormation handler for "Custom::S3BucketNotifications" resources (@aws-cdk/aws-s3)
      Code: ...
```

Tested with `cdk deploy MyBucketStack MyTopicStack` which successfully created the 2 stacks with the associated resources.

This being said, I am interested in cases where this kind of workaround is not possible. Please, feel free to share some examples.
