### ISSUE TITLE
[aws-eks] Cluster.addHelmChart no longer respecting repository field.

### ISSUE THREAD

**Issue by ten-lac** [aws/aws-cdk#11477]
The `HelmChartOptions` interface for `Cluster.addHelmChart` allows for a `repository` field which allows the pointing of the repository to pull the helm chart from.  This no longer works.

### Reproduction Steps
```javascript
        const prometheusHelmChart = cluster.addHelmChart('Prometheus', {
            chart: 'prometheus-operator',
            createNamespace: false,
            namespace: namespacePrometheusName,
            release: `prometheus-operator`,
            version: '9.3.2',
            repository: 'https://kubernetes-charts.storage.googleapis.com/',
            timeout: Duration.minutes(10),
            values: { ... }
       }
```

Also, the following CF stanza was generated

```yaml
ControlPlaneEKSchartPrometheus72B62D62:
    Type: Custom::AWSCDK-EKS-HelmChart
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B
          - Outputs.TennaK8Sqa1awscdkawseksKubectlProviderframeworkonEvent689A9A95Arn
      ClusterName:
        Ref: ControlPlaneEKSC6E4919A
      RoleArn:
        Fn::GetAtt:
          - ControlPlaneEKSCreationRole58D1869A
          - Arn
      Release: prometheus-operator
      Chart: prometheus-operator
      Version: 9.3.2
      Wait: true
      Timeout: 300s
      Values: "<...>"
      Namespace: prometheus-system
      Repository: https://kubernetes-charts.storage.googleapis.com/
    DependsOn:
      - ControlPlaneEKSchartPrometheusEFSProvisionerEB6A15C9
      - ControlPlaneEKSKubectlReadyBarrier1C298D16
      - ControlPlaneEKSNodegroupManagedPrivateWorkerPoolc52xlarge118920201112FAFA9E33
      - ControlPlaneEKSNodegroupManagedPublicWorkerPoolc5xlarge118920201112CD94DE82
      - MonitoringNamespaceprometheussystemDockerRegistryGlobalprometheussystemDockerRegistryGlobalprometheussystemmanifest7E9EEA9B
      - MonitoringNamespaceprometheussystemprometheussystemnamespacemanifestB28933AF
      - NetworkVpcIGW6BEA7B02
      - NetworkVpcPrivateSubnet1DefaultRoute08635105
      - NetworkVpcPrivateSubnet1RouteTable7D7AA3CD
      - NetworkVpcPrivateSubnet1RouteTableAssociation327CA62F
      - NetworkVpcPrivateSubnet1Subnet6DD86AE6
      - NetworkVpcPrivateSubnet2DefaultRouteA15DC6D5
      - NetworkVpcPrivateSubnet2RouteTableC48862D1
      - NetworkVpcPrivateSubnet2RouteTableAssociation89A2F1E8
      - NetworkVpcPrivateSubnet2Subnet1BDBE877
      - NetworkVpcPrivateSubnet3DefaultRouteFE7FEBED
      - NetworkVpcPrivateSubnet3RouteTable7FC52A8D
      - NetworkVpcPrivateSubnet3RouteTableAssociation616B0E34
      - NetworkVpcPrivateSubnet3Subnet8ABFAF5C
      - NetworkVpcPublicSubnet1DefaultRoute31EC04EC
      - NetworkVpcPublicSubnet1EIPE0D52090
      - NetworkVpcPublicSubnet1NATGateway64781A21
      - NetworkVpcPublicSubnet1RouteTable30235CE2
      - NetworkVpcPublicSubnet1RouteTableAssociation643926C7
      - NetworkVpcPublicSubnet1Subnet36933139
      - NetworkVpcPublicSubnet2DefaultRoute0CF082AB
      - NetworkVpcPublicSubnet2EIP24F41572
      - NetworkVpcPublicSubnet2NATGateway42CB86F5
      - NetworkVpcPublicSubnet2RouteTable0FACEBB2
      - NetworkVpcPublicSubnet2RouteTableAssociationC662643B
      - NetworkVpcPublicSubnet2SubnetC427CCE0
      - NetworkVpcPublicSubnet3DefaultRoute320997B4
      - NetworkVpcPublicSubnet3EIP22F0C93C
      - NetworkVpcPublicSubnet3NATGateway5DD3AF93
      - NetworkVpcPublicSubnet3RouteTable4F517CA2
      - NetworkVpcPublicSubnet3RouteTableAssociationDBCF32A1
      - NetworkVpcPublicSubnet3Subnet4BBF7F47
      - NetworkVpc7FB7348F
      - NetworkVpcVPCGW8F3799B5
      - PermissionEKSClusterAdminRoleEA0AD2E4
      - PermissionEKSClusterReadonlyRoleFE7F2F3C
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: Tenna-K8S-qa1/ControlPlane/EKS/chart-Prometheus/Resource/Default
```

### What did you expect to happen?
Expected Helm chart to install without error.  I do not expect the chart to be pulled from `charts.helm.sh` repo when `https://kubernetes-charts.storage.googleapis.com` has been specified.

### What actually happened?
<img width="1410" alt="Screen Shot 2020-11-14 at 7 21 16 PM" src="https://user-images.githubusercontent.com/54904348/99160598-96bbff00-26ae-11eb-9169-99c6f99777fd.png">

### Environment

  - **CDK CLI Version  :**
```
> cdk version
1.73.0 (build eb6f3a9)
```
  - **Framework Version:**
```
All @aws-cdk libraries at 1.73
```
  - **Node.js Version:** 
```
> node -v
v12.18.2
```
  - **OS               :**
```
macOS 10.15.7
```
  - **Language (Version):** 
```
Javascript
```

### Other

--- 

This is :bug: Bug Report
