### ISSUE TITLE
[aws-eks] Pending daemonset hanging indefinitely

### ISSUE THREAD

**Issue by cweidinger** [aws/aws-cdk#11609]
EKS 1.15 with fargate profile and spot instances in node group cause potinterrupthandler daemonset to try to start on fargate "node" which doesn't allow daemonsets. This causes a Pending daemonset that just hangs around indefinitely.

### Reproduction Steps

eks cluster with fargate profile and node group with spot instances

### What did you expect to happen?
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: ckecketesteksclusterchartspotinterrupthandler11c1473d
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-node-termination-handler
    app.kubernetes.io/version: 1.3.1
    helm.sh/chart: aws-node-termination-handler-0.7.3
    k8s-app: aws-node-termination-handler
...
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm
                - arm64
              - key: lifecycle # This is the thing I think should be there or something like it
                operator: In
                values:
                - Ec2Spot
```
### What actually happened?

the affinity rules without the lifecycle=Ec2Spot

### Environment

  - **CDK CLI Version  :** 1.55.0
  - EKS 1.15
--- 

This is :bug: Bug Report
