### ISSUE TITLE
[ecs-patterns] NetworkLoadBalancedFargateService creates wrong port on TargetGroup

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#11634]
I'm trying to create an ECS Fargate Service with a Loadbalancer for RabbitMQ. I need to have 2 ports: 5672 and 15672, both TCP. Of cource I'm trying to use the ecs-patterns class NetworkLoadBalancedFargateService. Unfortunately the class still creates a CFN template with port 80 on the target group. Creating another listener also fails.

### Reproduction Steps

```typescript
const service = new NetworkLoadBalancedFargateService(this, 'RabbitmqService', {
            cluster: cluster,
            desiredCount: 1,
            maxHealthyPercent: 100,
            minHealthyPercent: 0,
            listenerPort: 5672,
            taskImageOptions: {
                containerPort: 5672,
                image: ContainerImage.fromAsset('app/rabbitmq'),
                environment: {
                    RABBITMQ_NODENAME: this.stackName + '@localhost',
                    RABBITMQ_MNESIA_BASE: '/var/scratch',
                    RABBITMQ_MNESIA_DIR: '/var/scratch/rabbitmq',
                    RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"',
                },
                logDriver: LogDriver.awsLogs({
                    logGroup: logGroup,
                    streamPrefix: 'rabbitmq',
                }),
            },
            publicLoadBalancer: false,
            healthCheckGracePeriod: Duration.seconds(30),
            domainZone: hostedZone,
            domainName: 'test.com',
            memoryLimitMiB: 2048,
        })

 service.taskDefinition.defaultContainer?.addPortMappings({containerPort: 15672})
        service.loadBalancer.addListener('mgmt', {
            port: 15672,
        }).addTargets('mgmt', {
            port: 15672,
            targets: [service.service],
        })
```

### What actually happened?

Those are the relevant parts of the resulting CFN tempate:
```yaml
Resources:
  RabbitmqServiceLB19BC50B0:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: "false"
      Scheme: internal
      Subnets:
        - subnet-052c3eb97abf9d8a9
        - subnet-032eb7e9ac0b9ff03
      Type: network
  RabbitmqServiceLBPublicListener58D07760:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: RabbitmqServiceLBPublicListenerECSGroup2D7AF8A6
          Type: forward
      LoadBalancerArn:
        Ref: RabbitmqServiceLB19BC50B0
      Port: 5672
      Protocol: TCP
  RabbitmqServiceLBPublicListenerECSGroup2D7AF8A6:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetType: ip
      VpcId: vpc-08263c5e31125ad95
  RabbitmqServiceLBmgmt6C1CB509:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: RabbitmqServiceLBmgmtmgmtGroupF93BE1E6
          Type: forward
      LoadBalancerArn:
        Ref: RabbitmqServiceLB19BC50B0
      Port: 15672
      Protocol: TCP
  RabbitmqServiceLBmgmtmgmtGroupF93BE1E6:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 15672
      Protocol: TCP
      TargetType: ip
      VpcId: vpc-08263c5e31125ad95
  RabbitmqService094779AE:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: ClusterEB0386A7
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 1
      EnableECSManagedTags: false
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 5672
          TargetGroupArn:
            Ref: RabbitmqServiceLBPublicListenerECSGroup2D7AF8A6
        - ContainerName: web
          ContainerPort: 5672
          TargetGroupArn:
            Ref: RabbitmqServiceLBmgmtmgmtGroupF93BE1E6
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::GetAtt:
                - RabbitmqServiceSecurityGroupCFFC410F
                - GroupId
          Subnets:
            - subnet-052c3eb97abf9d8a9
            - subnet-032eb7e9ac0b9ff03
      TaskDefinition:
        Ref: RabbitmqServiceTaskDef6593B9B5
    DependsOn:
      - RabbitmqServiceLBmgmtmgmtGroupF93BE1E6
      - RabbitmqServiceLBmgmt6C1CB509
      - RabbitmqServiceLBPublicListenerECSGroup2D7AF8A6
      - RabbitmqServiceLBPublicListener58D07760
```

### Environment

  - **CDK CLI Version  :1.74.0**
  - **Framework Version:1.74.0**
  - **Node.js Version:v15.2.1**
  - **OS               :osx**
  - **Language (Version):typescript**

--- 

This is :bug: Bug Report
