### ISSUE TITLE
(aws-apigateway): specifying REGIONAL results in EDGE optimized api-gateway

### ISSUE THREAD

**Issue by ekeyser** [aws/aws-cdk#11690]
Specifying REGIONAL endpointType results in api-gateway being created as EDGE optimized.
This worked yesterday - doesn't work today. Seems odd.

### Reproduction Steps

```
this.apiDomainNameOptions = {
            domainName,
            certificate,
            securityPolicy: agw.SecurityPolicy.TLS_1_2,
            mtls: {
                bucket,
                key: 'truststore.pem',
            },
            endpointType: agw.EndpointType.REGIONAL,
        };
```
### What did you expect to happen?

REGIONAL api-gateway created

### What actually happened?
Edge optimized gateway created

```
7:35:24 PM | CREATE_FAILED        | AWS::ApiGateway::BasePathMapping | books-api/CustomDo...ckbooksapi6501FC16
Mutual TLS authentication is supported for Regional APIs only (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: ac7028b1-4d40-46ad-ba42-01006182
c9d7; Proxy: null)
```

### Environment

  - **CDK CLI Version  :** 1.75
  - **Framework Version:** 1.75.0 (build 7708242)
  - **Node.js Version:** v10.22.1
  - **OS               :** Ubuntu 20.04
  - **Language (Version):** TypeScript 3.7.5

### Other

--- 

This is :bug: Bug Report

**Comment by ekeyser** [comment]
Double checked `synth` creation yaml and confirm that yaml specifies REGIONAL
```
booksapiCustomDomainE814095B:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: api.inflectionpoint.org
      EndpointConfiguration:
        Types:
          - REGIONAL
      MutualTlsAuthentication:
        TruststoreUri: s3://368912206147-auth-store/truststore.pem
      RegionalCertificateArn:
        Fn::GetAtt:
          - apicertCertificateRequestorResourceE501F887
          - Arn
      SecurityPolicy: TLS_1_2
```
