### ISSUE TITLE
(secretsmanager): secret_name returns the end of the ARN with 6 character suffix

### ISSUE THREAD

**Issue by melodyyangaws** [aws/aws-cdk#11727]
Reopen the issue https://github.com/aws/aws-cdk/issues/11573

Need to create an external secret in EKS, which is retrieved from secrets manager. Currently, CDK returns a secret name with secrets manager's 6 character suffix.  Hopefully it can be fixed. Or a workaround would be appreciated.

It caused the error: `{"level":50,"time":1606359303455,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-5648bf6544-p87vp","message":"Secrets Manager can't find the specified secret.","code":"ResourceNotFoundException"`

### Reproduction Steps
1. create a random secret in secrets manager:
`
my_secret = Secret(self, 'xx', 
                    generate_secret_string=SecretStringGenerator(secret_string_template=json.dumps({'username': 'tester'}), generate_string_key="password")
 )
`
2.  create an external secret resource in EKS while replacing the place holder in the yaml file:
```
eks.KubernetesManifest(self,'xx',
            cluster=my_cluster,
            manifest=loadYamlReplaceVarLocal('ex-secret.yaml', 
                fields= {
                    "{{secret_name}}": my_secret.secret_name
                })
        )
```
The content of ex-secret.yaml:
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-external-secret
  namespace: jupyter
spec:
  backendType: secretsManager
  data:
    - key: {{secret_name}}
      name: password
      property: password          
```

### What did you expect to happen?
I want to get the correct secret name that matches the name in secrets manager console.

### What actually happened?

in CDK, `my_secret.secret_name` returns the end of full ARN with 6 character suffix, ie.`jHubSecretArn6E48ECC3-0YhYd3BbaFH5-qeNyUO`. The external secret object in EKS is actually expecting `jHubSecretArn6E48ECC3-0YhYd3BbaFH5`

### Environment

  - **CDK CLI Version  :** 1.74.0 (build e86602f)
  - **Framework Version:** 1.74.0
  - **Node.js Version:** v12.16.2
  - **OS               :** macOS Catalina 10.15.7
  - **Language (Version) :** Python 3.8.5

### Other

in CFN, it looks like this. can we further split it by '-', then take the first & second parts to construct the secret name?
"Value": {
        "Fn::Select": [6,{"Fn::Split": [":",{ "Ref": "jHubSecretArn6E48ECC3" }]}]
      }

This is :bug: Bug Report
