### ISSUE TITLE
(EC2): Rollback does not release EiPs

### ISSUE THREAD

**Issue by Jon-AtAWS** [aws/aws-cdk#11797]
### Reproduction Steps

This one's a little hard to document/repro. Here are a couple of parts of my stack that should cause the problem. First, manually create the DDB table "timestamps"

### Environment

  - **CDK CLI Version  :**
handler@laptop:~/github-code/monitoring-cdk $ cdk --version
1.75.0 (build 7708242)
  - **Framework Version:**
  - **Node.js Version:** 
handler@laptop:~/github-code/monitoring-cdk $ node -v
v14.15.1
  - **OS               :**
MacOS
  - **Language (Version):** 
handler@laptop:~/github-code/monitoring-cdk $ python --version
Python 3.8.3
### Other

--- 

This is :bug: Bug Report

**Comment by Jon-AtAWS** [comment]
Hm. I had detailed output and code in there but it dropped from the final version. Lemme try again

**Comment by Jon-AtAWS** [comment]
Code:

`    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "Monitoring VPC")

        table = ddb.Table(self, 'monitoring-lambda-timestamp',
                          table_name='timestamps',
                          partition_key=ddb.Attribute(
                                name="domain",
                                type=ddb.AttributeType.STRING
                          ),
                          sort_key=ddb.Attribute(
                              name='region',
                              type=ddb.AttributeType.STRING
                          ) )

`

**Comment by Jon-AtAWS** [comment]
First, *Manually* create the timestamps table. Then deploy the stack. It will fail with "table already exists". So far so good. 

Destroy the stack and check the EC2 console. The EIPs remain assigned. Eventually, fail the deploy often enough and you run out of EIPs. Shouldn't the rollback/stack delete remove the EIPs?

**Comment by rix0rrr** [comment]
That is surprising. Yes they should be deleted. If true, this would be a CloudFormation issue that we really can't do anything about though.

Can you figure out if the EIPs are still attached to something?

**Comment by Jon-AtAWS** [comment]
The EIPs are not attached, but they are allocated. Eventually, you run out of EIPs and the deploy fails because you can't allocate more EIPs. Are you able to repro with the snippet above? Can we escalate to CloudFormation?

**Comment by rix0rrr** [comment]
I cannot reproduce this, though.

The CloudFormation template generated by CDK (found in `cdk.out/MyStack.template.json`) basically looks like this:

```yaml
Resources:
  EIPAlloc:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
      Tags:
        - { "Key": "Name", "Value": "These IPs are made for testing" }
  Database:
    Type: "AWS::DynamoDB::Table"
    Properties:
      # Doesn't matter what the name is, as long as the table already exists
      TableName: test
      KeySchema:
        - { "AttributeName": "domain", "KeyType": "HASH" }
      AttributeDefinitions:
        - { "AttributeName": "domain", "AttributeType": "S" }
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    DependsOn:  # This just added to force the right ordering
      - EIPAlloc
```

There's more but those are the salient parts.

* CloudFormation will first allocate the EIP.
* Once it fails to create the DynamoDB table, CloudFormation will roll back what it already created (i.e. that EIP).

In my account and with this template, it will delete the EIP again. In fact it will do so without having me to delete the stack.

Have a look at the CloudFormation Event Log for your stack to see if that gives you any hints as to what might be wrong. 

Whatever it is, this seems to be specific to your account/setup.
