### ISSUE TITLE
(aws-ssm): StringParameter stringValue uses token in default value if token is in parameterName

### ISSUE THREAD

**Issue by john-kontralto** [aws/aws-cdk#11825]
If you try to get the `stringValue` from a parameter with a token in the parameterName, `stringValue` tries to set the `parameterName` as the default value for the `AWS::SSM::Parameter::Value<String>` Resource. This causes Cfn to fail template validation.

### Reproduction Steps

- Use `StringParameter.fromStringParameterAttributes` with a `parameterName` that contains a token and `simpleName: false`
- Use the `stringValue` property

### What did you expect to happen?

Template would validate

### What actually happened?

`stringValue` sets a `Default` value on the `AWS::SSM::Parameter::Value<String>` Resource containing a `Ref`.
Example:
```
  WorkerPathParameterParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default:
      Fn::Join:
        - ""
        - - /
          - Ref: DeploymentIdParameter
          - /Path
```

This causes Cfn template validation to fail with: `Template format error: Every Default member must be a string.`

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** 1.75.0
  - **Node.js Version:**  v12.16.2
  - **OS               :** OS X 10.14.6
  - **Language (Version):**  Version 3.9.7

### Other

The problem is here:
https://github.com/aws/aws-cdk/blob/92f305787142a4777c5815d6da4fdcb8f46d5b92/packages/%40aws-cdk/aws-ssm/lib/parameter.ts#L328

Since `default: attrs.parameterName`, any tokens in the `parameterName` get passed to that default and inserted into the template.

--- 

This is :bug: Bug Report
