### ISSUE TITLE
(aws-eks): EKS cluster creation fails on Connection was closed "https://sts.amazonaws.com/"

### ISSUE THREAD

**Issue by hrubyd** [aws/aws-cdk#11875]
## :question: General Issue
I try to create private EKS cluster under existing VPC and existing private subnets in that VPC. I have all VPC endpoint (sts, ect.) configured and I am able to create the cluster through `eks-ctl` but I have following error if I do it through CDK. 

```
15:09:28 | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | EKSCdkStackcluster...t/Resource/Default
Failed to create resource. Error: b'\nConnection was closed before we received a valid response from endpoint URL: "https://sts.amazonaws.com/".\n\nConnection was closed before we received a valid response from endpoint URL: "http
s://sts.amazonaws.com/".\nerror: unable to recognize "/tmp/manifest.yaml": Get https://XYZ.sk1.eu-west-1.eks.amazonaws.com/api?timeout=32s: getting credentials: exec: exit status 255\n'

Logs: /aws/lambda/EKSCdkStack-awscdkawseksKubectlPro-Handler886CB40B-176U3A52S12V7

at invokeUserFunction (/var/task/framework.js:95:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

### The Question
Do you know how to fix the error, please?

My CDK code:
`cdk-workshop.ts`
```
#!/usr/bin/env node
import * as cdk from '@aws-cdk/core';
import { CdkWorkshopStack } from '../lib/cdk-workshop-stack';

const app = new cdk.App();
const app_env = {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION
}

const workshopStack = new CdkWorkshopStack(app, 'DavidEksCluster', {
    env: app_env
});
```

`cdk-workshop-stack.ts`
```
import * as cdk from '@aws-cdk/core';
import * as aim from '@aws-cdk/aws-iam'
import {InterfaceVpcEndpoint, InterfaceVpcEndpointService, PrivateSubnet, SecurityGroup, Vpc} from '@aws-cdk/aws-ec2'
import * as eks from '@aws-cdk/aws-eks'
import {EndpointAccess} from "@aws-cdk/aws-eks";

export class CdkWorkshopStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpcNxt = Vpc.fromLookup(this, id + 'vpc-rtt-nxt', {
      vpcId: 'vpc-XYZ0'
    })

    const subnet1a = PrivateSubnet.fromPrivateSubnetAttributes(this, id + 'aws-dev-nxt-eu-west-1a-private', {
      subnetId: 'subnet-XYZ1a'
    })
    const subnet1b = PrivateSubnet.fromPrivateSubnetAttributes(this, id + 'aws-dev-nxt-eu-west-1b-private', {
      subnetId: 'subnet-XYZ1b'
    })
    const subnet1c = PrivateSubnet.fromPrivateSubnetAttributes(this, id + 'aws-dev-nxt-eu-west-1c-private', {
      subnetId: 'subnet-XYZ1c'
    })

    const cluster = new eks.Cluster(this, id + 'cluster-rtt-nxt', {
      version: eks.KubernetesVersion.V1_18,
      clusterName: 'cluster-test-1',
      defaultCapacity: 0,
      vpc: vpcNxt,
      vpcSubnets: [
        {
          subnets: [
            subnet1a,
            subnet1b,
            subnet1c
          ]
        }
      ],
      endpointAccess: EndpointAccess.PRIVATE,
      securityGroup:securityGroup
    });
  }
}
```

### Environment

  - **CDK CLI Version:** 1.76.0 (build c207717)
  - **Module Version:** 1.76.0
  - **Node.js Version:** v15.1.0
  - **OS:** macOS Catalina 10.15.7
  - **Language (Version):** TypeScript (3.9.7)

### Other information
I contacted aws support for help and here is the reply:
```
I have reviewed both of the configurations and tested by launching clusters with similar configurations both through the use of eksctl and CDK. I did everything that I believe could reproduce the same behavior, however I was not able to reproduce the error, but given that it the issue is produced by a CloudFormation custom resource Lambda backed function which is generated by the aws-eks module the next step would be to open an issue with the aws-cdk GitHub[1] and describe the issue being experienced. 

As I am not a developer or contributor to the project and since I can not control what gets executed on the Lambda function I am directing you to the below GitHub page that is actively reviewed and contributed to the CDK service team. The software developers on that team will be best suited to answer what is being executed in the custom resource Lambda backed resource(Custom::AWSCDK-EKS-KubernetesResource)[2][3] and how to resolve the issue.
```

It works without any issue if I run it through `eksctl create cluster -f cluster.yaml`. Here is the `cluster.yaml`:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-test-1
  region: eu-west-1  

managedNodeGroups:
  - name: cluster-test-1-ng
    instanceType: c5.2xlarge  
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    privateNetworking: true 

vpc:
  subnets:
    private:
      aws-dev-nxt-eu-west-1a-private:
        id: "subnet-XYZ1a"
      aws-dev-nxt-eu-west-1b-private:
        id: "subnet-XYZ1b"
      aws-dev-nxt-eu-west-1c-private:
        id: "subnet-XYZ1c"
  clusterEndpoints:
    publicAccess: false
    privateAccess: true

```
