### ISSUE TITLE
(elasticloadbalancingv2): cannot have more than one target group on a single NLB listener

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#11943]
NLB listeners currently allow for more than one target group to be added:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts#L33

However, there can only be one target group for an NLB listener since there can only be one default rule for an NLB listener: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html

### Reproduction Steps

```
import * as cdk from '@aws-cdk/core';
import * as ecs from '@aws-cdk/aws-ecs';
import * as elb from '@aws-cdk/aws-elasticloadbalancingv2';
import { Vpc } from '@aws-cdk/aws-ec2';
export class NlbTestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new Vpc(this, 'Vpc');
    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc
    });
    const taskDefinition = new ecs.TaskDefinition(this, 'TaskDef', {
      compatibility: ecs.Compatibility.FARGATE,
      cpu: "1024",
      memoryMiB: "2048",
    });
    const container = taskDefinition.addContainer('container', {
      image: ecs.ContainerImage.fromRegistry('node'),
    });
    container.addPortMappings({ containerPort: 80 });
    const service1 = new ecs.FargateService(this, 'Service1', {
      cluster,
      taskDefinition,
    });
    const service2 = new ecs.FargateService(this, 'Service2', {
      cluster,
      taskDefinition,
    });
    const lb = new elb.NetworkLoadBalancer(this, 'NLB', {
      vpc,
    })
    const listener = lb.addListener('listener1', {
      port: 80,
    });
    listener.addTargets('service1target', {
      port: 80,
      targets: [service1]
    })
    listener.addTargets('service2target', {
      port: 80,
      targets: [service2]
    })
  }
}
```

Deploying this stack results in the following CFN error:
```
Invalid request provided: CreateService error: The target group with targetGroupArn arn:aws:elasticloadbalancing:us-west-1:430030518091:targetgroup/NlbTe-NLBli-1XYX36JEGVQHP/010a21c45e3d17ea does not have an associated load balancer. (Service: Ecs, Status Code: 400, Request ID: 4f3d5f5f-9a56-4af9-8a2f-673267b35bb3, Extended Request ID: null)
```

### Environment

  - **CDK CLI Version  :** 1.77
  - **Framework Version:** 1.77
  - **Node.js Version:** v12.15.0
  - **OS               :** MacOS
  - **Language (Version):** Typescript 3.8.3

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This is subtle.

You can only have one rule and default action for an NLB listener; however, you can have multiple target groups assigned to that default rule. As long as you add multiple target groups at once, it's valid.

With your above reproduction, the second `addTargets` call replaces the defaultAction and target group, causing the first to be orphaned. If you check the `synth` output from the above, you'll see the following warning:

> [Warning at /NlbTestStack/NLB/listener1] A default Action already existed on this Listener and was replaced. Configure exactly one default Action. 

The code responsible for this warning calls out that this really _should_ be an error, but can't be (in v1) for backwards-compatibility reasons:
https://github.com/aws/aws-cdk/blob/a0340e337cd7a9be3f8da9a346cc996392b7b233/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-listener.ts#L133-L144

If you want/need to support multiple target groups, you can do so:
```ts
    const service1TargetGroup = new elb.NetworkTargetGroup(this, 'Service1Group', {
      port: 80,
      targets: [service1],
      vpc,
    });
    const service2TargetGroup = new elb.NetworkTargetGroup(this, 'Service2Group', {
      port: 80,
      targets: [service2],
      vpc,
    });
    lb.addListener('listener1', {
      port: 80,
      defaultTargetGroups: [service1TargetGroup, service2TargetGroup],
    });
```

Which produces the following synthesis:
```yaml
  NLBlistener1B46F543D:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - ForwardConfig:
            TargetGroups:
              - TargetGroupArn:
                  Ref: Service1GroupBA304057
              - TargetGroupArn:
                  Ref: Service2GroupE5B9C734
          Type: forward
      LoadBalancerArn:
        Ref: NLB55158F82
      Port: 80
      Protocol: TCP
    Metadata:
      aws:cdk:path: NlbTestStack/NLB/listener1/Resource
  Service1GroupBA304057:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetType: ip
      VpcId:
        Ref: Vpc8378EB38
    Metadata:
      aws:cdk:path: NlbTestStack/Service1Group/Resource
  Service2GroupE5B9C734:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetType: ip
      VpcId:
        Ref: Vpc8378EB38
    Metadata:
      aws:cdk:path: NlbTestStack/Service2Group/Resource
```
