### ISSUE TITLE
(apigatewayv2): VpcLink subnet selection ignored

### ISSUE THREAD

**Issue by ronaldslc** [aws/aws-cdk#12083]
```typescript
new apiGateway.VpcLink(stack, 'VpcLink', {
   vpc: props.vpc,
   vpcLinkName: 'VpcLink',
   subnets: []
})
```
would result in all VPC subnets being added
```Yaml
  VpcLink66988216:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: VpcLink
      SubnetIds:
        - Ref: XXXSubnet1SubnetC63F3793
        - Ref: XXXSubnet2SubnetB84D1BD7
        - Ref: XXXSubnet3Subnet6C7F7A39
      SecurityGroupIds: []
```
while
```typescript
new apiGateway.VpcLink(stack, 'VpcLink', {
   vpc: props.vpc,
   vpcLinkName: 'VpcLink',
   subnets: [subnet2, subnet3]
})
```
would result in all VPC subnets being added PLUS the extras repeated
```Yaml
  VpcLink66988216:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: VpcLink
      SubnetIds:
        - Ref: XXXSubnet1SubnetC63F3793
        - Ref: XXXSubnet2SubnetB84D1BD7
        - Ref: XXXSubnet3Subnet6C7F7A39
        - Ref: XXXSubnet2SubnetB84D1BD7
        - Ref: XXXSubnet3Subnet6C7F7A39
      SecurityGroupIds: []
```

### What did you expect to happen?

Select only specific subnets to deploy link to to resolve an issue with
`Subnet 'subnet-0dfd3813bb77f3d7a' is in Availability Zone 'ape1-az1' where service is not available (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException;` happening for unknown reasons

### What actually happened?

Cannot make workaround as the problematic subnet remains in the list in CloudFormation

### Environment

  - **CDK CLI Version  :** 1.78
  - **Framework Version:** 1.78
  - **Node.js Version:** 12.20.0
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** Typescript 3.9.7

### Other

--- 

This is :bug: Bug Report
