### ISSUE TITLE
(rds): cannot make RDS non publicly accessible

### ISSUE THREAD

**Issue by felipepulpo** [aws/aws-cdk#12093]
With cloudformation I could have public subnets and create a database non publicly accessible. 
I need it to be non public so quicksight recognizes the vpc connection and I can access it there.

In CDK this is not possible as described in https://stackoverflow.com/questions/57221125/on-aws-rds-on-aws-cdk-where-is-the-setting-to-make-database-publicly-accessible

How can I still reach what I was doing in CFN without private subnets?

### Reproduction Steps
CFN code:
```
Resources:
    Database:
        Type: AWS::RDS::DBInstance
        DeletionPolicy: Retain
        Properties:
            AllocatedStorage: !Ref StorageSpace
            AutoMinorVersionUpgrade: true
            AllowMajorVersionUpgrade: true
            BackupRetentionPeriod: !If [SmallInstance, 2, 7]
            DBInstanceClass: !Ref InstanceType
            DBInstanceIdentifier: !Ref InstanceId
            DBSnapshotIdentifier:
                !If [RestoreFromSnapshot, !Ref DBSnapshot, !Ref "AWS::NoValue"]
            DBName: !Ref DBName
            Engine: postgres
            EngineVersion: 12.2
            MasterUsername: !Ref AdminUser
            MasterUserPassword: !Ref DBPassword
            MultiAZ: false
            DBParameterGroupName: !Ref DBParamGroup122
            PubliclyAccessible: false
            StorageEncrypted: false
            StorageType: gp2
            CopyTagsToSnapshot: true
            VPCSecurityGroups:
                - !GetAtt DBSecurityGroup.GroupId
                - !GetAtt QuicksightRDSSecurityGroup.GroupId
            Tags:
                - Key: Name
                  Value: !Sub "${AWS::StackName}-db-replica"
```
### What did you expect to happen?
CDK has an option to make the database non publicly accesible

### What actually happened?
There is no way to make the DB non publicly accesible without private subnets

### Environment

  - **CDK CLI Version  : 1.76**
  - **Framework Version: 1.76**
  - **Node.js Version:** 10.18.1
  - **OS               :**
  - **Language (Version):** TypeScript (3.8.3)

--- 

This is :bug: Bug Report
