### ISSUE TITLE
[core] test_traffic parameter in CodeDeployBlueGreenHook should be optional

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#12295]
I was trying to use the core.CfnCodeDeployBlueGreenHook  ( no higher level constucts yet  ) to do greenblue ECS deployments. 

The parameter test_traffic_route shoudl in CfnTrafficRouting should be optional, but it has been made mandatory. 

The work around that i have used is to to use core.CfnHook and pass all the properties in json. 

I was attempting to use the template example found at 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html
as an example.

**Comment by NetaNir** [comment]
are your referring to `TestTrafficRoute ` parameter? Cause according to the docs you have attached - it should be required. Are you referring to a different parameter?

**Comment by mrpackethead** [comment]
```
Hooks:
  CodeDeployBlueGreenHook:
    Properties:
      TrafficRoutingConfig:
        Type: TimeBasedCanary
        TimeBasedCanary:
          StepPercentage: 15
          BakeTimeMins: 5
      Applications:
        - Target:
            Type: 'AWS::ECS::Service'
            LogicalID: ECSDemoService
          ECSAttributes:
            TaskDefinitions:
              - BlueTaskDefinition
              - GreenTaskDefinition
            TaskSets:
              - BlueTaskSet
              - GreenTaskSet
            TrafficRouting:
              ProdTrafficRoute:
                Type: 'AWS::ElasticLoadBalancingV2::Listener'
                LogicalID: ALBListenerProdTraffic
              TargetGroups:
                - ALBTargetGroupBlue
                - ALBTargetGroupGreen
    Type: 'AWS::CodeDeploy::BlueGreen'
 ```   
 
 here is the hook, there is no Test Traffic Route.
