### ISSUE TITLE
(CfnSecurityGroupIngress): unable to access SecurityGroupIngress properties

### ISSUE THREAD

**Issue by jahtoe** [aws/aws-cdk#12338]
### How do you access the SecurityGroupIngress properties?

The following code generates a "software.amazon.jsii.JsiiObject cannot be cast to software.amazon.awscdk.services.ec2.CfnSecurityGroupIngress" error 

on the line of code "CfnSecurityGroupIngress sgi = (CfnSecurityGroupIngress)obj;"

```
CfnSecurityGroup cfnSecurityGroup = (CfnSecurityGroup) resource_SecurityGroup.getCfnresource();

    if (cfnSecurityGroup.getSecurityGroupIngress() != null) {

      
      List<CfnSecurityGroupIngress> cfnSecurityGroupIngress = (List<CfnSecurityGroupIngress>) cfnSecurityGroup.getSecurityGroupIngress();
      
      
      ListIterator<CfnSecurityGroupIngress> it = cfnSecurityGroupIngress.listIterator();
      while (it.hasNext()) {
        Object obj = it.next();
        LOG.debug("obj: " + obj.toString());
        CfnSecurityGroupIngress sgi = (CfnSecurityGroupIngress)obj;
        LOG.debug("getFromPort" + sgi.getFromPort());
      }
```

How do you get access to the SecurityGroupIngress properties?

### Environment

  - **Java AWS CDK Version:1.79** 
  - **OS:ubuntu 18.04** 
  - **Java  (Version): 1.8** 

### Other information
https://stackoverflow.com/questions/65569499/how-to-process-aws-cdk-cfnsecuritygroup-in-java?noredirect=1#comment115929349_65569499

**Comment by peterwoodworth** [comment]
Hey @jahtoe,

Sorry for the long wait on this issue and thank you for your patience. It's been looked at and someone will get to it soon

**Comment by skinny85** [comment]
Hi @jahtoe ,

can you show what is `resource_SecurityGroup`, and how it's created?

Thanks,
Adam

**Comment by jahtoe** [comment]
> Hi @jahtoe ,
> 
> can you show what is `resource_SecurityGroup`, and how it's created?
> 
> Thanks,
> Adam

Hi @skinny85, Sorry for that, I've just removed the resource_SecurityGroup as it's just an Object I created that referenced the CfnSecurityGroup.

**Comment by skinny85** [comment]
Hey @jahtoe ,

can you show how is `cfnSecurityGroup` created?

Thanks,
Adam

**Comment by jahtoe** [comment]
> can you show how is `cfnSecurityGroup` created?

Hi @skinny85 I've updated the code.

Regards
Alex

**Comment by skinny85** [comment]
OK, the plot thickens I see 🙂.

Can you also show the template you're including here, or at least the part with the Security Groups?

Thanks,
Adam

**Comment by jahtoe** [comment]
Hi @skinny85 

I've added a template
Regards
Alex

**Comment by skinny85** [comment]
Hey @jahtoe ,

thanks for including the template. I see that the problem is you're using the wrong types. The type of the property `securityIngress` of `CfnSecurityGroup` is _not_ `CfnSecurityGroupIngress`. It's actually [`CfnSecurityGroup.IngressProperty`](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/ec2/CfnSecurityGroup.IngressProperty.html).

You can see it in the template:

```yaml
  RDSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      SecurityGroupIngress: # this is a list of CfnSecurityGroup.IngressProperty
        - Description: PSQL access from worker nodes
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref WebServerSecurityGroup
          FromPort: "5432"
          ToPort: "5432"
```

Hope this helps!

Thanks,
Adam

**Comment by jahtoe** [comment]
Hi @skinny85

I've tried CfnSecurityGroup.IngressProperty before in the form of the code below 

```
 public void TestingSecurityGroupExtraction2(CfnInclude template) throws Exception {

    List<IConstruct> lic = template.getNode().getChildren();
    for (IConstruct IC : lic) {
      if (IC instanceof CfnSecurityGroup) {
        CfnSecurityGroup C = (CfnSecurityGroup) IC;
        if (C.getSecurityGroupIngress() != null) {

          List<CfnSecurityGroup.IngressProperty> cfnSecurityGroupIngress = (List<CfnSecurityGroup.IngressProperty>) C.getSecurityGroupIngress();

          ListIterator<CfnSecurityGroup.IngressProperty> it = cfnSecurityGroupIngress.listIterator();
          while (it.hasNext()) {
            Object obj = it.next();
            LOG.debug("obj: " + obj.toString());
            CfnSecurityGroup.IngressProperty sgi = (CfnSecurityGroup.IngressProperty) obj;
            LOG.debug("getFromPort" + sgi.getFromPort());
          }
        }
      }
    }
  }
``` 

but I get the following error

```

2021-04-20 12:51:00,266 DEBUG com.iriusrisk.iac.awscdk.CreateResources [main] obj: software.amazon.jsii.JsiiObject@26b95b0b
2021-04-20 12:51:00,267 ERROR com.iriusrisk.iac.awscdk.AwsCdkStack [main] Cf-Import Error: software.amazon.jsii.JsiiObject cannot be cast to software.amazon.awscdk.services.ec2.CfnSecurityGroup$IngressProperty

```

How do I determine what the JsiiObject type is?

Kindly let me now if the code above has an error.

Regards
Jahtoe

**Comment by skinny85** [comment]
Hmm, you're correct @jahtoe. When you include the following template:

```yaml
Resources:
  ALBServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: vpc-12345
      GroupName: ALB SG
      GroupDescription: Allow access HTTP & HTTPS traffic to ALB
      SecurityGroupIngress:
        - Description: HTTP access from the world
          IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - Description: HTTPS access from the world
          IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
```

in Java with the following code:

```java
        CfnInclude cfnInclude = CfnInclude.Builder.create(this, "Template")
                .templateFile("cfn-security-group.yaml")
                .templateFile("minimal-cfn-security-group.yaml")
                .build();
        CfnSecurityGroup albServerSecurityGroup = (CfnSecurityGroup) cfnInclude.getResource("ALBServerSecurityGroup");
        List securityGroupIngresses = (List) albServerSecurityGroup.getSecurityGroupIngress();
        for (Object sgi : securityGroupIngresses) {
            System.out.println(sgi.getClass().getCanonicalName());
        }
```

The output is:

```
software.amazon.jsii.JsiiObject
software.amazon.jsii.JsiiObject
```

@RomainMuller is there any way to get the properties out of these `JsiiObject` objects that are the value of the `getSecurityGroupIngress()` getter?
