### ISSUE TITLE
(imagebuilder): use data property in imagebuilder components

### ISSUE THREAD

**Issue by yuleiwan** [aws/aws-cdk#12405]
When generating imagebuilder cfn template using aws-cdk, data property in imagebuilder components isn't parsed correctly.

### Reproduction Steps

for example, I need to generate an imagebuilder component in yaml format

```yaml
  MyComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: xxx
      Version: xxx
      Description: xxx
      ChangeDescription: xxx
      Platform: Linux
      Data: !Sub
        |
        name: xxx
        description: xxx
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: Exit
                action: ExecuteBash
                inputs:
                  commands:
                    - echo 1
```

When I use aws_cdk.aws_imagebuilder python API:

```python
imagebuilder.CfnComponent(
    self,
    id="xxx",
    name="xxx",
    version="xxx",
    description="xxx",
    change_description="xxx",
    platform="Linux",
    data=core.Fn.sub(TEST_DATA),
)

TEST_DATA = '''
|
name: xxx
description: xxx
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: Exit
        action: ExecuteBash
        inputs:
          commands:
            - echo 1 '''
```

it will get generated template looks like

```yaml
MyComponent:
  Properties:
    ChangeDescription: xxx
    Data:
      Fn::Sub: "\n|\nname: xxx\ndescription: xxx\nschemaVersion: 1.0\n\nphases:\n\
        \  - name: build\n    steps:\n      - name: Exit\n        action: ExecuteBash\n\
        \        inputs:\n          commands:\n            - echo 1"
    Description: xxx
    Name: xxx
    Platform: Linux
    Version: xxx
  Type: AWS::ImageBuilder::Component
```  
This data property format with double quotes can't be used in imagebuilder cloudformation stack. I didn't find how to parse data string in the API [document](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_imagebuilder/CfnComponent.html). Any suggestion for this issue? Thanks
### What did you expect to happen?

generate template with correct data property
```
  MyComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: xxx
      Version: xxx
      Description: xxx
      ChangeDescription: xxx
      Platform: Linux
      Data: !Sub
        |
        name: xxx
        description: xxx
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: Exit
                action: ExecuteBash
                inputs:
                  commands:
                    - echo 1
```
### What actually happened?

```yaml
MyComponent:
  Properties:
    ChangeDescription: xxx
    Data:
      Fn::Sub: "\n|\nname: xxx\ndescription: xxx\nschemaVersion: 1.0\n\nphases:\n\
        \  - name: build\n    steps:\n      - name: Exit\n        action: ExecuteBash\n\
        \        inputs:\n          commands:\n            - echo 1"
    Description: xxx
    Name: xxx
    Platform: Linux
    Version: xxx
  Type: AWS::ImageBuilder::Component
```  

### Environment

  - **CDK CLI Version  :**1.81.0 
  - **Framework Version:**
  - **Node.js Version:** v15.5.0
  - **OS               :** Mac
  - **Language (Version):**  python(3.8.3)

### Other

--- 

This is :bug: Bug Report
