### ISSUE TITLE
(aws-ecs): addCapacity does not save Amazon Linux image id to cdk.context.json

### ISSUE THREAD

**Issue by andreialecu** [aws/aws-cdk#12486]
We were troubleshooting issues with autoscaling groups being created every time there's a new Amazon Linux release. The documentation here:

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-autoscaling-readme.html

> NOTE: The Amazon Linux images selected will be cached in your cdk.json, so that your AutoScalingGroups don't automatically change out from under you when you're making unrelated changes. To update to the latest version of Amazon Linux, remove the cache entry from the context section of your cdk.json.
> 
> We will add command-line options to make this step easier in the future.

This however does not seem to happen. There is no relevant ID for the amazon linux image in the `cdk.context.json`.

It is probably relevant that the capacity is added via `@aws-cdk/aws-ecs` and not via autoscaling directly:

### Reproduction Steps

Note that this also uses a spot cluster:

```ts
this.cluster = new ecs.Cluster(this, "Cluster", {
  vpc: vpcStack.vpc,
});

this.cluster.addCapacity("Scaling", {
  maxCapacity: 2,
  minCapacity: 2,
  taskDrainTime: cdk.Duration.seconds(0),
  vpcSubnets: { subnetType },
  instanceType,
  spotPrice,
  spotInstanceDraining: true,
// machineImage not provided, but even providing it doesn't help
});
```

### What did you expect to happen?

AMI id to be saved so that the stack doesn't recreate on unrelated changes.

### What actually happened?

Stack is being recreated every time a new Amazon Linux image is released.

### Environment

  - **CDK CLI Version  :** 1.84.0
  - **Framework Version:** 1.84.0

### Other

We've been having this issue for a long time, recently upgraded from 1.71.0 where the problem also existed.

--- 

This is :bug: Bug Report

**Comment by andreialecu** [comment]
Relevant parameter from `cdk synth`:

```
Parameters:
  SsmParameterValueawsserviceecsoptimizedamiamazonlinux2arm64recommendedimageidC96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/arm64/recommended/image_id
```
