### ISSUE TITLE
(@aws-cdk/dynamo-db): replicationRegions and CodeBuild

### ISSUE THREAD

**Issue by adamskicool** [aws/aws-cdk#12776]
### The Question
When using the option `replictionRegion` in a DynamoDB table and using `CodePipeline` and `CodeBuild` to deploy the dynamo tables, the following error occurs in the action `codepipelineActions.CloudFormationCreateReplaceChangeSetAction`:
![error](https://user-images.githubusercontent.com/34753586/106295171-5ea96e80-6250-11eb-936b-633d0b3126f9.png)

It works fine when using the `CDK CLI` to deploy directly from my computer, but not when using CodePipeline with changeset approvals. 

### Environment

  - **CDK CLI Version:** 1.87.1
  - **Module Version:** ^1.86.0
  - **Node.js Version:** v12.19.0
  - **OS:** masOS 11.1 (locally)
  - **Language (Version):** Typescript ~3.9.7

### Other information
https://stackoverflow.com/questions/61650215/dynamodb-global-tables-through-replicationregions

Generated template

```yaml
Resources:
  TableCD117FA1:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ga-storage-stack/Table/Resource
  TableSourceTableAttachedPolicygastoragestackawscdkawsdynamodbReplicaProviderOnEventHandlerServiceRole03E74172953963CA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - TableCD117FA1
                  - Arn
              - Ref: AWS::NoValue
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":dynamodb:us-west-2:"
                  - Ref: AWS::AccountId
                  - :table/
                  - Ref: TableCD117FA1
        Version: "2012-10-17"
      PolicyName: TableSourceTableAttachedPolicygastoragestackawscdkawsdynamodbReplicaProviderOnEventHandlerServiceRole03E74172953963CA
      Roles:
        - Fn::GetAtt:
            - awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynamodbReplicaProviderNestedStackResource18E3F12D
            - Outputs.gastoragestackawscdkawsdynamodbReplicaProviderOnEventHandlerServiceRole489080A6Ref
    Metadata:
      aws:cdk:path: ga-storage-stack/Table/SourceTableAttachedPolicy-gastoragestackawscdkawsdynamodbReplicaProviderOnEventHandlerServiceRole03E74172/Resource/Resource
  TableSourceTableAttachedPolicygastoragestackawscdkawsdynamodbReplicaProviderIsCompleteHandlerServiceRoleB76E0AC3FC482622:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:DescribeTable
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - TableCD117FA1
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: TableSourceTableAttachedPolicygastoragestackawscdkawsdynamodbReplicaProviderIsCompleteHandlerServiceRoleB76E0AC3FC482622
      Roles:
        - Fn::GetAtt:
            - awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynamodbReplicaProviderNestedStackResource18E3F12D
            - Outputs.gastoragestackawscdkawsdynamodbReplicaProviderIsCompleteHandlerServiceRole1A1DA48CRef
    Metadata:
      aws:cdk:path: ga-storage-stack/Table/SourceTableAttachedPolicy-gastoragestackawscdkawsdynamodbReplicaProviderIsCompleteHandlerServiceRoleB76E0AC3/Resource/Resource
  TableReplicauswest21BCF2ED0:
    Type: Custom::DynamoDBReplica
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynamodbReplicaProviderNestedStackResource18E3F12D
          - Outputs.gastoragestackawscdkawsdynamodbReplicaProviderframeworkonEventFF3DAB11Arn
      TableName:
        Ref: TableCD117FA1
      Region: us-west-2
    DependsOn:
      - TableSourceTableAttachedPolicygastoragestackawscdkawsdynamodbReplicaProviderIsCompleteHandlerServiceRoleB76E0AC3FC482622
      - TableSourceTableAttachedPolicygastoragestackawscdkawsdynamodbReplicaProviderOnEventHandlerServiceRole03E74172953963CA
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ga-storage-stack/Table/Replicaus-west-2/Default
    Condition: TableStackRegionNotEqualsuswest20ED5FFFA
  awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynamodbReplicaProviderNestedStackResource18E3F12D:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
          - ""
          - - https://s3.
            - Ref: AWS::Region
            - "."
            - Ref: AWS::URLSuffix
            - /
            - Ref: AssetParameters4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290S3Bucket909E30FE
            - /
            - Fn::Select:
                - 0
                - Fn::Split:
                    - "||"
                    - Ref: AssetParameters4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290S3VersionKey5EBC399C
            - Fn::Select:
                - 1
                - Fn::Split:
                    - "||"
                    - Ref: AssetParameters4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290S3VersionKey5EBC399C
      Parameters:
        referencetogastoragestackAssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7S3Bucket1255BDCBRef:
          Ref: AssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7S3BucketD7707179
        referencetogastoragestackAssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7S3VersionKey35E02179Ref:
          Ref: AssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7S3VersionKey5CB89613
        referencetogastoragestackAssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3Bucket67730309Ref:
          Ref: AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3BucketEAC9DD43
        referencetogastoragestackAssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3VersionKeyD2CFF09FRef:
          Ref: AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3VersionKeyDD9AE9E7
    Metadata:
      aws:cdk:path: ga-storage-stack/@aws-cdk--aws-dynamodb.ReplicaProvider.NestedStack/@aws-cdk--aws-dynamodb.ReplicaProvider.NestedStackResource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.87.1,@aws-cdk/assets=1.87.1,@aws-cdk/aws-applicationautoscaling=1.87.1,@aws-cdk/aws-autoscaling-common=1.87.1,@aws-cdk/aws-cloudwatch=1.87.1,@aws-cdk/aws-codeguruprofiler=1.87.1,@aws-cdk/aws-dynamodb=1.87.1,@aws-cdk/aws-ec2=1.87.1,@aws-cdk/aws-ecr=1.87.1,@aws-cdk/aws-ecr-assets=1.87.1,@aws-cdk/aws-events=1.87.1,@aws-cdk/aws-iam=1.87.1,@aws-cdk/aws-kms=1.87.1,@aws-cdk/aws-lambda=1.87.1,@aws-cdk/aws-logs=1.87.1,@aws-cdk/aws-s3=1.87.1,@aws-cdk/aws-s3-assets=1.87.1,@aws-cdk/aws-sqs=1.87.1,@aws-cdk/aws-ssm=1.87.1,@aws-cdk/cloud-assembly-schema=1.87.1,@aws-cdk/core=1.87.1,@aws-cdk/custom-resources=1.87.1,@aws-cdk/cx-api=1.87.1,@aws-cdk/region-info=1.87.1,jsii-runtime=node.js/v12.19.0
    Metadata:
      aws:cdk:path: ga-storage-stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  TableStackRegionNotEqualsuswest20ED5FFFA:
    Fn::Not:
      - Fn::Equals:
          - us-west-2
          - Ref: AWS::Region
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  AssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7S3BucketD7707179:
    Type: String
    Description: S3 bucket for asset "10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7"
  AssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7S3VersionKey5CB89613:
    Type: String
    Description: S3 key for asset version "10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7"
  AssetParameters10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7ArtifactHashB2EBC4A6:
    Type: String
    Description: Artifact hash for asset "10f8cd166dc2442813a83b2f11d3a8f68cd322ef11c5505728cff42ad157b8f7"
  AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3BucketEAC9DD43:
    Type: String
    Description: S3 bucket for asset "c691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49c"
  AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3VersionKeyDD9AE9E7:
    Type: String
    Description: S3 key for asset version "c691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49c"
  AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cArtifactHash627DAAA7:
    Type: String
    Description: Artifact hash for asset "c691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49c"
  AssetParameters4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290S3Bucket909E30FE:
    Type: String
    Description: S3 bucket for asset "4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290"
  AssetParameters4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290S3VersionKey5EBC399C:
    Type: String
    Description: S3 key for asset version "4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290"
  AssetParameters4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290ArtifactHash015E056D:
    Type: String
    Description: Artifact hash for asset "4da17aeecf6d8b84ba00da639759c055d83347c951ccce4a6386f90376016290"
```
