### ISSUE TITLE
(aws-sam): cannot generate string policies for CfnFunction

### ISSUE THREAD

**Issue by spalladino** [aws/aws-cdk#12854]
The property `CfnFunctionProps.policies` accepts a list of both objects and strings. However, when I try to generate a list with a string, an empty object is generated instead.

### Reproduction Steps

Running `cdk synth` with the following construct:

```ts
new CfnFunction(scope, 'MyFunction', {
  policies: ['AWSLambdaExecute']
});
```

### What did you expect to happen?

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaExecute
```

### What actually happened?

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - {}
```

### Environment

  - **CDK CLI Version  :** 1.80.0
  - **Framework Version:**
  - **Node.js Version:** 12.18.3
  - **OS               :** Ubuntu 19.10
  - **Language (Version):** 

### Other

Note that if I use a string, instead of a list of strings, the output is correct.

```ts
new CfnFunction(scope, 'MyFunction', {
  policies: 'AWSLambdaExecute'
});
```

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: 'AWSLambdaExecute'
```
--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
@spalladino you're missing a bunch of required properties in your code, I'm surprised it compiles...

This:

```ts
        new sam.CfnFunction(this, 'MyFunction', {
            codeUri: {
                bucket: 'my-bucket',
                key: 'my-key',
            },
            runtime: 'nodejs-12.x',
            handler: 'index.handler',
            policies: 'AWSLambdaExecute',
        });
```

Produces this for me:

```yaml
Transform: AWS::Serverless-2016-10-31
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: my-bucket
        Key: my-key
      Handler: index.handler
      Runtime: nodejs-12.x
      Policies: AWSLambdaExecute
    Metadata:
      aws:cdk:path: TestStack/MyFunction
```
