### ISSUE TITLE
(aws-eks): create failed [ Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE)]

### ISSUE THREAD

**Issue by maieve** [aws/aws-cdk#13080]
```
import ec2 = require('@aws-cdk/aws-ec2');
import eks = require('@aws-cdk/aws-eks');
import cdk = require('@aws-cdk/core');
//import iam = require('@aws-cdk/aws-iam');

class EKSCluster extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpcId = "vpc-xxxxxx";
    const getExistingVpc = ec2.Vpc.fromLookup(this, 'xxxx-vpc',{isDefault: false,vpcId: vpcId });

    const projectName = "xxxxx";
    const environment = "alpha";
    const clusterName = projectName+"-"+environment+"-eks";

    const clusterSecurityGroup = new ec2.SecurityGroup(this,"eks-sg",{
      vpc: getExistingVpc,
      securityGroupName: clusterName+"-sg",
      allowAllOutbound: true,
      description: 'CDK eks Security Group'
    });
    clusterSecurityGroup.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(80));
    clusterSecurityGroup.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(443));
    clusterSecurityGroup.addIngressRule(ec2.Peer.ipv4("10.151.0.0/16"), ec2.Port.tcpRange(1,65000))


    const eksCluster = new eks.Cluster(this, 'Cluster', {
      vpc: getExistingVpc,
      version: eks.KubernetesVersion.V1_18,
      clusterName: clusterName,
      defaultCapacity: 0,
      vpcSubnets: [{ subnetType: ec2.SubnetType.PRIVATE }],
      securityGroup: clusterSecurityGroup
    });
    eksCluster.addNodegroupCapacity('www-node', {
      nodegroupName: "www",
      instanceTypes: [new ec2.InstanceType('t3.xlarge')],
      subnets: {
        subnetType: ec2.SubnetType.PRIVATE,
        availabilityZones: ['ap-northeast-2a', 'ap-northeast-2c']
      },
      minSize: 2,
      desiredSize: 2,
      maxSize: 2,
      diskSize: 20,
      amiType: eks.NodegroupAmiType.AL2_X86_64,
      labels: {"app": "test" },
      tags: {"Project": projectName}
    });

  }
}

const app = new cdk.App();
new EKSCluster(app, 'xxxxxxxx',{
  env : {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION,
  },
});

app.synth();
```

1. cdk create very very long almost 1hour  time out failed

2. result: eks master network subnet public+private (i want only private subnet)
```
vpcSubnets: [{ subnetType: ec2.SubnetType.PRIVATE }],
```

### log
```
multiTestClusterA: creating CloudFormation changeset...
  0/14 | 오후 6:33:27 | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack            | multiTestClusterA User Initiated
  0/14 | 오후 6:33:32 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | multiTestClusterA User Initiated
  0/14 | 오후 6:34:00 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Resource/CreationRole (ClusterCreationRole360249B6)
  0/14 | 오후 6:34:00 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Role (ClusterRoleFA261979)
  0/14 | 오후 6:34:00 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Nodegroupwww-node/NodeGroupRole (ClusterNodegroupwwwnodeNodeGroupRole9ADD7437)
  0/14 | 오후 6:34:00 | CREATE_IN_PROGRESS   | AWS::CDK::Metadata                    | @aws-cdk--aws-eks.ClusterResourceProvider/CDKMetadata/Default (CDKMetadata)
  0/14 | 오후 6:34:01 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Resource/CreationRole (ClusterCreationRole360249B6) Resource creation Initiated
  0/14 | 오후 6:34:01 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Role (ClusterRoleFA261979) Resource creation Initiated
  0/14 | 오후 6:34:01 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/MastersRole (ClusterMastersRole9AA35625)
  0/14 | 오후 6:34:01 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Nodegroupwww-node/NodeGroupRole (ClusterNodegroupwwwnodeNodeGroupRole9ADD7437) Resource creation Initiated
  0/14 | 오후 6:34:01 | CREATE_IN_PROGRESS   | AWS::EC2::SecurityGroup               | eks-sg (ekssgD0B8BE47)
  0/14 | 오후 6:34:01 | CREATE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/MastersRole (ClusterMastersRole9AA35625) Resource creation Initiated
  0/14 | 오후 6:34:02 | CREATE_IN_PROGRESS   | AWS::CDK::Metadata                    | @aws-cdk--aws-eks.ClusterResourceProvider/CDKMetadata/Default (CDKMetadata) Resource creation Initiated
  1/14 | 오후 6:34:03 | CREATE_COMPLETE      | AWS::CDK::Metadata                    | @aws-cdk--aws-eks.ClusterResourceProvider/CDKMetadata/Default (CDKMetadata)
  1/14 | 오후 6:34:06 | CREATE_IN_PROGRESS   | AWS::EC2::SecurityGroup               | eks-sg (ekssgD0B8BE47) Resource creation Initiated
  2/14 | 오후 6:34:08 | CREATE_COMPLETE      | AWS::EC2::SecurityGroup               | eks-sg (ekssgD0B8BE47)
  6/14 | 오후 6:34:21 | CREATE_COMPLETE      | AWS::IAM::Role                        | Cluster/Resource/CreationRole (ClusterCreationRole360249B6)
  6/14 | 오후 6:34:21 | CREATE_COMPLETE      | AWS::IAM::Role                        | Cluster/Role (ClusterRoleFA261979)
  6/14 | 오후 6:34:21 | CREATE_COMPLETE      | AWS::IAM::Role                        | Cluster/MastersRole (ClusterMastersRole9AA35625)
  6/14 | 오후 6:34:22 | CREATE_COMPLETE      | AWS::IAM::Role                        | Cluster/Nodegroupwww-node/NodeGroupRole (ClusterNodegroupwwwnodeNodeGroupRole9ADD7437)
  6/14 | 오후 6:34:24 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource (awscdkawseksClusterResourceProviderNestedStac
kawscdkawseksClusterResourceProviderNestedStackResource9827C454)
  6/14 | 오후 6:34:25 | CREATE_IN_PROGRESS   | AWS::IAM::Policy                      | Cluster/Resource/CreationRole/DefaultPolicy (ClusterCreationRoleDefaultPolicyE8BDFC7B)
  6/14 | 오후 6:34:25 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource (awscdkawseksClusterResourceProviderNestedStac
kawscdkawseksClusterResourceProviderNestedStackResource9827C454) Resource creation Initiated
  6/14 | 오후 6:34:26 | CREATE_IN_PROGRESS   | AWS::IAM::Policy                      | Cluster/Resource/CreationRole/DefaultPolicy (ClusterCreationRoleDefaultPolicyE8BDFC7B) Resource creation Initiated
  7/14 | 오후 6:34:47 | CREATE_COMPLETE      | AWS::IAM::Policy                      | Cluster/Resource/CreationRole/DefaultPolicy (ClusterCreationRoleDefaultPolicyE8BDFC7B)
 7/14 Currently in progress: multiTestClusterA, awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454
  8/14 | 오후 6:37:29 | CREATE_COMPLETE      | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource (awscdkawseksClusterResourceProviderNestedStac
kawscdkawseksClusterResourceProviderNestedStackResource9827C454)
  8/14 | 오후 6:37:33 | CREATE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | Cluster/Resource/Resource/Default (Cluster9EE0221C)
 8/14 Currently in progress: multiTestClusterA, Cluster9EE0221C
  9/14 | 오후 6:50:07 | CREATE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | Cluster/Resource/Resource/Default (Cluster9EE0221C) Resource creation Initiated
  9/14 | 오후 6:50:08 | CREATE_COMPLETE      | Custom::AWSCDK-EKS-Cluster            | Cluster/Resource/Resource/Default (Cluster9EE0221C)
 10/14 | 오후 6:50:12 | CREATE_IN_PROGRESS   | AWS::SSM::Parameter                   | Cluster/KubectlReadyBarrier (ClusterKubectlReadyBarrier200052AF)
 10/14 | 오후 6:50:12 | CREATE_IN_PROGRESS   | AWS::EKS::Nodegroup                   | Cluster/Nodegroupwww-node (ClusterNodegroupwwwnode4C558510)
 10/14 | 오후 6:50:12 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource (awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProv
iderNestedStackResourceA7AEBA6B)
 10/14 | 오후 6:50:13 | CREATE_IN_PROGRESS   | AWS::SSM::Parameter                   | Cluster/KubectlReadyBarrier (ClusterKubectlReadyBarrier200052AF) Resource creation Initiated
 10/14 | 오후 6:50:13 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource (awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProv
iderNestedStackResourceA7AEBA6B) Resource creation Initiated
 10/14 | 오후 6:50:14 | CREATE_COMPLETE      | AWS::SSM::Parameter                   | Cluster/KubectlReadyBarrier (ClusterKubectlReadyBarrier200052AF)
 10/14 | 오후 6:50:25 | CREATE_IN_PROGRESS   | AWS::EKS::Nodegroup                   | Cluster/Nodegroupwww-node (ClusterNodegroupwwwnode4C558510) Resource creation Initiated
10/14 Currently in progress: multiTestClusterA, ClusterNodegroupwwwnode4C558510, awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B
 11/14 | 오후 6:52:54 | CREATE_COMPLETE      | AWS::EKS::Nodegroup                   | Cluster/Nodegroupwww-node (ClusterNodegroupwwwnode4C558510)
11/14 Currently in progress: multiTestClusterA, awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B
 12/14 | 오후 6:56:53 | CREATE_COMPLETE      | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource (awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProv
iderNestedStackResourceA7AEBA6B)
 12/14 | 오후 6:56:58 | CREATE_IN_PROGRESS   | Custom::AWSCDK-EKS-KubernetesResource | Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE)
12/14 Currently in progress: multiTestClusterA, ClusterAwsAuthmanifestFE51F8AE
 12/14 | 오후 7:57:14 | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE) Custom Resource failed to stabilize in expected time. If you are using the Python cfn-r
esponse module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
        new CustomResource (E:\project\cloud-formation\cdk\eks-sample\cluster\node_modules\@aws-cdk\core\lib\custom-resource.js:28:25)
        \_ new KubernetesManifest (E:\project\cloud-formation\cdk\eks-sample\cluster\node_modules\@aws-cdk\aws-eks\lib\k8s-manifest.js:34:9)
        \_ new AwsAuth (E:\project\cloud-formation\cdk\eks-sample\cluster\node_modules\@aws-cdk\aws-eks\lib\aws-auth.js:25:9)
        \_ Cluster.get awsAuth [as awsAuth] (E:\project\cloud-formation\cdk\eks-sample\cluster\node_modules\@aws-cdk\aws-eks\lib\cluster.js:564:29)
        \_ new Cluster (E:\project\cloud-formation\cdk\eks-sample\cluster\node_modules\@aws-cdk\aws-eks\lib\cluster.js:359:14)
        \_ new EKSCluster (E:\project\cloud-formation\cdk\eks-sample\cluster\index.js:45:28)
        \_ Object.<anonymous> (E:\project\cloud-formation\cdk\eks-sample\cluster\index.js:81:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        \_ Module.load (internal/modules/cjs/loader.js:928:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        \_ internal/main/run_main_module.js:17:47
 12/14 | 오후 7:57:17 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | multiTestClusterA The following resource(s) failed to create: [ClusterAwsAuthmanifestFE51F8AE]. Rollback requested by user.

```

### Environment

npm: '6.14.8',
node: v14.15.1
cdk 1.89.0 (build df7253c)

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@maieve Does you VPC have outbound internet access?

The deployment fails because its unable to apply the manifest that defines the `aws-auth`. We have a lambda function that runs `kubectl` commands against the cluster, but it requires an internet connection to access the `eks` service for cluster authentication.

**Comment by maieve** [comment]
> @maieve Does your VPC have outbound internet access?
> 
> The deployment fails because its unable to apply the manifest that defines the `aws-auth`. We have a lambda function that runs `kubectl` commands against the cluster, but it requires an internet connection to access the `eks` service for cluster authentication.


This vpc is being used well without any problems.
The same goes for newly created vpc with cdk.
If the default capacity is set to 0->1, the corresponding bug does not occur.

How do I make the eks master network private?

**Comment by iliapolo** [comment]
> How do I make the eks master network private?

Do you mean the [endpoint access](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#endpoint-access)?

> If the default capacity is set to 0->1, the corresponding bug does not occur.

Something doesn't add up here. The `aws-auth` is configured regardless of the capacity...Can you share the VPC details from your `cdk.context.json` file?

**Comment by maieve** [comment]
> > eks 마스터 네트워크를 비공개로하려면 어떻게해야합니까?
> 
> [끝점 액세스](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#endpoint-access) 를 의미 합니까?
> 
> > 기본 용량을 0-> 1로 설정하면 해당 버그가 발생하지 않습니다.
> 
> 여기에 뭔가 추가되지 않습니다. 을 `aws-auth`에 관계없이 용량의 구성 ... 당신이 당신의 VPC 정보 공유 할 `cdk.context.json`파일을?


```yaml
```yaml
{
  "vpc-provider:account=098462681521:filter.isDefault=false:filter.vpc-id=vpc-0fc1a2f083833baa1:region=ap-northeast-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-0fc1a2f083833baa1",
    "vpcCidrBlock": "10.152.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
          {
            "subnetId": "subnet-041960c8a58530ba3",
            "cidr": "10.152.0.0/20",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-0ef44403d8f6e1ab3"
          },
          {
            "subnetId": "subnet-066b2ee3bf16a19fd",
            "cidr": "10.152.16.0/20",
            "availabilityZone": "ap-northeast-2c",
            "routeTableId": "rtb-0ef44403d8f6e1ab3"
          }
        ]
      },
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-01acf198bac38331f",
            "cidr": "10.152.80.0/20",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-0cc5578a87c10173d"
          },
          {
            "subnetId": "subnet-08b258bb8c1482346",
            "cidr": "10.152.112.0/20",
            "availabilityZone": "ap-northeast-2c",
            "routeTableId": "rtb-063d6cc6c9099ae6c"
          }
        ]
      }
    ]
  },
  "vpc-provider:account=098462681521:filter.isDefault=false:filter.vpc-id=vpc-03f5d7ea6eae38ca2:region=ap-northeast-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-03f5d7ea6eae38ca2",
    "vpcCidrBlock": "10.199.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "DB",
        "type": "Isolated",
        "subnets": [
          {
            "subnetId": "subnet-07c0d3890acae45af",
            "cidr": "10.199.4.0/24",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-0452f2c95a2cfa985"
          },
          {
            "subnetId": "subnet-05a2e4672509f418b",
            "cidr": "10.199.5.0/24",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-0400db60948a04724"
          }
        ]
      },
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-02c38467427235602",
            "cidr": "10.199.2.0/24",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-0f7e06fe88d51250c"
          },
          {
            "subnetId": "subnet-0464535b3756dda61",
            "cidr": "10.199.3.0/24",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-0695aff79f9a2bc25"
          }
        ]
      },
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
          {
            "subnetId": "subnet-077aade95e792b2b0",
            "cidr": "10.199.0.0/24",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-0bd66e1c2ba3224f8"
          },
          {
            "subnetId": "subnet-0ad7e2fba9e5f5bbc",
            "cidr": "10.199.1.0/24",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-009e2756536b28169"
          }
        ]
      }
    ]
  },
  "vpc-provider:account=098462681521:filter.isDefault=false:filter.vpc-id=vpc-0e8eb2e7e03ff6a01:region=ap-northeast-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-0e8eb2e7e03ff6a01",
    "vpcCidrBlock": "10.146.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-05e7813bcef2ac8c9",
            "cidr": "10.146.80.0/20",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-0bf196e0b4f2d061a"
          },
          {
            "subnetId": "subnet-00f5a3b3c70491ca3",
            "cidr": "10.146.96.0/20",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-0bf196e0b4f2d061a"
          },
          {
            "subnetId": "subnet-078f070e07154f81c",
            "cidr": "10.146.112.0/20",
            "availabilityZone": "ap-northeast-2c",
            "routeTableId": "rtb-0bf196e0b4f2d061a"
          }
        ]
      },
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
          {
            "subnetId": "subnet-02154dca76ce526ec",
            "cidr": "10.146.0.0/20",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-04120cdd2b49c9bf6"
          },
          {
            "subnetId": "subnet-0e4ba4c7584fff42a",
            "cidr": "10.146.16.0/20",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-04120cdd2b49c9bf6"
          },
          {
            "subnetId": "subnet-0c641615eb50b24ae",
            "cidr": "10.146.32.0/20",
            "availabilityZone": "ap-northeast-2c",
            "routeTableId": "rtb-04120cdd2b49c9bf6"
          }
        ]
      }
    ]
  },
  "vpc-provider:account=098462681521:filter.isDefault=false:filter.vpc-id=vpc-0cb5378fcdd2d50ac:region=ap-northeast-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-0cb5378fcdd2d50ac",
    "vpcCidrBlock": "10.151.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
          {
            "subnetId": "subnet-077505e258dbc71cf",
            "cidr": "10.151.0.0/20",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-03aab1755f42b2299"
          },
          {
            "subnetId": "subnet-0a39e3361f1805268",
            "cidr": "10.151.16.0/20",
            "availabilityZone": "ap-northeast-2c",
            "routeTableId": "rtb-03aab1755f42b2299"
          }
        ]
      },
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-052b71189398d02f6",
            "cidr": "10.151.80.0/20",
            "availabilityZone": "ap-northeast-2a",
            "routeTableId": "rtb-000ef2ea3d6e3e85f"
          },
          {
            "subnetId": "subnet-01b8541543b837d5a",
            "cidr": "10.151.112.0/20",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-0c6e2398f2af31078"
          },
          {
            "subnetId": "subnet-01c682ce4a7666d0f",
            "cidr": "10.151.32.0/20",
            "availabilityZone": "ap-northeast-2b",
            "routeTableId": "rtb-0c6e2398f2af31078"
          },
          {
            "subnetId": "subnet-083ba6a34edcb8512",
            "cidr": "10.151.96.0/20",
            "availabilityZone": "ap-northeast-2c",
            "routeTableId": "rtb-000ef2ea3d6e3e85f"
          }
        ]
      }
    ]
  }
}

```
```
