### ISSUE TITLE
EC2: security group creation fails when iam permissions are restricted by tags

### ISSUE THREAD

**Issue by dgoetsch** [aws/aws-cdk#13204]
In my organization, security groups are restricted by tags, so I can only change security groups that have tags.  On creation, this causes issues because currently, in the template output by cdk, there is always an entry representing the state of "allowAllOutbound" whether or not that method was actually called. Then when cfn tries to apply the template it tries to create the egress rules in parallel with the tags and that causes an unauthorized issue.

### Reproduction Steps

Example scala code:

```scala
//Tags are applied elsewhere in the stack, but it doesn't matter where you apply them
val securityGroup = SecurityGroup.Builder
      .create(this, "my-secutity-group")
      .securityGroupName("my-security-group")
      .vpc(vpc)
      .build()
```

### What did you expect to happen?

I expect a cfn entry with no egress rule defined, so that the tags exist before egress or ingress rules are defined:

```yaml
  mysecuritygroup382048:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my-service-dependencies-dev/my-secutity-group
      GroupName: my-group-dev
      Tags:
        - Key: tag1
          Value: value1
      VpcId: vpc-NOTTHEREALID
```

### What actually happened?

The generated cfn snippet for this resource had an egress rule defined, this caused security group creation - it looked like the tags didn't yet exist when it tried to create the security group:

```yaml
Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my-service-dependencies-dev/my-secutity-group
      GroupName: my-group-dev
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: tag1
          Value: value1
      VpcId: vpc-NOTTHEREALID
```

### Environment

  - CDK CLI Version  : 1.89.0
  - Framework Version: 1.89.0
  - Node.js Version: v10.16.3
  - OS               : Docker (debian)
  - Language (Version): Scala (2.13.2), Java (openjdk 11.0.9 2020-10-20
)

### Other

I was able to work around this by synthesizing the stack, copying the output, deleting the egress rule entry from the yaml, and manually updating the stack via the UI. The created security group still had an egress rule allowing all outbound traffic even though it wasn't defined in the cfn template, and it didn't break trying to change egress rule.  Then I re-deployed from cdk to align the template, and it worked. I do not think it is reasonable to do this work around in every region as I promote this change.

Here is the stacktrace from the failure:

```
0/6 | 4:56:21 PM | CREATE_FAILED        | AWS::EC2::SecurityGroup            | my-secutity-group (mysecuritygroup382048) API: ec2:RevokeSecurityGroupEgress You are not authorized to perform this operation. Encoded authorization failure message: **MASKED**
	new SecurityGroup (/tmp/jsii-kernel-90NSlU/node_modules/@aws-cdk/aws-ec2/lib/security-group.js:205:30)
	\_ obj._wrapSandboxCode (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:2720:58)
	\_ Kernel._wrapSandboxCode (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:3148:24)
	\_ Kernel._create (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:2720:34)
	\_ Kernel.create (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:2461:29)
	\_ KernelHost.processRequest (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:9457:36)
	\_ KernelHost.run (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:9420:22)
	\_ Immediate.setImmediate [as _onImmediate] (/tmp/jsii-java-runtime18342111350916640151/lib/program.js:9421:46)
	\_ runCallback (timers.js:705:18)
	\_ tryOnImmediate (timers.js:676:5)
	\_ processImmediate (timers.js:658:5)
```

--- 

This is :bug: Bug Report
