### ISSUE TITLE
 EC2: add a mechanism to disable inline security group rules, for tag-based authz scenarios

### ISSUE THREAD

**Issue by dgoetsch** [aws/aws-cdk#13256]
### Description: 

Security group constructor ALWAYS adds an egress rule to the security group declaration, even if none is defined.

The problem is the egress rule in the SecurityGroup declaration. CDK is is adding an egress rule for allowAllOutbound, even if allowAllOutbound was never called.

`addIngressRule` and `addEgressRule` already work as expected - they add new blocks to the template.  Once again: **The problem is that the constructor always adds an egress rule to the security group definition even `allowAllOutbound` is never called.**  If I delete the egress rule from the security group declaration, the entire thing works.

If no egress is defined, then it doesn't really make sense to artificially insert it into the generated template.  In our environment, artificially inserting this rule causes security group creation to fail due to IAM rules on tags.

### Reproduction Steps

Create a security group, with no Xgress rules defined until after the group is constructed:

```
 val appSecurityGroup =
      SecurityGroup.fromSecurityGroupId(
        this,
        "app-security-group-ref",
        "sg-appid"
      )

    val httpSecurityGroup =
      SecurityGroup.fromSecurityGroupId(this, "http-security-group-ref", "sg-httpid")

//Notice how there is no egress defined in the constructor
val securityGroup = SecurityGroup.Builder
      .create(this, "my-secutity-group")
      .securityGroupName("my-security-group")
      .vpc(vpc)
      .build()

    securityGroup.addIngressRule(appSecurityGroup, Port.tcp(Port))
    securityGroup.addIngressRule(httpSecurityGroup, Port.tcp(Port))
```

### What did you expect to happen?
CDK should NOT put an Egress rule in the output cdk declaration for "allowAllOutbound".

```
 secutitygroup37A50950:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: service-dependencies-dev/secutity-group
      GroupName: service-dev
      Tags:
        - Key: team
          Value: service-team
      VpcId: vpc-aaaaaa
    Metadata:
      aws:cdk:path: service-dependencies-dev/secutity-group/Resource
  secutitygroupfromservicedependenciesdevappsecuritygroupref0874CB1C63790D9CBD26:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from servicedependenciesdevappsecuritygroupref0874CB1C:6379
      FromPort: 6379
      GroupId:
        Fn::GetAtt:
          - secutitygroup37A50950
          - GroupId
      SourceSecurityGroupId: sg-aaaaaa
      ToPort: 6379
    Metadata:
      aws:cdk:path: service-dependencies-dev/secutity-group/from servicedependenciesdevappsecuritygroupref0874CB1C:6379
  secutitygroupfromservicedependenciesdevhttpsecuritygroupref4A75D33763793DE4EF63:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from servicedependenciesdevhttpsecuritygroupref4A75D337:6379
      FromPort: 6379
      GroupId:
        Fn::GetAtt:
          - secutitygroup37A50950
          - GroupId
      SourceSecurityGroupId: sg-bbbbbb
      ToPort: 6379
    Metadata:
      aws:cdk:path:service-dependencies-dev/secutity-group/from servicedependenciesdevhttpsecuritygroupref4A75D337:6379
```

### What actually happened?
CDK generated a template with an egress rule for allow all outbound in the declaration:

```
 secutitygroup37A50950:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: service-dependencies-dev/secutity-group
      GroupName: service-dev
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: team
          Value: service-team
      VpcId: vpc-aaaaaa
    Metadata:
      aws:cdk:path: service-dependencies-dev/secutity-group/Resource
  secutitygroupfromservicedependenciesdevappsecuritygroupref0874CB1C63790D9CBD26:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from servicedependenciesdevappsecuritygroupref0874CB1C:6379
      FromPort: 6379
      GroupId:
        Fn::GetAtt:
          - secutitygroup37A50950
          - GroupId
      SourceSecurityGroupId: sg-aaaaaa
      ToPort: 6379
    Metadata:
      aws:cdk:path: service-dependencies-dev/secutity-group/from servicedependenciesdevappsecuritygroupref0874CB1C:6379
  secutitygroupfromservicedependenciesdevhttpsecuritygroupref4A75D33763793DE4EF63:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from servicedependenciesdevhttpsecuritygroupref4A75D337:6379
      FromPort: 6379
      GroupId:
        Fn::GetAtt:
          - secutitygroup37A50950
          - GroupId
      SourceSecurityGroupId: sg-bbbbbb
      ToPort: 6379
    Metadata:
      aws:cdk:path:service-dependencies-dev/secutity-group/from servicedependenciesdevhttpsecuritygroupref4A75D337:6379
```

### Environment

    CDK CLI Version : 1.89.0
    Framework Version: 1.89.0
    Node.js Version: v10.16.3
    OS : Docker (debian)
    Language (Version): Scala (2.13.2), Java (openjdk 11.0.9 2020-10-20
    )

### Other

referencing: https://github.com/aws/aws-cdk/issues/13204 which was closed prematurely by a maintainer who made several false assumptions without waiting for a response or additional information. Adding additional context this time around.  Please don't just close this issue without actually having a conversation first.

--- 

This is :bug: Bug Report
