### ISSUE TITLE
Cannot use attributes in string interpolations because of tokens

### ISSUE THREAD

**Issue by yves-vogl** [aws/aws-cdk#13288]
## :question: General Issue

As far as i understood you've dropped strong types in favour of tokens which could be used like strings.
Now I've a relative simple use case which does not feel natural to me. I'm not sure if I got something wrong or this is simply not possible.

### The Question

I've a construct which has some path logic for creating a generated secret name for a certain user.

```typescript

private createGroup(groupName: string, path?: string): iam.Group {

    let group: iam.Group = new iam.Group(this, groupName, {
      groupName: groupName,
      path: (path ? path : this.iamPath)
    });

    let policy: iam.Policy = new iam.Policy(this, groupName + 'Policy');

    policy.addStatements(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        resources: [
          '*'
        ],
        actions: [
          'cloudformation:*'
        ]
      })
    );

    group.attachInlinePolicy(policy);

    return group;
  }


  private secretNameForUser(path: string, secretName: string, userName: string, groupName?: string): string {

    return path.concat(
      (groupName || ''),
      '/',
      userName,
      '/',
      secretName
    ).toLowerCase();

    return path;

  }

  private createUserInGroup(userName: string, group: iam.Group, path?: string): iam.User {

    let iamPath: string = (path ? path : this.iamPath)

    let password: cdk.SecretValue = new secretsmanager.Secret(this, userName + 'Password', {
      secretName: this.secretNameForUser(iamPath, 'password', userName, group.groupName.toString()),
      generateSecretString: {
        includeSpace: false,
        passwordLength: 32
      }
    }).secretValue;

    let user: iam.User = new iam.User(this, userName, {
      userName: userName,
      path: iamPath,
      groups: [
        group
      ],
      password: password
    });

    return user;
  }
```

The resulting CF:

 ```yaml
ProvisionerBitbucketPasswordFCD62054:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        IncludeSpace: false
        PasswordLength: 32
      Name: /non-interactive/${token[token.67]}/bitbucket/password
    Metadata:
      aws:cdk:path: ProvisionerStack/Provisioner/BitbucketPassword/Resource
  ProvisionerBitbucketE76AA47B:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Ref: ProvisionerProvisionersD19F757C
      LoginProfile:
        Password:
          Fn::Join:
            - ""
            - - "{{resolve:secretsmanager:"
              - Ref: ProvisionerBitbucketPasswordFCD62054
              - :SecretString:::}}
      Path: /non-interactive/
      UserName: Bitbucket
    Metadata:
      aws:cdk:path: ProvisionerStack/Provisioner/Bitbucket/Resource
```

This leads to:

```shell
8:33:56 PM | CREATE_FAILED        | AWS::SecretsManager::Secret | Provisioner/BitbucketPassword
Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@! (Service: AWSSecretsManager; Status Code: 400; Error Code: ValidationE
xception; Request ID: a87e55c4-f61d-4d73-92f8-048be0d1339d; Proxy: null)
```

I'd have exspected that CDK would either resolve the group name (even before deployment) or manage the depenency/reference instead of taking the attribute literally. Even toString() seems not to work.

### Environment

  - **CDK CLI Version:** 1.90.0 (build 7edba31)
  - **Module Version:** N/A
  - **Node.js Version:** v12.18.3
  - **OS:** macOS Mojave
  - **Language (Version):** TypeScript (3.9.9)
