### ISSUE TITLE
(custom-resources): AwsSdkCall DynamoDBStreams cannot be used dure to validation issue

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#13370]
It looks like If I use an AwsCustomResource making an API call to the DynamoDBStreams Service it gets rewritten to streams.dynamodb causing a validation issue.

### Reproduction Steps

```
const streamArnResource = new custom.AwsCustomResource(this, 'streamArn', {
    onCreate: {
        service: 'DynamoDBStreams',
        action: 'listStreams',
        parameters: {
            TableName: 'foo'
        },
        physicalResourceId: custom.PhysicalResourceId.of('streamArn')
    },
    policy: custom.AwsCustomResourcePolicy.fromSdkCalls({
        resources: custom.AwsCustomResourcePolicy.ANY_RESOURCE
    })
});
```

### What did you expect to happen?

Cloudformation snippet to be created along the lines of:

```
Create:
        service: DynamoDBStreams
        action: listStreams
        parameters:
          TableName: foo
        physicalResourceId:
          id: streamArn
```

### What actually happened?

Synth tries to rewrite the service name causing an error:
`Action 'streams.dynamodb:ListStreams' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.`

### Environment

  - **CDK CLI Version  : 1.88.0**
  - **Framework Version:**
  - **Node.js Version: 10** 
  - **OS               : MacOS **
  - **Language (Version): TypeScript (3.8.3)** 

### Other

--- 

This is :bug: Bug Report
