### ISSUE TITLE
(elasticloadbalancingv2): #13332 is a breaking change!

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#13437]
## :question: General Issue

#13332 is a breaking change!

### The Question
I believe #13332 fixing (#13150) is a breaking change since it adds the resource (with certificates) and then remove the old one (with same certificate), which results to removing the existing certificates.

I can't think of anything other than, doing the migration is two deployment or adding the missing certificates manually after the deployment. Both causes some disruption to the service (endpoints are gonna be unavailable for a couple of seconds/minutes).

I'd suggest to update the release note accordingly.

**Comment by akefirad** [comment]
Confirmed. The first certificates in the list will be gone, if one upgrades to version 1.92.0.

**Comment by njlynch** [comment]
Some potential learnings so far:

It appears that as-is, the `AWS::ElasticLoadBalancingV2::ListenerCertificate` resource reacts as expected on creates/deletes, but does ... odd .. things on update.

For the original bugs (#13150 and #13329), the issue was that if the listener was updated from having 2 to 3 certificates (requiring an update of the ListenerCertificate resource), one of the certificates would be dropped. Here, doing an upgrade from v1.91.0 to v1.92.0 means that any users that have successfully deployed with two certs attached to a single `ListenerCertificate` would see an update to that `ListenerCertificate` and the creation of a new `ListenerCertificate`. The creation appears to work, but the update causes one of the certificates to be removed.

-- **Deployed successfully (all at once, no updates) on v1.91.0** --

```
  LBListener49E825B4:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - RedirectConfig:
            Host: example.com
            StatusCode: HTTP_302
          Type: redirect
      LoadBalancerArn:
        Ref: LB8A12904C
      Certificates:
        - CertificateArn: arn:aws:acm:eu-west-1:123456789012:certificate/f53b3399-2092-4fd7-a777-33734a4dad22
      Port: 443
      Protocol: HTTPS
  LBListenerSSLCert177C324A:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: arn:aws:acm:eu-west-1:123456789012:certificate/b6e4aa65-6d49-4a4e-8321-af2790e4e128
        - CertificateArn: arn:aws:acm:eu-west-1:123456789012:certificate/8f87cdba-816e-4dda-b606-7760e513ca3d
      ListenerArn:
        Ref: LBListener49E825B4
```

-- **v1.92.0** --

```
  LBListener49E825B4:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - RedirectConfig:
            Host: example.com
            StatusCode: HTTP_302
          Type: redirect
      LoadBalancerArn:
        Ref: LB8A12904C
      Certificates:
        - CertificateArn: arn:aws:acm:eu-west-1:123456789012:certificate/f53b3399-2092-4fd7-a777-33734a4dad22
      Port: 443
      Protocol: HTTPS
  LBListenerSSLCert177C324A:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: arn:aws:acm:eu-west-1:123456789012:certificate/b6e4aa65-6d49-4a4e-8321-af2790e4e128
      ListenerArn:
        Ref: LBListener49E825B4
  LBListenerSSLCert26015FAF3:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: arn:aws:acm:eu-west-1:123456789012:certificate/8f87cdba-816e-4dda-b606-7760e513ca3d
      ListenerArn:
        Ref: LBListener49E825B4
```

-- **cdk diff** --

```
Stack Issue13437Stack
Resources
[+] AWS::ElasticLoadBalancingV2::ListenerCertificate LB/Listener/SSLCert2 LBListenerSSLCert26015FAF3
[~] AWS::ElasticLoadBalancingV2::ListenerCertificate LB/Listener/SSLCert LBListenerSSLCert177C324A replace
 └─ [~] Certificates (requires replacement)
     └─ @@ -1,8 +1,5 @@
        [ ] [
        [ ]   {
        [ ]     "CertificateArn": "arn:aws:acm:eu-west-1:123456789012:certificate/b6e4aa65-6d49-4a4e-8321-af2790e4e128"
        [-]   },
        [-]   {
        [-]     "CertificateArn": "arn:aws:acm:eu-west-1:123456789012:certificate/8f87cdba-816e-4dda-b606-7760e513ca3d"
        [ ]   }
        [ ] ]
```

In the above, the `b6e4aa65-6d49-4a4e-8321-af2790e4e128` certificate was the one that was dropped/removed entirely by the update.

The code was written to be backwards-compatible, such that if only two certificates were attached to a listener, no logical IDs would change. I suspect that is what needs to change here; if we create a new logical ID for both certificates, both should get "clean" (single-cert) resources, and both should update appropriately.
