### ISSUE TITLE
SimpleAD requires a plaintext password, incompatible with SCCS

### ISSUE THREAD

**Issue by kauer2** [aws/aws-cdk#13456]
The SimpleAD L1 construct in CDK has a required "password" property. This value has to be provided in plain text. This password ends up in CloudFormation templates, and source code control systems like git, SVN and so on.

Alternatively, a hardcoded password must be provided and the password reset manually immediately after building.

Changing the password in CDK does not avoid this, as CDK will try to replace the entire SimpleAD.

Ideally, it should be possible to provide a SecretsManager.Secret instead of a plain-text password. Alternatively, make the "password" property optional and, if it is not provided, set a random strong password on the SimpleAD. A manual password reset would still be needed, but the SimpleAD would not be vulnerable in the meantime.

Thanks, K.

**Comment by skinny85** [comment]
Hi @kauer2 ,

thanks for opening the issue. In general, we do not have influence over the `Cfn*` classes (what we call [Layer 1 resources](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib)), as those are controlled by either the individual services, or by CloudFormation.

What I can recommend is using the [`SecretValue.secretsManager()` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.SecretValue.html#static-secretswbrmanagersecretid-options), which allows you to reference a Secret in SecretsManager, without hard-coding anything into your code or template. It would look something like:

```ts
import * as cdk from '@aws-cdk/core';
import * as directoryservice from '@aws-cdk/aws-directoryservice';

class ExampleStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        new directoryservice.CfnSimpleAD(this, 'AD', {
            name: 'some-name',
            password: cdk.SecretValue.secretsManager('my-secret-name').toString(),
            size: '',
            vpcSettings: {
                vpcId: 'my-vpc',
                subnetIds: ['subnet-a', 'subnet-b'],
            },
        });
    }
}

const app = new cdk.App();

new ExampleStack(app, 'ExampleStack');
```

This produces:

```yaml
Resources:
  AD:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      Name: some-name
      Password: "{{resolve:secretsmanager:my-secret-name:SecretString:::}}"
      Size: ""
      VpcSettings:
        SubnetIds:
          - subnet-a
          - subnet-b
        VpcId: my-vpc
    Metadata:
      aws:cdk:path: ExampleStack/AD
```

Thanks,
Adam
