### ISSUE TITLE
(aws-elasticloadbalancingv2): TargetGroupAttributes for L2 ApplicationTargetGroup must be a list

### ISSUE THREAD

**Issue by dragosmc** [aws/aws-cdk#13509]
I recently implemented an ALB with Lambda setup in which the Lambda required multi-valued headers to be passed by the ALB. This can be achieved by setting the `lambda.multi_value_headers.enabled` to `true` in the target group's `TargetGroupAttributes`. The current L2 construct exposes the `setAttribute()` which can be used to achieve this.

### Reproduction Steps
Create a target group and set the lambda property to true:

```
myTargetGroup.setAttribute('lambda.multi_value_headers.enabled', 'true');
```
### What did you expect to happen?
The CF template to be valid, as per the [specs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html).

```
MyLambdaTargetGroupB7FEFAF5:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-target-group
      TargetGroupAttributes:
        - Key: lambda.multi_value_headers.enabled
          Value: "true"
      Targets:
        - Id:
            Fn::GetAtt:
              - MyLambda
              - Arn
      TargetType: lambda
```

### What actually happened?
The following CF template is generated

```
MyLambdaTargetGroupB7FEFAF5:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-target-group
      TargetGroupAttributes:
        "0":
          lambda.multi_value_headers.enabled: true
      Targets:
        - Id:
            Fn::GetAtt:
              - MyLambda
              - Arn
      TargetType: lambda
```

Upon deploying the stack, the following error is shown:

`Value of property TargetGroupAttributes must be of type List`

### Workaround
As a workaround, I have used the L1 construct:

```
        (myTargetGroup.node.defaultChild as CfnTargetGroup)
            .addPropertyOverride('TargetGroupAttributes',
                [{
                    Key: 'lambda.multi_value_headers.enabled',
                    Value: 'true'
                }]
            );
```

### Environment

  - **CDK CLI Version  :**   1.91.0
  - **Framework Version:** 1.91.0
  - **Node.js Version:** 12.14.1 
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (4.2.2)

I can have a go at trying to fix this.

--- 

This is :bug: Bug Report
