### ISSUE TITLE
IamRoleLambdaExecution - Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: fefaaa31-7c8a-4d85-96b5-af22b0f8c9ec; Proxy: null).

### ISSUE THREAD

**Issue by srjkrl20011991** [aws/aws-cdk#13587]
## :question: I get below error when i run serverless-deploy command
`
IamRoleLambdaExecution - Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: fefaaa31-7c8a-4d85-96b5-af22b0f8c9ec; Proxy: null).`

```
service: serverless-todo

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:ap-south-1

resources: 
  Resources: 
    TodosTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'

functions:
  create:
    handler: src/handler/createTodo.createTodo
    events: 
      - http:
          path: todos
          method: post
          cors: true

```
