### ISSUE TITLE
(aws-apigatewayv2): Specifying HttpMethod.ANY as allowMethod of CORS configuration causes deployment failure.

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#13643]
```typescript
new apigatewayv2.HttpApi(this, 'API', {
  corsPreflight: {
    allowMethods: [apigatewayv2.HttpMethod.ANY],
    allowOrigins: ['*'],
    allowHeaders: ['*'],
    maxAge: cdk.Duration.seconds(600),
  },
});
```

This generates such template:

```yaml
"APIXXXXXX": {
  "Type": "AWS::ApiGatewayV2::Api",
  "Properties": {
    "CorsConfiguration": {
      "AllowMethods": [
        "ANY"
      ],
      ...
```

But deploying this fails with the error: `Method ANY is not supported (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; ...)`

### What actually happened?

The below is correct CloudFormation template:

```yaml
"APIXXXXXX": {
  "Type": "AWS::ApiGatewayV2::Api",
  "Properties": {
    "CorsConfiguration": {
      "AllowMethods": [
        "*"
      ],
      ...
```

So the beginning code should generate such YAML.

### Environment

  - **CDK CLI Version:2.0.0-alpha.0 (build beadc66)**
  - **Framework Version: 2.0.0-alpha.0**
  - **Node.js Version: v15.10.0** 
  - **OS               : Linux acm-envy2-win-wsl 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux**
  - **Language (Version): TypeScript 4.2.3** 

--- 

This is :bug: Bug Report
