### ISSUE TITLE
(aws-cdk-ecs): metricCpuUtilization never returns data

### ISSUE THREAD

**Issue by m90** [aws/aws-cdk#13769]
### The Question

I'm trying to create a CPU Usage alert for an ECS cluster using the following code:

```js
    this.cpuUsageAlarm = new cloudwatch.Alarm(this, 'EcsCpuUsageAlarm', {
      alarmName: `some name`,
      metric: this.cluster.metricCpuUtilization(),
      threshold: 90
    })
```

The alarm gets created, but will never show data (i.e. "no data", not zero). When I use the Cloudwatch dashboard to view the cluster's CPU Usage, data is being displayed. I'm not sure if I use it incorrectly or if this a bug, but [the docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html#metricwbrcpuwbrutilizationprops) read like it should return something:

> This method returns the CloudWatch metric for this clusters CPU utilization.

For the sake of completeness, the cluster has `ContainerInsights` enabled:

```js
    this.cluster = new ecs.Cluster(this, 'EcsCluster', {
      clusterName: `cluster`,
      vpc: this.vpc,
      containerInsights: true
    })
```

Capacity is provisioned by Fargate using `ecsPatterns.ApplicationLoadBalancedFargateService`.

### Environment

  - **CDK CLI Version:** 1.94.1 
  - **Module Version:** 1.94.1 
  - **Node.js Version:** 14
  - **OS:** Ubuntu
  - **Language (Version):** JS

**Comment by peterwoodworth** [comment]
Hey @m90, sorry for the long response time.

I can't seem to reproduce this, but I can think of a couple things that might be going wrong. I'm sure you're already doing this, but make sure you're using your cluster so that there's data to measure. Second, it may take a bit of time after deployment for the alarm to start measuring data.

If you're still running into this, could you share your `cdk synth` output for the alarm?

**Comment by m90** [comment]
Thanks @peterwoodworth, to answer your question:

- the application does see load, so there certainly is data to measure
- a lot of time has passed since the deployment and it still does not display anything

This is the relevant portion of `cdk synth` as requested:

```yml
  BaseAgaveConstructAgaveEcsCpuUsageAlarmDE2F5F9C:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      AlarmDescription: CPU usage is very high on the application instance. Check if request volume is unusually high or if requests are stalling. If things look normal, consider scaling the cluster capacity.
      AlarmName: "Agave (shelflife/production): CPU usage above 90%"
      Dimensions:
        - Name: ClusterName
          Value:
            Ref: BaseAgaveConstructAgaveECSCluster17356C5A
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: 90
      TreatMissingData: notBreaching
    Metadata:
      aws:cdk:path: AgaveStack-shelflife/BaseAgaveConstruct/AgaveEcsCpuUsageAlarm/Resource
```

Don't know if it makes a difference, but the cluster itself has "Container Insights" enabled:

```yml
  BaseAgaveConstructAgaveECSCluster17356C5A:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: agave-shelflife-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
    Metadata:
      aws:cdk:path: AgaveStack-shelflife/BaseAgaveConstruct/AgaveECSCluster/Resource
```
