### ISSUE TITLE
AWS CDK CfnDBSubnetGroup creates mangled tags and locks AWS console 

### ISSUE THREAD

**Issue by gamma1148** [aws/aws-cdk#13808]
### The Question
When creating a CfnDBSubnetGroup using AWS CDK for Java, the group that is outputted contains tags that are automatically  generated by cloudformation.   These tags are not properly created, and cause error messages  "! Cannot Start with AWS".
When these error messages are present, you cannot add, edit or remove any tags.

### Environment

  - **CDK CLI Version:** 1.92.0 (build de536cc)
  - **Module Version:** 
  - **Node.js Version:** v15.11.0
  - **OS:** Windows 10
  - **Language:** Java

### Other information

This is a screenshot of the modify tags screen in the GUI.   The submit button remains greyed out and you cannot remove the offending tags.
![image](https://user-images.githubusercontent.com/64652993/112556317-524d1800-8da0-11eb-9a7f-cadb7b27fabf.png)

I called AWS Business Tech Support and they told me "Don't do that".

I believe the tags should be there, as every element generated by CF has similar tags.  I believe the AWS GUI is broken for DBSubnetGroups and is not dealing with these tags properly.

Here is my code to generate the DBSubnetGroup

`		CfnDBSubnetGroup myDBSubnetGroup = CfnDBSubnetGroup.Builder.create(this, "SNG-99999")
                     .dbSubnetGroupDescription("SNG-99999")
                     .dbSubnetGroupName("SNG-99999")
                     .subnetIds(mySubnets)
                     .build();`

**Comment by skinny85** [comment]
Hello @gamma1148 ,

thanks for opening the issue. I just tried this:

```java
        CfnDBSubnetGroup myDBSubnetGroup = CfnDBSubnetGroup.Builder.create(this, "SNG-99999")
                .dbSubnetGroupDescription("SNG-99999")
                .dbSubnetGroupName("SNG-99999")
                .subnetIds(Collections.singletonList("subnet-1"))
                .build();
```

And this is what I get as the result:

```yaml
Resources:
  SNG99999:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: SNG-99999
      SubnetIds:
        - subnet-1
      DBSubnetGroupName: SNG-99999
    Metadata:
      aws:cdk:path: hello-cdk-1/SNG-99999
```

As you can see, there are no tags added by the CDK anywhere.

Thanks,
Adam
