### ISSUE TITLE
aws_config: Cannot enable config via CDK

### ISSUE THREAD

**Issue by alexnelsone** [aws/aws-cdk#13978]
When enabling config via cdk and creating CfnConfigurationRecorder and CfnDeliveryChannel, get the message:

`Insufficient delivery policy to s3 bucket: arn:aws:s3:::BUCKET_NAME, unable to write to bucket, provided s3 key prefix is 'null', provided kms key is 'null'.
`

### Reproduction Steps
Using the following code to create Configuration Recorder and Delivery Channel

```
config_recorder = config.CfnConfigurationRecorder(self, 'ConfigRecorder',
                                                  role_arn=config_recorder_role.role_arn,
                                                  recording_group=
                                                  config.CfnConfigurationRecorder.RecordingGroupProperty(
                                                      all_supported=True,
                                                      include_global_resource_types=True)
                                                  ).add_depends_on(bucket_policy)

config_delivery_channel = config.CfnDeliveryChannel(self, 'ConfigDeliveryChannel',
                                                    name=f'{unique_id}-config-delivery-channel',
                                                    s3_bucket_name=config_bucket.bucket_arn,
                                                    sns_topic_arn=config_sns_topic.topic_arn,
                                                    s3_key_prefix=f'config',
                                                    config_snapshot_delivery_properties=
                                                        config.CfnDeliveryChannel.ConfigSnapshotDeliveryPropertiesProperty(
                                                            delivery_frequency='Three_Hours',
                                                        )
                                                    ).add_depends_on(bucket_policy)
```

### What did you expect to happen?
Expected Config to be enabled with no errors. 

### What actually happened?
Received error
`Insufficient delivery policy to s3 bucket: arn:aws:s3:::BUCKET_NAME, unable to write to bucket, provided s3 key prefix is 'null', provided kms key is 'null'.
`

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Framework Version:** 1.96.0
  - **Node.js Version:** 14.16.0
  - **OS               :** Ubuntu 18.04.5 LTS
  - **Language (Version):** Python 3.6

### Other

The output of the CDK is the following:

```
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      RoleARN:
        Fn::GetAtt:
          - ConfigRecorderRole442CB1C4
          - Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
    DependsOn:
      - ConfigBucketPolicy
      
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName:
        Fn::GetAtt:
          - ConfigBucketA3490E76
          - Arn
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Three_Hours
      Name: config-delivery-channel
```
Running a cloudformation with the below resource definition runs just fine:

```
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    DependsOn:
      - ConfigBucketPolicy
    Properties:
      RoleARN: !GetAtt ConfigRecorderRole.Arn
      RecordingGroup:
        AllSupported: True
        IncludeGlobalResourceTypes: True

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    DependsOn:
      - ConfigBucketPolicy.Arn
    Properties:
      Name: config-delivery-channel
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Three_Hours
      S3BucketName: !Ref ConfigBucket
      SnsTopicARN: !GetAtt SnsTopic.Arn
```
--- 

This is :bug: Bug Report
