### ISSUE TITLE
(cloudformation-include): Incorrect rendering of Sub functions when using CfnInclude parameters

### ISSUE THREAD

**Issue by daxAKAhackerman** [aws/aws-cdk#14047]
When importing a CloudFormation template using the CfnInclude class and specifying parameters with values that are the `valueAsString` property of instances of core CfnParameter, every instances of short sub functions (`!Sub`) are incorrectly translated. However, when the included template uses the long version of sub functions (`Fn::Sub`), the synthesized template is valid. 

### Reproduction Steps
**topic.yml**
```yaml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: !Sub my-sns-topic-${Environment}

```
**short-sub-stack.ts**
```typescript
import * as cdk from '@aws-cdk/core';
import * as cfninc from '@aws-cdk/cloudformation-include'


export class ShortSubStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const environment = new cdk.CfnParameter(this, 'Environment', {
      type: 'String'
    })

    new cfninc.CfnInclude(this, 'UserPool', {
      templateFile: './lib/cfn-modules/topic.yml',
      parameters: {
        Environment: environment.valueAsString
      }
    })
  }
}
```
```bash
cdk synth --no-version-reporting --no-path-metadata --no-asset-metadata
```

### What did you expect to happen?

The resulting template's sub functions should either be a valid short sub, or a valid long sub as such: 
```yaml
Fn::Sub:
  - my-sns-topic-${Environment}
  - Environment:
      Ref: Environment
```

### What actually happened?

An invalid sub function is produced as such:

```yaml
Fn::Sub:
  Fn::Join:
    - ""
    - - my-sns-topic-
      - Ref: Environment
```

Resulting in the following cfn-lint error: `E1019: Sub should be a string or array of 2 items` 

And the following CloudFormation error when deployed: `An error occurred (ValidationError) when calling the CreateChangeSet operation: Template error: One or more Fn::Sub intrinsic functions don't specify expected arguments. Specify a string as first argument, and an optional second argument to specify a mapping of values to replace in the string`

### Environment

  - **CDK CLI Version  :1.97.0**
  - **Framework Version:**
  - **Node.js Version:v14.16.0**
  - **OS               : macOS Big Sur 11.2.3**
  - **Language (Version):TypeScript (4.2.3)**

### Other

When using a long sub function, this issue does not happen and the produced cloudformation is valid. The following `topic.yml` file can be used to reproduce this behaviour: 

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: 
        Fn::Sub: 
          - my-sns-topic-${Environment}
          - Environment: !Ref Environment
```

--- 

This is :bug: Bug Report
