### ISSUE TITLE
(cdk-go): CfnInclude Template Generation Issue

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-cdk#14095]
Variables are failing to be fully substituted using CfnInclude, which is resulting in cfn errors creating changeset ```Template error: One or more Fn::Sub intrinsic functions don't specify expected arguments. Specify a string as first argument, and an optional second argument to specify a mapping of values to replace in the string```

https://github.com/ellistarn/testbed/blob/main/pkg/addons/karpenter/controller.go#L30

I'm including this template:
```
  KarpenterControllerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "KarpenterControllerRole-${ClusterName}"
      Path: /
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [{
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OpenIDConnectIdentityProvider}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "${OpenIDConnectIdentityProvider}:aud": "sts.${AWS::URLSuffix}",
                "${OpenIDConnectIdentityProvider}:sub": "system:serviceaccount:karpenter:karpenter"
              }
            }
          }]
        }
```
passing in parameters
```
cloudformationinclude.NewCfnInclude(scope, jsii.String(id), &cloudformationinclude.CfnIncludeProps{
		TemplateFile: jsii.String(path.RelativeTo("./iam.cfn.yaml")),
		Parameters: &map[string]interface{}{
			"ClusterName":                   *options.Cluster.ClusterName(),
			"OpenIDConnectIdentityProvider": *options.Cluster.OpenIdConnectProvider().OpenIdConnectProviderIssuer(),
		},
	})
```
which is generating
```
  "KarpenterControllerRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Fn::Sub": {
            "Fn::Join": [
              "",
              [
                "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [{\n    \"Effect\": \"Allow\",\n    \"Principal\": {\n      \"Federated\": \"arn:aws:iam::${AWS::AccountId}:oidc-provider/",
                {
                  "Fn::Select": [
                    1,
                    {
                      "Fn::Split": [
                        ":oidc-provider/",
                        {
                          "Ref": "ClusterOpenIdConnectProviderE7EB0530"
                        }
                      ]
                    }
                  ]
                },
                "\"\n    },\n    \"Action\": \"sts:AssumeRoleWithWebIdentity\",\n    \"Condition\": {\n      \"StringEquals\": {\n        \"${OpenIDConnectIdentityProvider}:aud\": \"sts.${AWS::URLSuffix}\",\n        \"${OpenIDConnectIdentityProvider}:sub\": \"system:serviceaccount:karpenter:karpenter\"\n      }\n    }\n  }]\n}\n"
              ]
            ]
          }
        },
        "Path": "/",
        "RoleName": {
          "Fn::Sub": {
            "Fn::Join": [
              "",
              [
                "KarpenterControllerRole-",
                {
                  "Ref": "Cluster9EE0221C"
                }
              ]
            ]
          }
        }
      }
    },
```

Two of the three references to `OpenIDConnectIdentityProvider` remain unresolved.

### Reproduction Steps
Fork https://github.com/ellistarn/testbed and `make apply`

### What did you expect to happen?

Substitution should have happened correctly. I was expecting these parameters to be injected as real parameters, rather than magically string substituted.

### Environment

  - **CDK CLI Version  :** `1.97.0 (build c52c2dc)`
  - **Framework Version:**
  - **Node.js Version:** v14.5.0
  - **OS               :** osx
  - **Language (Version):** go-1.16

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @ellistarn ,

thanks for opening the issue. Can you show what are `options.Cluster.ClusterName()` and `options.Cluster.OpenIdConnectProvider().OpenIdConnectProviderIssuer()` that you use for the values of the Parameters?

Thanks,
Adam

**Comment by ellistarn** [comment]
These are just passed in via

```
	cluster := awseks.NewCluster(stack, jsii.String("Cluster"), &awseks.ClusterProps{
		Vpc:                     vpc,
		ClusterName:             jsii.String(id),
		Version:                 awseks.KubernetesVersion_V1_18(),
		DefaultCapacityInstance: awsec2.InstanceType_Of(awsec2.InstanceClass_BURSTABLE3, awsec2.InstanceSize_XLARGE2),
	})
```
and then cluster is passed as options.cluster
```
	cloudformationinclude.NewCfnInclude(scope, jsii.String(id), &cloudformationinclude.CfnIncludeProps{
		TemplateFile: jsii.String(path.RelativeTo("./iam.cfn.yaml")),
		Parameters: &map[string]interface{}{
			"ClusterName":                   *options.Cluster.ClusterName(),
			"OpenIDConnectIdentityProvider": *options.Cluster.OpenIdConnectProvider().OpenIdConnectProviderIssuer(),
		},
	})
```

**Comment by skinny85** [comment]
1. I don't see `OpenIdConnectProvider` in `ClusterProps` above...? Where does that come from?
2. Can you show me the values you pass for `ClusterProps`? (Not reading them - writing them)

**Comment by ellistarn** [comment]
Oh -- I figured you'd be familiar with the accessors ```Cluster.ClusterName()``` and ```Cluster.OpenIdConnectProvider().OpenIdConnectProviderIssuer()``` since they are CDK owned https://github.com/aws/aws-cdk-go/blob/main/awscdk/awseks/awseks.go#L538

**Comment by ellistarn** [comment]
I further simplified the template to 

```
  KarpenterNodeInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "KarpenterNodeRole-${ClusterName}"
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
```

If I hardcode ClusterName to something, it works just fine. Somehow the variable injection isn't working as expected.

**Comment by ellistarn** [comment]
Further, if I hardcode the CDK variable 
```
	cloudformationinclude.NewCfnInclude(scope, jsii.String(id), &cloudformationinclude.CfnIncludeProps{
		TemplateFile: jsii.String(path.RelativeTo("./iam.cfn.yaml")),
		Parameters: &map[string]interface{}{
			"ClusterName":                   "test",
			"OpenIDConnectIdentityProvider": *options.Cluster.OpenIdConnectProvider().OpenIdConnectProviderIssuer(),
		},
	})
```
It also works. This means that the issue is narrowed down to how the CDK is passing in Cluster.Name() from the EKS Construct.

**Comment by ellistarn** [comment]
Printing out this property, I see: ${Token[TOKEN.394]}, detailed here: https://docs.aws.amazon.com/cdk/latest/guide/tokens.html.

**Comment by ellistarn** [comment]
If I'm understanding the code generation correctly
```
  "Fn::Sub": {
            "Fn::Join": [
              "",
              [
                "KarpenterNodeRole-",
                {
                  "Ref": "Cluster9EE0221C"
                }
              ]
            ]
          }
```,
The Sub function requires that the first argument is a string. It's not clear to me if the Join function counts as a string (it definitely resolves to a string).

**Comment by ellistarn** [comment]
Any update here?

**Comment by skinny85** [comment]
OK, now I understand what's happening. I believe this is the same problem as in https://github.com/aws/aws-cdk/issues/14047. The fix for it has already been merged, and will be released as part of CDK version `1.99.0` next week.

Let's keep this issue open until that time to confirm it's fixed.

**Comment by ellistarn** [comment]
Great thanks!

**Comment by MasonHM** [comment]
I believe that I'm seeing the same problem, and it appears to still be happening in CDK version `1.101.0`. In my case, a parameter is being correctly replaced two out of four times in a CloudWatch dashboard body.

#### `bin/test-cdk.ts`:
```typescript
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { CfnInclude } from '@aws-cdk/cloudformation-include';

class Dashboard extends Stack {
  constructor(scope: App, id: string) {
    super(scope, id);

    const cfnTemplate = new CfnInclude(this, 'DashboardTemplate', {
        templateFile: 'dashboard.yaml',
        parameters: {
            Stage: 'test'
        }
    });
  }
}

const app = new App();
new Dashboard(app, 'Dashboard');
```

#### `dashboard.yaml`
```yaml
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String

Resources:
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${Stage}-Dashboard
      DashboardBody: !Sub |
        {
            "widgets": [
                {
                    "type": "text",
                    "properties": {
                        "markdown": "${Stage} ${Stage}"
                    }
                },
                {
                    "type": "text",
                    "properties": {
                        "markdown": "${Stage} ${Stage}"
                    }
                }
            ]
        }
```

#### Actual `cdk synth ` output:
```bash
[masonme@f45c89b36d13] $ cdk --version
1.101.0 (build 149f0fc)

[masonme@f45c89b36d13] $ cdk synth
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardBody:
        Fn::Sub: |
          {
              "widgets": [
                  {
                      "type": "text",
                      "properties": {
                          "markdown": "test test"
                      }
                  },
                  {
                      "type": "text",
                      "properties": {
                          "markdown": "${Stage} ${Stage}"
                      }
                  }
              ]
          }
      DashboardName:
        Fn::Sub: test-Dashboard
```

#### Expected `cdk synth` output:
```bash
[masonme@f45c89b36d13] $ cdk synth
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardBody:
        Fn::Sub: |
          {
              "widgets": [
                  {
                      "type": "text",
                      "properties": {
                          "markdown": "test test"
                      }
                  },
                  {
                      "type": "text",
                      "properties": {
                          "markdown": "test test"
                      }
                  }
              ]
          }
      DashboardName:
        Fn::Sub: test-Dashboard
```
