### ISSUE TITLE
docdb: Cannot create database cluster: cannot find value in secret string

### ISSUE THREAD

**Issue by ryanvade** [aws/aws-cdk#14110]
I'm unable to create a Database Cluster and keep receiving this error:
`Could not find a value associated with JSONKey in SecretString`.

### Reproduction Steps

My Database Cluster:
```
constructor(scope: cdk.Construct, id: string, props: SharedResources) {
    super(scope, id, props);

    // Create the Database
    this.databaseCluster = new DatabaseCluster(this, 'todos-database', {
        masterUser: {
            username: this.clusterUsername, // NOTE: 'admin' is reserved by DocumentDB
        },
        instanceType: InstanceType.of(InstanceClass.M3, InstanceSize.MEDIUM),
        vpcSubnets: {
            subnetType: SubnetType.PRIVATE
        },
        vpc: props.vpc,
        dbClusterName: "todos-database-cluster",
    });
}
```

### What did you expect to happen?

A DatabaseCluster to be created with a password generated in secrets manager. 

### What actually happened?

I am seeing the following error in Cloud Formation:
`Could not find a value associated with JSONKey in SecretString`

### Environment

  - **CDK CLI Version  :** 1.97.0 (build c52c2dc)
  - **Framework Version:** 1.97.0
  - **Node.js Version:** v14.16.0
  - **OS               :** MacOS 11.2.3
  - **Language (Version):** Typescript 3.8.3

### Other

I've also attempted to create the secret value manually:
```
  constructor(scope: cdk.Construct, id: string, props: SharedResources) {
    super(scope, id, props);

    // Database Password
    const templatedSecret = new Secret(this, 'TemplatedSecret', {
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: 'password',
      },
    });

    // Create the Database
    this.databaseCluster = new DatabaseCluster(this, 'todos-database', {
        masterUser: {
            username: this.clusterUsername, // NOTE: 'admin' is reserved by DocumentDB
            password: templatedSecret.secretValueFromJson("password")
        },
        instanceType: InstanceType.of(InstanceClass.M3, InstanceSize.MEDIUM),
        vpcSubnets: {
            subnetType: SubnetType.PRIVATE,
        },
        vpc: props.vpc,
        dbClusterName: "todos-database-cluster"
    });
}
```

And received this error:
```
AppStack/todos-database/Resource [AWS::DocDB::DBCluster] is missing required property: masterUsername

/Users/ryan/Source/Repos/infra-demo-lnl/aws/node_modules/@aws-cdk/aws-docdb/lib/docdb.generated.ts:454
        inspector.addAttribute("aws:cdk:cloudformation:type", CfnDBClusterParameterGroup.CFN_RESOURCE_TYPE_NAME);
                            ^
While synthesizing AppStack/todos-database/Resource: Cannot read property 'renderTags' of undefined
```

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@ryanvade I wasn't able to reproduce this. Using your configuration, I actually got a different error:

```console
RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.m3.medium, Engine=docdb, EngineVersion=3.6.0, LicenseModel=na. For supported combinations of instance class and database engine version, see the documentation.
```

If I changed the instance type to `r5.large` it works properly and a `todosdatabaseSecretD17DF9C9-HUmhlvSA5huF` secret is created in secrets manager. 

Are you able to reproduce this in a clean installation? Im afraid there's not much we can do until we have a reproduction.

**Comment by ryanvade** [comment]
Yes I'm able to replicate with the following repository:  https://github.com/ryanvade/clean-docdb-test

And here is the latest error message: 
```
4:07:47 PM | CREATE_FAILED        | AWS::DocDB::DBCluster                       | todos-database
Could not find a value associated with JSONKey in SecretString
4:07:48 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                  | CleanDocdbTestStack
The following resource(s) failed to create: [todosdatabase2F2D1C05]. Rollback requested by user.


❌  CleanDocdbTestStack failed: Error: The stack named CleanDocdbTestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/ryan/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/Users/ryan/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:297:26)
    at CdkToolkit.deploy (/Users/ryan/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/Users/ryan/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/bin/cdk.ts:208:9)
The stack named CleanDocdbTestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by peterwoodworth** [comment]
Thank you for providing the repo! I was able to clone it and reproduce the error you got.

Here's the relevant `cdk synth` output:

```yaml
todosdatabaseSecretD17DF9C9:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Generated by the CDK for stack: "
            - Ref: AWS::StackName
      GenerateSecretString:
        ExcludeCharacters: '"@/'
        GenerateStringKey: password
        PasswordLength: 41
        SecretStringTemplate: "{}"
```

```yaml
todosdatabase2F2D1C05:
    Type: AWS::DocDB::DBCluster
    Properties:
      MasterUsername:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: todosdatabaseSecretD17DF9C9
            - :SecretString:username::}}
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: todosdatabaseSecretD17DF9C9
            - :SecretString:password::}}
      DBClusterIdentifier: test-database-cluster
      DBSubnetGroupName:
        Ref: todosdatabaseSubnetsDF7E1047
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - Fn::GetAtt:
            - todosdatabaseSecurityGroup1EECD80B
            - GroupId
```
