### ISSUE TITLE
(@aws-cdk/aws-cognito):  Value 'phone_number_verified' failed to satisfy constraint: Member must have length less than or equal to 20

### ISSUE THREAD

**Issue by ayachnes2** [aws/aws-cdk#14175]
On CDK 1.96.0, creating a UserPool and explicitly specifying the `phoneNumberVerified` attribute causes CloudFormation to fail deployment with the following:

```
CREATE_FAILED | AWS::Cognito::UserPool | Pool
1 validation error detected: Value 'phone_number_verified' at 'schema.1.member.name' failed to satisfy constraint: Member must have length less than or equal to 20 (Service: A
WSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException
ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | Stack
The following resource(s) failed to create: [PoolD3F588B8]. Rollback requested by user.
```
See the reproduction steps.

### Reproduction Steps

The following is the code needed to generate this error:

```typescript
import { App, Stack } from "@aws-cdk/core";
import { UserPool } from "@aws-cdk/aws-cognito";

const app = new App();

const stack = new Stack(app, "Stack");

new UserPool(stack, "Pool", {
  standardAttributes: {
    phoneNumberVerified: {
      mutable: true,
      required: false
    }
  }
});
```

Here is the CloudFormation template generated from this:

```yaml
Resources:
  PoolD3F588B8:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      Schema:
        - Mutable: true
          Name: phone_number_verified
          Required: false
      SmsVerificationMessage: The verification code to your new account is {####}
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```

Omitting `phoneNumberVerified` allows the stack to deploy successfully.

### What did you expect to happen?

I expected CloudFormation to deploy the Cognito pool with the `phone_number_verified` attribute with the given settings.

### What actually happened?

Instead, CloudFormation failed to deploy the pool with the error message above.

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Framework Version:** 1.96.0
  - **Node.js Version:** v14.16.0
  - **OS               :** macOS
  - **Language (Version):** TypeScript 3.9.7

--- 

This is :bug: Bug Report
