### ISSUE TITLE
(@aws-cdk/aws-iam): SAML provider name is not output

### ISSUE THREAD

**Issue by 14kw** [aws/aws-cdk#14294]
### Reproduction Steps

```
    new iam.SamlProvider(this, 'Provider', {
      metadataDocument: iam.SamlMetadataDocument.fromXml('document'),
      name: 'provider-name'
    });
```

### What did you expect to happen?

```
Resources:
  Provider2281708E:
    Type: AWS::IAM::SAMLProvider
    Properties:
      SamlMetadataDocument: document
      Name: provider-name
    Metadata:
      aws:cdk:path: CdkTestStack/Provider/Resource
```

### What actually happened?

Name property is missing.

```
Resources:
  Provider2281708E:
    Type: AWS::IAM::SAMLProvider
    Properties:
      SamlMetadataDocument: document
    Metadata:
      aws:cdk:path: CdkTestStack/Provider/Resource
```

### Environment

  - **CDK CLI Version  :** 1.100.0
  - **Framework Version:** 1.100.0
  - **Node.js Version:**  v15.4.0
  - **OS               :** macOS Catalina 10.15.7
  - **Language (Version):**  Typescript 3.9.9, Python 3.8.1

### Other

--- 

This is :bug: Bug Report
