### ISSUE TITLE
aws-fis: CfnExperimentTemplate does not generate a valid AWS::FIS::ExperimentTemplate

### ISSUE THREAD

**Issue by jwoehrle** [aws/aws-cdk#14293]
## :question: General Issue

CFN Yaml synthesized from `CfnExperimentTemplate`does not create a correct CFN `AWS::FIS::ExperimentTemplate`.

All keys in the synth are lower case, however in CFN they are expected as uppercase. This ends in errors during deploy like

```
Properties validation failed for resource fistemplate with message:
#: required key [Description] not found
#: required key [StopConditions] not found
#: required key [Targets] not found
#: required key [RoleArn] not found
#: required key [Tags] not found
#: extraneous key [stopConditions] is not permitted
#: extraneous key [description] is not permitted
#: extraneous key [targets] is not permitted
#: extraneous key [actions] is not permitted
#: extraneous key [roleArn] is not permitted
#: extraneous key [tags] is not permitted
```

### Environment

  - **CDK CLI Version:** 
  ❯ cdk --version
1.100.0 (build d996c6d)
  
  - **Module Version:** 
 1.100.0
  - **Node.js Version:** 
  ❯ node -v
v14.15.4
  - **OS:** 
  OSX Big Sur
  - **Language:** 
  TypeScript

### Other information
I'm using the following CDK snippet:

```
new fis.CfnExperimentTemplate(this,'fis-template', {
      description: 'My first Template',
      roleArn: role.roleArn,
      stopConditions: [
        { source: 'none' }
      ],
      tags: {},
      actions: {
        'TerminateInstances' : // omitted for brevity
      },
      targets: {
        'myInstance' : // omitted for brevity
      }
    })
```

deploying this fails with the above error message.
Looking at the synth output:
```
  fistemplate:
    Type: AWS::FIS::ExperimentTemplate
    Properties:
      description: My first Template
      roleArn:
        Fn::GetAtt:
          - fisrole33E76559
          - Arn
      stopConditions:
        - source: none
      tags: {}
      targets:
        myInstance:
          resourceTags: {}
          resourceType: aws:ec2:instance
          selectionMode: COUNT(1)
      actions:
        TerminateInstances:
          actionId: aws:ec2:stop-instances
          parameters: {}
          targets: {}
```

you can see that the property-keys like `description`, `roleArn`, ... are all starting with a lower letter. This is not what CFN expects according to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fis-experimenttemplate.html.
If I manually change the synth output to uppercase (and fix some other issues, which I will create separate issues for) and then deploy via `aws cloudformation create-stack ...` I can work around this issue.
