### ISSUE TITLE
(aws-docdb): Can not override subnet group 

### ISSUE THREAD

**Issue by brettswift** [aws/aws-cdk#14504]
Our VPC is not created by CDK.   DocDB selects the wrong subnet, and we can not override with the subnetGroupName. 

### Reproduction Steps

VPC has: 
* INFRA-playpen-Public-1
* INFRA-playpen-Public-2
* INFRA-playpen-PrivateApp-1
* INFRA-playpen-PrivateApp-2
* INFRA-playpen-PrivateData-1
* INFRA-playpen-PrivateData-2
* INFRA-playpen-PrivateData-3

Try to override: 

```typescript
        const subnetGroup = new docdb.CfnDBSubnetGroup(this, 'dbSubnetGroup', {
            subnetIds: [
                cdk.Fn.importValue('INFRA-CE-vpc-1-privatedata-subnet0-id'),
                cdk.Fn.importValue('INFRA-CE-vpc-1-privatedata-subnet1-id'),
                cdk.Fn.importValue('INFRA-CE-vpc-1-privatedata-subnet2-id'),
            ],
            dbSubnetGroupDescription: 'offers db assignment',
        })



        const cluster = new docdb.DatabaseCluster(this, 'offers', {
            instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MEDIUM),
            masterUser: masterUser,
            vpc, // Imported probably with wrong ID's.  But has all the subnets and we should be able to override the subnet group.
            engineVersion: '4.0.0',
            storageEncrypted: true,
            vpcSubnets: {
                subnetGroupName: subnetGroup.dbSubnetGroupName, // TODO: This does not work.
            }as ec2.SubnetSelection,
        } as docdb.DatabaseClusterProps)


```

### What actually happened?

3 data subnets to be in the subnet group applied to the cluster.

End resulting stack: 

```yaml
Resources:
  dbSubnetGroup:
    Type: AWS::DocDB::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: offers db assignment
      SubnetIds:
        - Fn::ImportValue: INFRA-vpc-1-privatedata-subnet0-id
        - Fn::ImportValue: INFRA-vpc-1-privatedata-subnet1-id
        - Fn::ImportValue: INFRA-vpc-1-privatedata-subnet2-id
  offersSubnets87DA0DB1:
    Type: AWS::DocDB::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for offers database
      SubnetIds:
        - Fn::ImportValue: INFRA-vpc-1-privateapp-subnet0-id
        - Fn::ImportValue: INFRA-vpc-1-privateapp-subnet1-id

~~~~
  theCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      ~~
      DBSubnetGroupName:
        Ref: offersSubnets87DA0DB1    // this should be dbSubnetGroup instead. 
```

### Environment

  - **CDK CLI Version  :*1.100.0*
  - **Framework Version:*1.100.0*
  - **Node.js Version:*v12.19.1*
  - **OS               :*OSX*
  - **Language (Version):*typescript (3.8.3)* 
 

### Other

I didn't have much luck with the escape hatches, however from reviewing the cluster.ts code I came up with this which seems to work: 

```typescript
        const subnetIds = [
            cdk.Fn.importValue('INFRA-vpc-1-privatedata-subnet0-id'),
            cdk.Fn.importValue('INFRA-vpc-1-privatedata-subnet1-id'),
            cdk.Fn.importValue('INFRA-vpc-1-privatedata-subnet2-id'),
        ]

        const subnets: ec2.ISubnet[] = [];
        let subnetNumber = 0
        subnetIds.forEach(subnetId => {
            subnetNumber = subnetNumber + 1;
            const subnet = ec2.Subnet.fromSubnetId(this, `subnet${subnetNumber}`, subnetId)
            subnets.push(subnet)
        })

// and in the cluster properties: 

~~~
vpcSubnets: {
                subnets,
}
~~~
```

--- 

This is :bug: Bug Report
