### ISSUE TITLE
(all modules): Using Dynamic References with 'number': types

### ISSUE THREAD

**Issue by apmclean** [aws/aws-cdk#14876]
With Dynamic references available:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html

We're seeing more creative ways of using these dynamic references to supply values to CloudFormation templates.  This works well for any values that take a `string` or `IResolavble` but proves problematic for any interfaces typed as `number`.

### Use Case

Below is a (very) simple use-case to illustrate the issue, however I realize that Memory isn't likely a real 'secret', however being able to take advantage of the key-value storage in secrets-manager, and referencing those keys in CloudFormation templates I'd expect to see this approach as reasonable even just for the convenience of not needing to mix and match secrets and SSM parameters and/or context values to parameterize.  It's supported by CloudFormation as well so there should be a path forward in CDK.

Create a secret and record its ARN.

```
aws secretsmanager create-secret \
  --name lambdaConfig \
  --description "Lambda configuration and secret environmental values" \
  --secret-string '{"maxMemory": 1024,"secret":"value"}'
```

Substitute the ARN above into the [ARN] section of this CloudFormation template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function using a secret for a numeric value
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      MemorySize: '{{resolve:secretsmanager:[ARN]:SecretString:maxMemory::}}'
      Code:
        ZipFile: |
          exports.handler = function(event, context) {
              console.log("REQUEST RECEIVED:\n" + JSON.stringify(event))
          }
      Environment:
        Variables:
          SECRET: '{{resolve:secretsmanager:[ARN]:secret::}}'
```

Deploy this template, and observe it will deploy successfully.  Although the provided `MemorySize:` is a `{{resolve:}}` and not a number, we don't get any objections from the CloudFormation service.

Now let's do this in the CDK?  Place your ARN in the [ARN] section as before.

```typescript
import * as cdk from '@aws-cdk/core';
import * as sm from '@aws-cdk/aws-secretsmanager'
import * as lambda from '@aws-cdk/aws-lambda'

export class NumberWithIresolveStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const secret = sm.Secret.fromSecretCompleteArn(this, 'Secret', '[ARN]')

    new lambda.Function(this, 'LambdaFunction', {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: new lambda.InlineCode('exports.handler = function(event, context) {console.log("REQUEST RECEIVED:" + JSON.stringify(event))}"'),
      handler: 'index.handler',
      memorySize: secret.secretValueFromJson('maxMemory'),
      environment: {
        SECRET_VALUE: secret.secretValueFromJson('maxMemory').toString()
      }
    })
  }
}
```

Typescript objects that memorySize is a number but we know what we're doing so lets add a `// @ts-ignore`.  When we synth the template we are still not successful `Error: Resolution error: Supplied properties not correct for "CfnFunctionProps"`.  I believe there are guards beyond TypeScript against these properties based on the CloudFormation specifications.

### Proposed Solution

Naively I'd suggest anything that takes a 'number' today could take 'number | IResolvable' in the future?  Secret implements IResolable and so do SSM parameters so I think that would address it?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
