### ISSUE TITLE
(aws-events): RuleTargetInput.fromObject does not work with two EventField.fromPath fields

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#14927]
Background:
We run custom builds using AWS CodeBuild for pull request branches before the code is merged to the main branch. 

Basically, we trigger a CodeBuild running a buildspec for any branch that gets created to run linters, security scans etc..

To be able to identify which branch we are running in the buildspec we would need to include the `referenceFullName ` in the EventBridge event (see https://docs.aws.amazon.com/codecommit/latest/userguide/monitoring-events.html#referenceUpdated) to form the identifier: `refs/heads/main^12345678901234567890123467890123456789` (see https://docs.aws.amazon.com/codebuild/latest/userguide/sample-source-version.html)

It, however, seems this does not work.

### Reproduction Steps

```ts

export const addBranchBuildProject = (scope: cdk.Construct, vpc: ec2.IVpc | undefined, repository: codecommit.Repository, repositoryName: string, installCommands = ['npm ci'], testCommands: string[] = []) => {
  const projectName = `${repositoryName}-branch-build`;
  const project = new codebuild.Project(scope, projectName, {
    source: codebuild.Source.codeCommit({
      repository,
    }),
    environment: { buildImage: codebuild.LinuxBuildImage.STANDARD_5_0 },
    vpc,
    environmentVariables,
    projectName,
    buildSpec: createBuildSpec(installCommands, testCommands),
  });

  // Map CodeCommit 'detail.commitId' to CodeBuild project StartBuild API call 'sourceVersion'
  const event = events.RuleTargetInput.fromObject({
    projectName: `${repositoryName}-branch-build`,
    sourceVersion: `${events.EventField.fromPath('$.detail.referenceFullName')}^${events.EventField.fromPath('$.detail.commitId')}`,
  });
  repository.onReferenceUpdated('onReferenceUpdated', {
    target: new targets.CodeBuildProject(project, {
      event,
    }),
  });
};


```

### What did you expect to happen?

I would expect to combine `referenceFullName^commitId` successfully.

### What actually happened?

```
Invalid InputTemplate for target Target0 : [Source: (String)"{"projectName":"component-name-branch-build","sourceVersion":<detail-referenceFullName}>>^<<${detail-commitId>}"; line: 1, column: 84]. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: 70d489b9-b1c6-422c-a0da-ebecc6ccfe29; Proxy: null)

```

Generated YAML:

```
      Targets:
        - Arn:
            Fn::GetAtt:
              - componentnamebranchbuild12ECDC4C
              - Arn
          Id: Target0
          InputTransformer:
            InputPathsMap:
              detail-referenceFullName: $.detail.referenceFullName
              detail-commitId: $.detail.commitId
            InputTemplate: '{"projectName":"component-name-branch-build","sourceVersion":<detail-referenceFullName}>>^<<${detail-commitId>}'
          RoleArn:
            Fn::GetAtt:
              - componentnamebranchbuildEventsRole3EF137C4
              - Arn
```

### Environment

  - **CDK CLI Version  :** 1.106.1 (build c832c1b)
  - **Framework Version:** 1.106.1 (build c832c1b)
  - **Node.js Version:** NodeJs 14
  - **OS               :** macOs
  - **Language (Version):** TypeScript 4

### Other

--- 

This is :bug: Bug Report
