### ISSUE TITLE
Roles with Federated Principals

### ISSUE THREAD

**Issue by mindstorms6** [aws/aws-cdk#15]
Hello my favorite CDK friends! 

Roles are so fun! You can do amazing things with them - and I dig the way they feel right now. The `assumedBy(principal)` works really well for like most of the use cases and it's so much better than doing it by hand <3

However, I have a somewhat fun use case!

In building some things that use cognito as an IDP - I need to be able to set an assume role policy doc like (raw CFN):

```yaml
AssumeRolePolicyDocument: 
  Version: "2012-10-17" 
  Statement: 
    - Effect: "Allow" 
      Principal: 
        Federated: "cognito-identity.amazonaws.com" 
      Action: - "sts:AssumeRoleWithWebIdentity" 
      Condition: 
        StringEquals: 
          cognito-identity.amazonaws.com:aud:
            Ref: <some pool>
        ForAnyValue:StringLike:
          cognito-identity.amazonaws.com:amr: authenticated
```

_oh  iam 🤨_

The problem, and why I'm filing the issue: `RoleProps` takes an `assumedBy`, and then has this useful comment:

> You can later modify the assume role policy document by accessing it via the `assumeRolePolicy` property.

Which is true! However, the type of `assumeRolePolicy` is `PolicyDocument` which only allows me to

```
export class PolicyDocument extends Token {
    public resolve(): any;
    get isEmpty(): boolean;
    public addStatement(statement: PolicyStatement): PolicyDocument;
```

I'm not sure of the right way to handle this.

The "short term" fix (IMO) is to just take an `PolicyDocument` as part of `RoleProps`, and use it if passed (basically it's legal to pass either an `assumedBy` or an `assumeRolePolicyDoc` but not both type thing)

What's your thoughts?

I'm going to do what I mentioned above to make headway - but wanted to make sure this gets solved in a fun way

<3 brebre
