### ISSUE TITLE
(aws-rds): IVpc mismatch with Vpc

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#15000]
Using v1.107.0 for all modules

```
Type 'Vpc' is not assignable to type 'IVpc'.
  Types of property 'vpnGatewayId' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```

### Reproduction Steps

```ts
import { Vpc } from "@aws-cdk/aws-ec2"
import { ServerlessCluster } from "@aws-cdk/aws-rds"
import { Stack } from "@aws-cdk/core"
...

  const stack = new Stack()
  const vpc = new Vpc(stack, "VPC", {})
  const db = new ServerlessCluster(stack, "DB", {
    vpc,
  })
```

### Environment

  - **CDK CLI Version  :** 1.1.07.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** typescript 4.2.4

### Other

--- 

This is :bug: Bug Report

**Comment by longtv2222** [comment]
I'm using the same CDK CLI version (1.107.0) and typescript version (4.2.4) as you and I can't recreate the error.  The following is my code 

```
import { Vpc } from "@aws-cdk/aws-ec2"
import { DatabaseClusterEngine, ServerlessCluster } from "@aws-cdk/aws-rds"
import { Stack } from "@aws-cdk/core"

const stack = new Stack()
const vpc = new Vpc(stack, "VPC", {})
const db = new ServerlessCluster(stack, "DB", {
    vpc,
    engine: DatabaseClusterEngine.AURORA_MYSQL
})
```

I created my project with `cdk init app --language typescript` .

**Comment by njlynch** [comment]
Thanks for the report, @revmischa , and for the help @longtv2222 !

@revmischa  - Is it possible to create a reproducible example of this? Off-hand, it does seem like it's possible there's a stale version of one of the libraries lying around; have you tried a clean install?

**Comment by revmischa** [comment]
> Thanks for the report, @revmischa , and for the help @longtv2222 !
> 
> @revmischa - Is it possible to create a reproducible example of this? Off-hand, it does seem like it's possible there's a stale version of one of the libraries lying around; have you tried a clean install?

I agree it sounds like it, I triple-checked the versions and deleted node_modules and package-lock and reinstalled

I can reproduce it in this repo - https://github.com/jetbridge/typescript-cdk-template
I have to cast `Vpc` to `IVpc` here https://github.com/jetbridge/typescript-cdk-template/blob/33ecc38b2fa8f52d9ecf57b0c4d7cab6035b23ee/packages/infra/lib/stack.ts#L50

**Comment by njlynch** [comment]
Hm. I can't reproduce it in that repo:

```ts
% git clone git@github.com:jetbridge/typescript-cdk-template.git
% cd typescript-cdk-template
% npm ci
% npm run build
% // Edited the stack.ts file to uncomment the "new Database" line, and removed the explicit cast.
% cd packages/infra
% cdk synth
```

That produced a valid output, including a DB with the VPC configured:

```
  DB4924F778:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      DatabaseName: template
      DBClusterIdentifier: template
      DBClusterParameterGroupName: default.aurora-postgresql10
      DBSubnetGroupName:
        Ref: DBSubnets7B70DA43
      EnableHttpEndpoint: true
      EngineMode: serverless
      MasterUsername:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: DBSecretB8D1B379
            - :SecretString:username::}}
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: DBSecretB8D1B379
            - :SecretString:password::}}
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2
        SecondsUntilAutoPause: 28800
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - Fn::GetAtt:
            - DBSecurityGroup302CDD63
            - GroupId
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: template/DB/Resource
```

Can you try following the same steps and see if it builds cleanly in a new directory?
