### ISSUE TITLE
StageProps.MethodOptions: / is being replace by ~1 in ResourcePath

### ISSUE THREAD

**Issue by daniel-michael38** [aws/aws-cdk#15036]
### The Question
I'm utilizing AWS's CDK to develop our API layer. Everything has worked so far and now I am adding in caching. I enabled CacheCluster in the stage and am trying to enable it for a handful of my endpoints. The problem I am facing is the CDK is changing the resource path from something like `/v1/configuration` to `/~1v1~1configuration`. I've tried escaping my /s, but that didn't fix my issue.  I'm also not seeing any documentation on how the string key is suppose to be formatted for `MethodOptions`.

CDK C# Code
```
new Amazon.CDK.AWS.APIGateway.Stage(this, "stagename", new Amazon.CDK.AWS.APIGateway.StageProps
{
    Deployment = deployment,
    StageName = "stagename",
    Variables = stageVariables,
    CacheClusterEnabled = true,
    CacheClusterSize = "1.6",
    DataTraceEnabled = true,
    LoggingLevel = MethodLoggingLevel.INFO,
    MetricsEnabled = true,
    TracingEnabled = true,
    MethodOptions = new Dictionary<string, IMethodDeploymentOptions>
    {
        { "/v1/configuration/GET", new MethodDeploymentOptions { CachingEnabled = true }}
    }
});

```
Resulting Method Settings in the stage:
```
MethodSettings:
  - DataTraceEnabled: true
    HttpMethod: "*"
    LoggingLevel: INFO
    MetricsEnabled: true
    ResourcePath: /*
  - CachingEnabled: true
    HttpMethod: GET
    ResourcePath: /~1v1~1configuration
```
### Environment

  - **CDK CLI Version:** 1.107.0 (build 52c4434)
  - **Node.js Version:** v16.0.0
  - **OS:** MacOS Big Sur 11.3.1
  - **Language (Version):** C#

### Other information
Stackoverflow: https://stackoverflow.com/questions/67892528/aws-cdk-setting-cache-adding-tildes-to-resource-path
