### ISSUE TITLE
(aws-cloudformation): Problem deleting stack with NLB and EIP attached to it

### ISSUE THREAD

**Issue by alexs20** [aws/aws-cdk#15057]
Deleting stack that has Network-Load-Balancer with two Elastic IP addresses attached creates an error "API: ec2:disassociateAddress You do not have permission to access the specified resource."

### Reproduction Steps

Create stack using this template (please note it has subnet definition missing, use any public subnet)
```
AWSTemplateFormatVersion: '2010-09-09'
Description: "TEST Network Load Balancer w EIP"

Resources:
  NlbEIp1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: !Sub "EIP-NLB-AZ1"
  NlbEIp2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: !Sub "EIP-NLB-AZ2"
  NetworkLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    DependsOn:
      - NlbEIp1
      - NlbEIp2
    Properties:
      Name: !Sub "TEST-NLB"
      Scheme: "internet-facing"
      Type: "network"
      SubnetMappings:
        - AllocationId: !GetAtt NlbEIp1.AllocationId
          SubnetId: !Ref PublicSubnet1
        - AllocationId: !GetAtt NlbEIp2.AllocationId
          SubnetId: !Ref PublicSubnet2
      IpAddressType: "ipv4"
      LoadBalancerAttributes:
        - Key: "deletion_protection.enabled"
          Value: "false"
        - Key: "load_balancing.cross_zone.enabled"
          Value: "true"
        - Key: "access_logs.s3.enabled"
          Value: "false"
```

### What did you expect to happen?

The stack should be deleted, NLB deleted, EIP released

### What actually happened?

NLB deleted but EIP not released. Stack deletion failed with error

DATE	NlbEIp1	DELETE_FAILED	API: ec2:disassociateAddress You do not have permission to access the specified resource.
DATE	NlbEIp2	DELETE_FAILED	API: ec2:disassociateAddress You do not have permission to access the specified resource.

### Environment

Stack deletion invoked from AWS web console

--- 

This is :bug: Bug Report
