### ISSUE TITLE
aws-appflow: How to setup Salesforce to EventBridge

### ISSUE THREAD

**Issue by d1manson** [aws/aws-cdk#15134]
[Here's an AWS blog post](https://aws.amazon.com/blogs/compute/building-salesforce-integrations-with-amazon-eventbridge/) describing connecting Salesforce to EventBridge with AppFlow.

I have managed to do that using the web console (as shown in the blog screenshots), however I'm finding it very tough to do the same with cdk. I accept I may need to setup the initial "connection" to Salesforce using the web console but was hoping most of the other config could be done with cdk, especially the field mappings.

This is roughly what I have so far...

```ts
new CfnFlow(this, 'sfAccountChanges', {
    flowName: 'sfAccountChanges',
    sourceFlowConfig: {
        connectorType: "Salesforce",
        connectorProfileName: "a-connection-i-setup-manually", 
        sourceConnectorProperties: {
            salesforce: {
                object: "AccountChangeEvent",
                "enableDynamicFieldUpdate": false,
                "includeDeletedRecords": true
            }
        }
    },
    destinationFlowConfigList: [{
        connectorType: "EventBridge",
        destinationConnectorProperties: {
            eventBridge: {
                object: ????
            }
        }
    }],
    triggerConfig: {
        triggerType: 'Event'
    },
    tasks: [{ // let's ignore this for now..
        "taskType": "Map",
        "sourceFields": [],
        "taskProperties": [],
        "connectorOperator": {
            salesforce: "PROJECTION"
        }
    }]
});
```

In particular I'm really not clear how to create/reference the "partner source" in event bridge and what the `object` bit actually means in this context.

This is a 📕 documentation issue ..or is it a missing feature (I'm not sure)?

**Comment by d1manson** [comment]
Update...

I believe the `object` can be a string of the form  `aws.partner/appflow/salesforce.com/<aws-account-id>`. I presume you can't actually create that using cdk (yet), which isn't too terrible, though it would be nice if you could.

Also, the error I'm currently faced with seems to relate to the `tasks` section...
```
[Task Validation Error: You must specify a projection task or a MAP_ALL task]
```

I've tried all kinds of things but can't seem to get past that error. I have now noticed that there is a `Map_all` value mentioned in the enum for the [cli docs](https://docs.aws.amazon.com/cli/latest/reference/appflow/create-flow.html) - see first screenshot - but not in the enum for the [cloudformation docs](https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Task.html) - see second screenshot. At certainly when I try it with cdk it says it's an invalid value for the enum. Neither doc mentions "projection" in that context, but it does come up within the connectorOperator (though I haven't had any luck with that either).

cli:
![Screenshot 2021-06-17 at 11 59 50](https://user-images.githubusercontent.com/4244876/122384401-92690480-cf63-11eb-8d30-f60c4ef0a390.png)

cloudformation
![Screenshot 2021-06-17 at 11 59 36](https://user-images.githubusercontent.com/4244876/122384405-939a3180-cf63-11eb-8d88-5db34950a36f.png)

**Comment by rix0rrr** [comment]
It might be that the enum value you're looking for hasn't been implemented in CloudFormation yet. Unfortunately we are limited by CloudFormation as to what we can achieve.

I'm sorry, but it doesn't look like your issues are actually related to the CDK, but more to CloudFormation (and specifically CloudFormation's implementation of AppFlow -- it's always a tough call to figure out if problems are related to CFN or the service itself).

I would recommend you try to get help on StackOverflow with this, or the AWS Forums.

Best of luck.

**Comment by benbatesbrooke** [comment]
@d1manson not sure if you're still having an issue here, but I was running into similar issues and was able to resolve with following YML. Using SAM, I was able to deploy the stack below, which includes the LambdaFunction, AppFlow and EventBridge configuration. 
The only manual step is to create the Connection to Salesforce for the AppFlow....looking for a way to automate that as well.
Hope this is somewhat helpful.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template

Globals:
  Function:
    Timeout: 3

Resources:
  YourLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: your-lambda-function/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      FunctionName: your-lambda-function

  YourAppFlow:
    Type: AWS::AppFlow::Flow
    Properties:
      FlowName: YourAppFlow # this must match the Resource name
      Description: Flow for handling mapping Salesforce Platform Event
      TriggerConfig:
        TriggerType: Event
      SourceFlowConfig:
        ConnectorType: Salesforce
        ConnectorProfileName: your-salesforce-connector # this was created in AWS console
        SourceConnectorProperties:
          Salesforce:
            Object: Your_Platform_Event__e
            EnableDynamicFieldUpdate: false
            IncludeDeletedRecords: false
      DestinationFlowConfigList:
        - ConnectorType: EventBridge
          DestinationConnectorProperties:
            EventBridge:
              Object: PDFEventBus
      Tasks:
        - TaskType: Filter
          ConnectorOperator:
            Salesforce: PROJECTION
          SourceFields:
            - field_1__c
            - field_2__c
        - TaskType: Map
          SourceFields:
            - field_1__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: id
            - Key: DESTINATION_DATA_TYPE
              Value: id
          DestinationField: field_1__c
          ConnectorOperator:
            Salesforce: NO_OP
        - TaskType: Map
          SourceFields:
            - field_2__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: string
            - Key: DESTINATION_DATA_TYPE
              Value: string
          DestinationField: field_2__c
          ConnectorOperator:
            Salesforce: NO_OP
  
  YourEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "aws.partner/appflow/salesforce.com/${aws_account_id}/YourEventBus"
      EventSourceName: !Sub "aws.partner/appflow/salesforce.com/${aws_account_id}/YourEventBus"
    DependsOn: YourAppFlow
```
