### ISSUE TITLE
(kinesis): StreamEncryption supported region condition does not respect allocateLogicalId

### ISSUE THREAD

**Issue by straygar** [aws/aws-cdk#15224]
### Reproduction Steps
1. Create a Stack, which implements `allocateLogicalId`, adding a static prefix to resource name
2. Create a `kinesis.Stream` in this stack
3. `cdk deploy`

### What did you expect to happen?
Stack deploys successfully

### What actually happened?
Stack deployment fails, with the error message:
```
Error [ValidationError]: Template error: unresolved condition dependency AwsCdkKinesisEncryptedStreamsUnsupportedRegions in Fn::If
```

### Environment

  - **CDK CLI Version  :** 1.109.0
  - **Framework Version:** 1.109.0
  - **Node.js Version:**  14.17.1
  - **OS               :** MacOS
  - **Language (Version):**  TypeScript

### Other

Looking into the template, the cause appears to be a hard-coded key somewhere:
```
Resources:
  straygarKinesisStream46752A3E:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      RetentionPeriodHours: 24
      StreamEncryption:
        Fn::If:
          - AwsCdkKinesisEncryptedStreamsUnsupportedRegions  # no prefix
          - Ref: AWS::NoValue
          - EncryptionType: KMS
            KeyId: alias/aws/kinesis
```

but the actual condition has its logical ID changed, causing the unresolved error:
```
Conditions:
  straygarAwsCdkKinesisEncryptedStreamsUnsupportedRegions:  # has the prefix
    Fn::Or:
      - Fn::Equals:
          - Ref: AWS::Region
          - cn-north-1
      - Fn::Equals:
          - Ref: AWS::Region
          - cn-northwest-1
```

--- 

This is :bug: Bug Report
