### ISSUE TITLE
(aws-stepfunctions): A way to opt out of granting IAM permissions to step function tasks

### ISSUE THREAD

**Issue by mcintyre94** [aws/aws-cdk#15292]
When a step function is created using CDK, its role is granted the permissions required to run it - for example lambda invoke on any lambdas. My feature request is a parameter (optional, defaulting to false) that can opt out of this functionality.

### Use Case

When testing my step functions locally, I use a combination of localstack and SAM.

- The lambdas are run with sam using `sam local start-lambda --port 3001 --env-vars local-env.json`
- Localstack is started using `localhost:3001` as its `STEPFUNCTIONS_LAMBDA_ENDPOINT`
- I deploy the stack to localstack + run it

Since SAM does not have an ARN for each lambda, I have to reference them by name (not ARN) in my step function. This works fine - I can create a step function with a stage that invokes `WorkflowStepExecuteFunction` by name and it will be run. Note that this isn't really a hack - step functions support invoking a lambda by name or ARN according to the documentation: https://docs.aws.amazon.com/step-functions/latest/dg/connect-lambda.html 

However when I'm trying to migrate to CDK I end up with a permission on the role:

```
  dailySentimentUpdatestateMachineRoleDefaultPolicy3E9E01E4:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource: WorkflowStepExecuteFunction
        Version: "2012-10-17"
      PolicyName: dailySentimentUpdatestateMachineRoleDefaultPolicy3E9E01E4
      Roles:
        - Ref: dailySentimentUpdatestateMachineRoleA2B53DC7
    Metadata:
      aws:cdk:path: CdkTestStack/dailySentimentUpdate/stateMachineRole/DefaultPolicy/Resource
```

This rightly fails to deploy to either AWS or localstack, with the error `Resource WorkflowStepExecuteFunction must be in ARN format or "*"`

### Proposed Solution

For my use case I'd be happy to give a permission of `*`, allowing the step function to invoke any lambda. I can create a role myself with this permission and pass it to the step function.

The only thing I need from CDK is an optional parameter (defaults false) named something like `skipAddingPermissionsToRole`. If this is set and true, then the role passed to the step function does not gain any permissions. 

### Other

I haven't tried this yet but I think this would involve putting an if around this part of the constructor: https://github.com/aws/aws-cdk/blob/4330fe82f6200499dae8fd614679eeac0db67f0b/packages/%40aws-cdk/aws-stepfunctions/lib/state-machine.ts#L406

```typescript
if(!props.skipAddingPermissionsToRole) {
      for (const statement of graph.policyStatements) {
          this.addToRolePolicy(statement);
     } 
}
```

I think if this prop was added then it would be worth throwing an error if `role` is not passed and the new prop is set to true. Since this would create a new role with no permissions and not work.

* [x] :wave: I may be able to implement this feature request
~~:warning: This feature might incur a breaking change~~

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
What code did you write to get LambdaInvoke to create the policy you cite? To me, the proper way of working around this particular case is to modify the task definition (by overriding [`LambdaInvoke.toStateJson`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.LambdaInvoke.html#towbrstatewbrjson)) to use the function name instead of the function ARN in `Parameters.FunctionName`, as well as adding a `*` policy to the state machine role. Please let me know if you need more details.

To address the feature request as a whole, the use-case you cite is not compelling enough to modify the API of `StateMachine` so drastically. I'm happy to discuss further if you have any questions!

**Comment by mcintyre94** [comment]
@BenChaimberg here's a minimal repro:

```typescript
#!/usr/bin/env node
import * as cdk from '@aws-cdk/core';
import * as iam from '@aws-cdk/aws-iam'
import * as lambda from '@aws-cdk/aws-lambda'
import * as stepfunctions from '@aws-cdk/aws-stepfunctions'
import { LambdaInvoke } from '@aws-cdk/aws-stepfunctions-tasks'

class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const stateMachineRole = new iam.Role(this, 'stateMachineRole', {
      assumedBy: new iam.ServicePrincipal('states.amazonaws.com')
    })

    // We need to allow lambda:* because IAM roles only work with ARNs or *
    // And when we run locally we don't have an ARN for the WorkflowStepExecute function
    stateMachineRole.addToPolicy(new iam.PolicyStatement({
      resources: ['*'],
      actions: ['lambda:InvokeFunction'],
    }));

    // When running locally we use a lambda name not ARN
    const lambdaName = 'WorkflowStepExecuteFunction'
    const executeLambda = lambda.Function.fromFunctionArn(this, 'executeLambda', lambdaName)

    const definition = new LambdaInvoke(this, 'execute-lambda', {
      lambdaFunction: executeLambda
    })

    new stepfunctions.StateMachine(this, "StateMachine", {
      stateMachineName: "StateMachineName",
      definition,
      stateMachineType: stepfunctions.StateMachineType.STANDARD,
      role: stateMachineRole,
    });
  }
}

const app = new cdk.App();
new MyStack(app, 'app')
```

This synthesises to the following template:

```yaml
Resources:
  stateMachineRole0282B2BF:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: app/stateMachineRole/Resource
  stateMachineRoleDefaultPolicyFA97A916:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource: WorkflowStepExecuteFunction
        Version: "2012-10-17"
      PolicyName: stateMachineRoleDefaultPolicyFA97A916
      Roles:
        - Ref: stateMachineRole0282B2BF
    Metadata:
      aws:cdk:path: app/stateMachineRole/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - stateMachineRole0282B2BF
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"execute-lambda","States":{"execute-lambda":{"End":true,"Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"WorkflowStepExecuteFunction","Payload.$":"$"}}}}
      StateMachineName: StateMachineName
      StateMachineType: STANDARD
<snip>
```

So the role policy has the invalid statement:

```
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource: WorkflowStepExecuteFunction
```

But per the documentation I linked in my initial comment the lambda invoke ` :states:::lambda:invoke","Parameters":{"FunctionName":"WorkflowStepExecuteFunction","Payload.$":"$"}}}}` is perfectly valid. It just can't be used as a plain name in an IAM statement.

---

I don't think I've understood the workaround you suggested. Is the result of `toStateJson` used to populate `graph.policyStatements`? To be clear the function name works fine in `Parameters.FunctionName`, it just doesn't work in the generated IAM statement. If I can override the policy statement generated for the `LambdaInvoke` that's ending up on `graph.policyStatements` that would definitely solve the issue, I'm just not sure how that's generated?
