### ISSUE TITLE
(aws-cloudtrail): incorrect Trail synthesis when management_events is False

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-cdk#15488]
Deploying a CloudTrail Trail which has `management_events=ReadWriteType.NONE` and a data event (S3 event selector) raises the following error in CFN:
```
Invalid combination of parameters in EventSelectors. When includeManagementEvents is false, DataResources must not be empty (Service: AWSCloudTrail; Status Code: 400; Error Code: InvalidEventSelectorsException; Request ID: 0dfd3be1-f327-4e8b-aa77-64a07c59059c; Proxy: null)
```

### Reproduction Steps
Below code will reproduce the error. Make sure to replace the `account` with a valid AWS account ID:
```
#!/usr/bin/env python3

from aws_cdk.aws_cloudtrail import ReadWriteType, S3EventSelector, Trail
from aws_cdk.aws_kms import Key
from aws_cdk.aws_s3 import BlockPublicAccess, Bucket, BucketAccessControl, BucketEncryption
from aws_cdk.core import App, Construct, Environment, RemovalPolicy, Stack

class TrailBugStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cmk: Key = Key(
            self,
            "bucket-cmk",
            trust_account_identities=True,
        )

        bucket: Bucket = Bucket(
            self,
            "bucket",
            bucket_name=f"my-bucket-{self.region}-{self.account}",
            encryption=BucketEncryption.KMS,
            encryption_key=cmk,
            versioned=False,
            access_control=BucketAccessControl.BUCKET_OWNER_FULL_CONTROL,
            block_public_access=BlockPublicAccess.BLOCK_ALL,
            removal_policy=RemovalPolicy.DESTROY,
        )

        Trail(
            self,
            "trail",
            is_multi_region_trail=False,
            include_global_service_events=False,
            management_events=ReadWriteType.NONE,
        ).add_s3_event_selector(
            s3_selector=[
                S3EventSelector(bucket=bucket)
            ]
        )


app = App()
TrailBugStack(app, "TrailBugStack", env=Environment(account="111111111111", region="us-east-1"))

app.synth()
```

Now for the interesting part. I have used `cfn-flip` to flip the synthesized template from JSON to YAML and the event selector section of the trail definition looks like this:
```
      EventSelectors:
        - IncludeManagementEvents: false
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Join
                  - ''
                  - - !GetAtt 'bucket43879C71.Arn'
                    - /
```
 If you remove the hyphen before `DataResources`:
```
      EventSelectors:
        - IncludeManagementEvents: false
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Join
                  - ''
                  - - !GetAtt 'bucket43879C71.Arn'
                    - /
```
and try to deploy the resulting YAML template, it succeeds. Whereas with the hyphen it fails. So it looks to me like the `cdk synth` for a CloudTrail Trail is broken.

### Environment

  - **CDK CLI Version : 1.110.1**
  - **Framework Version: 1.110.1**
  - **Node.js Version: v16.4.0** 
  - **OS: macOS Catalina**
  - **Language (Version): Python 3.7.7** 

--- 

This is :bug: Bug Report
