### ISSUE TITLE
cloudformation-include: CfnInclude loses some parameter references in resource definitions

### ISSUE THREAD

**Issue by oshaughnessy** [aws/aws-cdk#16046]
Hi. I'm using the python version of cdk. I've tried this in both recent versions of cdk 1 and the latest cdk 2.

Using `aws_core.cloudformation_include.CfnInclude()` to import a template results in some parameter refs in resource definitions getting lost, where they change from `!Ref _param_name_` to `_stack_name_/_param_name_`.

The behavior happens consistently with the same sets of parameters/reference points. Native `aws_cdk.CfnParameter` constructs are being passed via `CfnInclude(parameters=...)` with all of the parameters discovered in the template as discovered before calling `CfnInclude`. Some of them are retained in the resulting template resources with `Fn::Ref`, but others are converted to strings as described above.

### Reproduction Steps

Given this CloudFormation template stored as `template.yaml`:

```yaml
---
Parameters:
 BucketName:
   Type: AWS::SSM::Parameter::Value<String>
   Default: /lambdas/BucketName
   Description: $ssm$ BucketName where lambda deployment packages are stored
 ZipFilePrefix:
   Type: String
   Default: dev
   Description: $alfred$ deployment package of lambda
Resources:
 SSMParameter:
   Type: AWS::SSM::Parameter
   Properties:
     Type: String
     Name:
       Ref: BucketName
     Value:
       Fn::Join:
         - "/"
         - - Ref: ZipFilePrefix
           - my-lambda-code-1.2.3.zip
```

and given this Python `requirements.txt` installed in a venv:

```
aws-cdk-lib>=2.0.0rc1
constructs>=10.0.0
ruamel.yaml
```

this Python 3 code exhibits the bug in question:

```py
#!/usr/bin/env python3

import constructs
import aws_cdk
import aws_cdk.cloudformation_include
import ruamel.yaml

TEMPLATE_PATH = './template.yaml'
CDK_OUTDIR = 'cdk-output'


def read_yaml(path: str) -> dict:
    """Process a string as YAML data
    returns: dict representing the YAML object structure
    """

    yaml = ruamel.yaml.YAML()
    yaml.default_flow_style = False

    with open(path, "r") as file_path:
            data = file_path.read()
            yaml_dict = yaml.load(data)
    return yaml_dict


def main():
   app = aws_cdk.App(outdir=CDK_OUTDIR)
   stack_name = 'cdk-16046-test'
   stack = aws_cdk.Stack(app, stack_name)
   template_dict = read_yaml(TEMPLATE_PATH)
   parameters = template_dict.get('Parameters', {})

   import_params = {}
   for (param, pinfo) in parameters.items():
       import_params[param] = aws_cdk.CfnParameter(
           stack, param,
           type=pinfo['Type'],
           description=pinfo.get('Description', ''),
           default=pinfo.get('Default', '')
       )


   aws_cdk.cloudformation_include.CfnInclude(
       stack, 'test_data',
       template_file=TEMPLATE_PATH,
       preserve_logical_ids=False,
       parameters=import_params
   )


if __name__ == '__main__':
   main()
```

### What did you expect to happen?

All `!Ref`s from my imported template should be represented as `Fn::Ref`s in the synthesized stack.

### What actually happened?

Some parameter references from my imported template are represented as strings following the pattern `_stack_name_/_param_name_`.

From the example above:

```json
{
 "Parameters": {
   "BucketName": {
     "Type": "AWS::SSM::Parameter::Value<String>",
     "Default": "/lambdas/BucketName",
     "Description": "$ssm$ BucketName where lambda deployment packages are stored"
   },
   "ZipFilePrefix": {
     "Type": "String",
     "Default": "dev",
     "Description": "$alfred$ deployment package of lambda"
   },
   "BootstrapVersion": {
     "Type": "AWS::SSM::Parameter::Value<String>",
     "Default": "/cdk-bootstrap/hnb659fds/version",
     "Description": "Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store."
   }
 },
 "Resources": {
   "testdataSSMParameter1389DF25": {
     "Type": "AWS::SSM::Parameter",
     "Properties": {
       "Type": "String",
       "Value": {
         "Fn::Join": [
           "/",
           [
             {
               "Ref": "ZipFilePrefix"
             },
             "my-lambda-code-1.2.3.zip"
           ]
         ]
       },
       "Name": "cdk-16046-test/BucketName"
     }
   }
 },
...
```

### Environment

  - **CDK CLI Version  :** 2.0.0-rc.17
  - **Framework Version:** 2.0.0rc17
  - **Node.js Version:** v12.18.3
  - **OS               :** centos7
  - **Language (Version):** Python 3.8.6

### Other

Example:

Original template has a definition like this:

```yaml
Parameters:
    BucketName:
      Type: String
      Default: my-bucket-name
      Description: $something$ BucketName where Lambda code is stored
    LambdaZipPrefix:
      Type: String
      Default: lambdas/
      Description: $something$ S3 object prefix where Lambda zip files are kept

Resources:
    LambdaFunctionSOMEHASH:
        Type:  AWS::Lambda::Function
        Properties:
          Code:
            S3Bucket:
              Ref: BucketName
            S3Key:
              Fn::Join:
                - ""
                -  - Ref: LambdaZipPrefix
                    - /my-lambda.zip
            Handler: ...
```

Resulting template has a definition like this:

```yaml
Parameters:
    BucketName:
      Type: String
      Default: my-bucket-name
      Description: $something$ BucketName where Lambda code is stored
    LambdaZipPrefix:
      Type: String
      Default: lambdas/
      Description: $something$ S3 object prefix where Lambda zip files are kept

Resources:
    LambdaFunctionNEWCDKHASH:
        Type:  AWS::Lambda::Function
        Properties:
          Code:
            S3Bucket: my-cdk-stack/BucketName
            S3Key:
              Fn::Join:
                - ''
                -  - Ref: LambdaZipPrefix
                    - /my-lambda.zip
            Handler: ...
```

--- 

This is :bug: Bug Report
