### ISSUE TITLE
(cognito): Ability to add/delete/update a scope attached to a Resource Server

### ISSUE THREAD

**Issue by ameya-parab** [aws/aws-cdk#16123]
### The Question

As part of our build pipelines, we have business requirements to add/update/delete scope/s attached to an existing resource server. The templates are synthesized using AWS CDK for python and seem to lack such functionality. Currently, the user_pool has a method [add_resource_server](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html#resource-servers), which creates a new resource server but it does not allow the developer to add or delete scopes from an existing resource server. We thought when running a 'cdk deploy' to provision an already existing resource server with a new scope, the cdk utility would perform a 'cdk diff' before assuming that the resource server needs to be created.

**Already Existing Resource Server**

```yaml
userpoolresourceserverRS1AAFC7C48:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
        Identifier: RS1
        Name: RS1
        UserPoolId: region_abcdef
        Scopes:
            - ScopeDescription: Authentication scope for client_1
               ScopeName: client_1.read
```

**Adding a Scope to an already existing Resource Server**

```yaml
userpoolresourceserverRS1AAFC7C48:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
        Identifier: RS1
        Name: RS1
        UserPoolId: region_abcdef
        Scopes:
            - ScopeDescription: Authentication scope for client_1
               ScopeName: client_1.read
            - ScopeDescription: Authentication scope for client_2
               ScopeName: client_2.read
```

When deploying the second YAML file, the cdk utility does not perform a 'cdk diff' to analyze what resources/properties are already deployed, but instead tries to recreate the resource server.

### Environment

  - **CDK CLI Version:** 1.110.0
  - **Module Version:**  1.110.0
  - **Node.js Version:** aws-cdk@1.110.0
  - **OS:** Linux
  - **Language (Version):** python: 3.8

### Other information
Because of the above scenario, the 'cdk deployment' errors out when trying to create an user pool app client, as the scope is not attached to the resource server, when the app client is being provisioned.

```log
APP01-NVSGISRSSR36-MODELLAMBDA-295-xgboostwineclassify: deploying...
--
1046 | STACK_NAME: creating CloudFormation changeset...
1047 | 0/11 \|7:12:14 PM \| REVIEW_IN_PROGRESS   \| AWS::CloudFormation::Stack           \| STACK_NAME User Initiated
1048 | 0/11 \|7:12:20 PM \| CREATE_IN_PROGRESS   \| AWS::CloudFormation::Stack           \| STACK_NAME User Initiated
1049 | 0/11 \|7:12:45 PM \| CREATE_IN_PROGRESS   \| AWS::Cognito::UserPoolResourceServer \| user_pool/RS1 (userpoolresourceserver)
1050 | 2/11 \|7:12:46 PM \| CREATE_IN_PROGRESS   \| AWS::CDK::Metadata                   \| CDKMetadata/Default (CDKMetadata)
1051 | 2/11 \|7:12:47 PM \| CREATE_IN_PROGRESS   \| AWS::Cognito::UserPoolResourceServer \| user_pool/RS1 (userpoolresourceserver) Resource creation Initiated
1052 | 2/11 \|7:12:47 PM \| CREATE_COMPLETE      \| AWS::Cognito::UserPoolResourceServer \| user_pool/RS1 (userpoolresourceserver)
1053 | 2/11 \|7:12:47 PM \| CREATE_IN_PROGRESS   \| AWS::CDK::Metadata                   \| CDKMetadata/Default (CDKMetadata) Resource creation Initiated
1054 | 2/11 \|7:12:47 PM \| CREATE_COMPLETE      \| AWS::CDK::Metadata                   \| CDKMetadata/Default (CDKMetadata)
1055 | 2/11 \|7:12:49 PM \| CREATE_IN_PROGRESS   \| AWS::Cognito::UserPoolClient         \| user_pool/app_client (userpoolappclient)
1056 | 2/11 \|7:12:50 PM \| CREATE_FAILED        \| AWS::Cognito::UserPoolClient         \| user_pool/app_client (userpoolappclientF524FE77) Invalid scope requested: RS1/client_2.read (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ScopeDoesNotExistException; Request ID: 85981a30-f574-464b-aa24-4e5bbbd0c038; Proxy: null)
1057 | new UserPoolClient (/tmp/jsii-kernel-JRGFqR/node_modules/@aws-cdk/aws-cognito/lib/user-pool-client.js:163:26)
1058 | \_ ImportedUserPool.addClient (/tmp/jsii-kernel-JRGFqR/node_modules/@aws-cdk/aws-cognito/lib/user-pool.js:163:16)
1059 | \_ /tmp/tmpbfz6xage/lib/program.js:8183:134
1060 | \_ Kernel._wrapSandboxCode (/tmp/tmpbfz6xage/lib/program.js:8795:24)
1061 | \_ /tmp/tmpbfz6xage/lib/program.js:8183:107
1062 | \_ Kernel._ensureSync (/tmp/tmpbfz6xage/lib/program.js:8776:28)
1063 | \_ Kernel.invoke (/tmp/tmpbfz6xage/lib/program.js:8183:34)
1064 | \_ KernelHost.processRequest (/tmp/tmpbfz6xage/lib/program.js:9692:36)
1065 | \_ KernelHost.run (/tmp/tmpbfz6xage/lib/program.js:9655:22)
1066 | \_ Immediate._onImmediate (/tmp/tmpbfz6xage/lib/program.js:9656:46)
1067 | \_ processImmediate (internal/timers.js:461:21)
1068 | 2/11 \|7:12:51 PM \| ROLLBACK_IN_PROGRESS \| AWS::CloudFormation::Stack           \| STACK_NAME The following resource(s) failed to create: [userpoolappclient]. Rollback requested by user.
```
