### ISSUE TITLE
(aws_logs): CfnMetricFilter  - missing quotes on filter_pattern param

### ISSUE THREAD

**Issue by ilsurih** [aws/aws-cdk#16278]
I am using CfnMetricFilter to create alert based on log event text, AWS CF fails to apply synthed template with error:
```
Invalid metric filter pattern (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 26b1...-...-...76c8; Proxy: null)
```

### Reproduction Steps
```
CfnMetricFilter(
            self,
            id="NoRecordsMetricFilter",
            log_group_name="/aws/lambda/function_name",
            filter_pattern="My error text",
            metric_transformations=[
                CfnMetricFilter.MetricTransformationProperty(
                    metric_namespace="my-namespace",
                    metric_name="NoRecordsCountError",
                    metric_value="1",
                )
            ],
        )
```
### What did you expect to happen?
log patten attribute must be wrapped with double quotes:
`      FilterPattern: "My error text" `

### What actually happened?

This code translates to the following cfn resource:
```
  NoRecordsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: My error text #FIXME: this field must be quoted 
      LogGroupName: /aws/lambda/function_name
      MetricTransformations:
        - MetricName: NoRecordsCountError
          MetricNamespace: my-namespace
          MetricValue: "1"
```

### Environment

  - **CDK CLI Version  :** 1.119.0 (build 2921d64)
  - **Framework Version:**
  - **Node.js Version:** v16.8.0
  - **OS               :** MacOS 11.5.2
  - **Language (Version):** Python 3.9

### Other
I noticed that the param is wrapped with quotes if it contains any special symbol, like ! at the beginning, so probably default output should be wrapped with quotes too

--- 

This is :bug: Bug Report
