### ISSUE TITLE
(codebuild): Unable to read temporary credentials from environment in codebuild container

### ISSUE THREAD

**Issue by kontinuity** [aws/aws-cdk#16272]
I am trying to run a `cdk deploy` command from within codebuild. Based on research the cdk roles do not work and the container itself needs to be prepped for role change. I used the `buildspec.yml` to fetch temp credentials via sts and set it in the env but cdk deploy does not see them.

### Reproduction Steps

0000 is my redacted but valid account id. I can see the echo output in pipeline.

```
 build:
    commands:
      - echo Dev Build starting...
      - ASSUME_ROLE_ARN="arn:aws:iam::00000:role/RoleNameForBuild"
      - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test)
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - echo $AWS_SESSION_TOKEN
      - cdk deploy
```
### What did you expect to happen?

The cdk cli sees the env variables and uses the assumed role credentials to perform the build actions i.e. cdk deploy.

### What actually happened?

cdk fails with the following error:
```
Need to perform AWS calls for account 00000, but no credentials have been configured
```

### Environment

  - **CDK toolkit version: 1.120.0 (build 6c15150)**
  - **Node.js Version: 14**
  - **OS               : LinuxBuildImage.STANDARD_5_0,**
  - **Language (Version): Typescript 4.4.2**

### Other

```
Need to perform AWS calls for account 000000, but no credentials have been configured
Error: Need to perform AWS calls for account 000000, but no credentials have been configured
    at SdkProvider.forEnvironment (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:149:46)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CloudFormationDeployments.prepareSdkFor (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:252:22)
    at CloudFormationDeployments.readCurrentTemplate (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:166:26)
    at CdkToolkit.deploy (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:161:33)
    at initCommandLine (/usr/local/share/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:214:9)
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @kontinuity,

thanks for opening the issue. Can you add a line `aws sts get-caller-identity` to the buildspec right after you set your environment variables, and see whether that succeeds?

Thanks,
Adam

**Comment by kontinuity** [comment]
@skinny85 Through trial and error the issue seems to be that the environment either does not persist across commands even though buildspec version is 0.2 OR cdk is unable to read the env variables.

`cdk -v` throws an error with:

```
Resolving default credentials
Unable to determine the default AWS account: Error: ENOENT: no such file or directory, open '/root/.aws/credentials'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.readFileSync (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Object.getProfilesFromSharedConfig (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/util.js:976:41)
    at ProcessCredentials.load (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/credentials/process_credentials.js:75:31)
    at ProcessCredentials.coalesceRefresh (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/credentials.js:205:12)
    at ProcessCredentials.refresh (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/credentials/process_credentials.js:163:10)
    at ProcessCredentials.get (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/credentials.js:122:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/.aws/credentials'
}
```

I eventually have fallen back to manually writing a `/root/.aws/credentials` file via `aws sts get-session-token` while elevating the role of the pipeline stack.

**Comment by skinny85** [comment]
Can you actually try just creating an empty `/root/.aws/credentials` (literally just `touch /root/.aws/credentials`), and see if that helps?

**Comment by kontinuity** [comment]
@skinny85 Tried that too. It only suppresses the error (which by the way only shows up with `-v`) but does not solve the reading of env variables in CodeBuild container.

**Comment by skinny85** [comment]
Sorry, I'm not sure I understand what you mean.

Can you show me the buildspec, and the full output of `cdk deploy -v`, after you add the `touch /root/.aws/credentials` command to the buildspec?

**Comment by ryparker** [comment]
@kontinuity were you able to resolve this?

**Comment by kontinuity** [comment]
@ryparker Generated temp credentials as part of install in buildspec.yml

```
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Build is starting now...
      - echo Generating AWS credentials file
      - mkdir -p /root/.aws
      - touch /root/.aws/credentials
      - aws sts get-caller-identity
      - ASSUME_ROLE_ARN="arn:aws:iam::0000000000:role/XXXX"
      - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test)
      - echo $TEMP_ROLE
      - export CDK_DEFAULT_ACCOUNT=0000000000
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretA
      - ccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - echo "[default]" | tee -a /root/.aws/credentials
      - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" | tee -a /root/.aws/credentials
      - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" | tee -a /root/.aws/credentials
      - echo "aws_session_token=${AWS_SESSION_TOKEN}" | tee -a /root/.aws/credentials
      - aws sts get-caller-identity
      - echo Installing source dependencies...
      - cp .env.dev .env.local
      - yarn global add aws-cdk --silent
      - yarn --silent --frozen-lockfile
```
