### ISSUE TITLE
(aws-cloudfront,aws-cloudfront-origins): Wrong domain name for importing the existing S3(not created in the same region with CloudFront CDK stack) as a origin in CF

### ISSUE THREAD

**Issue by terrificdm** [aws/aws-cdk#16386]
When you import the exisiting S3 bucket as S3 origin for CloudFront, if the bucket was not created in the same region which is defined in .evn.region for CloudFront CDK stack, you will get the wrong domain name(wrong region flag) for the S3 origin.

### Reproduction Steps

```
# bin/test.ts

#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { TestStack } from '../lib/test-stack';

const app = new cdk.App();
new TestStack(app, 'TestStack', {
  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-1' }
});


# lib/test-stack.ts

import * as cdk from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';
import * as cloudfront from '@aws-cdk/aws-cloudfront';
import * as origins from '@aws-cdk/aws-cloudfront-origins';
import * as iam from '@aws-cdk/aws-iam';

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const s3BucketName = 'demo2cloudfront' // The existing bucket which was created in other region rather than the region of this stack.
    
    const s3Origin = s3.Bucket.fromBucketName(this, 'ImportBucket', s3BucketName);
    
    const oai = new cloudfront.OriginAccessIdentity(this, 'OAI'); // Create an OAI for CloudFront to use
    
    const policyStatement = new iam.PolicyStatement({
      actions:    [ 's3:GetObject' ],
      resources:  [ s3Origin.arnForObjects("*") ],
      principals: [ oai.grantPrincipal ],
    }); 
    
    new s3.BucketPolicy(this, 'cloudfrontAccessBucketPolicy', {
      bucket: s3Origin,
    }).document.addStatements(policyStatement); 
    
    new cloudfront.Distribution(this, 'myDist', {
      defaultBehavior: {origin: new origins.S3Origin(s3Origin, {originAccessIdentity: oai})}
      });
  }
}
```

### What did you expect to happen?

The existing bucket was created seperated in the other region, e.g. "us-east-2", so the domain name of the bucket should be demo2cloudfront.s3.us-east-2 in CloudFront origin configuration, but it became demo2cloudfront.s3.us-east-1...

### What actually happened?

Because of wrong domain name of the bucket, the CloudFront cannot access the S3 origin. And when you conduct "cdk synth", you will find that the wong region is synthesized for constructing the domain name of S3 as below.
```
 Origins:
          - DomainName:
              Fn::Join:
                - ""
                - - demo2cloudfront.s3.us-east-1.
                  - Ref: AWS::URLSuffix
            Id: TestStackmyDistOrigin17D42EFBD
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: OAIE1EFC67F
```
The reason to deploy S3 and CloudFront seperately is we want to decouple Infra/App/CDN layer in different CDK apps/stacks, and because L@E which we are going to use is forced to be opted in us-east-1, so we set .env.region as us-east-1 for CloudFront Stack. 

### Environment

  - **CDK CLI Version  :** 1.121.0
  - **Framework Version:** 1.121.0
  - **Node.js Version:** v10.24.1
  - **OS               :**Amazon Linux2
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report
