### ISSUE TITLE
(aws-s3): Enabling autoDeleteObjects tries to create a new role via custom resource provider

### ISSUE THREAD

**Issue by haslam22** [aws/aws-cdk#16459]
## :question: General Issue

When enabling `autoDeleteObjects` in the `Bucket` construct in `aws-s3`, the following `CustomResourceProvider` lambda and role gets added to my CloudFormation template:

```
CustomS3AutoDeleteObjectsCustomResourceProviderRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
    ManagedPolicyArns:
     - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  Metadata:
    aws:cdk:path: my-stack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Role
CustomS3AutoDeleteObjectsCustomResourceProviderHandler:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      S3Bucket:
        Ref: AssetParametersBucket
      S3Key:
        Fn::Join:
          - ""
          - - Fn::Select:
                - 0
                - Fn::Split:
                    - "||"
                    - Ref: AssetParametersVersionKey
            - Fn::Select:
                - 1
                - Fn::Split:
                    - "||"
                    - Ref: AssetParametersVersionKey
    Timeout: 900
    MemorySize: 128
    Handler: __entrypoint__.handler
    Role:
      Fn::GetAtt:
        - CustomS3AutoDeleteObjectsCustomResourceProviderRole
        - Arn
    Runtime: nodejs12.x
    Description:
      Fn::Join:
        - ""
        - - "Lambda function for auto-deleting objects in "
          - Ref: mybucket
          - " S3 bucket."
  DependsOn:
    - CustomS3AutoDeleteObjectsCustomResourceProviderRole
  Metadata:
    aws:cdk:path: my-stack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler
```

However, I'm working in a locked down corporate AWS account where I don't have permissions to create a new role. There are some preset roles that I'm allowed to use instead. Unfortunately the above fails because of this and my stack doesn't deploy with the following error:

`API iam:CreateRole User: ... is not authorized to perform iam:CreateRole on resource: CustomS3AutoDeleteObject...` 

(Code reference for where this role gets created: https://github.com/aws/aws-cdk/blob/3e9f04dbbd7aadb8ab4394fefd6281f1d6d30fe0/packages/%40aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts#L193)

In some other areas of CDK, this is mitigated by allowing the user to specify a lambda execution role. For example the `BucketDeployment` construct in `aws-s3-deployment` (also powered by lambda functions under the hood) allows providing a pre-existing lambda execution role ARN that is used instead:

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-deployment.BucketDeployment.html#construct-props

And so using this role prop, I can provide a pre-existing lambda execution role and not run into this issue. I can't see this being possible in `CustomResourceProvider` though.

### The Question

Is there any way to use the `autoDeleteObjects` functionality in the `Bucket` construct without it creating a new role for which I don't have permissions to create?

### Environment

  - **CDK CLI Version:** 1.115.0
  - **Module Version:** 1.100.0
  - **Node.js Version:** 14.17.3
  - **OS:** CentOS 7
  - **Language (Version):** Typescript 3.9.9
