### ISSUE TITLE
(AWS Config): EC2_INTERNET_GATEWAY maps to the wrong Resource Type

### ISSUE THREAD

**Issue by Pandafriendd** [aws/aws-cdk#16463]
`EC2_INTERNET_GATEWAY` maps to the wrong Resource Type

### Reproduction Steps

This bug can be replicated by below snippet:

```
new config.ManagedRule(this, "myRule", {
      identifier: config.ManagedRuleIdentifiers.INTERNET_GATEWAY_AUTHORIZED_VPC_ONLY,
      ruleScope: config.RuleScope.fromResource(config.ResourceType.EC2_INTERNET_GATEWAY),
    })
```

Synthesized template looked like:

```
Resources:
  myRule463F9234:
    Type: AWS::Config::ConfigRule
    Properties:
      Source:
        Owner: AWS
        SourceIdentifier: INTERNET_GATEWAY_AUTHORIZED_VPC_ONLY
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::CustomerGateway
```

### What did you expect to happen?

`ComplianceResourceTypes` in synthesized template should be `AWS::EC2::InternetGateway` rather than `AWS::EC2::CustomerGateway`

### What actually happened?

https://github.com/aws/aws-cdk/blob/ae09c16531636ee90067a90eedc790c88e74c6e1/packages/%40aws-cdk/aws-config/lib/rule.ts#L1358

Which should be mapped to `AWS::EC2::InternetGateway`

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report
