### ISSUE TITLE
(aws-batch): Add support for multi-node job definitions

### ISSUE THREAD

**Issue by Askannz** [aws/aws-cdk#16793]
### What is the problem?

In awscli (and boto3, etc), it's possible to register a multi-node job definition to Batch by leaving out the `containerProperties` field and instead setting `type` to `"multinode"` and filling out `nodeProperties` with a list of the nodes to run. See https://docs.aws.amazon.com/cli/latest/reference/batch/register-job-definition.html

However this cannot be done in CDK. The construct `JobDefinition` does have a `nodeProps` property, however since the field `container` (equivalent of `containerProperties` above) is a required one, it is not possible to leave it out (does not pass type checking). See API docs: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.JobDefinition.html

You can work around the type checking by filling both fields (`container` and `nodeProps`), but then CDK deployment fails with an error saying that one of the container properties field is empty (even though none of them are).

### Reproduction Steps

This works in awscli:
```
{
    "jobDefinitionName": "test",
    "type": "multinode",
    "nodeProperties": {
        "numNodes": 1,
        "mainNode": 0,
        "nodeRangeProperties": [
            {
                "targetNodes": "0:1",
                "container": {
                    "image": "ubuntu:20.04",
                    "vcpus": 1,
                    "memory": 512
                }
            }
        ]
    }
} 
```

This should be the equivalent in CDK, but does not pass type checking (complains that the property `container` is missing):
```typescript
import * as cdk from "@aws-cdk/core";
import * as batch from '@aws-cdk/aws-batch';
import * as ecs from '@aws-cdk/aws-ecs';

const container_props = {
    image: new ecs.RepositoryImage("ubuntu:20.04"),
    vcpus: 1,
    memoryLimitMiB: 512
}

const app = new cdk.App();

export class MyStack extends cdk.Stack {

    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const jobDef = new batch.JobDefinition(this, "Job definition", {
            nodeProps: {
                count: 1,
                mainNode: 0,
                rangeProps: [
                    {
                        container: container_props
                    }
                ]
            }
        })
    }
}

const myStack = new MyStack(app, "MyStack");
```

Adding `container: container_props` to the properties of `JobDefinition` passes type checking, but then trying to deploy the stack results in an error (see below).

### What did you expect to happen?

Being able to register a multi-node Batch job definition by leaving out the `container` property of the CDK construct `JobDefinition` and filling `nodeProps` instead.

### What actually happened?

The property `container` is not optional, so it is not possible to register a job definition by filling only the list of nodes. This is not consistent with the behavior of awscli and the AWS API.

If both `container` and `JobDefinition` are filled, the following error happens on deploy:

```
MyStack: deploying...
MyStack: creating CloudFormation changeset...
3:53:51 PM | CREATE_FAILED        | AWS::Batch::JobDefinition | JobdefinitionB933C029
An error occurred (ClientException) when calling the RegisterJobDefinition operation: Error executing request, Exception : Container properties should not be empty, RequestId: 3e699b0e-0b9e-425f-93f5-4
7b087c11393

        new JobDefinition (/home/robin/Prog/See-Mode/Projects/Scratchpad/cdk_batch_bug_repro/node_modules/@aws-cdk/aws-batch/lib/job-definition.ts:223:20)
        \_ new MyStack (/home/robin/Prog/See-Mode/Projects/Scratchpad/cdk_batch_bug_repro/test.ts:18:24)
        \_ Object.<anonymous> (/home/robin/Prog/See-Mode/Projects/Scratchpad/cdk_batch_bug_repro/test.ts:35:17)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (/home/robin/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1310:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (/home/robin/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1313:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
        \_ main (/home/robin/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:331:12)
        \_ Object.<anonymous> (/home/robin/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:482:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
        \_ node:internal/main/run_main_module:17:47

```

### CDK CLI Version

1.125.0 (build 67b4921)

### Node.js Version

v16.10.0

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (7.24.1)

**Comment by peterwoodworth** [comment]
Have you tried using the [`CfnJobDefinition`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.CfnJobDefinition.html)? If CloudFormation is able to support your use case ([which it looks like it does](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-containerproperties)) then you'll be able to make use of the L1 construct here.

Our L2 JobDefinition is currently configured to require the container property, so asking for our L2 to support this use case would be a feature request rather than a bug. I can relabel this as such if you would like to see this feature on the `JobDefinition` construct

The failure to deploy here is interesting to me. Could you post your `cdk synth` for the JobDefinition construct? Thanks

**Comment by Askannz** [comment]
Thanks Peter, we were able to register the job definition using `CfnJobDefinition` as a workaround.

I assumed the behavior of `JobDefinition` was a bug since (to my understanding) it makes the construct property `nodeProps` useless, which in turn makes the API a bit confusing. But in any case, support for this feature in the L2 API would be appreciated.

Here's the output of `cdk synth` for the code sample above when both `container` and `nodeProps` are filled out:

```
Resources:
  JobdefinitionB933C029:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      ContainerProperties:
        Image: ubuntu:20.04
        Privileged: false
        ReadonlyRootFilesystem: false
        ResourceRequirements:
          - Type: VCPU
            Value: "1"
          - Type: MEMORY
            Value: "512"
      NodeProperties:
        MainNode: 0
        NodeRangeProperties:
          - Container:
              Image: ubuntu:20.04
              Privileged: false
              ReadonlyRootFilesystem: false
              ResourceRequirements:
                - Type: VCPU
                  Value: "1"
                - Type: MEMORY
                  Value: "512"
            TargetNodes: "0:1"
        NumNodes: 1
      PlatformCapabilities:
        - EC2
      RetryStrategy:
        Attempts: 1
      Timeout: {}
    Metadata:
      aws:cdk:path: MyStack/Job definition/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VOyw6CMBD8Fu9loSZ6NsGT8VS/oCxLXJDdpC0abfh3QS96msm8MhbsdgfV5uAfscB2KDNqIMiX5HEwtUpMYcJk6k4cRZ0C0soXo+XEKrNZi7nxCa+QT9ocqWP5WGvuT5gN+xHO/vV0eiNDGGHZSZ6Fwk9qNqItQR/Lu92DrZZ3fWQuwiSJRwL3xTdeaieUugAAAA==
    Metadata:
      aws:cdk:path: MyStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

```
