### ISSUE TITLE
(python-lambda): Rate exceeded pulling public.ecr.aws/sam/build-python3.7

### ISSUE THREAD

**Issue by jmhossler** [aws/aws-cdk#16927]
### General Issue

We get a toomanyrequests: Rate exceeded error when pulling 

### The Question

In our deployment pipeline (ran on github actions), we synthesize our cdk package. During that process, we get this error:

```
Step 1/9 : ARG IMAGE=public.ecr.aws/sam/build-python3.7
Step 2/9 : FROM $IMAGE
toomanyrequests: Rate exceeded
docker exited with status 1
Subprocess exited with error 1
```

Before we do that, though, we make sure to configure out AWS credentials and login to Amazon ECR:
```
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ~~
          aws-secret-access-key: ~~
          aws-region: ~~
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
```

This happens when we're trying to synthesize our lambda. We've found a lot of issues on the CDK repository related to this from 2020 (e.g. https://github.com/aws/aws-cdk/issues/11774 ), but all of them seem to be related to pulling images from dockerhub, not the public ecr repository. We attempted to fix this by explicitly logging into amazon ECR in case we were using an anonymous user that was getting clashes (we maybe do 10-20 builds a day, so we shouldn't be hitting the rate limit on our own).

How should we be pulling this image from the public ecr repository so we don't get this rate exceeded? This is randomly failing our builds and makes us rerun the entire workflow.

### CDK CLI Version

1.125.0

### Node.js Version

14.17.4

### Language

Typescript

### Language Version

TypeScripted (3.9.7)

### Other information

One of the potential solutions we found for the dockerhub issue was to make our own python runtime environment and point it to an image in our own private ECR repo. I would _really_ like it if this wasn't the solution, since I do not want to maintain that runtime environment image.
