### ISSUE TITLE
pipelines: support BuildSpec.fromSourceFileName

### ISSUE THREAD

**Issue by markreyndev** [aws/aws-cdk#17178]
### General Issue

CodeBuildStepProps BuildSpec Issues

### The Question

I am trying to use CDK Pipelines, I need it to create a buildspec that has functionality similar to this

```
version: 0.2

env:
  secrets-manager:
    MY_SECRET: /my_department/my_secret:MyProperty

phases:
  install:
    runtime-versions:
      dotnet: latest 
  pre_build:
    commands:
      - echo $MY_SECRET
      - REPOSITORY_URI=my_repository
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest -f MySolution.MyProject/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin my_aws_account.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
```

I am trying to configure the buildspec with CodeBuildStepProps

```
var devStage = pipeline.AddStage(new Stage(this, "Dev"));

devStage.AddPre(new CodeBuildStep("CodeBuildStep", new CodeBuildStepProps
```

The properties on CodeBuildStepProps have the following issues

`PartialBuildSpec = BuildSpec.FromSourceFilename("buildspec.yml"),`
Results in a Amazon.JSII.Runtime.JsiiException: Can only merge buildspecs created using BuildSpec.fromObject()

`PartialBuildSpec = BuildSpec.FromObject(),`
Is there any documentation on how to convert the yml above to a Dictionary<string, object>()
It would be much easier if I could add the BuildSpec FromYml, FromJson or FromAnnonymousObject

I've also tried 

```
BuildEnvironment = new BuildEnvironment
{
    Privileged = true,
    EnvironmentVariables = new Dictionary<string, IBuildEnvironmentVariable>
    {
        {
            "MY_SECRET",
            new BuildEnvironmentVariable
            {
                Type = BuildEnvironmentVariableType.SECRETS_MANAGER,
                Value = "/my_department/my_secret:MyProperty"
            }
        }
    }
},
Commands = new[]
{
    "echo $MY_SECRET | tee MySolution.MyProject/NuGet.Config",
    "REPOSITORY_URI=my_repository",
    "COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)",
    "IMAGE_TAG=${COMMIT_HASH:=latest}",
    "docker build -t $REPOSITORY_URI:latest -f MySolution.MyProject/Dockerfile .",
    "docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG",
    "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin my_aws_account.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com",
    "docker push $REPOSITORY_URI:latest",
    "docker push $REPOSITORY_URI:$IMAGE_TAG"
}
```

But this loses the Buildspec secrets-manager env, and the insall, pre_build and post_build phases

The cdk synth works with the BuildEnvironment and Commands, but the build fails with what I think is a substitution issue with $MY_SECRET

I suspect I am using the CDK incorrectly, but I am struggling to find any good C# documentation for creating buildspecs using CDK Piplines

Please help

### CDK CLI Version

1.128.0 (build 1d3883a)

### Framework Version

.NET 5.0

### Node.js Version

v14.17.4

### OS

Windows 10

### Language

.NET

### Language Version

.NET 5.0.303
