### ISSUE TITLE
(apigw): cannot specify path requestParameter

### ISSUE THREAD

**Issue by mdesouky** [aws/aws-cdk#17318]
### What is the problem?

Cannot Specify a Path request Parameter for an API Integration, I have this piece of code to specify and lambda API Integration as follows
```python
lambda_integration = _apigw.LambdaIntegration(
            handler=website_lambda,
            proxy=True,
            integration_responses=[{
                'statusCode': '200',
                'responseParameters': {
                    'method.response.header.Access-Control-Allow-Origin': "'*'",
                }
            }],
            request_parameters={"integration.request.path.object": "method.request.path.page"}
        )
#Add Method to the API Resource
        api_resource.add_method(
            'GET', lambda_integration,
            method_responses=[{
                'statusCode': '200',
                'responseParameters': {
                    'method.response.header.Access-Control-Allow-Origin': True,
                }
            }]
        )
```
this passes testing and `cdk synth` but cloudformation deployment fails with:
```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.request.path.page] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: c5624fed-0df4-4e3f-a6e4-edde0372cf2f; Proxy: null)
```

### Reproduction Steps

`cdk deploy`

```
# Add API Resource
        api_resource = api.root.add_resource(
            'website_lambda',
            default_cors_preflight_options=_apigw.CorsOptions(
                allow_methods=['GET', 'OPTIONS'],
                allow_origins=_apigw.Cors.ALL_ORIGINS,
                allow_headers=['X-Forwarded-For, Content-Type'],
                max_age=cdk.Duration.seconds(600)
            )
        )
        #Add Lambda Integration
        lambda_integration = _apigw.LambdaIntegration(
            handler=website_lambda,
            proxy=True,
            integration_responses=[{
                'statusCode': '200',
                'responseParameters': {
                    'method.response.header.Access-Control-Allow-Origin': "'*'",
                }
            }],
            request_parameters={"integration.request.path.object": "method.request.path.page"}
        )
```

### What did you expect to happen?

Successful deployment and configuration of Request Path parameter on the API gateway method

### What actually happened?

Cloudformation error
```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.request.path.page] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: c5624fed-0df4-4e3f-a6e4-edde0372cf2f; Proxy: null)
```

### CDK CLI Version

1.130.0 (build 9c094ae)

### Framework Version

1.130.0 (build 9c094ae)

### Node.js Version

v16.10.0

### OS

Mac Os Moneterey v12.0.1

### Language

Python

### Language Version

3.8.8

### Other information

What I'm trying to do is put a an API gateway in front of a lambda that fetches static website content from an s3 bucket
trying to replicate this SAM config
```yaml
APIGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  InsightsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET, OPTIONS'"
        AllowHeaders: "*"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  InsightsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: insights_lambda.lambda_handler
      Role: !GetAtt InsightsLambdaRole.Arn
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
      Events:
        GetNetworkPerformance:
          Type: Api
          Properties:
            Path: /network_perf/{date}
            Method: get
            RestApiId: !Ref InsightsApi
            RequestParameters:
              - method.request.path.date
  ```
