### ISSUE TITLE
(aws-codebuild): whenusing BuildSpec.fromObjectToYaml({customBuildSpec}) - adds an extra line customBuildspec: |- to the rendered buildspec

### ISSUE THREAD

**Issue by pandrel** [aws/aws-cdk#17340]
### General Issue

(aws-codebuild): Error when using BuildSpec.fromObjectToYaml({customBuildSpec})

### The Question

I am trying to use below code for building a custom buildspec file with pipelineproject. 

```ts
const customBuildSpec = fs.readFileSync('codebuild/customBuildSpec.yaml', 'utf8');
const checkovCodeBuild = new codebuild.PipelineProject(this, 'Build', {
  buildSpec: codebuild.BuildSpec.fromObjectToYaml({customBuildSpec}),
  environment: {
    buildImage: codebuild.LinuxBuildImage.STANDARD_5_0
  },
  encryptionKey: artifactsKey,
  role: pipelineRole,
  projectName: 'Build'
})
```

The rendered build spec will have an extra line at the beginning of the buildspec file and extra tabs each line - causing the stage to fail with error 

```
1 | [Container] 2021/11/04 16:46:26 Waiting for agent ping
-- | --
2 | [Container] 2021/11/04 16:46:27 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/11/04 16:46:28 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/11/04 16:46:28 CODEBUILD_SRC_DIR=/codebuild/output/src283207796/src
5 | [Container] 2021/11/04 16:46:28 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2021/11/04 16:46:30 Phase complete: DOWNLOAD_SOURCE State: FAILED
7 | [Container] 2021/11/04 16:46:30 Phase context status code: YAML_FILE_ERROR Message: wrong number of container tags, expected 1
```

Rendered buildspec file:

```
customBuildSpec: | - 
  version: 0.2
  env:
    shell: bash
    variables:
      envName: ${envName}
      region: ${region}
-- TRUNCATED --
```

Expected

```
version: 0.2
env:
  shell: bash
  variables:
    envName: ${envName}
    region: ${region}
-- TRUNCATED --
```

Is there a different way to use codebuild.BuildSpec.fromObjectToYaml() to read content from a file ?

### CDK CLI Version

1.130.0 (build 9c094ae)

### Node.js Version

v16.13.0

### Language

Typescript

### Language Version

typescript@3.9.10
