### ISSUE TITLE
(aws-cdk): short issue description

### ISSUE THREAD

**Issue by zgriesinger** [aws/aws-cdk#17834]
### What is the problem?

I'm trying to deploy from my M1 MacBook to ECS Fargate using the `ecs-patterns`

What I noticed when running this was that my tasks in ECS were always failing due to architecture failures even though my Docker image and machine build architecture is `aarch64/arm64`

I stumbled upon this https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-arm64.html and noticed when I ran `cdk synth` that this block of CloudFormation was missing in the CDK

```yaml
  serviceafargateserviceTaskDefDEF69B32:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        ...
        RuntimePlatform:
          CpuArchitecture: ARM64
          OperatingSystemFamily: LINUX
```

Once I manually added this to the CloudFormation it worked, I'm working on a fix for it in the CDK itself but I'm pretty new to the CDK so I might be missing something! I couldn't find this option anywhere except in the root `TaskDefinition` class.

### Reproduction Steps

```bash
gh repo clone zgriesinger/monorepo
npm i
# Assuming CDK/Docker is setup _and_ you are building on ARM
npm run deploy -w @zgriesinger/service-a 
```

### What did you expect to happen?

CloudFormation is successful and ARM built docker image runs on ARM ec2 instances

### What actually happened?

ECS Task fails over and over with
```
standard_init_linux.go:228: exec user process caused: exec format error
```
Which is the standard error for cross arch failures

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v16.13.1

### OS

MacOS Monterey (Apple Silicon)

### Language

Typescript

### Language Version

3.9.7
