### ISSUE TITLE
(golang) awscdk/v2/awsiot: CfnTopicRule_DynamoDBv2ActionProperty empty generated cfn

### ISSUE THREAD

**Issue by karl-dau** [aws/aws-cdk#17902]
### What is the problem?

When I construct a TopicRule using `CfnTopicRule_DynamoDBv2ActionProperty`, then the generated CloudFormation is missing the actual action details.

### Reproduction Steps
```go
	ddbV2Action := &awsiot.CfnTopicRule_ActionProperty{
		DynamoDBv2: &awsiot.CfnTopicRule_DynamoDBv2ActionProperty{
			PutItem: awsiot.CfnTopicRule_PutItemInputProperty{
				TableName: table.TableName(),
			},
			RoleArn: iotRole.RoleArn(),
		},
	}

	ruleprops := &awsiot.CfnTopicRuleProps{
		TopicRulePayload: awsiot.CfnTopicRule_TopicRulePayloadProperty{
			Actions:          &[]*awsiot.CfnTopicRule_ActionProperty{ddbV2Action},
			AwsIotSqlVersion: aws.String("2016-03-23"),
			Sql:              aws.String(sqlStatement),
		},
	}

	awsiot.NewCfnTopicRule(stack, aws.String("ExampleRule"), ruleprops)
```

### What did you expect to happen?

I expected the Output to look like this:

```
  Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - DynamoDBv2:
              PutItem:
                TableName:
                  Ref: <table name redacted>
              RoleArn:
                Fn::GetAtt:
                  - IoTtoDynamoDBRole47C5C8A5
                  - Arn
        AwsIotSqlVersion: "2016-03-23"
        Sql: <sql redacted>
```

### What actually happened?

I only see this:

```
  Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - DynamoDBv2: {}
        AwsIotSqlVersion: "2016-03-23"
        RuleDisabled: false
        Sql: <sql redacted>
```

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Node.js Version

v17.2.0.

### OS

macOS Monteray

### Language

Go

### Language Version

Go 1.17.3

### Other information

A workaround:

```go
ddbV2Action := &awsiot.CfnTopicRule_ActionProperty{
		DynamoDBv2: &awsiot.CfnTopicRule_DynamoDBv2ActionProperty{
			PutItem: awsiot.CfnTopicRule_PutItemInputProperty{
				TableName: table.TableName(),
			},
			RoleArn: iotRole.RoleArn(),
		},
	}

	ruleprops := &awsiot.CfnTopicRuleProps{
		TopicRulePayload: awsiot.CfnTopicRule_TopicRulePayloadProperty{
			Actions:          &[]*awsiot.CfnTopicRule_ActionProperty{ddbV2Action},
			AwsIotSqlVersion: aws.String("2016-03-23"),
			Sql:              aws.String(SqlString),
		},
	}

	bytes, err := json.MarshalIndent(ruleprops, "", "    ")
	if err != nil {
		panic(err)
	}

	correctProps := &awsiot.CfnTopicRuleProps{}
	err = json.Unmarshal(bytes, correctProps)
	if err != nil {
		panic(err)
	}

	awsiot.NewCfnTopicRule(stack, aws.String("EampleRule"), correctProps)
```
