### ISSUE TITLE
(backup): granularity of `deleteAfter` and `moveToColdStorage` could be wrong

### ISSUE THREAD

**Issue by kaizen3031593** [aws/aws-cdk#18075]
### What is the problem?

https://github.com/aws/aws-cdk/blob/d5362f001656dfeecc5d8388b9f1c9ce77190ea4/packages/%40aws-cdk/aws-backup/lib/plan.ts#L184-L185

The CDK limits `deleteAfter` and `moveToColdStorage` to be a whole number of days. This is likely due to the cloudformation spec calling them `deleteAfterDays` and `moveToColdStorageAfterDays`. However, cloudformation docs show both properties can take a double. So perhaps the CDK is more stringent than necessary.

Related to #17602.

### Reproduction Steps

Create a backupPlan with `deleteAfter` or `moveToColdStorage`.

### What did you expect to happen?

Potentially, CDK should allow fractions of days.

### What actually happened?

CDK limits the user to a whole number of days.

### CDK CLI Version

2.2.0

### Framework Version

IDK

### Node.js Version

12

### OS

Mac

### Language

Typescript

### Language Version

3.8.3

### Other information

I don't actually know if this is something the `Duration` class allows. Probably involves some investigation.

**Comment by jumic** [comment]
Yes, CloudFormation supports datatype `number`. However, from my point of view, only a whole number of days can be used. I don't think we have to correct anything at the moment.

I tried to create a backup plan in the AWS console. The input field doesn't allow decimal separators.
![image](https://user-images.githubusercontent.com/15660169/146613720-11d10b8a-c86f-481f-b222-8040fe4a2979.png)

In the dropdown, you can only select days, no hours.
![image](https://user-images.githubusercontent.com/15660169/146613750-2f2b4a02-8b8f-4e87-88b1-54e100fff43a.png)

I deployed a CloudFormation template with value `DeleteAfterDays: 11.5`.
```yml
Resources:
  MyPlan2001109E:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: MyPlan
        BackupPlanRule:
          - Lifecycle:
              DeleteAfterDays: 11.5
            RuleName: MyPlanRule0
            TargetBackupVault:
              Fn::GetAtt:
                - MyPlanVault18F54E98
                - BackupVaultName
  MyPlanVault18F54E98:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: Cdk16634StackMyPlanVaultBD54EF25
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
```

The deployment was successful. `.5` is ignored. In AWS console I can see `11 days`:
```
Lifecycle
Never transition to cold storage
Expire after 11 days
```

@kaizen3031593 Is there anything else I should try?
