### ISSUE TITLE
(aws-cloudfront): ResponseHeaderPolicy not being applied to Distribution

### ISSUE THREAD

**Issue by ChrsWoo** [aws/aws-cdk#18276]
### What is the problem?

Hi all,

We are trying to create a custom Response Headers Policy according to the documentation here: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.ResponseHeadersPolicy.html

We're seeing our `ResponseHeadersPolicy` being created, but it isn't being applied to our Cloudfront Distribution with this setup:
```
const responseHeadersPolicy = new ResponseHeadersPolicy(...);

const distribution = new Distribution(this, "DistName", {
    defaultBehavior: {
        origin: new S3Origin(bucket),
        cachePolicy: CachePolicy.CACHING_DISABLED,
        responseHeadersPolicy: responseHeadersPolicy,
    }
});
```
### Reproduction Steps

1. Create a `ResponseHeadersPolicy` in your stack with CDK 1.138.0
```
const responseHeadersPolicy = new ResponseHeadersPolicy(this, "PolicyName", {...}); // policy config is unimportant for this bug
```

2. Attach the above policy to the `Distribution`
```
const distribution = new Distribution(this, "DistName", {
    defaultBehavior: {
        origin: new S3Origin(bucket),
        cachePolicy: CachePolicy.CACHING_DISABLED,
        responseHeadersPolicy: responseHeadersPolicy, // policy attached here
    }
});
```
3. Deploy your stack without errors
4. In the AWS console, navigate to CloudFront -> Distributions -> {Distribution ID} -> Edit behavior
5. The "Response headers policy" dropdown will be unpopulated, but our "PolicyName" policy will be a selectable option.

### What did you expect to happen?

The custom Response Headers Policy is applied to the Distribution automatically by CDK.

### What actually happened?

The custom Response Headers Policy is created successfully, but is not applied to the Distribution by CDK.

### CDK CLI Version

unknown at present (managed by another team)

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @ChrsWoo, 

I can't reproduce this. When you synth, are you seeing this in your template under `CloudFront::Distribution.Properties.DistributionConfig.DefaultCacheBehavior`?
```
            "ResponseHeadersPolicyId": {
              "Ref": "ResponseHeadersPolicy13DBF9E0"
            },
```

**Comment by ChrsWoo** [comment]
Hey @peterwoodworth 

Yes, I got an output like you showed. Might this then be an issue with Cloudfront itself rather than CDK?

Cheers

**Comment by peterwoodworth** [comment]
Yeah, the issue here would probably be with CloudFront rather than CDK. Is this issue consistent for you on multiple deployments?

**Comment by ChrsWoo** [comment]
@peterwoodworth yes, we have tried both our own custom policies and the off-the-shelf `SECURITY_HEADERS` policy and the issue occurs every time.

**Comment by peterwoodworth** [comment]
Interesting, I'm still unable to reproduce this. Do you have premium support?

**Comment by ChrsWoo** [comment]
@peterwoodworth Apparently only some in our org have premium, the rest of us have basic. I will go through the AWS Support Dashboard though.

**Comment by ChrsWoo** [comment]
Just for more clarification, I can see the Cloudformation template also shows the expected yaml:

```yaml
...
PolicyNameEDC056FC:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: MySecurityPolicy
        SecurityHeadersConfig:
          ...
  ...
  DistName683DF8FB:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ResponseHeadersPolicyId:
            Ref: PolicyNameEDC056FC
```
