### ISSUE TITLE
(aws-cdk-lib/core): Resource tags (i.e. 'Name') are now missing from many resources

### ISSUE THREAD

**Issue by einstein-it** [aws/aws-cdk#18418]
### What is the problem?

We upgraded our stacks to CDK v2.7.0, re-bootstrapped our environment as described in documentation and were able to deploy. However, none of the deployed resources are being tagged now. We are using the same method, i.e. ```cdk.Tags.of(...).add(...)```, for all resource tagging where applicable, for example:

```ts
 this.securityGroup = new ec2.SecurityGroup(this, libName, {
    description: libDescription,
    securityGroupName: libName,
    allowAllOutbound: libAllowOutbound,
    vpc: libVpc
});
 
 cdk.Tags.of(this.securityGroup).add('Name', libName);
```

Here is the synthesized template from a stack containing the above code (with CDK ```v2.7.0```, no tags):

```yml
Description: Lambda function generic security group
Resources:
  myslacklambdasecuritygroupmyslacklambdaD5AFE3B5:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda function security group
      GroupName: my-slack-lambda
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-XXXXXXXXXXXXX
    Metadata:
      aws:cdk:path: my-slack-lambda-security-group/my-slack-lambda-security-group/my-slack-lambda/Resource
  myslacklambdasecuritygroupmyslacklambdasecuritygroupid90882C6E:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value:
        Fn::GetAtt:
          - myslacklambdasecuritygroupmyslacklambdaD5AFE3B5
          - GroupId
      Description: Lambda function security group ID
      Name: my-slack-lambda-security-group-id
    Metadata:
      aws:cdk:path: my-slack-lambda-security-group/my-slack-lambda-security-group/my-slack-lambda-security-group-id/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VOSwrCMBA9i/tktBX0AC7cSj2AxHSUaU0iM4mllNzdBFFw9XhfXgt72KzMJNr2o37QFZZzNHZUHUpIbFEV77KgbYuBNjHF+cghPdXh5v+ErERcbTP5+8mwcRiRa+xHcq70u5yVDz3CIOtXs4NmW34MQqQ5+UgOofvgG1w+PuGiAAAA
    Metadata:
      aws:cdk:path: my-slack-lambda-security-group/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

Here is the synthesized template from the same stack (with CDK ```v1.139.0```, tags are present):

```yml
Description: Lambda function generic security group
Resources:
  myslacklambdasecuritygroupmyslacklambdaD5AFE3B5:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda function security group
      GroupName: my-slack-lambda
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: Name
          Value: my-slack-lambda
      VpcId: vpc-09eafaa2e200d9350
    Metadata:
      aws:cdk:path: my-slack-lambda-security-group/my-slack-lambda-security-group/my-slack-lambda/Resource
  myslacklambdasecuritygroupmyslacklambdasecuritygroupid90882C6E:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value:
        Fn::GetAtt:
          - myslacklambdasecuritygroupmyslacklambdaD5AFE3B5
          - GroupId
      Description: Lambda function security group ID
      Name: my-slack-lambda-security-group-id
    Metadata:
      aws:cdk:path: my-slack-lambda-security-group/my-slack-lambda-security-group/my-slack-lambda-security-group-id/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WOwQrCMAyGn8V71lkFwZuwg1eZT1CyKN1oK0k7kdJ3t0UUPOXPz5fwaaX3R7XdnMxTOpyWPmNgUvkaDS4wBC+RE0YYSUJiJBhu/psLtKNMuKs8YWIbX2cO6dGgv6KAiGtP2fr7xbBxFIkb9ltKKeDDRGqWftWHqlWtZrG24+SjdaTGz3wDpxwferIAAAA=
    Metadata:
      aws:cdk:path: my-slack-lambda-security-group/CDKMetadata/Default
```

As you can see, the same code generates tags just fine in CDK v1.139.0.

### Reproduction Steps

Synthesize templates with ```v1.139.0``` and ```v2.7.0```, using any stack that contains resource tagging via:

 ```ts
cdk.Tags.of(...).add('Name', '...');
```

### What did you expect to happen?

We expect resource tag 'Name' to be applied.

### What actually happened?

Resource tag 'Name' is not applied.

### CDK CLI Version

v2.7.0

### Node.js Version

v16.13.0

### OS

MacOS Monterey 12.1

### Language

Typescript

**Comment by ryparker** [comment]
Hey @einstein-it 👋🏻 

I'm having trouble reproducing this. 

Here's what I'm testing with:

```ts
import { App, Stack, Tags } from "aws-cdk-lib";
import { Bucket } from "aws-cdk-lib/aws-s3";
import { SecurityGroup, Vpc } from "aws-cdk-lib/aws-ec2";

const app = new App();
const stack = new Stack(app, "test-tags");

const securityGroup = new SecurityGroup(stack, "TempSecurityGroup", {
  vpc: new Vpc(stack, "TempVpc"),
});

Tags.of(securityGroup).add("Environment", "UAT"); // Works just fine
```

CloudFormation template (just the SecurityGroup):

```yml
TempSecurityGroup80CF6ABF:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sample-tags/TempSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: Environment
          Value: UAT
      VpcId:
        Ref: TempVpcF4D0C8C8
    Metadata:
      aws:cdk:path: sample-tags/TempSecurityGroup/Resource
```

Are you aware of any tag removal statements in your code? 

i.g.
```ts
// Remove the tag from all resources except subnet resources
Tags.of(theBestStack).remove('StackType', {
  excludeResourceTypes: ['AWS::EC2::Subnet']
});
```
