### ISSUE TITLE
(cfn-include): AWS::NoValue fails for a boolean-typed property

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#18420]
### What is the problem?

When trying to include a template with the `cloudformation-include` module that uses `{ Ref: 'AWS::NoValue' }` for a boolean-typed property, you get an error like:

```
Error: Expected 'true' or 'false' for boolean value, got: '${Token[AWS.NoValue.7]}'
```

### Reproduction Steps

Here's a minimal template showing the issue:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: "true"
        ViewerCertificate:
          CloudFrontDefaultCertificate:
            Ref: "AWS::NoValue"
```
