### ISSUE TITLE
aws_secretsmanager: fromSecretNameV2 doesnt work

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#18555]
### What is the problem?

Given this code:
```
my_secret = secretsmanager.Secret.from_secret_name_v2(
    self, "my_secret",
    secret_name="hello"
)
my_secret.grant_read(s3_event_handler)
```
the resulting iam policy has a bunch of question marks in it:
```
          - Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :secretsmanager:eu-west-1:123123123123:secret:hello-??????

```
which is invalid

### Reproduction Steps

see above

### What did you expect to happen?

valid iam policy

### What actually happened?

invalid iam policy

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Framework Version

2.8.0

### Node.js Version

v14.18.3

### OS

Ubuntu 20.04.3 LTS

### Language

Python
