### ISSUE TITLE
(aws-iam): invalid CloudFormation generated when overriding CfnRole inline policies

### ISSUE THREAD

**Issue by Jengah** [aws/aws-cdk#18801]
### What is the problem?

When adding a property override to the inline policies of a `CfnRole`, invalid CloudFormation is generated. `PolicyName` and `PolicyDocument` should be UpperCamelCase

### Reproduction Steps

```
# policy_document is some json
# role is a CfnRole


rule_policies = [
    iam.CfnRole.PolicyProperty(
        policy_name="some-name",
        policy_document=policy_document
    )
]

role.add_property_override('Policies', rule_policies)
```

### What did you expect to happen?

Valid CloudFormation
```
     Policies:
        - PolicyDocument:
            Statement:
              - Action: some:Action
                Resource:
                  - Fn::GetAtt:
                      - SomeResource
                      - Arn
                Effect: Allow
          PolicyName: some-name
```

### What actually happened?

Generated CloudFormation:
```
      Policies:
        - policyDocument:
            Statement:
              - Action: some:Action
                Resource:
                  - Fn::GetAtt:
                      - SomeResource
                      - Arn
                Effect: Allow
          policyName: some-name
```

Should be `PolicyDocument` and `PolicyName`, but Cloudformation generates `policyDocument` and `policyName` instead.  This causes an "Unknown" change in `cdk diff`, because it is not valid synthesized CloudFormation
```
┌───┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬───────────────────────────────┬────────────────────────────────────────┬───────────┐
│   │ Resource                                                                                                              │ Effect  │ Action                        │ Principal                              │ Condition │
├───┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼───────────────────────────────┼────────────────────────────────────────┼───────────┤
│ + │                                                                                                                       │ Unknown │                               │ AWS:${IamResources/Role}           │           │
├───┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼───────────────────────────────┼────────────────────────────────────────┼───────────┤
```

### CDK CLI Version

2.10.0 (build e5b301f)

### Framework Version

2.10.0

### Node.js Version

16.13.1

### OS

macOS Big Sur v11.6

### Language

Python

### Language Version

Python (3.9.6)
