### ISSUE TITLE
Cloudfront customOriginSource with s3 reference seems to be broken

### ISSUE THREAD

**Issue by skorfmann** [aws/aws-cdk#1882]
Given the following resources:

```typescript
const bucket = new s3.Bucket(this, `${props.name}Bucket`, {
  publicReadAccess: true,
  websiteIndexDocument: "index.html",
  websiteErrorDocument: "404.html",
  removalPolicy: cdk.RemovalPolicy.Orphan
});


new cloudfront.CloudFrontWebDistribution(
  this,
  `${props.name}Distribution`,
  {
    aliasConfiguration: {
      names: props.domainNames,
      acmCertRef: props.certificateArn 
    },
    viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.RedirectToHTTPS,
    priceClass: cloudfront.PriceClass.PriceClass200,
    originConfigs: [
      {
        customOriginSource: {
          originProtocolPolicy: cloudfront.OriginProtocolPolicy.HttpOnly,
          domainName: bucket.bucketWebsiteUrl
        },
        behaviors: [{ isDefaultBehavior: true }]
      }
    ]
  }
);
```

The stack synthesizes properly, but the creation fails with the following error message:

```bash
 5/10 | 11:37:27 PM | CREATE_FAILED        | AWS::CloudFront::Distribution | LivejamDistribution/LivejamMainDistribution/CFDistribution (LivejamDistributionLivejamMainDistributionCFDistribution579AF62B) The parameter origin name cannot contain a colon. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidArgument; Request ID: ed592c47-394d-11e9-9a3d-7928c3cc16b1)
```

When I provide the `domainName` as string input, it works as expected.

**Comment by erpheus** [comment]
I think the problem might be that you set `domainName: bucket.bucketWebsiteUrl` where you probably needed something like `domainName: bucket.DomainName`.

I'm using CloudFormation myself so I don't know exactly how you have to specify what you have to write, but the error seems similar to mine: I was passing a full url ("https://example.org") where only a domain ("example.org") was needed. The colon error comes from the https*:* 

Hope this helps!

**Comment by hoegertn** [comment]
Thanks, the `https://` is indeed the problem. But the needed domain name is not available in CFN as it seems. The DomainName property is the bucket domain and not the website domain. This seems to be missing in CFN.

**Comment by vahdet** [comment]
A quick workaround for getting rid of `http://` or `https://` is [splitting](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-split.html) the `WebsiteURL` of the bucket. See the `DomainName` value in the following snippet:

```
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    ...

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: MyCloudFrontDistributionId
            DomainName: !Select [1, !Split ["//", !GetAtt MyBucket.WebsiteURL]]
            CustomOriginConfig:
              ...
```
