### ISSUE TITLE
(aws-codecommit): Repository code initialization fails when empty files exist within the contents

### ISSUE THREAD

**Issue by codeJack** [aws/aws-cdk#19012]
### What is the problem?

When attempting to initialize a CodeCommit repository with some `code` contents the stack fails with a `Code supplied is not a valid .zip archive` error if, among the contents, one or more empty files exist (eg. __init__.py).

This behavior applies to any of the supported [Code](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_codecommit/Code.html) sources : `from_asset`, `from_directory`, `from_zip_file`.

### Reproduction Steps

```python
# Example with from_asset
dirname = os.path.dirname(__file__)
repository_code = Asset(
    scope=self,
    id="RepositoryCodeAsset",
    exclude=[".vscode", "__pycache__"],
    path=os.path.join(dirname, "code"),
)

aws_codecommit.Repository(
    scope=self,
    id="CodeCommitRepository",
    repository_name="repository_name",
    code=aws_codecommit.Code.from_asset(asset=repository_code),
)
```

The `code` folder shall contain one or more empty files.

### What did you expect to happen?

The stack should have been deployed successfully, the code commit `repository_name` repository should have been created and initiated with the contents from the `code` folder.

Also, the error message could have been more precise : the zip archive is perfectly valid, the issue (assuming there is one) is with its contents.

### What actually happened?

`cdk deploy` fails with a `Code supplied is not a valid .zip archive` error on the CodeCommit resource.

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Framework Version

aws-cdk-lib==2.8.0

### Node.js Version

v16.10.0

### OS

MacOS 11.6.3

### Language

Python

### Language Version

Python(3.9.10)

**Comment by skinny85** [comment]
Hey @codeJack,

thanks a lot for opening the issue. Confirming I was able to reproduce it. Fascinating! I'm curious whether this is limited to CodeCommit, or is this some bigger issue in how we handle Assets in the CDK.

**Comment by skinny85** [comment]
Hmm. I just tried with a manually-created ZIP file that contains just an empty file (not a CDK asset), and it was created successfully. So it _does_ seem like this is something weird that the CDK Assets do.

**Comment by jmejco** [comment]
```python
repository_code = s3_assets.Asset(
    scope=self,
    id="RepositoryCodeAsset",
    exclude=[".vscode", "__pycache__"],
    path=os.path.join(dirname, "code"),
    bundling=BundlingOptions(
        image=DockerImage.from_registry(
            image="public.ecr.aws/docker/library/alpine:latest"
        ),
        command=[
            "sh",
            "-c",
            """
                apk update && apk add zip
                zip -r -j /asset-output/code.zip /asset-input/*
                """,
        ],
        user="root",
    ),
)
```

It seems to work fine when using `BundlingOptions` to create the zip manually.

**Comment by skinny85** [comment]
What the hell is this ZIP sorcery that is making this fail 😄

**Comment by skinny85** [comment]
Here's the CDK code creating the archive: https://github.com/aws/aws-cdk/blob/6eb775e829d62913bff849d43ed7339f9910d8de/packages/cdk-assets/lib/private/archive.ts#L9-L49.

I don't see anything suspicious there...

**Comment by sawalanipawan** [comment]
Got same error when the code contents had empty `__init__.py` file.

After running `cdk deploy` command, CDK first creates the zip file and uploads it to the S3 bucket and then initiates the stack creation.

I tried to reference the ZIP created by CDK in below CFN template and tried deploying the stack using this template:
```
Resources:
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyRepositoryName
      Code:
        BranchName: main
        S3:
          Bucket: my-cdk-bucket
          Key: 'assets/code-zipped-by-cdk.zip'
```
The stack creation failed with same `Code supplied is not a valid .zip archive` error.


Then, I tried to create the ZIP manually and added that zip to a S3 bucket. Then I created a CFN stack using below template:
```
Resources:
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyRepositoryName
      Code:
        BranchName: main
        S3:
          Bucket: mybucket
          Key: 'mymanuallyzippedcode.zip'
```
The stack was created successfully.

Now, this means that there is an issue in CDK during creation of ZIP file.
