### ISSUE TITLE
cdk.Aws parameters are not accessible

### ISSUE THREAD

**Issue by briannab12** [aws/aws-cdk#1902]
I am trying to pass in a reference to the AWS account id and region as environment variables. 

Here is the snippet of my code that is causing the error:
```
import cdk = require('@aws-cdk/cdk');
export class LevRxCpInftStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        const envRegion = {
    	     value: cdk.Aws.region,
	     type: cb.BuildEnvironmentVariableType.PlainText
        }
        const envAccount = {
	    value: cdk.Aws.accountId,
	    type: cb.BuildEnvironmentVariableType.PlainText
        }
    }
}
```

Here is my error:
```
lib/lev_rx-cp-inft-stack.ts:112:18 - error TS2339: Property 'region' does not exist on type 'typeof Aws'.
112     value: cdk.Aws.region,
                       ~~~~~~
lib/lev_rx-cp-inft-stack.ts:116:18 - error TS2339: Property 'accountId' does not exist on type 'typeof Aws'.
116     value: cdk.Aws.accountId,
                       ~~~~~~~~~
```

In the documentation, it says the attributes exist on the cdk.Aws object. 
https://awslabs.github.io/aws-cdk/refs/_aws-cdk_cdk.html#aws

This is what I am trying to achieve in the cloud formation:
```
EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
```
