### ISSUE TITLE
@aws-cdk/aws-route53:  DNS Record Names using SSM resolved hosted zone names, have an extra . at the end

### ISSUE THREAD

**Issue by AndreeaIugaTR** [aws/aws-cdk#19134]
### What is the problem?

A “.” is appended to the dns records using SSM resolved hosted zone names. 

### Reproduction Steps

```ts 

  const param_hostedzone = new CfnParameter(this, `SSMParameterValue-ZoneName`, { 

        type: 'AWS::SSM::Parameter::Value<String>', 

        default: `/path/to/ssm/parameter` 

}); 

const hostedZone = new r53.HostedZone(this, 'HostedZone', { 

        zoneName: param_hostedzone.valueAsString 

}); 

 

new r53.ARecord(stack, 'record-id', { 

    target: r53.RecordTarget.fromValues(), 

    zone: hostedZone, 

    recordName: 'myrecord', 

    ttl: Duration.seconds(120) 

}); 

``` 

### What did you expect to happen?

```text 

Resources: 

  recordid664FE6E8: 

    Type: AWS::Route53::RecordSet 

    Properties: 

      Name: 

        Fn::Join: 

          - "" 

          - - myrecord. 

            - Ref: SSMParameterValueZoneName 

      Type: A 

      HostedZoneId: 

        Ref: SSMParameterValuehostedzonesprivateid 

      ResourceRecords: [] 

      TTL: "1233" 

``` 

### What actually happened?

```text 

Resources: 

  recordid664FE6E8: 

    Type: AWS::Route53::RecordSet 

    Properties: 

      Name: 

        Fn::Join: 

          - "" 

          - - myrecord. 

            - Ref: SSMParameterValueZoneName 

            - "." 

      Type: A 

      HostedZoneId: 

        Ref: SSMParameterValuehostedzonesprivateid 

      ResourceRecords: [] 

      TTL: "1233" 

``` 

### CDK CLI Version

2.13.0 

### Node.js Version

14.19.0 

### OS

All

### Language

Typescript

### Other information

CDK code: https://github.com/aws/aws-cdk/blob/e11d5378c33bea609ed09c998b305fdfd28999a9/packages/%40aws-cdk/aws-route53/lib/util.ts#L52-L64

**Comment by AndreeaIugaTR** [comment]
@comcalvi It causes a deploy time error since the it will re-add the . at the end. 
```yaml

Resources: 

  recordid664FE6E8: 

    Type: AWS::Route53::RecordSet 

    Properties: 

      Name: 

        Fn::Join: 

          - "" 

          - - myrecord. 

            - Ref: SSMParameterValueZoneName 

            - "." 

      Type: A 

      HostedZoneId: 

        Ref: SSMParameterValuehostedzonesprivateid 

      ResourceRecords: [] 

      TTL: "1233" 

```
