### ISSUE TITLE
(ecr): imageScanOnPush: true setting not working

### ISSUE THREAD

**Issue by bergac** [aws/aws-cdk#19155]
### What is the problem?

Hi!

I was updating the cdk version from 1.63.0 to 1.145.0 and did not change anything on the ecr specific code.
However, I saw the imageScanOnPush was changed from `Scan on push` to `Manual` and some scan on push configurations where deleted in the generated CloudfFormation template.

I think it is a bug (looking at the CDK docs, I'm doing exactly what the thing to enable imageScanOnPush).
But if I'm forgetting configuration or doing something wrong, please let me know!

### Reproduction Steps

In `ecr-stack.ts`:
```ts
import { Repository, TagStatus } from '@aws-cdk/aws-ecr';
import { Construct, Duration, Stack, StackProps } from '@aws-cdk/core';

export class EcrStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);
    const repositoryName = 'some-repository';
    const repository = new Repository(this, 'ecr-repository', {
      repositoryName: repositoryName,
      imageScanOnPush: true,
    });
    repository.addLifecycleRule({
      tagStatus: TagStatus.UNTAGGED,
      maxImageAge: Duration.days(5),
    });
    repository.addLifecycleRule({
      tagStatus: TagStatus.TAGGED,
      tagPrefixList: ['develop'],
      maxImageCount: 10,
    });
    repository.addLifecycleRule({
      tagStatus: TagStatus.TAGGED,
      tagPrefixList: ['master'],
      maxImageCount: 100,
    });
  }
}
```

and creating the stack (with correct account and region):
```ts
import { App } from '@aws-cdk/core';
import { EcrStack } from './ecr-stack.ts';
const app = new App();

new EcrStack(
      app,
      `stack-ecr`,
     {
         env: { account: <acountId>, region: <region> },
     }
    );
```

and then running `cdk synth`, creates the following yaml file:
```yaml
Resources:
  ecrrepository***:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: '{"rules":[{"rulePriority":1,"selection":{"tagStatus":"untagged","countType":"sinceImagePushed","countNumber":5,"countUnit":"days"},"action":{"type":"expire"}},{"rulePriority":2,"selection":{"tagStatus":"tagged","tagPrefixList":["develop"],"countType":"imageCountMoreThan","countNumber":10},"action":{"type":"expire"}},{"rulePriority":3,"selection":{"tagStatus":"tagged","tagPrefixList":["master"],"countType":"imageCountMoreThan","countNumber":100},"action":{"type":"expire"}}]}'
      RepositoryName: some-repository
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: <cdk-path-here>/ecr-repository/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zXKUQqDMAyA4bP4XuMCDvY48AbdCSRmUGXNSNKNUXr3IeLTzw8fAo5XuHT3+Ws9LdtQSZShPnymLUySzbWQh+mZI5sUJW5ht0wKNfJbLLno7wDntRayLAyrDR8cAW+A3Wop9VqypxdDPPoHGOnqqX4AAAA=
    Metadata:
      aws:cdk:path: <cdk-path-here>/CDKMetadata/Default
```

And in the UI I see the configuration is Manual, while I'd expect `Scan on push`:
![Screenshot 2022-02-25 at 11 32 33](https://user-images.githubusercontent.com/42515536/155700779-459d5d3f-f9cb-4e67-8eb7-0c71d9dcca28.png)

### What did you expect to happen?

I'd expect the configuration is not set to `Manual` but to `Scan on push`.

### What actually happened?

Manual scanOnPush configuration

### CDK CLI Version

1.145.0

### Node.js Version

v14.18.1

### OS

Mac OS Montery 12.2.1

### Language

Typescript

### Language Version

4.3.5
