### ISSUE TITLE
(cognito-idp): cannot use Cognito identity pool for role mappings 

### ISSUE THREAD

**Issue by michaeljfazio** [aws/aws-cdk#19222]
### Description

The following role mapping will fail:

```typescript
 const identityPool = new IdentityPool(this, "IdentityPool", {
      roleMappings: [
        {
          providerUrl: IdentityPoolProviderUrl.custom(userPool.userPoolProviderUrl),
          resolveAmbiguousRoles: false,
          useToken: true
        }
      ]
    })
```
The reason it will fail is because the internal logic is to map the provided URL as the corresponding key value, which is performed [here](https://github.com/aws/aws-cdk/blob/009d68912267de9dcf4136a7d80a652a891b7bb9/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L199).

The same function is achieved in Cloudformation by specifying the key separately from the provider url. See notes specified under the [IdentityProvider field description](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypoolroleattachment-rolemapping.html#cfn-cognito-identitypoolroleattachment-rolemapping-identityprovider).

### Use Case

Referencing user pool from the same stack.

### Proposed Solution

Allow the ability to optionally specify static key when creating a role mapping.

### Other information

Possible (untested) workaround is to create role attachment with Cfn resource and manually assign an arbitrary key.

```typescript
    const identityPool = new IdentityPool(this, "IdentityPool", {
      allowUnauthenticatedIdentities: false
    })

    new CfnIdentityPoolRoleAttachment(this, "RoleAttachment2", {
      identityPoolId: identityPool.identityPoolId,
      roleMappings: {
        cognito: { // 👈 manually specified key of "cognito"
          type: "Token",
          ambiguousRoleResolution: "Deny",
          identityProvider: userPool.userPoolProviderUrl
        }
      }
    }).node.addDependency(identityPool)
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
It looks like this is because there is no Cognito provider type in this enum:

https://github.com/aws/aws-cdk/blob/4eac4deb98411e921e5a2e6477185207b8588f75/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool.ts#L103-L124

Feel free to submit it.

**Comment by SamStephens** [comment]
@rix0rrr said:

> It looks like this is because there is no Cognito provider type in this enum:
> 
> https://github.com/aws/aws-cdk/blob/4eac4deb98411e921e5a2e6477185207b8588f75/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool.ts#L103-L124
> 
I don't think it's as simple as that.

IdentityPoolProviderType provides the USER_POOL constant, which I believe is for Cognito User Pools. [IdentityPoolProviderUrl provides a userPool method that uses this constant](https://github.com/aws/aws-cdk/blob/v2.31.0/packages/@aws-cdk/aws-cognito-identitypool/lib/identitypool.ts). The documentation includes [an example of IdentityPoolProviderUrl.userPool being used with a Cognito user pool provider URL](https://github.com/aws/aws-cdk/blob/v2.31.0/packages/@aws-cdk/aws-cognito-identitypool/README.md?plain=1#L341).

I'm using the IdentityPoolProviderUrl.userPool method, and getting the same results.

```
 const identityPool = new IdentityPool(this, "IdentityPool", {
      roleMappings: [
        {
          providerUrl: IdentityPoolProviderUrl.userPool(userPool.userPoolProviderUrl),
          resolveAmbiguousRoles: false,
          useToken: true
        }
      ]
    })
```

(or more accurately, the Python equivalent, as I use Python). userPool is of course an earlier instantated aws_cognito.UserPool construct.

The specific error message we're getting is similar to

```
Error: Resolution error: Resolution error: "${Token[TOKEN.209]}" is used as the key in a map so must resolve to a string, but it resolves to: {"Fn::GetAtt":["UserPool6BA7E5F2","ProviderURL"]}. Consider using "CfnJson" to delay resolution to deployment-time..
```

The problem being that as @michaeljfazio points out, [the provider URL is used as the key of a map](https://github.com/aws/aws-cdk/blob/v2.31.0/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L199). However map keys do not allow for tokens, only for hard coded values.

As @michaeljfazio also points out, the solution is to stop providing the identity provider using the role mapping keys, and instead use the IdentityProvider attribute of the role mapping object. [The existing code already sets the attribute](https://github.com/aws/aws-cdk/blob/v2.31.0/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L182). So all that is needed is to stop using the provider URL as the map key.

What the map key should be instead of the provider URL is an open question. Maybe it could be an optional parameter to [IdentityPoolRoleMapping](https://github.com/aws/aws-cdk/blob/v2.31.0/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L62-L87) that you are required to provide if the providerUrl is a Token.

**Comment by SamStephens** [comment]
FYI, the issue is currently incorrectly labelled [@aws-cdk/aws-iam](https://github.com/aws/aws-cdk/labels/%40aws-cdk%2Faws-iam).

**Comment by SamStephens** [comment]
The possible workaround that @michaeljfazio provides does not work, because an IdentityPool creates a DefaultRoleAttachment, and the CfnIdentityPoolRoleAttachment suggested conflicts with the existing DefaultRoleAttachment.

**Comment by alukach** [comment]
@SamStephens Thanks for your comments.  I have been hitting my head against this (also using Python).  Your description of the issue is inline with my thinking.  

However, I get a bit lost when you describe the solution.

> stop providing the identity provider using the role mapping keys, and instead use the IdentityProvider attribute of the role mapping object. [The existing code already sets the attribute](https://github.com/aws/aws-cdk/blob/v2.31.0/packages/%40aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L182). So all that is needed is to stop using the provider URL as the map key.
>
> What the map key should be instead of the provider URL is an open question.

Are you suggesting a change to CDK, or is this a change to CloudFormation itself? Reading through the [`AWS::Cognito::IdentityPoolRoleAttachment`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html#aws-resource-cognito-identitypoolroleattachment-properties) docs, I see:

> `RoleMappings`
> How users for a specific identity provider are mapped to roles. This is a string to the `RoleMapping` object map. The string identifies the identity provider. For example: `graph.facebook.com` or `cognito-idp.us-east-1.amazonaws.com/us-east-1_abcdefghi:app_client_id`.

At the end of the day, CDK will need to populate the RoleMappings on the CloudFormation Template. To create the Cognito IDP key, CDK is going to need to resolve the tokens at time of synthesis due to the fact that it's a CloudFormation restriction that keys can't be composed of tokens, correct? 

As a workaround, I was trying to apply some ideas from #12988 (i.e. leaning on [`CfnIdentityPoolRoleAttachment`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.CfnIdentityPoolRoleAttachment.html)) but ran into some other issues.  I'll report back here if I make any progress.  Please do let me know if you find a path forward.

**Comment by SamStephens** [comment]
@alukach this would be a CDK change.

If you have a look at [the documentation for a RoleMapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypoolroleattachment-rolemapping.html#cfn-cognito-identitypoolroleattachment-rolemapping-identityprovider), it says:

> **IdentityProvider**: Identifier for the identity provider for which the role is mapped. For example: graph.facebook.com or cognito-idp.us-east-1.amazonaws.com/us-east-1_abcdefghi:app_client_id (http://cognito-idp.us-east-1.amazonaws.com/us-east-1_abcdefghi:app_client_id). This is the identity provider that is used by the user for authentication.
>
> If the identity provider property isn't provided, the key of the entry in the RoleMappings map is used as the identity provider.

I read this as saying that if the IdentityProvider is provided, then the key of the Role Mapping can be any arbitrary string, it does not also have to be the identifier for the identity provider. I have not verified this experimentally, however.

You can see this from the template my CDK currently generates. I've hardcoded the identity provider temporarily to work around this issue. The role mapping generated for my attachment is:

```
    "RoleMappings": {
     "cognito-idp.us-west-2.amazonaws.com/us-west-2_pool_id:client_id": {
      "AmbiguousRoleResolution": "Deny",
      "IdentityProvider": "cognito-idp.us-west-2.amazonaws.com/us-west-2_pool_id:client_id",
      "Type": "Token"
     }
    },
```

See the identity provider is there as the key in RoleMappings, but also present as IdentityProvider.

I'm suggesting we provide a way for the CDK to generate this as:

```
    "RoleMappings": {
     "cognito": {
      "AmbiguousRoleResolution": "Deny",
      "IdentityProvider": "cognito-idp.us-west-2.amazonaws.com/us-west-2_pool_id:client_id",
      "Type": "Token"
     }
    },
```

Instead.

**Comment by alukach** [comment]
@SamStephens Thanks for the clarification.

> I read this as saying that if the IdentityProvider is provided, then the key of the Role Mapping can be any arbitrary string, it does not also have to be the identifier for the identity provider.

This does indeed track with the [example in the `AWS::Cognito::IdentityPoolRoleAttachment` docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html#aws-resource-cognito-identitypoolroleattachment--examples), wherein the key is a generic `userpool1`: 

```yaml
IdentityPoolRoleAttachment: 
  Type: AWS::Cognito::IdentityPoolRoleAttachment 
  Properties: 
    IdentityPoolId: !Ref IdentityPool
    Roles: 
      "authenticated": !GetAtt AuthenticatedRole.Arn 
      "unauthenticated": !GetAtt UnAuthenticatedRole.Arn 
    RoleMappings:  
      "graph.facebook.com":
        IdentityProvider: "graph.facebook.com" 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "goodvalue"
      "userpool1": 
        IdentityProvider: !Ref CognitoUserPool 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "goodvalue"
```

I will do my best to find some time tomorrow to play around with the CDK lib and see if I can make such a change in the lib (not sure how to cross-compile to Python locally, so we'll see how this goes...)

**Comment by SamStephens** [comment]
@alukach Awesome; I'm not working this week, but am back next week and would have time to look at this.

I think the main challenge is working out how the RoleMappings keys should be defined now they're no longer always the IdentityProvider.

I think we need to be careful that this scheme is resilient, that a given identity provider always retains the same key.

For a concrete example of what I mean, a naive solution would be just to make all the keys be numbered incrementally: `roleMapping1`, `roleMapping2`, and so on. So the role mappings you show above might look like:

```
IdentityPoolRoleAttachment: 
  Type: AWS::Cognito::IdentityPoolRoleAttachment 
  Properties: 
    IdentityPoolId: !Ref IdentityPool
    Roles: 
      "authenticated": !GetAtt AuthenticatedRole.Arn 
      "unauthenticated": !GetAtt UnAuthenticatedRole.Arn 
    RoleMappings:  
      "roleMapping1":
        IdentityProvider: "graph.facebook.com" 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "goodvalue"
      "roleMapping2": 
        IdentityProvider: !Ref CognitoUserPool 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "goodvalue"
```

The problem being that if you add a new role mapping to the **beginning** of the role mapping list, the keys of all the existing mappings will change:

```
IdentityPoolRoleAttachment: 
  Type: AWS::Cognito::IdentityPoolRoleAttachment 
  Properties: 
    IdentityPoolId: !Ref IdentityPool
    Roles: 
      "authenticated": !GetAtt AuthenticatedRole.Arn 
      "unauthenticated": !GetAtt UnAuthenticatedRole.Arn 
    RoleMappings:  
      "roleMapping1":
        IdentityProvider: "new.provider.com" 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "badvalue"
      "roleMapping2":
        IdentityProvider: "graph.facebook.com" 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "goodvalue"
      "roleMapping3": 
        IdentityProvider: !Ref CognitoUserPool 
        AmbiguousRoleResolution: Deny 
        Type: Rules 
        RulesConfiguration: 
          Rules: 
            - Claim: "sub" 
              MatchType: "Equals" 
              RoleARN: !GetAtt AuthenticatedRole.Arn 
              Value: "goodvalue"
```

My take is that the cleanest way to deal with this is to not make the CDK generate the keys; to have them provided by users.

I'd do this by adding a roleMappingName optional string to [IdentityPoolRoleMapping](https://github.com/aws/aws-cdk/blob/v2.31.1/packages/@aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L58-L87).

I'd then update the role mapping logic to use that name if it's provided. Change [the map setting code](https://github.com/aws/aws-cdk/blob/v2.31.1/packages/@aws-cdk/aws-cognito-identitypool/lib/identitypool-role-attachment.ts#L199) to be:

```
if (prop.roleMappingName) {
  acc[prop.roleMappingName] = roleMapping;
} else {
  acc[prop.providerUrl.value] = roleMapping;
}
```

A nice side effect of doing it this way is that the code is backwards compatible. Existing role mappings continue to work as before, but you can provide a roleMappingName to avoid using the providerUrl as the key in the role mapping hash.
