### ISSUE TITLE
(aws_cdk.aws_applicationautoscaling): CfnScalableTarget.ScheduledActionProperty does not synthesize vaild cloudformation when using a CfnCondition

### ISSUE THREAD

**Issue by Jengah** [aws/aws-cdk#19246]
### What is the problem?

When using a `CfnCondition` to conditionally set `scheduled_actions` within a `CfnScalableTarget`, the Scheduled Action properties are not synthesized to valid CloudFormation.  Things work as expected without using a `CfnCondition`.

### Reproduction Steps

Conditionally enable Scheduled Actions on a `ScalableTarget` utilizing a `CfnCondition` based on the value of a `CfnParameter`

```
        scheduled_scaling_param = CfnParameter(
            # .. param details ...
            allowed_values=["true", "false"]
        )

        scheduled_scaling_condition = CfnCondition(
            self,
            "ScheduledScalingCondition",
            expression=Fn.condition_equals(scheduled_scaling_param.value, "true"),
        )

        scalable_target = aa.CfnScalableTarget(
            # ... other req'd properties ...
            scheduled_actions=Fn.condition_if(
                scheduled_scaling_condition.logical_id,
                [
                    aa.CfnScalableTarget.ScheduledActionProperty(
                        schedule="cron(0 0 * * ? *)",
                        scheduled_action_name="OffHoursScaleDown",
                        scalable_target_action=aa.CfnScalableTarget.ScalableTargetActionProperty(
                            max_capacity=6,
                            min_capacity=1,
                        ),
                    ),
                    aa.CfnScalableTarget.ScheduledActionProperty(
                        schedule="cron(0 13 * * ? * )",
                        scheduled_action_name="NormalTrafficScaleUp",
                        scalable_target_action=aa.CfnScalableTarget.ScalableTargetActionProperty(
                            max_capacity=6,
                            min_capacity=4,
                        ),
                    ),
                ],
                Aws.NO_VALUE,
            ),
        )
```

Synthesize with `cdk synth`

### What did you expect to happen?

Expected valid Cloudformation as a result of `cdk synth` as such (how we currently handle this in raw yaml CloudFormation):

```
ScheduledActions:
        Fn::If:
          - ScheduledScalingCondition
          - - Schedule: cron(0 0 * * ? *)
              ScheduledActionName: OffHoursScaleDown
              ScalableTargetAction:
                MaxCapacity: 6
                MinCapacity: 1
            - Schedule: cron(0 13 * * ? * )
              ScheduledActionName: NormalTrafficScaleUp
              ScalableTargetAction:
                MaxCapacity: 6
                MinCapacity: 4
          - Ref: AWS::NoValue
```

### What actually happened?

Invalid properties as a result of `cdk synth`:

```
ScheduledActions:
        Fn::If:
          - ScheduledScalingCondition
          - - schedule: cron(0 0 * * ? *)
              scheduledActionName: OffHoursScaleDown
              scalableTargetAction:
                maxCapacity: 6
                minCapacity: 1
            - schedule: cron(0 13 * * ? * )
              scheduledActionName: NormalTrafficScaleUp
              scalableTargetAction:
                maxCapacity: 6
                minCapacity: 4
          - Ref: AWS::NoValue
```

Which results in a failed `cdk deploy` due to `Encountered unsupported property schedule`

### CDK CLI Version

2.15.0

### Framework Version

2.15.0

### Node.js Version

16.13.1

### OS

macOS Big Sur v11.6

### Language

Python

### Language Version

Python (3.9.6)

### Other information

I am currently in the process of migrating our maintained CloudFormation yaml templates to CDK. In the spirit of creating as minimal difference between our deployed stack, I am trying to recreate our yaml via `cdk synth` as closely as possible. We currently use a Condition based on the value of a parameter to enable Scheduled Actions on a ScalableTarget. The idea here being that we have the ability to turn scaling on/off without a code change.

example of the raw yaml we write for our currently deployed CF stacks:
```
ScheduledActions:
        Fn::If:
        - ScheduledScaling
        -
          - ScalableTargetAction:
              MinCapacity: 1
              MaxCapacity: 6
            Schedule: "cron(0 0 * * ? *)"
            ScheduledActionName: OffHoursScaleDown
          - ScalableTargetAction:
              MinCapacity: 4
              MaxCapacity: 6
            Schedule: "cron(0 13 * * ? *)"
            ScheduledActionName: NormalTrafficScaleUp
        - !Ref "AWS::NoValue"
```
