### ISSUE TITLE
aws_dynamodb: Table grant inconsistencies

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [aws/aws-cdk#20105]
### Describe the bug

When attempting to grant table permissions to an `IPrincipal`, we expect those permissions to be added but they are silently ignored.

### Expected Behavior

Table permissions should be granted to any `IGrantable`.

### Current Behavior

Table permissions are not granted to `IPrincipal`s.

### Reproduction Steps

Example code:
```ts
const table = new aws_dynamodb.Table(this, 'my-table', {
    encryption: aws_dynamodb.TableEncryption.CUSTOMER_MANAGED,
    partitionKey: {
        name: 'id',
        type: aws_dynamodb.AttributeType.STRING,
    },
    tableName: 'my-table-name',
});

const role = aws_iam.Role.fromRoleArn(this, 'Role1', `arn:aws:iam::${accountId}:role/Role1`);
const principal = new aws_iam.ArnPrincipal(`arn:aws:iam::${accountId}:role/Role2`);

table.grantReadWriteData(role);
table.grantReadWriteData(principal);
```

Example synth'd template snippet:
```yaml
Resources:
  mytableKeyF511837D:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :iam::000000000000:root
            Resource: "*"
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::000000000000:role/Role2
            Resource: "*"
        Version: "2012-10-17"
      Description: Customer-managed key auto-created for encrypting DynamoDB table at my-stack/my-table
      EnableKeyRotation: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  mytable0324D45C:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        KMSMasterKeyId:
          Fn::GetAtt:
            - mytableKeyF511837D
            - Arn
        SSEEnabled: true
        SSEType: KMS
      TableName: my-table-name
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  Role1Policy1275B564:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - mytable0324D45C
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - mytableKeyF511837D
                - Arn
        Version: "2012-10-17"
      PolicyName: Role1Policy1275B564
      Roles:
        - Role1
```

You can see here that the `ArnPrincipal` is only granted KMS-related usage. It is ignored for the table permissions policy.

### CDK CLI Version

2.21.1 (build a6ee543)

### Node.js Version

v14.19.1

### OS

Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64

### Language

Typescript

### Language Version

TypeScript (4.6.3)

**Comment by skinny85** [comment]
Hi @vito-laurenza-zocdoc,

thanks for opening the issue. The reason the `ArnPrincipal` is ignored by the Table is that an `ArnPrincipal` does not have a Policy document where the permission to access the DynamoDB Table might be registered.

Note that the KMS Key has a resource policy, which can be made to trust that Principal, but DynamoDB Tables do not have a resource policy.

Did you perhaps want to use the [`Role.fromRoleArn()` method](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#static-fromwbrrolewbrarnscope-id-rolearn-options) instead?

Thanks,
Adam

**Comment by vito-laurenza-zocdoc** [comment]
> Hi @vito-laurenza-zocdoc,
> 
> thanks for opening the issue. The reason the `ArnPrincipal` is ignored by the Table is that an `ArnPrincipal` does not have a Policy document where the permission to access the DynamoDB Table might be registered.
> 
> Note that the KMS Key has a resource policy, which can be made to trust that Principal, but DynamoDB Tables do not have a resource policy.
> 
> Did you perhaps want to use the [`Role.fromRoleArn()` method](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#static-fromwbrrolewbrarnscope-id-rolearn-options) instead?
> 
> Thanks, Adam

Hi Adam,

That's for looking at this. In my exact use case, I was attempting to grant Table permissions to a `CompositePrincipal`. I just simplified things for this GH issue report. I have a list of roles that I want to grant permissions to. If I loop over them we end up with lots of duplication in the policy that seems unnecessary at best, and has the potential to cause the policy to bump against the hard PolicySize quota at worst.

All that said, it seems wrong that the types at play here imply I would be able to use an `IPrincipal` as a grantee, only to find out that the policy was not created silently.

Thanks again for looking at this,
Vito

**Comment by skinny85** [comment]
Unfortunately, things are a little complex, as you've seen, so failing is probably not a good idea 🙂.

Can you make sure you're on a version  no earlier than`2.18.0` (or `1.150.0` if you're using V1), when [this change](https://github.com/aws/aws-cdk/pull/19114) was released, enable the `@aws-cdk/aws-iam:minimizePolicies` feature flag in your `cdk.context.json` file, and see if that removes the duplication in the policies generated by looping through the principals?

Thanks,
Adam

**Comment by vito-laurenza-zocdoc** [comment]
@skinny85 -- sorry for the late reply. That feature flag doesn't work for my use case because the merge does not happen on the `Roles` parameter.

e.g. this code:

```ts
const table = new aws_dynamodb.Table(this, 'my-table', {
    encryption: aws_dynamodb.TableEncryption.CUSTOMER_MANAGED,
    partitionKey: {
        name: 'id',
        type: aws_dynamodb.AttributeType.STRING,
    },
    tableName: 'my-table-name',
});

const roleOne = aws_iam.Role.fromRoleArn(this, 'Role1', `arn:aws:iam::${accountId}:role/Role1`);
const roleTwo = aws_iam.Role.fromRoleArn(this, 'Role2', `arn:aws:iam::${accountId}:role/Role2`);

table.grantReadWriteData(roleOne);
table.grantReadWriteData(roleTwo);

```

results in this synth'd template snippet:

```yaml
  Role1Policy1275B564:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - mytable0324D45C
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - mytableKeyF511837D
                - Arn
        Version: "2012-10-17"
      PolicyName: Role1Policy1275B564
      Roles:
        - Role1
  Role2PolicyFB7A062B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - mytable0324D45C
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - mytableKeyF511837D
                - Arn
        Version: "2012-10-17"
      PolicyName: Role2PolicyFB7A062B
      Roles:
        - Role2
```
