### ISSUE TITLE
java: Can't satisfy List<Object> parameters in Cfn*Props.Builder methods

### ISSUE THREAD

**Issue by mbulman** [aws/aws-cdk#2013]
When creating a Cfn*Props builder, methods that accept a `List<Object>` parameter don't seem to behave properly (or I'm doing something wrong).

As an example, when setting up an API Gateway Usage Plan, I want the resulting template to look something like:

```yaml
UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
        UsagePlanName: MyUsagePlan
        ApiStages:
            - Stage: Foo
              ApiId: Bar
```

The property I have trouble with is `ApiStages`, which is a list of objects (Maps, specifically).  My first attempt was the following Java code:

```java
Map<String, String> stage = ImmutableMap.of(
        "ApiId", "Foo"
        "Stage", "Bar");

ArrayList<Object> stages = new ArrayList<Object>();
stages.add(stage);

CfnUsagePlan usagePlan = new CfnUsagePlan(this, "UsagePlan", CfnUsagePlanProps.builder()
        .withUsagePlanName("MyUsagePlan")
        .withApiStages(stages)
        .build());
```

...but this yields:

```yaml
UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
        UsagePlanName: MyUsagePlan
        ApiStages:
            - {}
```

If I use `addPropertyOverride` instead, I am able to get the expected result:

```java
Map<String, String> stage = ImmutableMap.of(
        "ApiId", "Foo"
        "Stage", "Bar");

ArrayList<Object> stages = new ArrayList<Object>();
stages.add(stage);

CfnUsagePlan usagePlan = new CfnUsagePlan(this, "UsagePlan", CfnUsagePlanProps.builder()
        .withUsagePlanName("MyUsagePlan")
        .build());
        
usagePlan.addPropertyOverride("ApiStages", stages);
```

I've seen this behavior on multiple Cfn*Props Builders that expect List<Object> types, so it isn't specific to CfnUsagePlan.

Let me know what other info or things I can do that would be helpful.  Thanks
