### ISSUE TITLE
(iam): invalid iam policy generated when calling addEventSource on lambda with role from secretsmanager

### ISSUE THREAD

**Issue by fanhongy** [aws/aws-cdk#20204]
### Describe the bug

When creating below cdk script and to create a Lambda function with a SQS as a event source, will generate a invalid CloudFormation template:

```
from aws_cdk import (
    aws_lambda as _lambda,
    aws_lambda_event_sources as eventscr,
    aws_ec2 as ec2,
    Stack,
    aws_secretsmanager as sm,
    aws_sqs as sqs,
    aws_iam as iam,
)
from constructs import Construct

class SqsLambdaStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
            
        secret = sm.Secret.from_secret_name_v2(self, "secret", "/lambda/arn")
        
        role_arn = secret.secret_value_from_json("arn").to_string()

        secret_value = secret.secret_value
        
        queue = sqs.Queue(self, "lambdaqueue", )
        
        dummy_event_source = eventscr.SqsEventSource(queue)
        
        role = iam.Role.from_role_arn(self, "LambdaAdminRole", role_arn=role_arn)

        dummy_lambda = _lambda.Function(
            self, 'DummyHandler',
            runtime=_lambda.Runtime.PYTHON_3_7,
            code=_lambda.Code.from_asset('lambda'),
            handler='custom_resource_handler.handler',
            role = role,
        )
        
        dummy_lambda.add_event_source(dummy_event_source)
```

It will generate below `AWS::IAM::Policy`:
```
  LambdaAdminRolePolicy539E9856:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - lambdaqueue7CC04665
                - Arn
        Version: "2012-10-17"
      PolicyName: LambdaAdminRolePolicy539E9856
      Roles:
        - Fn::Select:
            - 1
            - Fn::Split:
                - /
                - Fn::Select:
                    - 5
                    - Fn::Split:
                        - ":"
                        - Fn::Join:
                            - ""
                            - - "{{resolve:secretsmanager:arn:"
                              - Ref: AWS::Partition
                              - ":secretsmanager:"
                              - Ref: AWS::Region
                              - ":"
                              - Ref: AWS::AccountId
                              - :secret:/lambda/arn:SecretString:arn::}}
```

This will fail with error while creating the change set: 
```
❌  SqsLambdaStack failed: Error [ValidationError]: Template error: Fn::Select  cannot select nonexistent value at index 1
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-05-04T02:04:59.284Z,
  requestId: '67dad83a-cbc1-4afe-9845-a32d04be2326',
  statusCode: 400,
  retryable: false,
  retryDelay: 930.8011188151826
}

Template error: Fn::Select  cannot select nonexistent value at index 1
```

### Expected Behavior

Generate a valid template and deploy, and grant proper permission to the lambda execution role.

### Current Behavior

This will fail with error while creating the change set: 
```
❌  SqsLambdaStack failed: Error [ValidationError]: Template error: Fn::Select  cannot select nonexistent value at index 1
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v14.5.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-05-04T02:04:59.284Z,
  requestId: '67dad83a-cbc1-4afe-9845-a32d04be2326',
  statusCode: 400,
  retryable: false,
  retryDelay: 930.8011188151826
}

Template error: Fn::Select  cannot select nonexistent value at index 1
```

### Reproduction Steps

Deploy the script above will reproduce the issue. 

### Possible Solution

Without assign the queue or some other resource requires permission changes in the Lambda execution role will not trigger this issue. 

use a plan-text string for the method: `aws_iam.Role.from_role_arn()` will avoid this issue. 

### Additional Information/Context

This issue happens when add resource to lambda function requires permission changes in the Lambda execution role, such as a SQS queue as event source, mount a file system to the function that requires changes in execution role will cause this issue. 

### CDK CLI Version

2.22.0 (build 1db4b16)

### Node.js Version

v14.5.0

### OS

AZ2

### Language

Typescript, Python

### Language Version

Python 3.7.10
