### ISSUE TITLE
feat(iam): merge IAM Policies when all of Users, Groups, and Roles are equal

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [aws/aws-cdk#20379]
### Describe the feature

Currently, the `@aws-cdk/aws-iam:minimizePolicies` feature flag allows IAM Policy *Statements* to be merged only. Additionally it should be possible to merge Policies themselves if all of Users, Groups, and Roles are equal.

### Use Case

Given this code:

```ts
    const table = new aws_dynamodb.Table(this, 'my-table', {
        encryption: aws_dynamodb.TableEncryption.CUSTOMER_MANAGED,
        partitionKey: {
            name: 'id',
            type: aws_dynamodb.AttributeType.STRING,
        },
        tableName: 'my-table-name',
    });
    
    const roleOne = aws_iam.Role.fromRoleArn(this, 'Role1', `arn:aws:iam::${accountId}:role/Role1`);
    const roleTwo = aws_iam.Role.fromRoleArn(this, 'Role2', `arn:aws:iam::${accountId}:role/Role2`);
    
    table.grantReadWriteData(roleOne);
    table.grantReadWriteData(roleTwo);
```

the following policies are created:

```yaml
  Role1Policy1275B564:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - mytable0324D45C
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - mytableKeyF511837D
                - Arn
        Version: "2012-10-17"
      PolicyName: Role1Policy1275B564
      Roles:
        - Role1
  Role2PolicyFB7A062B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - mytable0324D45C
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - mytableKeyF511837D
                - Arn
        Version: "2012-10-17"
      PolicyName: Role2PolicyFB7A062B
      Roles:
        - Role2
```

I would like to see a merged Policy created instead, i.e.:

```yaml
  MergedPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - mytable0324D45C
                  - Arn
              - Ref: AWS::NoValue
          - Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - mytableKeyF511837D
                - Arn
        Version: "2012-10-17"
      PolicyName: MergedPolicy
      Roles:
        - Role1
        - Role2
```

### Other Information

Related: #20105

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.24.1 (build 585f9ca)

### Environment details (OS name and version, etc.)

Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64
