### ISSUE TITLE
(aws-s3): Grant Read not working as expected

### ISSUE THREAD

**Issue by rubenandre** [aws/aws-cdk#20618]
### Describe the bug

I'm creating a simple cdk stack. (1 user, 1 bucket).

The bug happens when I call the grantRead method of S3.bucket, since it should add in the bucket policy permissions for that user to read things from the bucket, and it's not happening.

It's only happening on the bucket side, in the iam side, a policy is injected allowing [s3:GetBucket*, s3:GetObject*, s3:List*].

The method grantReadWrite worked as expected.

My Stack Code (account ID redacted):

```ts
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3'
import * as iam from 'aws-cdk-lib/aws-iam'

export class BlobTestStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const blobTestUser = new iam.User(this, 'BlobTestUser', {
            userName: "BlobTestUser"
        })

        const s3Bucket = new s3.Bucket(this, 'BlobTestS3Bucket', {
            encryption: s3.BucketEncryption.S3_MANAGED,
            versioned: true,
            publicReadAccess: false,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
            enforceSSL: true
        })

        const administratorAccessRoleArn = 'arn:aws:iam::************:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AdministratorAccess_****************'

        s3Bucket.grantReadWrite(new iam.ArnPrincipal(administratorAccessRoleArn))
        s3Bucket.grantRead(blobTestUser)
    }
}
```

Output from cdk synth where it's possible to see that does not exist one statement allowing the Read permissions to the user created.

```yaml
Resources:
  BlobTestUser4C72A964:
    Type: AWS::IAM::User
    Properties:
      UserName: BlobTestUser
    Metadata:
      aws:cdk:path: BlobTestStack/BlobTestUser/Resource
  BlobTestUserDefaultPolicy8DE11D40:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - BlobTestS3BucketC2581D5C
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BlobTestS3BucketC2581D5C
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: BlobTestUserDefaultPolicy8DE11D40
      Users:
        - Ref: BlobTestUser4C72A964
    Metadata:
      aws:cdk:path: BlobTestStack/BlobTestUser/DefaultPolicy/Resource
  BlobTestS3BucketC2581D5C:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: BlobTestStack/BlobTestS3Bucket/Resource
  BlobTestS3BucketPolicy9A05FF67:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: BlobTestS3BucketC2581D5C
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: "false"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - Fn::GetAtt:
                  - BlobTestS3BucketC2581D5C
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BlobTestS3BucketC2581D5C
                        - Arn
                    - /*
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::************:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AdministratorAccess_************
            Resource:
              - Fn::GetAtt:
                  - BlobTestS3BucketC2581D5C
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BlobTestS3BucketC2581D5C
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: BlobTestStack/BlobTestS3Bucket/Policy/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02OQQrCMBBFz+I+GUkrHkAvIBXXEtMRpmkTyCSKhNzdxgi6ev8//uJ30O1AbfSTpRmtnOkG+Ry1sWJV10x6gXxhDOJ4dx+e/EzmVWtLRXAP+ZCMxVjtNzX8xv+9lGoGZJ+CwSKcHxEm3j7UHlS/vpmYSIbkIi0IQ+Mb3mNMBakAAAA=
    Metadata:
      aws:cdk:path: BlobTestStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/***********/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

### Expected Behavior

Add a statement to the bucket policy allowing the Principal (user BlobTestUser) to execute the actions [s3:GetBucket*, s3:GetObject*, s3:List*].

### Current Behavior

Shown in the "Describe bug" section

### Reproduction Steps

Shown in the "Describe bug" section

### Possible Solution

2.24.1 (build 585f9ca)

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v16.13.1

### OS

MacOS 12.3.1

### Language

Typescript

### Language Version

3.9.7
