### ISSUE TITLE
pipelines.CodePipelineSource.sourceAttribute() can be only called from synth step

### ISSUE THREAD

**Issue by micsafi** [aws/aws-cdk#20643]
### Describe the bug

This is follow-up issue to earlier issue #19184.

It seems that accessing the pipeline source variables only works from the Pipeline synth step. If you call the sourceAttribute() method from any CodeBuildStep later in the pipeline chain, you get the mentioned error.

### Expected Behavior

I expected that I can access source variables in any step of the pipeline or even set them as default variables.

This should work:

```
    pipeline.addWave('test', {
            pre: [
                new CodeBuildStep('test', {
                    commands: [],
                    buildEnvironment: {
                        environmentVariables: {
                            'COMMIT_ID': {value: source.sourceAttribute('CommitId')}
                        }
                    }
                })
            ]
        });
```

Also this should be possible, setting them as default for all CodeBuild steps:

```
codeBuildDefaults: {
                buildEnvironment: {
                    environmentVariables: {
                        'COMMIT_ID': {value: source.sourceAttribute('CommitId')},
                    }
                }
            }
```

### Current Behavior

Following error is generated while cdk synth:

     t`hrow new Error(`Output for step ${this.step} not configured. Either the step is not in the pipeline, the step implementation did not call 'this.discoverReferencedOutputs()', or this engine does not support Outputs for this step.`);`

### Reproduction Steps

See code examples above.

### CDK CLI Version

2.27

### Node.js Version

v16 LTS

### OS

macOS or Linux

### Language

Typescript

**Comment by kodai305** [comment]
I am facing the same problem.

I want to pass source.sourceAttribute('CommitId') to aws-cdk-lib.StageProps.

**Comment by Snurppa** [comment]
Hi,

found this by the same error message. 

But I was able to overcome the issue by passing the `source.sourceAttribute('CommitId')` to the [env](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodeBuildStep.html#env) prop of the `CodeBuildStep`, having first tried to introduced the attribute reference in [buildEnvironment.environmentVariables](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodeBuildStep.html#env).

So the working version looks like:
```javascript
new CodeBuildStep('Validate', { 
    env: {
        COMMIT_ID: sourceCode.sourceAttribute('CommitId'),
    },
    input: sourceCode,
    commands: [
        'npm ci', // ....
    ],
});
```

After this `synth` and everything worked. You can see from `synth` output that it wrote the attribute reference to the `AWS::CodePipeline::Pipeline` resource's Action:
```yaml
    Type: AWS::CodePipeline::Pipeline
# .... Actions: ...
- ActionTypeId:
    Category: Build
    Owner: AWS
    Provider: CodeBuild
    Version: "1"
  Configuration:
    ProjectName:
      Ref: FrontendPipelineValidate500AB41A
    EnvironmentVariables: '[{"name":"COMMIT_ID","type":"PLAINTEXT","value":"#{Source@OrgId_reponame.CommitId}"}]'
  ```
 where as the `buildEnvironment.environmentVariables` map to `AWS::CodeBuild::Project`, one example with variable 'Environment: { value: 'dev'}`:
 ```yaml
  FrontendPipelineValidate500AB41A:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Description: Pipeline step cdk-pipeline/Pipeline/app/Validate
      EncryptionKey:
        Fn::GetAtt:
          - PipelineArtifactsBucketEncryptionKeyE7E
          - Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
# So error comes, if you tried to pass `source.sourceAttribute('CommitId')` here.
          - Name: Environment
            Type: PLAINTEXT
            Value: dev
```
