### ISSUE TITLE
pipelines: synth step cannot assume CDK Toolkit's lookup role

### ISSUE THREAD

**Issue by SydneyUni-Jim** [aws/aws-cdk#20877]
### Describe the bug

When using a CDK pipeline (`cdk.aws_pipelines.CodePipeline`), the role created for the CodeBuild project for the synth step is not given permission to assume the lookup role from the CDK toolkit (eg `cdk-hnb659fds-lookup-role-123456789012-ap-southeast-2`).

### Expected Behavior

A CDK app with the following code executes in the synth step of the CDK pipeline.

```typescript
ec2.Vpc.fromLookup(this, 'DefaultVpc', { isDefault: true })
```

### Current Behavior

The CDK app fails to execute with the an error.

```
…
[Container] 2022/06/26 03:57:29 Entering phase BUILD
[Container] 2022/06/26 03:57:29 Running command npm ci
added 357 packages in 12.279s
[Container] 2022/06/26 03:57:55 Running command npm run build
> aws-cdk-pipeline-lookup-issue@0.1.0 build /codebuild/output/src653894531/src
> tsc
[Container] 2022/06/26 03:58:06 Running command npm run cdk synth
> aws-cdk-pipeline-lookup-issue@0.1.0 cdk /codebuild/output/src653894531/src
> cdk "synth"
current credentials could not be used to assume 'arn:aws:iam::123456789012:role/cdk-hnb659fds-lookup-role-123456789012-ap-southeast-2', but are for the right account. Proceeding anyway.
[Error at /LookupIssuePipelineStack/Prod/LookupIssue] You are not authorized to perform this operation.
[Container] 2022/06/26 03:58:24 Command did not exit successfully npm run cdk synth exit status 1
[Container] 2022/06/26 03:58:24 Phase complete: BUILD State: FAILED
[Container] 2022/06/26 03:58:24 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run cdk synth. Reason: exit status 1
…
```

CodePipeline outcomes are:
- Source
  - SydneyUni-Jim_aws-cdk-pipeline-lookup-issue (succeeded)
- Build (failed)
  - Synth (failed)
- UpdatePipeline (not run)
- Prod (not run)

### Reproduction Steps

Prerequisites
- You have the ARN for a CodeStar connection that can read the GitHub repo.

##### Step 1: Success

1. `git clone --branch step1 https://github.com/SydneyUni-Jim/aws-cdk-pipeline-lookup-issue.git`
1. `cd aws-cdk-pipeline-lookup-issue`
1. `npm install`
1. `export CODESTAR_CONNECTION_ARN='`the ARN of your CodeStar connection`'`
1. `npm run cdk deploy`
1. Observe that the CDK pipeline can synthesise the stacks

##### Step 2: Failure
1. `git checkout step2`
1. `npm run cdk deploy`
1. Observe that the CDK pipeline now fails to synthesise the stacks

##### Changes from step1 to step2
```diff
diff --git a/bin/aws-cdk-pipeline-lookup-issue.ts b/bin/aws-cdk-pipeline-lookup-issue.ts
index 49a008f..bfadcc3 100644
--- a/bin/aws-cdk-pipeline-lookup-issue.ts
+++ b/bin/aws-cdk-pipeline-lookup-issue.ts
@@ -10,7 +10,7 @@ const ACCOUNT = process.env.CDK_DEFAULT_ACCOUNT
 const REGION = process.env.CDK_DEFAULT_REGION
 const CODESTAR_CONNECTION_ARN = process.env.CODESTAR_CONNECTION_ARN!
 const GITHUB_REPO = process.env.GITHUB_REPO ?? 'SydneyUni-Jim/aws-cdk-pipeline-lookup-issue'
-const GITHUB_BRANCH = process.env.GITHUB_BRANCH ?? 'step1'
+const GITHUB_BRANCH = process.env.GITHUB_BRANCH ?? 'step2'

 const app = new cdk.App();

diff --git a/lib/aws-cdk-pipeline-lookup-issue-stack.ts b/lib/aws-cdk-pipeline-lookup-issue-stack.ts
index d07727c..96a1fa7 100644
--- a/lib/aws-cdk-pipeline-lookup-issue-stack.ts
+++ b/lib/aws-cdk-pipeline-lookup-issue-stack.ts
@@ -1,16 +1,22 @@
 import { Stack, StackProps } from 'aws-cdk-lib';
+import * as ec2 from 'aws-cdk-lib/aws-ec2';
 import { Construct } from 'constructs';
-// import * as sqs from 'aws-cdk-lib/aws-sqs';

 export class AwsCdkPipelineLookupIssueStack extends Stack {
+
+  public readonly securityGroup: ec2.SecurityGroup
+
   constructor(scope: Construct, id: string, props?: StackProps) {
     super(scope, id, props);

     // The code that defines your stack goes here

-    // example resource
-    // const queue = new sqs.Queue(this, 'AwsCdkPipelineLookupIssueQueue', {
-    //   visibilityTimeout: cdk.Duration.seconds(300)
-    // });
+    const vpc = ec2.Vpc.fromLookup(this, 'DefaultVpc', {
+      isDefault: true,
+    })
+    this.securityGroup = new ec2.SecurityGroup(this, 'SecurityGroup', {
+      vpc,
+    })
   }
+
 }
```

### Possible Solution

cdk is producing the following

```yaml
# …

PipelineBuildSynthCdkBuildProject6BEFA8E6:
  Type: AWS::CodeBuild::Project
  Properties:
    # …
    ServiceRole:
      Fn::GetAtt:
        - PipelineBuildSynthCdkBuildProjectRole231EEA2A
        - Arn

PipelineBuildSynthCdkBuildProjectRole231EEA2A:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Version: "2012-10-17"

PipelineBuildSynthCdkBuildProjectRoleDefaultPolicyFB6C941C:
  Type: AWS::IAM::Policy
  Properties:
    PolicyName: PipelineBuildSynthCdkBuildProjectRoleDefaultPolicyFB6C941C
    Roles:
      - Ref: PipelineBuildSynthCdkBuildProjectRole231EEA2A
    PolicyDocument:
      Statement:
        - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Effect: Allow
          Resource:
            - Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :logs:ap-southeast-2:123456789012:log-group:/aws/codebuild/
                  - Ref: PipelineBuildSynthCdkBuildProject6BEFA8E6
                  - :*
            - Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :logs:ap-southeast-2:123456789012:log-group:/aws/codebuild/
                  - Ref: PipelineBuildSynthCdkBuildProject6BEFA8E6
        - Action:
            - codebuild:BatchPutCodeCoverages
            - codebuild:BatchPutTestCases
            - codebuild:CreateReport
            - codebuild:CreateReportGroup
            - codebuild:UpdateReport
          Effect: Allow
          Resource:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - :codebuild:ap-southeast-2:123456789012:report-group/
                - Ref: PipelineBuildSynthCdkBuildProject6BEFA8E6
                - -*
        - Action:
            - s3:Abort*
            - s3:DeleteObject*
            - s3:GetBucket*
            - s3:GetObject*
            - s3:List*
            - s3:PutObject
            - s3:PutObjectLegalHold
            - s3:PutObjectRetention
            - s3:PutObjectTagging
            - s3:PutObjectVersionTagging
          Effect: Allow
          Resource:
            - Fn::GetAtt:
                - PipelineArtifactsBucketAEA9A052
                - Arn
            - Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - PipelineArtifactsBucketAEA9A052
                      - Arn
                  - /*
      Version: "2012-10-17"

# …
```

The policy needs this extra statement.

```yaml
        - Effect: Allow
          Action:
            - sts:AssumeRole
          Resource:
            - arn:aws:iam::123456789012:role/cdk-hnb659fds-lookup-role-123456789012-ap-southeast-2
```

### Additional Information/Context

This is how I've created the CDK pipeline. It's not much different from what is documented in the [aws-cdk-lib.pipelines overview](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html)

```typescript
const pipeline = new pipelines.CodePipeline(this, 'Pipeline', {
  synth: new pipelines.ShellStep('Synth', {
    env: {
      CODESTAR_CONNECTION_ARN,
      GITHUB_REPO,
      GITHUB_BRANCH,
    },
    input: pipelines.CodePipelineSource.connection(GITHUB_REPO, GITHUB_BRANCH, {
      connectionArn: CODESTAR_CONNECTION_ARN,
    }),
    commands: [
      'npm ci',
      'npm run build',
      'npm run cdk synth',
    ],
  }),
});
```

### CDK CLI Version

2.29.1 (build c42e961)

### Node.js Version

14.19.3

### OS

macOS 12.4 arm64

### Language

Typescript

### Language Version

4.7.4
