### ISSUE TITLE
(rds): ServerlessClusterProps is missing copyTagsToSnapshot

### ISSUE THREAD

**Issue by SydneyUni-Jim** [aws/aws-cdk#20968]
### Describe the bug

[DatabaseClusterProps.copyTagsToSnapshot](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseClusterProps.html#copytagstosnapshot) exists but [ServerlessClusterProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.ServerlessClusterProps.html) does not have this property.

The [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot) does not suggest that this doesn't apply to Aurora Serverless.

### Expected Behavior

This compiles

```typescript
new rds.ServerlessCluster(scope, id, {
  copyTagsToSnapshot: true,
  engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_2_07_1 }),
  // …
})
```

and generates a CFT with

```yaml
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
       CopyTagsToSnapshot: true
       Engine: aurora-mysql
       EngineMode: serverless
       EngineVersion: 5.7.mysql_aurora.2.07.1
       # …
```

### Current Behavior

A TypeScript error that ServerlessClusterProps does not have copyTagsToSnapshot.

### Reproduction Steps

Try to `copyTagsToSnapshot: true` to the props when creating a `rds.ServerlessCluster`.

### CDK CLI Version

2.30.0 (build 1529743)

### Node.js Version

v14.19.3

### OS

macOS 12.4 arm64

### Language

Typescript

### Language Version

TypeScript (4.7.4)
