### ISSUE TITLE
aws-cognito: UserAttributeUpdateSettings does not seem to take effect when set

### ISSUE THREAD

**Issue by kenfdev** [aws/aws-cdk#21061]
### Describe the bug

When using the `CfnUserPool` to create a User Pool, `UserAttributeUpdateSettings` seems to have no effect.

Below is a minimum code I've tried.

```cs
public class CognitoStack : Stack
{
  internal CognitoStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
  {
    new CfnUserPool(this, "UserPool", new CfnUserPoolProps
    {
      UserAttributeUpdateSettings = new Dictionary<string, object>
      {
        ["AttributesRequireVerificationBeforeUpdate"] = new string[] { "email" }
      }
    });
  }
}
```

When running `cdk synth`, the output doesn't include anything related to `UserAttributeUpdateSettings`.

```yaml
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Metadata:
      aws:cdk:path: CognitoStack/UserPool
...
```

When writing similar code in TypeScript as follows:

```ts
export class CdkTsSampleStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const cfnUserPool = new cognito.CfnUserPool(this, 'MyCfnUserPool', {
      userAttributeUpdateSettings: {
        attributesRequireVerificationBeforeUpdate: ['email'],
      },
    });
  }
}
```

I get the expected output when running `cdk synth`

```yaml
Resources:
  MyCfnUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
    Metadata:
      aws:cdk:path: CdkTsSampleStack/MyCfnUserPool
...
```

### Expected Behavior

`UserAttributeUpdateSettings` should be applied when used in dotnet like it is in TypeScript.

```yaml
    Properties:
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
```

### Current Behavior

The Cfn output generated by running `cdk synth` does not include `UserAttributeUpdateSettings`

```
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Metadata:
      aws:cdk:path: CognitoStack/UserPool
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Metadata:
      aws:cdk:path: CognitoStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

### Reproduction Steps

The stack definition below would reproduce the problem.

```cs
using System.Collections.Generic;
using Amazon.CDK;
using Amazon.CDK.AWS.Cognito;
using Constructs;

namespace CdkDotnetSample
{
  public class CognitoStack : Stack
  {
    internal CognitoStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
    {
      new CfnUserPool(this, "UserPool", new CfnUserPoolProps
      {
        UserAttributeUpdateSettings = new Dictionary<string, object>
        {
          ["AttributesRequireVerificationBeforeUpdate"] = new string[] { "email" }
        }
      });
    }
  }
}

```

### Possible Solution

Perhaps I am not using the `Dictionary` as expected, but it seems like the `UserAttributeUpdateSettings` property is completely ignored and not mapped to the Cfn.

### CDK CLI Version

2.31.0 (build b67950d)

### Node.js Version

v16.15.1

### OS

Ubuntu 20.04.4 LTS

### Language

.NET

### Language Version

6.0.301

**Comment by peterwoodworth** [comment]
Our [.NET Api Reference](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.Cognito.CfnUserPool.html) should show some examples of how to accomplish this:

```.NET
CfnUserPool cfnUserPool = new CfnUserPool(this, "MyCfnUserPool", new CfnUserPoolProps {
  UserAttributeUpdateSettings = new UserAttributeUpdateSettingsProperty {
        AttributesRequireVerificationBeforeUpdate = new [] { "attributesRequireVerificationBeforeUpdate" }
    },
}
```
Does this work?

**Comment by kenfdev** [comment]
@peterwoodworth 
Oh shoot... must have missed that part.  
Worked as expected when I use UserAttributeUpdateSettingsProperty! 

```yaml
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
```

I wonder if this could be typed better?  It's an `object` for dotnet:

```cs
public object? UserAttributeUpdateSettings { get; set; }
```

but it's strongly typed in TypeScript

```ts
readonly userAttributeUpdateSettings?: CfnUserPool.UserAttributeUpdateSettingsProperty | cdk.IResolvable;
```

Wish I could contribute to fix it but am not sure where it should be edited 😞
