### ISSUE TITLE
aws_events: EventBus doesn't include tags

### ISSUE THREAD

**Issue by jangolano** [aws/aws-cdk#21604]
### Describe the bug

EventBus constructs are not being tagged when applying tags to the whole application

### Expected Behavior

EventBus should include the tags that we define at the application level.

### Current Behavior

EventBus constructs are not being tagged when applying tags to the whole application

### Reproduction Steps

Create a CDK project with EventBus and add tags at the application level.

### CDK CLI Version

2.37.1

### Node.js Version

16.9.0

### OS

Window

### Language

Python

**Comment by peterwoodworth** [comment]
I'm finding the same behavior @jangolano, thanks for reporting this.

The EventBus resource on CloudFormation [has a `Tags` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-tags), which means that this resource should be considered taggable by CDK.

However, this tags property comes with its own special [`TagEntry` type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-eventbus-tagentry.html) as opposed to using the universal Tag resource. I think this is what is ultimately preventing us from detecting the EventBus as taggable.

You can still set the tag for now with escape hatches doing something like this
```ts
    const eb = new EventBus(this, 'eventbus')

    const cfneb = eb.node.defaultChild as CfnEventBuseiifccuguikrierehbrdhhnddrgvlbneiuvuljkhltgg

    cfneb.addPropertyOverride('Tags', [{
      Key: 'key',
      Value: 'value'
    }])
```

**Comment by moltar** [comment]
Also, a notable difference, is that tags cannot be changed. Requires resource replacement.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html

And I haven't found in the console where the tags are even shown. Nor can you apply them in the UI.

**Comment by moltar** [comment]
Also maybe related: https://repost.aws/questions/QUrtTcjqzWTDa0CmmexF_auQ/event-bus-update-failed-unsupported-operation

**Comment by evgenyka** [comment]
Tried with CDK 2.127.0 and it is working fine (both create and delete tags). Can you pls confirm that it is not working with the latest CDK version? Also, please provide the sample code to reproduce. 

```
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { AwsEventbusStack } from '../lib/aws-eventbus-stack';

const app = new cdk.App();
new AwsEventbusStack(app, 'AwsEventbusStack', {
    // Define tags for the entire app
    tags: {
      environment: 'production',
      project: 'my-project',
    }
});
```

```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as events from 'aws-cdk-lib/aws-events';

export class AwsEventbusStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    
    // Create an EventBus
    const eventBus = new events.EventBus(this, 'MyEventBus', {
      eventBusName: 'MyEventBus', // You can specify the name of the event bus here
    });

    // Output the ARN of the created EventBus
    new cdk.CfnOutput(this, 'EventBusArn', {
      value: eventBus.eventBusArn,
      description: 'ARN of the created EventBus',
    });
  }
}
```

**Comment by NutterzUK** [comment]
Hi @evgenyka.

I've created the smallest possible example based on `cdk init` for typescript and made it available here:
https://github.com/NutterzUK/aws-cdk-issue-21604

For reference:
```
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { Environment, Tags } from 'aws-cdk-lib';

import { AwsCdkIssue21604Stack } from '../lib/aws-cdk-issue-21604-stack';

const app = new cdk.App();
new AwsCdkIssue21604Stack(app, 'AwsCdkIssue21604Stack', {});

Tags.of(app).add("MyKey", "MyValue")
```



Along with:

```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as events from 'aws-cdk-lib/aws-events';


export class AwsCdkIssue21604Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);


    const queue = new sqs.Queue(this, 'QueueWithTags', {
       visibilityTimeout: cdk.Duration.seconds(300)
    });

    const eventBridgeEventBus = new events.EventBus(this, 'EventBridgeWithoutTags', {
       eventBusName: "eventBusName"
    });

  }
}

```


Creates:

```
stephen@Stephens-MacBook-Pro aws-cdk-issue-21604 % cdk synth
Resources:
  QueueWithTagsE3C1882C:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: MyKey
          Value: MyValue
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: AwsCdkIssue21604Stack/QueueWithTags/Resource
  EventBridgeWithoutTagsC8667403:
    Type: AWS::Events::EventBus
    Properties:
      Name: eventBusName
    Metadata:
      aws:cdk:path: AwsCdkIssue21604Stack/EventBridgeWithoutTags/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWNwQ7CIBBEv8U7rNievNr4AbYfYFpYk211iV2oB8K/CzWeZuZNJtPAqTVgDuNHtHWLftIEaQijXVRB9yRvgXSLGFF1D95NVrghh8KvVS9RavX3OdfUo/i42n3UeXYUyHNW7B3CLMetMXAur7MQ6TVyoBdC/9Mv1P4h25IAAAA=
    Metadata:
      aws:cdk:path: AwsCdkIssue21604Stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```


But I would expect the EventBridge event bus to have the same tags applied, as they worked with SQS.
