### ISSUE TITLE
(integ-tests): sdk and assertions can generate custom resource types with more than 60 characters causing validation errors

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#22055]
### Describe the bug

I can't use `awsApiCall('Redshift', 'describeClusters', {...})`  due to validation errors in CloudFormation. 

### Expected Behavior

Using `assertions.awsApiCall`  generates a valid Resource Type that doesn't throw errors

### Current Behavior

I received the following error when attempting to write integ tests using `assertions.awsApiCall`

```
Deployment failed: Error: Stack Deployments Failed: ValidationError: 1 validation error detected: Value '[AWS::IAM::Role, AWS::Lambda::Function, Custom::DeployAssert@SdkCallRedshiftdescribeClusterParameters]' at 'typeNameList' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 204, Member must have length greater than or equal to 10, Member must satisfy regular expression pattern: [A-Za-z0-9]{2,64}::[A-Za-z0-9]{2,64}::[A-Za-z0-9]{2,64}(::MODULE){0,1}]
```

`Custom::DeployAssert@SdkCallRedshiftdescribeClusterParameters` did not match the expected regex pattern.

__Edit__:

Well it looks like this is the actual problem

from [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html)
> You can specify a custom resource type name up to a maximum length of 60 characters. 

`Custom::DeployAssert@SdkCallRedshiftdescribeClusterParameters`. Just so happens to be `61` characters long ...

### Reproduction Steps

Cut down integration test file

```ts
import * as ec2 from '@aws-cdk/aws-ec2';
import * as redshift from '@aws-cdk/aws-redshift';
import * as cdk from '@aws-cdk/core';
import * as integ from '@aws-cdk/integ-tests';

const app = new cdk.App();

const stack = new cdk.Stack(app, 'foo')
const vpc = new ec2.Vpc(stack, 'Vpc');
const cluster = new redshift.Cluster(stack, 'Cluster', {
  vpc: vpc,
  vpcSubnets: {
    subnetType: ec2.SubnetType.PUBLIC,
  },
  masterUser: {
    masterUsername: 'admin',
  },
});

const test = new integ.IntegTest(app, 'aws-cdk-redshift-reboot-test', {
  testCases: [stack],
  stackUpdateWorkflow: true,
  diffAssets: true,
});

test.assertions.awsApiCall('Redshift', 'describeClusters', {
  ClusterIdentifier: cluster.clusterName,
});

app.synth();


```

### Possible Solution

Remove/replace the `@` symbol or provide documentation on how to opt-in to allow that symbol

### Additional Information/Context

I removed the `@` symbol from the types [defined here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/integ-tests/lib/assertions/providers/lambda-handler/types.ts#L4-L5) and rebuilt the `integ-tests` module. 

When I did this, the problem went away

### CDK CLI Version

2.41.0

### Node.js Version

v16.16.0

### OS

OsX

### Language

Typescript

**Comment by dontirun** [comment]
I did some further testing and the title of the issue may be incorrect, but I still don't know why that specific custom resource name isn't working.

This template works `Custom::DeployAssert@SdkCallLambdainvoke`

```yml
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/custom-resource
      RetentionInDays: 30

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: custom-resource-execution-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogGroup
                  - logs:PutLogEvents
                Resource: !GetAtt Logs.Arn

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import logging
          import cfnresponse

          def handler(event, context):
              logger = logging.getLogger()
              logger.setLevel(logging.INFO)
              try:
                  if event['RequestType'] == 'Delete':
                      logger.info('Deleted!')
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return

                  logger.info('It worked!')
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception:
                  logger.exception('Signaling failure to CloudFormation.')
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})
      FunctionName: custom-resource
      Handler: index.handler
      Role: !GetAtt ExecutionRole.Arn
      Runtime: python3.7
      Timeout: 30

  CustomResource:
    Type: Custom::DeployAssert@SdkCallLambdainvoke
    Properties:
      ServiceToken: !GetAtt Function.Arn

```

**Comment by dontirun** [comment]
This template also works `Custom::DeployAssertSdkCallRedshiftdescribeClusterParameters`

```yml
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/custom-resource
      RetentionInDays: 30

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: custom-resource-execution-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogGroup
                  - logs:PutLogEvents
                Resource: !GetAtt Logs.Arn

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          # https://yellowdesert.consulting/2018/10/13/cloudformation-custom-resources-avoiding-the-two-hour-exception-timeout/
          import logging
          import cfnresponse

          def handler(event, context):
              logger = logging.getLogger()
              logger.setLevel(logging.INFO)
              try:
                  if event['RequestType'] == 'Delete':
                      logger.info('Deleted!')
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return

                  logger.info('It worked!')
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception:
                  logger.exception('Signaling failure to CloudFormation.')
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})
      FunctionName: custom-resource
      Handler: index.handler
      Role: !GetAtt ExecutionRole.Arn
      Runtime: python3.7
      Timeout: 30

  CustomResource:
    Type: Custom::DeployAssertSdkCallRedshiftdescribeClusterParameters
    Properties:
      ServiceToken: !GetAtt Function.Arn
```

**Comment by dontirun** [comment]
This template __doesn't__ work `Custom::DeployAssert@SdkCallRedshiftdescribeClusterParameters`

```yml
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/custom-resource
      RetentionInDays: 30

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: custom-resource-execution-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogGroup
                  - logs:PutLogEvents
                Resource: !GetAtt Logs.Arn

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import logging
          import cfnresponse

          def handler(event, context):
              logger = logging.getLogger()
              logger.setLevel(logging.INFO)
              try:
                  if event['RequestType'] == 'Delete':
                      logger.info('Deleted!')
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return

                  logger.info('It worked!')
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception:
                  logger.exception('Signaling failure to CloudFormation.')
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})
      FunctionName: custom-resource
      Handler: index.handler
      Role: !GetAtt ExecutionRole.Arn
      Runtime: python3.7
      Timeout: 30

  CustomResource:
    Type: Custom::DeployAssert@SdkCallRedshiftdescribeClusterParameters
    Properties:
      ServiceToken: !GetAtt Function.Arn
```
