### ISSUE TITLE
(aws-s3): Invalid configuration for server access logging bucket when using `ObjectOwnership.BUCKET_OWNER_ENFORCED`

### ISSUE THREAD

**Issue by shanman190** [aws/aws-cdk#22183]
### Describe the bug

```
let accessLogsBucket = new Bucket(scope, 'AccessLogsBucket', {
  objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED, // <-- start of the issue here
});

let dataBucket = new Bucket(scope, 'DataBucket', {
  objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
  serverAccessLogsBucket: accessLogsBucket // <-- second part of the issue
});
```

This internally yields an S3 Bucket representing the `AccessLogsBucket` in the following YAML:
```
AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
        AccessControl: LogDeliveryWrite # <-- third part of the problem
        OwnershipControls:
            Rules:
            - ObjectOwnership: BucketOwnerEnforced
        UpdateReplacePolicy: Retain
        DeletionPolicy: Retain
```

In this CloudFormation template, the S3 service rejects the request stating that ACLs cannot be configured when ObjectOwnership is configured to BucketOwnerEnfoced.

Source:  https://github.com/aws/aws-cdk/blob/9726e8fa07bcf496c79f8ab3be1c9f04b0e5dc3a/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1832

### Expected Behavior

If ObjectOwnership.BUCKET_OWNER_ENFORCED has been configured, then the ACL should not be set

### Current Behavior

The S3 service returns the following error to CloudFormation:

```
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; [...])
```

### Reproduction Steps

See bug description

### CDK CLI Version

2.42.1

### Node.js Version

16.17.0

### OS

Windows

### Language

Typescript, Python
