### ISSUE TITLE
s3: autoDeleteObjects fails on deploy with "NoSuchKey" error

### ISSUE THREAD

**Issue by deshruch** [aws/aws-cdk#22198]
### Describe the bug

I have this snippet in my cdk app

```
let current_removal_policy=RemovalPolicy.RETAIN;
let currentAutoDeleteObjects=false;
let env = this.node.tryGetContext('env');
    if(env===null || env==='prod')
    {
    env='prod'
    current_removal_policy=RemovalPolicy.RETAIN;
    }
    if(env==='dev')
    {
    current_removal_policy=RemovalPolicy.DESTROY;
    currentAutoDeleteObjects=true;
    }

 this.s3LoggingBucket = new Bucket(this, 'LogBucket', {
      accessControl: BucketAccessControl.LOG_DELIVERY_WRITE,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      removalPolicy: current_removal_policy,
      autoDeleteObjects: currentAutoDeleteObjects,
    });

```

I get the following error in Cloudformation:

```
Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: Lambda, Status Code: 400,

```

If I look at the synthesized Cloudformation template, I see this:
```
CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e57c1acaa363d7d2b81736776007a7091bc73dff4aeb8135627c4511a51e7dca.zip
      Timeout: 900
      MemorySize: 128
      Handler: __entrypoint__.handler
      Role:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
          - Arn
      Runtime: nodejs14.x
      Description:
        Fn::Join:
          - ""
          - - "Lambda function for auto-deleting objects in "
            - Ref: CommonResourcesLogBucketFC1ABCC9
            - " S3 bucket."
    DependsOn:
      - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
```

I checked the cdk-hnb659fds-assets-* bucket. It exists, but the  e57c1acaa363d7d2b81736776007a7091bc73dff4aeb8135627c4511a51e7dca.zip doesnt.

### Expected Behavior

I should be able to set the autoDeleteObjects bucket property conditionally and be able to successfully deploy the stack.
Upon deletion of the stack, the bucket must be deleted along with all objects.

### Current Behavior

Stack fails to deploy with this error:

```
Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: Lambda, Status Code: 400,

```

### Reproduction Steps

1. Create a cdk app which takes in a context parameter 'env' with value 'dev'.
2. Use code snippet provided to conditionally set the removal policy and autoDeleteObjects property.
3. Synthesize the stack and deploy the stack.

### Possible Solution

With current implementation, the zip is not available for the lambda to pick up. 
May be adding  inline code for lambda handler to support auto-delete-objects could work. 
Then there would be no dependency on the bucket or the zip.

### CDK CLI Version

2.36

### Node.js Version

16.15.1

### OS

linux

### Language

Typescript
