### ISSUE TITLE
Update bootstrap template & CLI

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#22744]
Add two new flags to the `bootstrap` command.

## CLI Flags

- `--example-permissions-boundary`

If the user sets this to true then the bootstrap template will create a permission boundary policy with the base policy. It will also apply the permission boundary to the bootstrap cfn-exec IAM role. We will provide instructions on how to add additional policy statements to this managed policy. At a high level this can either be done by, 1. editing the template prior to bootstrapping, or 2. we can provide a link to the console where the user can edit the policy.

- `--custom-permissions-boundary <NAME>`

If the user already has a permission boundary policy and they do not want the bootstrap template to create one, they can provide the name of the policy and the permission boundary will be applied to the bootstrap cfn-exec IAM role.

## Bootstrap Template

```yml
PermissionsBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          # If permission boundaries do not have an explicit allow
          # then the effect is deny
          - Sid: ExplicitAllowAll
            Action:
              - "*"
            Effect: Allow
            Resource: "*"
          # Default permissions to prevent privilege escelation
          - Sid: DenyAccessIfRequiredPermBoundaryIsNotBeingApplied
            Action:
              - iam:CreateUser
              - iam:CreateRole
              - iam:PutRolePermissionsBoundary
              - iam:PutUserPermissionsBoundary
            Condition:
              StringEquals:
                iam:PermissionsBoundary:
                  Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/cdk-${Qualifier}-BootstrapPermissionBoundary-${AWS::AccountId}-${AWS::Region}
            Effect: Allow
            Resource: "*"
          - Sid: DenyPermBoundaryIAMPolicyAlteration
            Action:
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Effect: Deny
            Resource:
              Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/cdk-${Qualifier}-BootstrapPermissionBoundary-${AWS::AccountId}-${AWS::Region}
          - Sid: DenyRemovalOfPermBoundaryFromAnyUserOrRole
            Action: 
              - iam:DeleteUserPermissionBoundary
              - iam:DeleteRolePermissionBoundary
            Effect: Deny
            Resource: "*"
        Version: "2012-10-17"
      Description: "Bootstrap Permission Boundary"
      ManagedPolicyName: 
        Fn::Sub: cdk-${Qualifier}-BootstrapPermissionBoundary-${AWS::AccountId}-${AWS::Region}
      Path: /
```
