### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by JoshMcCullough** [aws/aws-cdk#22773]
### Describe the bug

Additional `RoleDefaultPolicy5FFB7DAB` added to template during synth.

### Expected Behavior

Existing role already includes the policy described in `RoleDefaultPolicy5FFB7DAB`, so it shouldn't be included in the template.

### Current Behavior

No errors, stack deploys okay but template contains extraneous data, maybe?

### Reproduction Steps

Stack:
```ts
export class MyStack extends Stack {
  private params: Params;

  buildStack() {
    const deadLetterQueue = this.buildDeadLetterQueue();
    const role = this.buildRole(deadLetterQueue, startTimeParam);
    const fn = this.buildFunction(deadLetterQueue, role);

    this.buildEventRule(deadLetterQueue, fn);
  }

  buildDeadLetterQueue() {
    const { stackName } = this.params;

    return new SQS.Queue(this, RESOURCE_IDS.DeadLetterQueue, {
      queueName: `${stackName}_dl`,
    });
  }

  buildRole(deadLetterQueue: SQS.Queue) {
    const { stackName } = this.params;

    return new IAM.Role(this, RESOURCE_IDS.Role, {
      roleName: stackName,
      assumedBy: new IAM.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        IAM.ManagedPolicy.fromManagedPolicyArn(this, 'AWSLambdaBasicExecutionRole', 'arn:region:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'),
      ],
      inlinePolicies: {
        'dead-letter-queue_send-message': new IAM.PolicyDocument({
          statements: [new IAM.PolicyStatement({
            effect: IAM.Effect.ALLOW,
            actions: [IAMActions.SQS.SEND_MESSAGE],
            resources: [deadLetterQueue.queueArn],
          })],
        }),
      }
    });
  }

  buildFunction(encryptionKey: KMS.IKey, deadLetterQueue: SQS.Queue, bucket: S3.Bucket, startTimeParam: SSM.StringParameter, role: IAM.Role) {
    const { stackName } = this.params;

    return new NodeLambda.NodejsFunction(this, RESOURCE_IDS.Function, {
      functionName: stackName,
      runtime: Lambda.Runtime.NODEJS_16_X,
      entry: path.join(__dirname, '/../src/handler.ts'),
      handler: 'handleEvent',
      role,
      architecture: Lambda.Architecture.X86_64,
      memorySize: 256,
      deadLetterQueue,
      timeout: Duration.minutes(15),
    });
  }

  buildEventRule(deadLetterQueue: SQS.Queue, fn: Lambda.Function) {
    return new Events.Rule(this, RESOURCE_IDS.FunctionSchedule, {
      description: `Runs the ${fn.functionName} lambda every 5 minutes.`,
      schedule: Events.Schedule.rate(Duration.minutes(5)),
      targets: [new EventTargets.LambdaFunction(fn, {
        deadLetterQueue,
        retryAttempts: 3,
      })]
    });
  }
}
```

Generated Template:
```yml
Resources:
  DeadLetterQueue9F481546:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-stack_dl
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: my-stack/DeadLetterQueue/Resource
  Role1ABCC5F0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:region:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action: sqs:SendMessage
                Effect: Allow
                Resource:
                  Fn::GetAtt:
                    - DeadLetterQueue9F481546
                    - Arn
            Version: "2012-10-17"
          PolicyName: queue_send-message
      RoleName: my-stack
    Metadata:
      aws:cdk:path: my-stack/Role/Resource
  RoleDefaultPolicy5FFB7DAB:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - DeadLetterQueue9F481546
                - Arn
        Version: "2012-10-17"
      PolicyName: RoleDefaultPolicy5FFB7DAB
      Roles:
        - Ref: Role1ABCC5F0
    Metadata:
      aws:cdk:path: my-stack/Role/DefaultPolicy/Resource
  Function76856677:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: ...
        S3Key: fae71eee636f198d6c41252ecf68776815625622f8346272b5920b612a6273b6.zip
      Role:
        Fn::GetAtt:
          - Role1ABCC5F0
          - Arn
      Architectures:
        - x86_64
      DeadLetterConfig:
        TargetArn:
          Fn::GetAtt:
            - DeadLetterQueue9F481546
            - Arn
      FunctionName: my-stack
      Handler: index.handleEvent
      MemorySize: 256
      Runtime: nodejs16.x
      Timeout: 900
    DependsOn:
      - RoleDefaultPolicy5FFB7DAB
      - Role1ABCC5F0
    Metadata:
      aws:cdk:path: my-stack/Function/Resource
      aws:asset:path: asset.fae71eee636f198d6c41252ecf68776815625622f8346272b5920b612a6273b6
      aws:asset:is-bundled: true
      aws:asset:property: Code
  FunctionSchedule755EA547:
    Type: AWS::Events::Rule
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Runs the "
            - Ref: Function76856677
            - " lambda every 5 minutes."
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - Function76856677
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: my-stack/FunctionSchedule/Resource
  FunctionScheduleAllowEventRulemystackFunction0694A6EAAAB4168E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - Function76856677
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - FunctionSchedule755EA547
          - Arn
    Metadata:
      aws:cdk:path: my-stack/FunctionSchedule/AllowEventRulemystackFunction0694A6EA
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

### CDK CLI Version

2.50.0

### Node.js Version

18.4.0

### OS

Manjaro Linux 22

### Language

Typescript

### Language Version

4.8.4

### Other information

Possibly related to:
- https://github.com/aws/aws-cdk/issues/4196
- https://github.com/aws/aws-cdk/issues/2985
