### ISSUE TITLE
aws-opensearchservice: vpc_subnets setting is ignored, resulting in incorrect subnets in CloudFormation

### ISSUE THREAD

**Issue by patrickmryan** [aws/aws-cdk#22953]
### Describe the bug

The Domain construct (https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_opensearchservice/Domain.html) accepts a set of subnets to be used when deploying an Opensearch domain in a VPC. For development purposes, I am trying to deploy a domain in one AZ, thus one subnet. The CFn template that results from the synthesis, however, includes all three subnets in the VPC. The stack fails deploy because more than one subnet is specified.

### Expected Behavior

The resulting template should include exactly one subnet.

### Current Behavior

The Domain construct (https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_opensearchservice/Domain.html) is emitting the wrong subnets when the stack is synthesized.

When the stack attempts to deploy, this error comes from CFn:

Resource handler returned message: "Invalid request provided: You must specify exactly one subnet. (Service: OpenSearch, Status Code: 400, Request ID: f7830da9-0855-4d30-856f-09b775279d90)" (RequestToken: 90cb80f8-63c0-1497-52c1-e248a8faabce, HandlerErrorCode: InvalidRequest)

If I edit the CFn template and delete the two extra subnets, the stack will deploy successfully.

### Reproduction Steps

Complete code is at https://github.com/patrickmryan/opensearch-cdk

The construct in the stack looks like this. Note that exactly one hardcoded subnet is listed:

```
        domain = oss.Domain(
            self,
            "OssDomain",
            version=oss.EngineVersion.open_search("2.3"),  #    OPENSEARCH_1_3,
            ebs=oss.EbsOptions(volume_size=100),
            node_to_node_encryption=True,
            encryption_at_rest=oss.EncryptionAtRestOptions(enabled=True),
            vpc=vpc,
            # vpc_subnets=[
            #     ec2.SubnetSelection(subnets=subnets, availability_zones=["us-east-1c"])
            # ],
            vpc_subnets=[{"aSubnet": "subnet-0f360a0e465712c55"}],
            security_groups=[security_group],
            capacity=oss.CapacityConfig(
                data_node_instance_type="t3.small.search", data_nodes=1
            ),
            enforce_https=True,
            fine_grained_access_control=domain_security,
        )
```

The resource in the resulting CFn template looks like this:
```
  OssDomainD02EBC02:
    Type: AWS::OpenSearchService::Domain
    Properties:
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: master
          MasterUserPassword: Mast3r!!
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 1
        InstanceType: t3.small.search
        ZoneAwarenessEnabled: false
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-0-2019-07
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 100
        VolumeType: gp2
      EncryptionAtRestOptions:
        Enabled: true
      EngineVersion: OpenSearch_2.3
      LogPublishingOptions: {}
      NodeToNodeEncryptionOptions:
        Enabled: true
      VPCOptions:
        SecurityGroupIds:
          - Fn::GetAtt:
              - OssDomainSG8B8F43D7
              - GroupId
        SubnetIds:
          - subnet-0638d700031799333
          - subnet-012e93105ebf767bc
          - subnet-0f360a0e465712c55
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: OssStack/OssDomain/Resource
```

Note the three subnets

### Possible Solution

I do not have a solution. My expectation is that the behavior of the vpc_subnets option of Domain should be identical to that of the vpc_subnets parameter of ApplicationLoadBalancer.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

v16.13.1

### OS

Linux (Cloud9)

### Language

Python

### Language Version

3.8.13
