### ISSUE TITLE
(aws-cdk-lib): Stack Transform Macro AWS::SecretsManager-2020-07-23 creates broken HostedRotation Lambda

### ISSUE THREAD

**Issue by zinklandi** [aws/aws-cdk#23331]
### Describe the bug

Using Hosted-Rotation and thereby using the Transform Macro "AWS::SecretsManager-2020-07-23" creates the following template snippet. This snippet creates a Lambda-Function which actually uses the runtime `PYTHON_3_9`. As the runtime does not fit to the code provided in the aws-provided S3 Bucket this lambda throws errors not being able to import modules.

#### Error
```log
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named '_pg' Traceback (most recent call last):
```

#### Template

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    endpoint:
        Type: String
        Description: The Secrets Manager endpoint to use.
    functionName:
        Type: String
        Description: The name of the Lambda function.
    invokingServicePrincipal:
        Type: String
        Description: The service principal for the invoking service.
        Default: "secretsmanager.amazonaws.com"
    vpcSubnetIds:
        Type: CommaDelimitedList
        Description: A comma-separated list of VPC subnet IDs applied to the database network. 
        Default: ""
    vpcSecurityGroupIds:
        Type: CommaDelimitedList
        Description: A comma-separated list of security group IDs applied to the database.
        Default: ""
    kmsKeyArn:
        Type: String
        Description: The ARN of the KMS key that Secrets Manager uses to encrypt the secret.
        Default: ""
    excludeCharacters:
        Type: String
        Description: A string of the characters that you don't want in the password.
        Default: ":/@\"'\\"

Conditions:
    AddVpcConfig:
        !And
            - !Not [!Equals ["", !Join ["", !Ref vpcSubnetIds]]]
            - !Not [!Equals ["", !Join ["", !Ref vpcSecurityGroupIds]]]
    KmsKeyArnExists:
        !Not [!Equals ["", !Ref kmsKeyArn]]

Resources:
    SecretsManagerRDSPostgreSQLRotationSingleUser:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName:
                Ref: functionName
            Description: Rotates a Secrets Manager secret for Amazon RDS PostgreSQL credentials using the single user rotation strategy.
            Handler: lambda_function.lambda_handler
            Runtime: python3.9
            CodeUri: s3://secrets-manager-rotation-apps-9e825f5413b8ec477b47f17943b55cee/SecretsManagerRDSPostgreSQLRotationSingleUser/SecretsManagerRDSPostgreSQLRotationSingleUser.zip
            Timeout: 30
            Policies: 
            - VPCAccessPolicy: {}
            - AWSSecretsManagerRotationPolicy:
                FunctionName:
                    Ref: functionName
            - !If
                - KmsKeyArnExists
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - kms:Decrypt
                            - kms:DescribeKey
                            - kms:GenerateDataKey
                        Resource: !Ref kmsKeyArn
                - !Ref "AWS::NoValue"
            Environment:
                Variables:
                    SECRETS_MANAGER_ENDPOINT:
                        Ref: endpoint
                    EXCLUDE_CHARACTERS:
                        Ref: excludeCharacters
            VpcConfig:
                !If
                    - AddVpcConfig
                    -
                        SubnetIds: !Ref vpcSubnetIds
                        SecurityGroupIds: !Ref vpcSecurityGroupIds
                    - !Ref "AWS::NoValue"
            Tags:
                SecretsManagerLambda: Rotation

    LambdaPermission:
        Type: 'AWS::Lambda::Permission'
        Properties:
            Action: 'lambda:InvokeFunction'
            FunctionName: !GetAtt SecretsManagerRDSPostgreSQLRotationSingleUser.Arn
            Principal: !Ref invokingServicePrincipal
            SourceAccount: !Ref "AWS::AccountId"

Outputs:
    RotationLambdaARN:
        Description: The ARN of the rotation lambda
        Value: !GetAtt SecretsManagerRDSPostgreSQLRotationSingleUser.Arn
```

### Expected Behavior

Automated created Lambda Functions (like this HostedRotation one) should work.

### Current Behavior

Scheduled Key/Secret Rotation does not work

### Reproduction Steps

Create a Stack, apply the transform macro to it `stack.addTransform('AWS::SecretsManager-2020-07-23');` and create a secret within this stack. To this secret add a hostedRotation lambda (by using `secret.addRotationSchedule()` function or by the help of the secretsManager like it is shown below). A nested stack will be generated by CloudFormation automatically containing the CloudFormation template described within the problem/bug section of this issue.

```typescript
import {
  aws_secretsmanager as secretsManager,
} from 'aws-cdk-lib';

new secretsManager.CfnRotationSchedule(this, 'RotationConstruct', {
      secretId: 'arn:aws:secretsmanager::99999999999:secret:secret-name',
      rotationRules: {
        automaticallyAfterDays: 30,
      },
      hostedRotationLambda: {
        rotationType: 'PostgreSQLSingleUser',
        ...
      },
    });
```

### Possible Solution

The Code within the aws-provided S3 Bucket contains dependencies which require a runtime of `PYTHON_3_7`.
Current Solution is to download the already deployed code as zip file and then create a custom lambda using that zip file and the right runtime `PTYHON_3_7`.

### CDK CLI Version

2.32.0

### Node.js Version

v16.10

### OS

MacOS

### Language

Typescript
