### ISSUE TITLE
ApiGateway when creating domain: Invalid tag key. Tag keys cannot start with 'aws:'

### ISSUE THREAD

**Issue by ScopeSV** [aws/aws-cdk#23738]
### Describe the bug

When trying to configure a domain with cloudformation via serverless config,
I get the error ` Invalid tag key. Tag keys cannot start with 'aws:'`

I did the same process a couple of days ago, with the same config, and it worked seamlessly. 

### Expected Behavior

To create the domain

### Current Behavior

 Invalid tag key. Tag keys cannot start with 'aws:'

After this occurred, I tried for fun to create a tag that started with `aws:` in the aws console, 
and got the same error. So it seems like something is putting on a `aws:` tag which is not allowed (anymore?)

### Reproduction Steps

```yml
    CustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      DependsOn:
        - Certificate
      Properties:
        DomainName: "domain name"
        DomainNameConfigurations:
          - CertificateArn: !Ref Certificate
            SecurityPolicy: TLS_1_2
            EndpointType: REGIONAL
```

### CDK CLI Version

no cdk

### Node.js Version

14, 16

### OS

OS X newest

### Language

Typescript

### Language Version

not relevant
