### ISSUE TITLE
(aws-appsync): Datasource not found after migrating from aws-appsync-alpha

### ISSUE THREAD

**Issue by danrivett** [aws/aws-cdk#23743]
### Describe the bug

We were previously using `@aws-cdk/aws-appsync-alpha` version `2.12.0-alpha.0` and recently migrated to the stable AppSync CDK construct in `2.60.0`.

CDK deploys are now failing as the `AWS::AppSync::Resolver` generated cannot find associated `AWS::AppSync::DataSource`:

```
12:30:25 p.m. | CREATE_FAILED        | AWS::AppSync::Resolver          | apiQuerygetCart3792FB8F
No data source found named Query-getCart (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 33df3ea5-79c8-49d0-acd3-b8b0cf1c6549; Proxy: null)
```

We think it's related to this PR merged 3 months ago: aws/aws-cdk#22378 which changed how DataSource names are sanitized to remove invalid characters (such as hyphens in our case).

It used to sanitize the name and apply the sanitized name to both the L1 and L2 Construct `name` field, however now it only santitizes the underlying L1 `CfnDataSource` `name` field and not the L2 `name` field leaving it inconsistent and resulting in the above error.

### Expected Behavior

I would expect that both the L2 and L1 names be the same like it was prior to aws/aws-cdk#22378 to avoid issues such as we encountered where the wrong name is used and can't be found.

### Current Behavior

The L1 `CfnDataSource` `name` field is sanitized (in our case stripping out hyphens) whilst the L2 DataSource Construct is not. This leads to the CDK not deploying the stack correctly since it cannot find the DataSource:

```
  apiQuerygetCart3792FB8F:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - apiC8550315
          - ApiId
      FieldName: getCart
      TypeName: Query
      DataSourceName: Query-getCart
      Kind: UNIT
...
  cartcartresolversQuerygetCartdatasource4A98C914:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt:
          - apiC8550315
          - ApiId
      Name: QuerygetCart
      Type: AWS_LAMBDA
...
```

### Reproduction Steps

Create an AppSync Resolver with a DataSource (such as a `LambdaDataSource`) that has a name with a hypen in it.

### Possible Solution

The L2 `name` field should be set to `supportedName` so that it matches the L1 `name` field.

See [here](https://github.com/aws/aws-cdk/blob/6dc15d4/packages/%40aws-cdk/aws-appsync/lib/data-source.ts#L118-L128).

### CDK CLI Version

2.60.0

### Node.js Version

16.19.0

### OS

MacOS

### Language

Typescript
