### ISSUE TITLE
cfn-include: CFN function not working with tags

### ISSUE THREAD

**Issue by agp28** [aws/aws-cdk#23934]
### Describe the bug

Using CfnInclude to use a cloudformation template having cfn functions like "Fn::If" gives an error.

**Simplified sample cloudformation temlate:-**

```
    "V2UserLoadBalancer": {
      "Type": "AWS::ElasticLoadBalancingV2::LoadBalancer",
      "Properties": {
        "Tags": [
          {
            "Fn::If": [
              "SomeCondition",
              {
                "Key": "SomeKey",
                "Value": "SomeValue"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          }
        ]
      }
    }
```

**Error Message:-**
```
Error: Resolution error: Supplied properties not correct for "CfnLoadBalancerProps"
  tags: element 0: {} should have a 'key' and a 'value' property.
```

When trying to use CFN function with tags for 

Similar bug that was filed in past, but it looks https://github.com/aws/aws-cdk/pull/19923 it only worked for a certain set of tag properties.

### Expected Behavior

It should have worked without giving any errors related to tags.

### Current Behavior

CfnInclude is not supporting Tag properties with conditions for certain resources due to which it becomes impossible to consume such templates. 

### Reproduction Steps

Added in issue description.

### CDK CLI Version

2.60.0

### Node.js Version

16

### OS

macOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this, I'm able to confirm the same error with a template I can verify successfully deploys.

My guess as to why this is happening is because the other fix addressed an atypical way to tag resources in CloudFormation. i.e. the resource addressed in the other PR doesn't use the `Tags` universal type, and instead a [`TagProperty` type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-tags.html). Since it uses a unique type, my theory is that the tag property doesn't go through [`validateCfnTag()`](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/core/lib/runtime.ts#L252) check like it does for most resources, but instead goes through the `validateObject()` check. I could be wrong however, and even if I'm right I'm not sure how we should fix this.

**Comment by ozeebee** [comment]
Hello, I'm experiencing same issue ...
Any chance to have this fixed ?
Or any clue to work-around this ?
Thanks !

**Comment by BrandonShutter** [comment]
Bump, running into this as well.

**Comment by jamestelfer** [comment]
This issue causes the [Buildkite Elastic Stack](https://github.com/buildkite/elastic-ci-stack-for-aws/tree/main) template to fail to import: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/main/templates/aws-stack.yml

Errors are of the form:

```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnBucketProps"
  tags: element 0: {} should have a 'key' and a 'value' property.
```

Commenting out the offending tag specifications allows this to work:

```yaml
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Role
                Value: buildkite-agent
              - Key: Name
                Value: !Ref InstanceName
              - Key: BuildkiteAgentRelease
                Value: !Ref BuildkiteAgentRelease
              - Key: BuildkiteQueue
                Value: !Ref BuildkiteQueue
              - !If
                - UseCostAllocationTags
                - Key: !Ref CostAllocationTagName
                  Value: !Ref CostAllocationTagValue
                - !Ref "AWS::NoValue"
```

Hopefully this gives a further real world test subject for any fix.
