### ISSUE TITLE
(aws-amazonmq): CfnBroker.UserProperty username/password doesn't support IResolvable

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#24015]
### Describe the bug

When using the `CfnBroker` to construct a new AmazonMQ Broker, and passing an array of `UserProperty` to `users`, `username` and `password` are not typed to allow `IResolvable` values, even though they work.

### Expected Behavior

Expected `username` and `password` to accept `IResolvable` values.

### Current Behavior

Type error that a `string` is expected.

### Reproduction Steps

```
  const broker = new CfnBroker(scope, brokerName, {
    autoMinorVersionUpgrade: true,
    brokerName,
    deploymentMode,
    engineType,
    engineVersion,
    hostInstanceType: instanceType,
    publiclyAccessible: publicInstance,
    users: [
      {
        password: SecretValue.secretsManager('/my/rabbitmq/creds', { jsonField: 'password' }),
        username: SecretValue.secretsManager('/my/rabbitmq/creds', { jsonField: 'username' })
      }
    ]
  });
```

### Possible Solution

The workaround is to case the `UserProfie` object `as any`:

```
  const broker = new CfnBroker(scope, brokerName, {
    autoMinorVersionUpgrade: true,
    brokerName,
    deploymentMode,
    engineType,
    engineVersion,
    hostInstanceType: instanceType,
    publiclyAccessible: publicInstance,
    users: [
      {
        password: SecretValue.secretsManager('/my/rabbitmq/creds', { jsonField: 'password' }),
        username: SecretValue.secretsManager('/my/rabbitmq/creds', { jsonField: 'username' })
      } as any
    ]
  });
```

Using `cdk synth` I can see that properties are set as such:

```
    Properties:
      AutoMinorVersionUpgrade: true
      BrokerName: dev-infra-core-default-rmq
      DeploymentMode: SINGLE_INSTANCE
      EngineType: RABBITMQ
      EngineVersion: 3.10.10
      HostInstanceType: mq.m5.large
      PubliclyAccessible: true
      Users:
        - Password: "{{resolve:secretsmanager:/my/rabbitmq/creds:SecretString:password::}}"
          Username: "{{resolve:secretsmanager:/my/rabbitmq/creds:SecretString:username::}}"
```

I'm then able to log into the rabbitmq instance web interface using the credentials from the same secret.

### CDK CLI Version

2.63.0

### Framework Version

2.63.0

### Node.js Version

18

### OS

MacOS

### Language

Typescript

### Language Version

4.8.4
