### ISSUE TITLE
(stepfunctions_tasks): BatchSubmitJob emits incorrect RoleDefaultPolicy and invalid CFN when jobQueueArn is defined later.

### ISSUE THREAD

**Issue by endian675** [aws/aws-cdk#24084]
### Describe the bug

`BatchSubmitJob()` generates an invalid RoleDefaultPolicy by emitting the literal value `$.jobQueueArn` instead of wildcard. This behaviour is inconsistent with `jobDefinitionArn`, which emits a wildcard when the value of the variable is not available (i.e., it will be created later, outside of CDK/CFN). 

``` 
MonteCarloPipelineRoleDefaultPolicy3E3E3B10:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Preprocessing329E01E4
                - Arn
          - Action: batch:SubmitJob
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":batch:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :job-definition/*
              - $.jobQueueArn <----------INVALID
```

### Expected Behavior

``` 
MonteCarloPipelineRoleDefaultPolicy3E3E3B10:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Preprocessing329E01E4
                - Arn
          - Action: batch:SubmitJob
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":batch:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :job-definition/*
              - Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":batch:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :job-queue/
 ```

### Current Behavior

```
  MonteCarloPipelineRoleDefaultPolicy3E3E3B10:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - Preprocessing329E01E4
                - Arn
          - Action: batch:SubmitJob
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":batch:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :job-definition/*
              - Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":batch:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :job-queue/*`

### Reproduction Steps

```        
montecarlo_task = stepfunctions_tasks.BatchSubmitJob(self, 'MonteCarlo',
          job_name=stepfunctions.JsonPath.string_at('$.jobName'),
          job_queue_arn=stepfunctions.JsonPath.string_at('$.jobQueueArn'),
          job_definition_arn=stepfunctions.JsonPath.string_at('$.jobDefinitionArn'),
          result_path='$.output',
          array_size=stepfunctions.JsonPath.number_at('$.output.Payload.body.arrayJobSize'),
          payload=
              stepfunctions.TaskInput.from_object({
                      "action": "price",
                      "inputUri": stepfunctions.JsonPath.string_at('$.inputUri'),
                      "outputUri": stepfunctions.JsonPath.string_at('$.outputUri'),
                      "bucket": stepfunctions.JsonPath.string_at('$.output.Payload.body.bucket'),
                      "key": stepfunctions.JsonPath.string_at('$.output.Payload.body.key')
              })
          )
```

### Possible Solution

`jobDefinitionArn` is handled correctly, `jobQueueArn` should be handled the same way

### Additional Information/Context

_No response_

### CDK CLI Version

2.50.0 (build 4c11af6)

### Framework Version

_No response_

### Node.js Version

v16.18.1

### OS

Amazon Linux 2

### Language

Python

### Language Version

Python (3.7.16)

### Other information

_No response_
