### ISSUE TITLE
EC2: EC2.Volume.throughput does not get passed on into CFN

### ISSUE THREAD

**Issue by chrisdotn** [aws/aws-cdk#24107]
### Describe the bug

I'm using `EC2.Volume` to create a GP3-Volume and I specify the `throughput` explicitly. The value does not make it to the CFN script and hence the resulting volume has the default througput of 125. 

This is the CDK:

```
import { Stack, StackProps, RemovalPolicy, Size, Tags } from "aws-cdk-lib";
import { Construct } from "constructs";
import { Volume, EbsDeviceVolumeType } from "aws-cdk-lib/aws-ec2";
import { NagSuppressions } from "cdk-nag";

export interface DataVolumeStackProps extends StackProps { }

export class DataVolumeStack extends Stack {
  public readonly dataVolume: Volume
  constructor(scope: Construct, id: string, props: DataVolumeStackProps) {
    super(scope, id, props);

    this.dataVolume = new Volume(this, 'DataVolume', {
      availabilityZone: Stack.of(this).availabilityZones[0],
      size: Size.tebibytes(2),
      volumeType: EbsDeviceVolumeType.GP3,
      removalPolicy: RemovalPolicy.RETAIN,
      throughput: 250,
    })

    Tags.of(this.dataVolume).add('Name', 'Data Volume')

    // cdk-nag suppressions
    NagSuppressions.addResourceSuppressions(
      this,
      [
        {
          id: "AwsSolutions-EC26",
          reason: "Volume used for storing public data, no need for encryption",
        },
      ],
      true
    );
  }
}
```

The resulting CFN doesn't say anything about throughput: 
```
Resources:
  DataVolume175940C2:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: eu-west-1a
      MultiAttachEnabled: false
      Size: 2048
      Tags:
        - Key: Name
          Value: Data Volume
      VolumeType: gp3
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: DataVolumeStack/DataVolume/Resource
      cdk_nag:
        rules_to_suppress:
          - reason: Volume used for storing public data, no need for encryption
            id: AwsSolutions-EC26
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzPWM1BMLC/WTU7J1s3JTNKrDi5JTM7WAQrFpyYb6VWH5eeU5qbqOKflQVi1IGZQanF+aVEykJOXn5Kql1WsX2ZopmdoCTQrqzgzU7eoNK8kMzdVLwhCAwCjDN5cZwAAAA==
    Metadata:
      aws:cdk:path: DataVolumeStack/CDKMetadata/Default
  
// cut Output, Parameters, Rules 
```

### Expected Behavior

The resulting CFN should include a `Throughput` setting, the resulting Volume should have the correct througput.

### Current Behavior

The resulting CFN does not include a `Throughput` setting, the resulting Volume has the default througput of 125.

### Reproduction Steps

cdk synth

### CDK CLI Version

2.64.0

### Node.js Version

v16.19.0

### OS

MacOS (Ventura)

### Language

Typescript
