### ISSUE TITLE
(aws-dynamodb): adding DeletionProtectionEnabled property to TableProps

### ISSUE THREAD

**Issue by sakurai-ryo** [aws/aws-cdk#24540]
### Describe the feature

Deletion protection feature is now available for DynamoDB.
announcement: https://aws.amazon.com/jp/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/

When using CloudFormation, the property DeletionProtectionEnabled is available.
```yaml
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: test
      ....
      DeletionProtectionEnabled: true
```

I propose to add the `deletionProtectionEnabled` property to TableProps  to support this feature.

### Use Case

Enable delete protection on table creation or update to protect the table.

### Proposed Solution

Add DeletionProtectionEnabled property to TableProps.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.TableProps.html

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.67.0

### Environment details (OS name and version, etc.)

Macos
