### ISSUE TITLE
(aws-ecs): Creating cluster with id 'Resource' fails  

### ISSUE THREAD

**Issue by organom** [aws/aws-cdk#24547]
### Describe the bug

Creating an `ecs.Cluster` with id `Resource`  and `enableFargateCapacityProviders: true` fails

### Expected Behavior

`Resource` should be an allowed id when creating an `ecs.Cluster`, even with `enableFargateCapacityProviders` set to true

### Current Behavior

Fails with

```
/.../node_modules/constructs/src/construct.ts:403
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'Resource' in Cluster [Resource]
    at Node.addChild (/.../node_modules/constructs/src/construct.ts:403:13)
    at new Node (/.../node_modules/constructs/src/construct.ts:71:17)
    at new Construct (/.../node_modules/constructs/src/construct.ts:463:17)
    at new CfnElement (/.../node_modules/aws-cdk-lib/core/lib/cfn-element.js:1:469)
    at new CfnRefElement (/.../node_modules/aws-cdk-lib/core/lib/cfn-element.js:2:818)
    at new CfnResource (/.../node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:825)
    at new CfnClusterCapacityProviderAssociations (/.../node_modules/aws-cdk-lib/aws-ecs/lib/ecs.generated.js:1:29530)
    at MaybeCreateCapacityProviderAssociations.visit (/.../node_modules/aws-cdk-lib/aws-ecs/lib/cluster.js:1:17319)
    at recurse (/.../node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:1848)
    at recurse (/.../node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:2176)
```

### Reproduction Steps

The typical example of the usage of an id being `Resouce` would be on the implementation of a custom construct around ecs.Cluster

```typescript
import {Construct} from 'constructs';
import {FargateAlbService, FargateAlbServiceOptions} from './fargate-alb-service';
import {IVpc} from 'aws-cdk-lib/aws-ec2';
import {LogGroup} from 'aws-cdk-lib/aws-logs';
import * as ecs from 'aws-cdk-lib/aws-ecs';

export class FargateCluster extends Construct {
	readonly resource: ecs.ICluster;

	constructor(scope: Construct, id: string, props: {vpc: IVpc}) {
		super(scope, id);

		this.resource = new ecs.Cluster(this, 'Resource', {
			containerInsights: true,
			enableFargateCapacityProviders: true,
			executeCommandConfiguration: {
				logConfiguration: {
					cloudWatchLogGroup: new LogGroup(this, 'EcsLogGroup', {}),
					cloudWatchEncryptionEnabled: false
				},
				logging: ecs.ExecuteCommandLogging.OVERRIDE,
			},
			vpc: props.vpc
		});
            
 		// extra Custom code
	}
```

In case we use lets say `Resource1` as ID and synthesize, we find out that ecs.Cluster is creating the cluster with path `Resource` and the `ClusterCapacityProviderAssociations` with the `id` given, in this case `Resouce1`

```
  ECSResource147ACA014:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          LogConfiguration:
            CloudWatchEncryptionEnabled: false
            CloudWatchLogGroupName:
              Ref: ECSEcsLogGroupF7D52C21
          Logging: OVERRIDE
    Metadata:
      aws:cdk:path: test/ECS/Resource1/Resource
  ECSResource1B4649305:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      Cluster:
        Ref: ECSResource147ACA014
      DefaultCapacityProviderStrategy: []
    Metadata:
      aws:cdk:path: test/ECS/Resource1/Resource1
```

### CDK CLI Version

2.67.0

### Node.js Version

18.13.0

### OS

MacOs 

### Language

Typescript

### Language Version

TypeScript (4.9.5)
