### ISSUE TITLE
(bootstrap): remove Security Hub finding ECR.3

### ISSUE THREAD

**Issue by tenjaa** [aws/aws-cdk#24723]
### Describe the feature

Similar to https://github.com/aws/aws-cdk/pull/24175 I would like to see a lifecycle rule that does not do much but at least per default resolves the finding.

I know that there is an RFC for garbage collection in the works.

### Use Case

After enabling AWS Foundational Security Best Practices v1.0.0 in the security hub,
I am always frustrated when I see failed checks.

### Proposed Solution

Similar to https://github.com/aws/aws-cdk/pull/24175 just a a LifecyclePolicy to the repository:

```yaml
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "no-op",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 365
                },
                "action": { "type": "expire" }
              }
            ]
          }
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

-
