### ISSUE TITLE
aws-elasticloadbalancingv2: SSM Secure reference is not supported in: [AWS::ElasticLoadBalancingV2::ListenerRule/Properties/Actions]

### ISSUE THREAD

**Issue by SydneyUni-Jim** [aws/aws-cdk#24904]
### Describe the bug

CDK code like this.

```typescript
listener.addAction('Authenticate', {
  priority: 200,
  conditions: [ ListenerCondition.pathPatterns([ '/login' ]) ],
  action: ListenerAction.authenticateOidc({
    authorizationEndpoint: 'https://idp/oauth2/v1/authorize',
    clientId: 'id',
    clientSecret: SecretValue.ssmSecure('clientSecret'),,
    issuer: 'https://idp',
    tokenEndpoint: 'https://idp/oauth2/v1/token',
    userInfoEndpoint: 'https://idp/oauth2/v1/userinfo',
    scope: 'openid profile email',
    next: ListenerAction.forward([ backendTarget ]),
  })
})
```

Synthesises as this.

```yaml
ALBListenerAuthenticateRule8274275E:
  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  Properties:
    Actions:
      - AuthenticateOidcConfig:
          AuthorizationEndpoint: https://idp/oauth2/v1/authorize
          ClientId: id
          ClientSecret: "{{resolve:ssm-secure:clientSecret}}"
          Issuer: https://idp
          Scope: openid profile email
          TokenEndpoint: https://idp/oauth2/v1/token
          UserInfoEndpoint: https://idp/oauth2/v1/userinfo
        Order: 1
        Type: authenticate-oidc
      - Order: 2
        TargetGroupArn:
          Ref: ALBListenerBackendServiceGroup47D91FB3
        Type: forward
    Conditions:
      - Field: path-pattern
        PathPatternConfig:
          Values:
            - /login
    Priority: 200
    ListenerArn:
      Ref: ALBListener57D72953
  Metadata:
    aws:cdk:path: app/ALB/Listener/AuthenticateRule/Resource
```

But the CloudFormation fails to create the change set.

```
failed: Error: Failed to create ChangeSet cdk-deploy-change-set on app: FAILED, SSM Secure reference is not supported in: [AWS::ElasticLoadBalancingV2::ListenerRule/Properties/Actions]
```

### Expected Behavior

The CDK works around the CloudFormation limitation.

### Current Behavior

The CDK uses a SSM Secure reference where it's not supported.

### Reproduction Steps

See the bug description

### CDK CLI Version

2.72.1 (build ddbfac7)

### Framework Version

2.72.1

### Node.js Version

v19.8.1

### OS

macos 13.3 aarch64

### Language

Typescript

### Language Version

TypeScript (4.9.5)
