### ISSUE TITLE
S3: Cors rules not synthesizing exposeHeaders

### ISSUE THREAD

**Issue by anjanvb** [aws/aws-cdk#25122]
### Describe the bug

I've got an S3 bucket like this

```javascript
new s3.Bucket(this, 'my-bucket', {
      bucketName: 'my-bucket',
      versioned: false,
      encryption: s3.BucketEncryption.KMS,
      bucketKeyEnabled: true,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      cors: [{
              allowedMethods: [
                s3.HttpMethods.GET,
                s3.HttpMethods.HEAD,
                s3.HttpMethods.POST,
                s3.HttpMethods.PUT
              ],
              allowedOrigins: ['*'],
              allowedHeaders: ['*'],
              exposeHeaders: [                
                "x-amz-server-side-encryption",
                "x-amz-request-id",
                "x-amz-id-2",
                "ETag"
              ],
              maxAge: 3000
            }]
    });   
```

The Cfn synthesized is this

```yaml
BucketName: my-bucket
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
            AllowedOrigins:
              - "*"
            MaxAge: 3000
```

Bucket gets created with `ExposeHeaders: []` in CORS rule.

### Expected Behavior

The appropriate `ExposeHeaders` should be applied in the CORS rule.

### Current Behavior

CDK is not synthesizing the `exposeHeaders` correctly.

### Reproduction Steps

create a bucket as shown above.

### CDK CLI Version

2.39.1

### Node.js Version

v14.18.2

### OS

MacOS

### Language

Typescript

### Language Version

CDK App is written in Javascript.

### Other information

Version info 

"aws-cdk-lib": "^2.39.1"

**Comment by pahud** [comment]
I guess you should use `exposedHeaders` instead of `exposeHeaders`

This is my synthesized output:

```yaml
  mybucket15D133BF:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID:
                Fn::GetAtt:
                  - mybucketKey36A9D130
                  - Arn
              SSEAlgorithm: aws:kms
      BucketName: my-bucket
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            MaxAge: 3000
```
