### ISSUE TITLE
CloudFront does not use global domain name for S3 origins

### ISSUE THREAD

**Issue by nodomain** [aws/aws-cdk#25253]
### Describe the bug

When creating a CloudFront behavior with an S3 origin, the regional domain name is used.

### Expected Behavior

The global domain name shall be used.

### Current Behavior

This results to errors like this:
```xml
<Error>
<Code>PermanentRedirect</Code>
<Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
<Endpoint>s3.amazonaws.com</Endpoint>
<Bucket>xxx</Bucket>
<RequestId>yyy</RequestId>
<HostId>wI/t0et5UGWUS7cNLNnpdL+KdbW3mDydKf267yfQcjRwf202qUiClSMitDG9UvlHtgvdV2FOmFsLb7ZOyA/kbA==</HostId>
</Error>
```

### Reproduction Steps

Respective code:

```typescript
    const errorPagesOrigin = new S3Origin(Bucket.fromBucketAttributes(this, 'ErrorPagesBucket', { bucketName: 'xxx', region: 'us-east-1' }));

// ...
 additionalBehaviors: {
    '_errorpages/*': {
        origin: errorPagesOrigin,
        compress: true,
        allowedMethods: AllowedMethods.ALLOW_GET_HEAD,
        viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS
    },
// ...
```

### CDK CLI Version

2.76.0 (build 78c411b)

### Node.js Version

v16.16.0

### OS

Mac OS

### Language

Typescript

**Comment by pahud** [comment]
If your bucket and cdk deploying region are both in `us-east-1`, it should work!

check out my sample below:

```ts

    const errorPagesBucket = new s3.Bucket(this, 'ErrorPageBucket');

    new s3d.BucketDeployment(this, 'deploy', {
      destinationBucket: errorPagesBucket,
      sources: [s3d.Source.asset(path.join(__dirname, '../_errorpages'))],
    })

    const originAccessIdentity = new cloudfront.OriginAccessIdentity(this, 'OriginAccessIdentity');
    errorPagesBucket.grantRead(originAccessIdentity)

    // const errorPagesOrigin = new origins.S3Origin(s3.Bucket.fromBucketAttributes(this, 'ErrorPagesBucket', { bucketName: 'pahud-tmp-us-east-1', region: 'us-east-1' }));
    const importedBucket = s3.Bucket.fromBucketAttributes(this, 'ErrorPagesBucket', { 
      bucketName: errorPagesBucket.bucketName, 
      region: 'us-east-1',
    });

    const errorPagesOrigin = new origins.S3Origin(importedBucket, {
      originAccessIdentity,
    });

    const dist = new cloudfront.Distribution(this, 'DemoDist', {
      defaultBehavior: {
        origin: new origins.HttpOrigin('aws.amazon.com'),
      },
      additionalBehaviors: {
        '_errorpages/*': {
            origin: errorPagesOrigin,
            compress: true,
            allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD,
            viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS
        },
      },
    });

    new CfnOutput(this, 'DistURL', { value: `https://${dist.distributionDomainName}` })
   
```

cdk synth

```
 DemoDist003812C6:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            Compress: true
            PathPattern: _errorpages/*
            TargetOriginId: demostack5DemoDistOrigin2E03F6AE0
            ViewerProtocolPolicy: redirect-to-https
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: demostack5DemoDistOrigin19C14FFC1
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            DomainName: aws.amazon.com
            Id: demostack5DemoDistOrigin19C14FFC1
          - DomainName:
              Fn::Join:
                - ""
                - - Ref: ErrorPageBucketFD04CE26
                  - .s3.us-east-1.amazonaws.com
            Id: demostack5DemoDistOrigin2E03F6AE0
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: OriginAccessIdentityDF1E3CAC
```


Accessing the error page


```sh
% curl https://d2zmyxahwihxos.cloudfront.net/_errorpages/default.html
Hello CDK
```
