### ISSUE TITLE
Multiple security groups associated to a fargate service

### ISSUE THREAD

**Issue by npb17** [aws/aws-cdk#2540]
You can associate multiple security groups to a fargate service (i think the limit is 5 currently). The higher level cdk construct for fargate service currently only allows a single security group.

Is there something in the works that would allow us to associate multiple security groups or a possible workaround?

**Comment by tsykora-verimatrix** [comment]
I've the same issue. I'd like to assign two different security groups to a Fargate Service but FargateService construct only allows one. If I try to specify two in a list, I get back:

jsii.errors.JSIIError: Expected object reference, got [{"$jsii.byref":"@aws-cdk/aws-ec2.SecurityGroupXXXXX"},{"$jsii.byref":"@aws-cdk/aws-ec2.SecurityGroupXXXXX"}]

Documentation states "securitygroups", plural:
security_group (Optional[ISecurityGroup]) – The security groups to associate with the service. If you do not specify a security group, the default security group for the VPC is used. Default: - A new security group is created.

But it only takes a single SG.
Afaik there is no workaround for this atm.

**Comment by robertd** [comment]
Same issue here. We just hit the wall with this one and unfortunately override doesn't work (or I don't know how to set it up :) ).
```typescript
const resource = tnmaccessService.node.findChild("Service") as ecs.CfnService;
resource.networkConfiguration.awsvpcConfiguration.securityGroups = [ "sg-12345", "sg-54321"];
```

**Comment by tsykora-verimatrix** [comment]
@robertd override doesn't work either. Afaik there is no workaround. I had to create a SG with ingress rules mixed from the two SGs that I wanted to use. It is ugly and not maintainable at large scale.

**Comment by robertd** [comment]
@tsykora-verimatrix #3985 should address this issue. Hopefully it makes it into `1.8.0`.

**Comment by robertd** [comment]
@tsykora-verimatrix Here is a workaround

```typescript
const cfnService = ecsService.node.findChild("Service") as ecs.CfnService;

//Inject cfn override for multiple SGs
cfnService.addOverride("Properties.NetworkConfiguration.AwsvpcConfiguration.SecurityGroups", [
  secGroupA.securityGroupId, 
  secGroupB.securityGroupId
]);
```

Output CFN...
```
NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - sg-12345
            - sg-67890
          Subnets:
            - subnet-12345
            - subnet-54321
            - subnet-67890
```
