### ISSUE TITLE
Lambda's `retry_attempts` argument does not seem to work when it is the target of Eventbridge rule

### ISSUE THREAD

**Issue by eugeneh101** [aws/aws-cdk#25423]
### Describe the bug

When the target of an Eventbridge rule is a Lambda, `retry_attempts` argument does not seem to be binding. For example, if I set `retry_attempts` to be 0 and the Lambda fails, the Lambda will be invoked with the same `RequestId` 1 minute later and another invocation 2 minutes after that (also with the same `RequestId)`. That is a total of 3 invocations (1 original + 2 retries).
I discovered that on instantiating a `aws_cdk.aws_lambda.Function` that the argument `retry_attempts` has a default value of 2.

I would like to set `retry_attempts` to 0 when I add the Lambda as the target to the Eventbridge rule, not set `retry_attempts` when instantiating a Lambda `Function` (I want to be able to leave this value unset as the default). There's presumably a use case where this distinction is important such as if there's another asynchronous invocation of this Lambda where you want it to have 2 retries but you specifically want 0 retries as the Eventbridge rule target.

Also, there is a case where you want retries from Eventbridge to be very high. When adding Lambda as Eventbridge target, `retry_attempts` allows a maximum of 185 retries. However, Lambda `Function` instantiation allow allows `retry_attempts` to only 2 retries. I assume that having more than 2 Lambda retries as part of Eventbridge target is not currently possible thru `cdk`.

### Expected Behavior

I expected when setting up the Eventbridge rule's target that the `retry_attempts` would work.

### Current Behavior

`retry_attempts` as set by Lambda `Function`'s instantiation is used.

### Reproduction Steps

```python
from aws_cdk import (
    App,
    Duration,
    Stack,
    aws_events as events,
    aws_events_targets as events_targets,
    aws_lambda as _lambda,
)


class TempStack(Stack):
    def __init__(
        self, scope, construct_id, **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.broken_lambda = _lambda.Function(
            self,
            "BrokenLambda",
            runtime=_lambda.Runtime.PYTHON_3_9,
            code=_lambda.InlineCode("def handler(event, context): raise"),
            handler="index.handler",
            # retry_attempts=0,  # actually does something. I don't want to set this argument

        )

        self.scheduled_eventbridge_event = events.Rule(
            self,
            "RunEvery3Minutes",
            event_bus=None,
            schedule=events.Schedule.rate(Duration.minutes(3)),
        )
        self.scheduled_eventbridge_event.add_target(
            events_targets.LambdaFunction(
                handler=self.broken_lambda,
                retry_attempts=0,  # doesn't seem to do anything. I want to use this argument
            )
        )


app = App()
TempStack(app, "TempStack")
app.synth()
```

### CDK CLI Version

2.77.0 (build 06a0b19)

### Node.js Version

9.5.0

### OS

macOs Ventura 13.0

### Language

Python

### Language Version

Python 3.9.16

**Comment by peterwoodworth** [comment]
This is working for me, are you seeing this in your template? Look at `MaximumRetryAttempts`.

```
  Rule4C995B7F:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - Function76856677
              - Arn
          Id: Target0
          RetryPolicy:
            MaximumRetryAttempts: 0
```

My code:

```
        fn = _lambda.Function(self, "MyFunc",
            runtime=_lambda.Runtime.NODEJS_14_X,
            handler="index.handler",
            code=_lambda.Code.from_inline("exports.handler = handler.toString()")
        )

        rule = events.Rule(self, "rule",
            event_pattern=events.EventPattern(
                source=["aws.ec2"]
            )
        )

        queue = sqs.Queue(self, "Queue")

        rule.add_target(targets.LambdaFunction(fn,
            dead_letter_queue=queue,  
            max_event_age=cdk.Duration.hours(2), 
            retry_attempts=3
        ))
```

**Comment by eugeneh101** [comment]
@peterwoodworth Nice to see you here. Thanks for answering my other Issue.

Here's what I get when I run `cdk synth`:
```
Resources:
  BrokenLambdaServiceRole31391E55:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TempStack/BrokenLambda/ServiceRole/Resource
  BrokenLambda367CBACE:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "def handler(event, context): raise"
      Role:
        Fn::GetAtt:
          - BrokenLambdaServiceRole31391E55
          - Arn
      Handler: index.handler
      Runtime: python3.9
    DependsOn:
      - BrokenLambdaServiceRole31391E55
    Metadata:
      aws:cdk:path: TempStack/BrokenLambda/Resource
  RunEvery3Minutes2D3569AB:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(3 minutes)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - BrokenLambda367CBACE
              - Arn
          Id: Target0
          RetryPolicy:
            MaximumRetryAttempts: 0
    Metadata:
      aws:cdk:path: TempStack/RunEvery3Minutes/Resource
  RunEvery3MinutesAllowEventRuleTempStackBrokenLambdaD162C99A1D93EA0D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - BrokenLambda367CBACE
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - RunEvery3Minutes2D3569AB
          - Arn
    Metadata:
      aws:cdk:path: TempStack/RunEvery3Minutes/AllowEventRuleTempStackBrokenLambdaD162C99A
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02MywrCMBREv6X75PoCi+uC65J+gKRJxGubG8hDkZB/N7UuujozZ2CO0Lawb+Q7cKUnPuMIeYhSTayqW56lHbWEfE2kIjpi3Z22uTfeYgi1FYbSQhZuNsuwsDDzMhRDtelvK0thwgSXvFrVJneONMbfWf+JD0e7E1zgcG6eAZH7RBGtAbHyCx9dGO26AAAA
    Metadata:
      aws:cdk:path: TempStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

Yep, `MaximumRetryAttempts: 0` is showing up in the Cloudformation template. However when I deploy this stack, the Clooudwatch logs looks like this:
<img width="1023" alt="Screenshot 2023-05-04 at 10 26 25 PM" src="https://user-images.githubusercontent.com/8621541/236366026-e5f5be84-61d2-4777-addf-d33c09bd3ade.png">
The same `RequestId` (31b5332e-25ce-4b2e-9357-99b9a3a93e56) is showing up 3 times: 1 original call and then 1 retry at 1 minute afterwards and 1 retry at 2 minutes after that.


If I go to the next `RequestId` (33f09206-3d9e-4507-a7f0-f798ab437bb6), same thing:
<img width="897" alt="Screenshot 2023-05-04 at 10 29 33 PM" src="https://user-images.githubusercontent.com/8621541/236366242-ba7414f8-96dd-4fb3-9397-a726ae28c059.png">


Is that evidence that `MaximumRetryAttempts: 0` in Cloudformation template is not working?
