### ISSUE TITLE
(dms): CfnReplicationSubnetGroup.replication_subnet_group_identifier not set

### ISSUE THREAD

**Issue by rectalogic** [aws/aws-cdk#25700]
### Describe the bug

`CfnReplicationSubnetGroup.replication_subnet_group_identifier` is generated by CFN and accessible using `Ref`. But the attribute is `None` in the CDK unless explicitly set by the user. This causes the `CfnReplicationInstance` to end up with no subnet group at all.

### Expected Behavior

`CfnReplicationSubnetGroup.replication_subnet_group_identifier` should resolve to `{"Ref": "SubnetGroup"}` instead of the locally set name (which may be `None`, or the wrong case e.g. see https://github.com/aws/aws-cdk/issues/11385 )

### Current Behavior

If not explicity set, it resolves to `None`

### Reproduction Steps

`dms_stack.py`
```python
from aws_cdk import (
    # Duration,
    Stack,
    aws_dms as dms,
)
from constructs import Construct

class DmsStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        subnet_group = dms.CfnReplicationSubnetGroup(
            self,
            "SubnetGroup",
            replication_subnet_group_description="sg",
            subnet_ids=[
                "XXX"
            ],
        )
        replication_instance = dms.CfnReplicationInstance(
            self,
            "ReplicationInstance",
            replication_instance_class="dms.t3.large",
            replication_subnet_group_identifier=subnet_group.replication_subnet_group_identifier,
        )
```
synthing this results in a template that does not reference the subnet group at all:
```yaml
  SubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupDescription: sg
      SubnetIds:
        - XXX
    Metadata:
      aws:cdk:path: DmsStack/SubnetGroup
  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      ReplicationInstanceClass: dms.t3.large
    Metadata:
      aws:cdk:path: DmsStack/ReplicationInstance
```
If you change `replication_subnet_group_identifier=subnet_group.replication_subnet_group_identifier` to `replication_subnet_group_identifier=subnet_group.ref`, then it synthesizes a correct reference to the subnet group:
```yaml
  SubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupDescription: sg
      SubnetIds:
        - XXX
    Metadata:
      aws:cdk:path: DmsStack/SubnetGroup
  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      ReplicationInstanceClass: dms.t3.large
      ReplicationSubnetGroupIdentifier:
        Ref: SubnetGroup
    Metadata:
      aws:cdk:path: DmsStack/ReplicationInstance
```

### Possible Solution

Make `CfnReplicationSubnetGroup.replication_subnet_group_identifier` return `CfnReplicationSubnetGroup.ref` so it is always the correct subnet group identifier.
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_dms/CfnReplicationSubnetGroup.html

### CDK CLI Version

2.80.0 (build bbdb16a)

### Framework Version

aws-cdk-lib==2.80.0

### Node.js Version

v16.19.0

### OS

macOS 13.3.1

### Language

Python

### Language Version

Python 3.10.9
