### ISSUE TITLE
sagemaker: The YAML template for the PipelineDefinitionBody property is in Upper Camel Case (Pascal Case) while the template generated by the CDK has this property in Camel Case

### ISSUE THREAD

**Issue by JawadAr** [aws/aws-cdk#25774]
### Describe the bug

The YAML template for the `AWS::SageMaker::Pipeline` resource in the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html) is as follows:

```yaml
Type: AWS::SageMaker::Pipeline
Properties: 
  ParallelismConfiguration: 
    ParallelismConfiguration
  PipelineDefinition: 
    PipelineDefinition
  PipelineDescription: String
  PipelineDisplayName: String
  PipelineName: String
  RoleArn: String
  Tags: 
    - Tag
```
The `PipelineDefinition` property is further defined as follows:

```yaml
  PipelineDefinitionBody: String
  PipelineDefinitionS3Location: 
    S3Location
```

Which means that a valid template could be:

```yaml
Type: AWS::SageMaker::Pipeline
Properties: 
  PipelineDefinition: 
      PipelineDefinitionBody: String
  PipelineDescription: String
  PipelineDisplayName: String
  PipelineName: String
  RoleArn: String
  Tags: 
    - Tag
```

Notice that the property `PipelineDefinitionBody` is in Pascal Case. But what the CDK generates is:

```yaml
Type: AWS::SageMaker::Pipeline
Properties: 
  PipelineDefinition: 
      pipelineDefinitionBody: String
  PipelineDescription: String
  PipelineDisplayName: String
  PipelineName: String
  RoleArn: String
  Tags: 
    - Tag
```

Notice that the property `pipelineDefinitionBody` is in Camel Case. Which is causing the following error in CloudFormation:

```
Properties validation failed for resource SampleCfnPipeline with message: #/PipelineDefinition: #: only 1 subschema matches out of 2 #/PipelineDefinition: #: 0 subschemas matched instead of one #/PipelineDefinition: required key [PipelineDefinitionBody] not found #/PipelineDefinition: extraneous key [pipelineDefinitionBody] is not permitted #/PipelineDefinition: required key [PipelineDefinitionS3Location] not found #/PipelineDefinition: extraneous key [pipelineDefinitionBody] is not permitted
```
The Python stack code for creating the template is as follows:

```python
class MySageMakerStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        
        pipeline_def = sagemaker.CfnPipeline.PipelineDefinitionProperty(
            pipeline_definition_body = "String"
        )

        cfn_pipeline = sagemaker.CfnPipeline(self, "SampleCfnPipeline",
            pipeline_definition=pipeline_def,
            pipeline_name="String",
            role_arn="String",
            pipeline_description="String",
            pipeline_display_name="String"
        )
```

Any generic code would reproduce the error.

Python CDK version: `2.81.0`
CDK ToolKit version: `2.81.0`
Machine: `Macbook Pro 2020, 13-inch`
OS: `Ventura 13.0.1`
IDE: `VSCode`

### Expected Behavior

I expected the CDK to generate a valid template for the `AWS::SageMaker::Pipeline` resource. Which is as follows:

```yaml
Type: AWS::SageMaker::Pipeline
Properties: 
  PipelineDefinition: 
      PipelineDefinitionBody: String
  PipelineDescription: String
  PipelineDisplayName: String
  PipelineName: String
  RoleArn: String
  Tags: 
    - Tag
```

Notice that the property `PipelineDefinitionBody` is in Pascal Case.

### Current Behavior

What the CDK currently generates is:

```yaml
Type: AWS::SageMaker::Pipeline
Properties: 
  PipelineDefinition: 
      pipelineDefinitionBody: String
  PipelineDescription: String
  PipelineDisplayName: String
  PipelineName: String
  RoleArn: String
  Tags: 
    - Tag
```

Notice that the property `pipelineDefinitionBody` is in Camel Case.

### Reproduction Steps

Use the following stack in python CDK:

```python
class MySageMakerStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        
        pipeline_def = sagemaker.CfnPipeline.PipelineDefinitionProperty(
            pipeline_definition_body = "String"
        )

        cfn_pipeline = sagemaker.CfnPipeline(self, "SampleCfnPipeline",
            pipeline_definition=pipeline_def,
            pipeline_name="String",
            role_arn="String",
            pipeline_description="String",
            pipeline_display_name="String"
        )
```

### Possible Solution

Possibly a typo error in converting from code to YAML.

### Additional Information/Context

Python CDK version: `2.81.0`
CDK ToolKit version: `2.81.0`
Machine: `Macbook Pro 2020, 13-inch`
OS: `Ventura 13.0.1`
IDE: `VSCode`

### CDK CLI Version

2.81.0

### Framework Version

2.81.0

### Node.js Version

18.16.0

### OS

Ventura 13.0.1

### Language

Python

### Language Version

3.9.7

**Comment by pahud** [comment]
Yes I can reproduce it in python.

I'll discuss this with the team.

**Comment by pahud** [comment]
Hi @JawadAr 

This is a [cfnspec patch issue](https://github.com/aws/aws-cdk/blob/fec928edb0a3d29ac4311209b9d5756c9c943ac0/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json#L450) and we are tracking at https://github.com/aws/aws-cdk/issues/21767

At this moment, you will need to write your CDK in python like this:

```py
sagemaker.CfnPipeline(self, "IssueTriagePyPipeline",
                              pipeline_name="IssueTriagePyPipeline",
                              role_arn="0000000000000000000000000:role/service-role/AmazonSageMaker-ExecutionRole-20210802T151519",
                              pipeline_definition={
                                  "PipelineDefinitionBody": "foo"
                              }
        )
```

And you should get the synthed resource like

```yaml
Resources:
  IssueTriagePyPipeline:
    Type: AWS::SageMaker::Pipeline
    Properties:
      PipelineDefinition:
        PipelineDefinitionBody: foo
      PipelineName: IssueTriagePyPipeline
      RoleArn: 0000000000000000000000000:role/service-role/AmazonSageMaker-ExecutionRole-20210802T151519
```

Let me know if it works for you.
