### ISSUE TITLE
SubscriptionFilter FilterPattern.allEvents() is removed after deployment

### ISSUE THREAD

**Issue by diepjy** [aws/aws-cdk#2591]
**Describe the bug**
After deploying a stack with a SubscriptionFilter, there is a drift in the SubscriptionFilter as the `FilterPattern` in the SubscriptionFilter is removed after the deployment is complete for `filterPattern: FilterPattern.allEvents()`. 

It doesn't seem to be affecting the lambda function which is subscribed to the filter as it's seems to be receiving the all events.

Apologies if this is not a bug and is intended behavior - however it is causing a drift in the stack.

**To Reproduce**
```
new SubscriptionFilter(this,
    id,
    {
      logGroup,
      destination: lambdaFunction,
      filterPattern: FilterPattern.allEvents(),
    }
);
```

The SubscriptionFilter resource in CloudFormation expected:
```
{
  "DestinationArn": [ARN],
  "FilterPattern": "",
  "LogGroupName": [LogGroup]
}
```

The SubscriptionFilter resource in CloudFormation current:
```
{
  "DestinationArn": [ARN],
  "LogGroupName": [LogGroup]
}
```

**Expected behavior**
AWS to retain `FilterPattern: FilterPattern.allEvents()` which should be `FilterPattern: ""` after deployment and not cause a drift in the stack. Or the template should not include a FilterPattern.

`cdk synth` outputs the following:
```
Subscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn:
        Fn::GetAtt:
          - [lambdaFunction]
          - Arn
      FilterPattern: ""
      LogGroupName:
        Ref: LogGroup
    Metadata:
      aws:cdk:path: [path]/Resource
```
So it seems like it is deploying a FilterPattern.

**Version:**
 - OS: Windows 10
 - Programming Language: TypeScript
 - CDK Version: 0.29.0
