### ISSUE TITLE
[cognito] CfnUserPoolClient writeAttributes problem

### ISSUE THREAD

**Issue by alberto-roli** [aws/aws-cdk#2608]
Hello,
I am experiencing a problem with the deploy of Cognito UserPoolClient with writeAttributes props.

this is the cdk code:
```
new CfnUserPoolClient(this, stagePrefix + 'PoolClientName', {
            clientName: stagePrefix + 'PoolClientName',
            refreshTokenValidity: 365,
            writeAttributes: ["given_name"],
            userPoolId: userPool.ref
        });
```

This synthesizes in:
```
devPoolClientName:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: devUserPool
      ClientName: dev-PoolClientName
      RefreshTokenValidity: 365
      WriteAttributes:
        - given_name
```

Looks good but on deploy Cloud Formation fails with:

> dev-PoolClientName (devPoolClientName) Invalid write attributes specified while creating a client (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: fd9b67e3-7c7c-11e9-93d0-fd46c856c171)

Any ideas?

Thank you
