### ISSUE TITLE
aws-elasticloadbalancingv2: ALB loadBalancerDnsName token does not resolve

### ISSUE THREAD

**Issue by csmcallister** [aws/aws-cdk#26103]
### Describe the bug

Start with an ALB:

```typescript
const alb = new elbv2.ApplicationLoadBalancer(this, "Alb", {
      vpc,
});
```

Now try to use that ALB's `loadBalancerDnsName` attribute in a Cognito User Pool Client's callback urls:

```typescript
const userPoolClient = new cognito.UserPoolClient(this, "UserPoolClient", {
        ...
        callbackUrls: [
          `https://${alb.loadBalancerDnsName}/oauth2/idpresponse`.toLowerCase(),
          `https://${alb.loadBalancerDnsName}/`.toLowerCase(),
        ],
        logoutUrls: [`https://${alb.loadBalancerDnsName}/`.toLowerCase()]
      },
});
```

With the above, I expect the token for the `alb.loadBalancerDnsName` to resolve much the same as an S3 bucket's name would resolve when setting it as an environment variable for a lambda function (which is shown in the docs for Tokens [here](https://docs.aws.amazon.com/cdk/v2/guide/tokens.html)).

The issue is that the tokens do not resolve. If I look at the user pool client in the AWS console, you'll see:

![image](https://github.com/aws/aws-cdk/assets/33464354/3e5eec71-954d-477a-89ac-da3951019bdb)

Naturally this results in a `redirect_mismatch` error when trying to authenticate after visiting the ALB DNS:

![image](https://github.com/aws/aws-cdk/assets/33464354/1e8b0dc5-e8e9-4cfb-963e-9a85e1a7e6b4)

### Expected Behavior

I expected the tokens for the load balancer's DNS name to resolve.

### Current Behavior

The token values do not resolve.

### Reproduction Steps

Here's a stack to reproduce:

```typescript
import * as cdk from 'aws-cdk-lib';
import * as cognito from "aws-cdk-lib/aws-cognito";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as elbv2 from "aws-cdk-lib/aws-elasticloadbalancingv2";
import { Construct } from 'constructs';

export class TestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "vpc", {
      cidr: "10.30.0.0/16",
      natGateways: 1,
      maxAzs: 2,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'public',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: 'private',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        },
     ]
    });

    const albSg = new ec2.SecurityGroup(this, "SecurityGroupAlb", {
      vpc,
      allowAllOutbound: true,
    });
    albSg.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(443));

    const alb = new elbv2.ApplicationLoadBalancer(this, "Alb", {
      vpc,
      internetFacing: true,
      securityGroup: albSg,
    });

    const userPool = new cognito.UserPool(this, "UserPool");
    new cognito.UserPoolClient(this, "UserPoolClient", {
      userPool,
      userPoolClientName: "UserPoolClient",
      generateSecret: true,
      oAuth: {
        flows: {
          authorizationCodeGrant: true,
        },
        scopes: [cognito.OAuthScope.OPENID],
        callbackUrls: [
          `https://${alb.loadBalancerDnsName}/oauth2/idpresponse`.toLowerCase(),
          `https://${alb.loadBalancerDnsName}/`.toLowerCase(),
        ],
        logoutUrls: [`https://${alb.loadBalancerDnsName}/`.toLowerCase()]
      },
      refreshTokenValidity: cdk.Duration.days(30),
      supportedIdentityProviders: [cognito.UserPoolClientIdentityProvider.COGNITO],
    });

    new cdk.CfnOutput(this, "LoadBalancerDNS", {
      value: `https://${alb.loadBalancerDnsName}`,
    });
  }
}
```

### Possible Solution

No idea. Current workaround is deploying the ALB first, grabbing the DNS as a `CfnOutput`, and then hardcoding. Not very ideal from an automation standpoint.

### Additional Information/Context

I've tried using [Token.asString](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Token.html#static-aswbrstringvalue-options) to generate a string encoding and calling `.toString()` on the token object, but the result is the same. However, that was merely out of desperation since the `alb.loadBalancerDnsName` is supposed to already be a String.

Additionally, the token does resolve when I use it to set an environment variable in an ECS container:

```typescript
const container = taskDefinition.addContainer("UiContainer", {
     ...
      environment: {
        ALB_DNS: alb.loadBalancerDnsName,
      },
    });
```

### CDK CLI Version

2.85.0 (build 4e0d726)

### Node.js Version

16.20

### OS

WSL (Ubuntu 22.04.2)

### Language

Typescript

### Language Version

4.9.4

**Comment by peterwoodworth** [comment]
Using runtime logic (in this case, `toLowerCase()`) can break tokens. The generated template looks like this:

```yaml
      CallbackURLs:
        - https://${token[token.744]}/oauth2/idpresponse
        - https://${token[token.744]}/
      ClientName: UserPoolClient
      GenerateSecret: true
      LogoutURLs:
        - https://${token[token.744]}/
```

You can't use synth time logic on something not known until deploy time. If you remove the `toLowerCase()` this will create a good template. 

```yaml
      CallbackURLs:
        - Fn::Join:
            - ""
            - - https://
              - Fn::GetAtt:
                  - Alb16C2F182
                  - DNSName
              - /oauth2/idpresponse
        - Fn::Join:
            - ""
            - - https://
              - Fn::GetAtt:
                  - Alb16C2F182
                  - DNSName
              - /
      ClientName: UserPoolClient
      GenerateSecret: true
      LogoutURLs:
        - Fn::Join:
            - ""
            - - https://
              - Fn::GetAtt:
                  - Alb16C2F182
                  - DNSName
              - /
```

Though, if you absolutely need to transform the name to lowercase, there will need to be a bit of a workaround.
