### ISSUE TITLE
CDK to CFN template is serializing incorrectly

### ISSUE THREAD

**Issue by srivastavr** [aws/aws-cdk#26111]
### Issue Description

Hi, 

We are passing `array of array` in payload from step function to a lambda function, below is the sample code 

```new LambdaInvoke(scope, id, {
            lambdaFunction: serviceCallHandler,
            resultSelector: resultSelector,
            resultPath: resultPath,
            payload: TaskInput.fromObject({
                key1: [
                    [
                        {
                            key2: {
                                key3: 'value1',
                            },
                            key4: [
                                [
                                    {
                                        key5: {
                                            key6: 'value2',
                                        },
                                    },
                                ],
                            ],
                        },
                    ],
                ],
            }),
        }
```

but after building, the cloud formation template converts this into array of objects with `0` index at places which is incorrect. 

like this  
```
 {
        "Ref": "AWS::Partition"
       },
       ":states:::lambda:invoke\",\"Parameters\":{\"FunctionName\":\"",
       {
        "Fn::GetAtt": [
         "servicecallhandler3F6E12B2",
         "Arn"
        ]
       },
       "\",\"Payload\":{\"key1\":[{\"0\":{\"key2\":{\"key3\":\"value1\"},\"key4\":[{\"0\":{\"key5\":{\"key6\":\"value2\"}}}]}}]}}}
```

### Expected Behavior

```
 {
        "Ref": "AWS::Partition"
       },
       ":states:::lambda:invoke\",\"Parameters\":{\"FunctionName\":\"",
       {
        "Fn::GetAtt": [
         "servicecallhandler3F6E12B2",
         "Arn"
        ]
       },
       "\",\"Payload\":{\"key1\":[[{\"key2\":{\"key3\":\"value1\"},\"key4\":[[{\"key5\":{\"key6\":\"value2\"}]}]}}]]}}
```

### Test Cases

NA

### Expected Behavior

```
 {
        "Ref": "AWS::Partition"
       },
       ":states:::lambda:invoke\",\"Parameters\":{\"FunctionName\":\"",
       {
        "Fn::GetAtt": [
         "servicecallhandler3F6E12B2",
         "Arn"
        ]
       },
       "\",\"Payload\":{\"key1\":[[{\"key2\":{\"key3\":\"value1\"},\"key4\":[[{\"key5\":{\"key6\":\"value2\"}]}]}}]]}}
```

### Current Behavior

```
{
        "Ref": "AWS::Partition"
       },
       ":states:::lambda:invoke\",\"Parameters\":{\"FunctionName\":\"",
       {
        "Fn::GetAtt": [
         "servicecallhandler3F6E12B2",
         "Arn"
        ]
       },
       "\",\"Payload\":{\"key1\":[{\"0\":{\"key2\":{\"key3\":\"value1\"},\"key4\":[{\"0\":{\"key5\":{\"key6\":\"value2\"}}}]}}]}}}
```

### Reproduction Steps

building the typescript code

### Possible Solution

The serialization is implemented in CDK:

https://github.com/aws/aws-cdk/blob/a79794e3f2609e6efa5cf659eec039964a8ad61c/packages/aws-cdk-lib/aws-stepfunctions/lib/input.ts#L21-L23

### CDK CLI Version

 "aws-cdk": "^2.72.0"

### Node.js Version

NodeJS/releases/default.331411.0

### OS

Linux

### Language

Typescript

### Language Version

"typescript": "^4.9.4"

**Comment by srivastavr** [comment]
reference from CFN : https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1722

**Comment by pahud** [comment]
This is the code I used to reproduce this issue

```ts
export class Demo2Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const obj = {
      key1: [
          [
              {
                  key2: {
                      key3: 'value1',
                  },
                  key4: [
                      [
                          {
                              key5: {
                                  key6: 'value2',
                              },
                          },
                      ],
                  ],
              },
          ],
      ],
    }
    const payload = sfn.TaskInput.fromObject(obj)
    const invoke = new sfntasks.LambdaInvoke(this, 'Invoke Func', {
      lambdaFunction: getLambdaFunction(this),
      payload,
    });

    new sfn.StateMachine(this, 'StateMachine', {
      definition: invoke,
    })
    
    new CfnOutput(this, 'input', { value: JSON.stringify(payload) })
  };
};

```

I can confirm the CfnOutput is rendered correctly

```
Outputs:
  input:
    Value: '{"type":1,"value":{"key1":[[{"key2":{"key3":"value1"},"key4":[[{"key5":{"key6":"value2"}}]]}]]}}'
```

But the state machine DefinitionString is not rendered correctly


```
 StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Invoke Func","States":{"Invoke Func":{"End":true,"Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"
            - Fn::GetAtt:
                - Func217E03A4
                - Arn
            - '","Payload":{"key1":[{"0":{"key2":{"key3":"value1"},"key4":[{"0":{"key5":{"key6":"value2"}}}]}}]}}}}}'
```
