### ISSUE TITLE
ec2: InitCommand.argvCommand dedupes its args, causing the wrong command to be generated)

### ISSUE THREAD

**Issue by fidothe** [aws/aws-cdk#26221]
### Describe the bug

using `ec2.InitCommand.argvCommand()` can, in some circumstances, remove duplicate strings from the input array, causing unexpected output.

### Expected Behavior

Expected the following

```typescript
ec2.InitCommand.argvCommand([
  'useradd', '-u', '1001', '-g', '1001', 'eguser',
]),
ec2.InitCommand.argvCommand([
  'useradd', '-a', '-u', '1001', '-g', '1001', 'eguser',
]),
```

To generate the following YAML:

```yaml
          commands:
            "000":
              command:
                - useradd
                - -u
                - "1001"
                - -g
                - "1001"
                - eguser
            "001":
              command:
                - useradd
                - -a
                - -u
                - "1001"
                - -g
                - "1001"
                - eguser
```

### Current Behavior

The following YAML was generated. Note the omission of the second occurrence of '1001' in the second command:

```yaml
          commands:
            "000":
              command:
                - useradd
                - -u
                - "1001"
                - -g
                - "1001"
                - eguser
            "001":
              command:
                - useradd
                - -a
                - -u
                - "1001"
                - -g
                - eguser
```

### Reproduction Steps

The CDK App in the provided repo contains the minimal resources needed to demonstrate the bug when running `cdk synth`:

https://github.com/fidothe/cdk-ec2-construct-bug-repro

`git clone https://github.com/fidothe/cdk-ec2-construct-bug-repro && cd cdk-ec2-construct-bug-repro && cdk synth`

### CDK CLI Version

2.85.0 (build 4e0d726)

### Node.js Version

v18.16.1

### OS

macOS 13.4.1

### Language

Typescript

### Language Version

Typescript (5.1.5)

**Comment by pahud** [comment]
Yes I can reproduce this in my account

With this configuration:

```ts
      init: ec2.CloudFormationInit.fromElements(
        ec2.InitCommand.argvCommand([
          'useradd', '-a', '-u', '1001', '-g', '1001', 'eguser',
        ]),
        ec2.InitCommand.argvCommand([
          'useradd', '-a', '-u', '1001', '-g', '1001', 'eguser',
        ]),
        ec2.InitCommand.argvCommand([
          'useradd', '-u', '1001', '-g', '1001', 'eguser',
        ]),
```

I got incorrect template definition(001 and 002) as below:

```
      AWS::CloudFormation::Init:
        configSets:
          default:
            - config
        config:
          commands:
            "000":
              command:
                - useradd
                - -a
                - -u
                - "1001"
                - -g
                - "1001"
                - eguser
            "001":
              command:
                - useradd
                - -a
                - -u
                - "1001"
                - -g
                - eguser
            "002":
              command:
                - useradd
                - -u
                - "1001"
                - -g
                - eguser
```
