### ISSUE TITLE
(iot_sitewise): (python model asset creation causes enum error)

### ISSUE THREAD

**Issue by awspiv** [aws/aws-cdk#26841]
### Describe the bug

Running the following in cdk.  The ```cdk synth``` works as expected, but ```cdk deploy``` results in enum error.  Looking through all documentation including copy and pasting example codes always results in "Measruement" types resulting in this error. 

### Expected Behavior

Both a sitewise model and asset generated within the account. 

### Current Behavior

Following error appears:

![image](https://github.com/aws/aws-cdk/assets/133160584/80e73603-74e7-4695-bbcd-ee3ef7f727c7)

### Reproduction Steps

```        

class MyStack(Stack):

    def __init__(self, scope: Construct, id: str,  **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
    
        asset_model = iotsitewise.CfnAssetModel(
                    self,
                    "MyAssetModel",
                    asset_model_name="TestMyAssetModel",
                    asset_model_properties=[iotsitewise.CfnAssetModel.AssetModelPropertyProperty(
                            data_type="DOUBLE",
                            logical_id="mylogid",
                            name="volts",  
                            unit="V",
                            type=iotsitewise.CfnAssetModel.PropertyTypeProperty(type_name="Measurment")                            
                            )                        
                            ]
                )
                 
        cfn_asset = iotsitewise.CfnAsset(self, "MyCfnAsset",
            asset_model_id=asset_model.ref,
            asset_name="assetName",
        )
```

### CDK CLI Version

2.92.0 (build bf62e55)

### Node.js Version

v20.5.1

### OS

Ubuntu 22.04.3 LTS

### Language

Python

### Language Version

3.10.x

**Comment by peterwoodworth** [comment]
Hm, this looks like it's a service error since the template looks to me like it's synthesizing properly from what you've given it

```yaml
Resources:
  MyAssetModel:
    Type: AWS::IoTSiteWise::AssetModel
    Properties:
      AssetModelName: TestMyAssetModel
      AssetModelProperties:
        - DataType: DOUBLE
          LogicalId: mylogid
          Name: volts
          Type:
            TypeName: Measurment
          Unit: V
    Metadata:
      aws:cdk:path: BucketPolicyStack/MyAssetModel
```

It looks like you misspelled `Measurement` actually (dropped the second `e`)
