### ISSUE TITLE
(CDK Deploy): (Elastic IP tags are not created as part of creation process)

### ISSUE THREAD

**Issue by bturner-cpacket** [aws/aws-cdk#26878]
### Describe the bug

We have an AWS Service Control Policy (SCP) applied from our organization that prevents the creation of new resources if they dont have an `owner` tag in the format of an email.  This has not been an issue for creation resources using the AWS console, the AWS CLI, or Python3 with boto3, however, it appears to be an issue with the AWS CDK.  

The issue does not happen with instances and volumes with the same restrictions, only Elastic IP's.

I am guessing the issue is that with the CDK, the Elastic IP is created, then tags are applied after the Elastic IP has been created but I am not sure.

Here is my sample code the reproduces the problem:
```
from aws_cdk import (
    aws_ec2 as ec2,
    core as cdk,
)


class MyEc2ProjectStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "MyVpc",
                      max_azs=2,
                      )

        instance = ec2.Instance(self, "MyInstance",
                                instance_type=ec2.InstanceType("t2.micro"),
                                machine_image=ec2.MachineImage.latest_amazon_linux(),
                                propagate_tags_to_volume_on_creation=True,
                                vpc=vpc,
                                )

        cdk.Tags.of(instance).add("owner", "a@b.com")
        cdk.Tags.of(instance).add("Name", "a-test-cdk")
        cdk.Tags.of(vpc).add("owner", "a@b.com")
```

When I run `cdk synth`, I see the proper tags on the EIP's:

```
Resources:
  MyVpcF9F0CA6F:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/Resource
  MyVpcPublicSubnet1SubnetF6608456:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVpcF9F0CA6F
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/18
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc/PublicSubnet1
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/Subnet
  MyVpcPublicSubnet1RouteTableC46AB2F4:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVpcF9F0CA6F
      Tags:
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc/PublicSubnet1
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/RouteTable
  MyVpcPublicSubnet1RouteTableAssociation2ECEE1CB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: MyVpcPublicSubnet1RouteTableC46AB2F4
      SubnetId:
        Ref: MyVpcPublicSubnet1SubnetF6608456
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/RouteTableAssociation
  MyVpcPublicSubnet1DefaultRoute95FDF9EB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: MyVpcPublicSubnet1RouteTableC46AB2F4
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MyVpcIGW5C4A4F63
    DependsOn:
      - MyVpcVPCGW488ACE0D
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/DefaultRoute
  MyVpcPublicSubnet1EIP096967CB:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc/PublicSubnet1
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/EIP
```

However when I run `cdk deploy` I get errors :

```
✨  Synthesis time: 4.22s

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬────────────────────────────────┬────────┬────────────────┬───────────────────────────────┬───────────┐
│   │ Resource                       │ Effect │ Action         │ Principal                     │ Condition │
├───┼────────────────────────────────┼────────┼────────────────┼───────────────────────────────┼───────────┤
│ + │ ${MyInstance/InstanceRole.Arn} │ Allow  │ sts:AssumeRole │ Service:ec2.${AWS::URLSuffix} │           │
└───┴────────────────────────────────┴────────┴────────────────┴───────────────────────────────┴───────────┘
Security Group Changes
┌───┬─────────────────────────────────────────────┬─────┬────────────┬─────────────────┐
│   │ Group                                       │ Dir │ Protocol   │ Peer            │
├───┼─────────────────────────────────────────────┼─────┼────────────┼─────────────────┤
│ + │ ${MyInstance/InstanceSecurityGroup.GroupId} │ Out │ Everything │ Everyone (IPv4) │
└───┴─────────────────────────────────────────────┴─────┴────────────┴─────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
MyEc2ProjectStack: deploying... [1/1]
MyEc2ProjectStack: creating CloudFormation changeset...
[████████··················································] (4/29)

10:14:19 PM | CREATE_FAILED        | AWS::EC2::EIP                         | MyVpc/PublicSubnet2/EIP
Resource handler returned message: "You are not authorized to perform this operation. Encoded authorization failure message: <REDACTED>
(Service: Ec2, Status Code: 403, Request ID: ec6461a0-7f7d-4865-802d-4544a6efb207)" (RequestToken: 35b1d1ff-fa03-2d39-8263-be53a5fcae69, HandlerErrorCode: AccessDenied)
10:14:19 PM | CREATE_FAILED        | AWS::EC2::EIP                         | MyVpc/PublicSubnet1/EIP
Resource handler returned message: "You are not authorized to perform this operation. Encoded authorization failure message: <REDACTED> (Service: Ec2, Status Code: 403, Request ID: bc8936a3-e911-4060-a124-62e4b1a71966)" (RequestToken: d4145145-00d3-e4a2-4a3d-7d339550cb3a, HandlerErrorCode: AccessDenied)
10:14:20 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | MyEc2ProjectStack
The following resource(s) failed to create: [MyVpcIGW5C4A4F63, MyVpcPublicSubnet1EIP096967CB, MyVpcF9F0CA6F, MyInstanceInstanceRole1C4D4747, MyVpcPublicSubnet2EIP8CCBA239, CDKMetadata]. Rollback requested b
y user.
10:14:20 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | MyEc2ProjectStack
The following resource(s) failed to create: [MyVpcIGW5C4A4F63, MyVpcPublicSubnet1EIP096967CB, MyVpcF9F0CA6F, MyInstanceInstanceRole1C4D4747, MyVpcPublicSubnet2EIP8CCBA239, CDKMetadata]. Rollback requested b
y user.
```

Decoding the error message shows me the issue is the SCP for Elastic IP's not being properly tagged.

I have tried variations of using ec2.CfnVPC but none of those worked.

```
vpc = ec2.CfnVPC(self, "MyVpc",  
    cidr_block="10.0.0.0/16",  # You need to specify a CIDR block  
    tags=[  
        cdk.CfnTag(key="owner", value="a@b.com"),  
    ],  
)
```

If I remove the SCP section for elastic IP `owner` tag and keep the same policy for instances and volumes I am able to successfully deploy my stack.

### Expected Behavior

Successful deployment of my CDK stack

### Current Behavior

Failure to deploy due to the Elastic IP not being tagged at creation time.

### Reproduction Steps

Here is my sample code the reproduces the problem:
```
from aws_cdk import (
    aws_ec2 as ec2,
    core as cdk,
)


class MyEc2ProjectStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "MyVpc",
                      max_azs=2,
                      )

        instance = ec2.Instance(self, "MyInstance",
                                instance_type=ec2.InstanceType("t2.micro"),
                                machine_image=ec2.MachineImage.latest_amazon_linux(),
                                propagate_tags_to_volume_on_creation=True,
                                vpc=vpc,
                                )

        cdk.Tags.of(instance).add("owner", "a@b.com")
        cdk.Tags.of(instance).add("Name", "a-test-cdk")
        cdk.Tags.of(vpc).add("owner", "a@b.com")
```

When I run `cdk synth`, I see the proper tags on the EIP's:

```
Resources:
  MyVpcF9F0CA6F:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/Resource
  MyVpcPublicSubnet1SubnetF6608456:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVpcF9F0CA6F
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/18
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc/PublicSubnet1
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/Subnet
  MyVpcPublicSubnet1RouteTableC46AB2F4:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVpcF9F0CA6F
      Tags:
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc/PublicSubnet1
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/RouteTable
  MyVpcPublicSubnet1RouteTableAssociation2ECEE1CB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: MyVpcPublicSubnet1RouteTableC46AB2F4
      SubnetId:
        Ref: MyVpcPublicSubnet1SubnetF6608456
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/RouteTableAssociation
  MyVpcPublicSubnet1DefaultRoute95FDF9EB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: MyVpcPublicSubnet1RouteTableC46AB2F4
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MyVpcIGW5C4A4F63
    DependsOn:
      - MyVpcVPCGW488ACE0D
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/DefaultRoute
  MyVpcPublicSubnet1EIP096967CB:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: MyEc2ProjectStack/MyVpc/PublicSubnet1
        - Key: owner
          Value: a@b.com
    Metadata:
      aws:cdk:path: MyEc2ProjectStack/MyVpc/PublicSubnet1/EIP
```

However when I run `cdk deploy` I get errors :

```
✨  Synthesis time: 4.22s

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬────────────────────────────────┬────────┬────────────────┬───────────────────────────────┬───────────┐
│   │ Resource                       │ Effect │ Action         │ Principal                     │ Condition │
├───┼────────────────────────────────┼────────┼────────────────┼───────────────────────────────┼───────────┤
│ + │ ${MyInstance/InstanceRole.Arn} │ Allow  │ sts:AssumeRole │ Service:ec2.${AWS::URLSuffix} │           │
└───┴────────────────────────────────┴────────┴────────────────┴───────────────────────────────┴───────────┘
Security Group Changes
┌───┬─────────────────────────────────────────────┬─────┬────────────┬─────────────────┐
│   │ Group                                       │ Dir │ Protocol   │ Peer            │
├───┼─────────────────────────────────────────────┼─────┼────────────┼─────────────────┤
│ + │ ${MyInstance/InstanceSecurityGroup.GroupId} │ Out │ Everything │ Everyone (IPv4) │
└───┴─────────────────────────────────────────────┴─────┴────────────┴─────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
MyEc2ProjectStack: deploying... [1/1]
MyEc2ProjectStack: creating CloudFormation changeset...
[████████··················································] (4/29)

10:14:19 PM | CREATE_FAILED        | AWS::EC2::EIP                         | MyVpc/PublicSubnet2/EIP
Resource handler returned message: "You are not authorized to perform this operation. Encoded authorization failure message: <REDACTED>
(Service: Ec2, Status Code: 403, Request ID: ec6461a0-7f7d-4865-802d-4544a6efb207)" (RequestToken: 35b1d1ff-fa03-2d39-8263-be53a5fcae69, HandlerErrorCode: AccessDenied)
10:14:19 PM | CREATE_FAILED        | AWS::EC2::EIP                         | MyVpc/PublicSubnet1/EIP
Resource handler returned message: "You are not authorized to perform this operation. Encoded authorization failure message: <REDACTED> (Service: Ec2, Status Code: 403, Request ID: bc8936a3-e911-4060-a124-62e4b1a71966)" (RequestToken: d4145145-00d3-e4a2-4a3d-7d339550cb3a, HandlerErrorCode: AccessDenied)
10:14:20 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | MyEc2ProjectStack
The following resource(s) failed to create: [MyVpcIGW5C4A4F63, MyVpcPublicSubnet1EIP096967CB, MyVpcF9F0CA6F, MyInstanceInstanceRole1C4D4747, MyVpcPublicSubnet2EIP8CCBA239, CDKMetadata]. Rollback requested b
y user.
10:14:20 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | MyEc2ProjectStack
The following resource(s) failed to create: [MyVpcIGW5C4A4F63, MyVpcPublicSubnet1EIP096967CB, MyVpcF9F0CA6F, MyInstanceInstanceRole1C4D4747, MyVpcPublicSubnet2EIP8CCBA239, CDKMetadata]. Rollback requested b
y user.
```

Decoding the error message shows me the issue is the SCP for Elastic IP's not being properly tagged.

I have tried variations of using ec2.CfnVPC but none of those worked.

```
vpc = ec2.CfnVPC(self, "MyVpc",  
    cidr_block="10.0.0.0/16",  # You need to specify a CIDR block  
    tags=[  
        cdk.CfnTag(key="owner", value="a@b.com"),  
    ],  
)
```

If I remove the SCP section for elastic IP `owner` tag and keep the same policy for instances and volumes I am able to successfully deploy my stack.

### Possible Solution

Similar to how the CDK has a `propagate_tags_to_volume_on_creation=True` flag it would be good if we could do this for Elastic IP's?  

### CDK CLI Version

2.86.0 (build 1130fab)

### Node.js Version

v16.20.1

### OS

AWS Linux - 4.14.255-314-253.539.amzn2.x86_64

### Language

Python

### Language Version

Python 3.7.16

### Other information

chatGPT gave me these helpful nuggets of information :) 

`Currently, the CDK does not have a direct way to add tags during EIP creation when using the low-level CfnEIP construct. This makes it tricky when SCPs require tags upon resource creation, as is your case.`

`Feedback to AWS: If you believe this is an issue with how CDK is handling the Elastic IP creation and tagging process, you might want to provide feedback to AWS or raise it in the AWS CDK GitHub repository.`
