### ISSUE TITLE
aws-imagebuilder: wrong case in CFN template for properties of AmiDistributionConfiguration

### ISSUE THREAD

**Issue by cvmeq** [aws/aws-cdk#26912]
### Describe the bug

I am deploying an EC2 Image Builder pipeline using CDK using the [auto generated L1 constructs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_imagebuilder/README.html).

To configure how AMIs are distributed by the pipeline I am using `CfnDistributionConfiguration.AmiDistributionConfigurationProperty` ([documentation here](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_imagebuilder/CfnDistributionConfiguration.html#amidistributionconfigurationproperty)) which corresponds to [AWS::ImageBuilder::DistributionConfiguration::AmiDistributionConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-imagebuilder-distributionconfiguration-amidistributionconfiguration.html).

The problem that I observed is that the properties of `AmiDistributionConfiguration` in the synthesized CloudFormation templated are generated in camel case (e.g., `targetAccountIds`) while they should be given in title case (e.g., `TargetAccountIds`).

The Image Builder pipeline is deployed and apparently works as specified, but this could be hinting at a bug somewhere so I'm reporting here.

### Expected Behavior

Properties of `AmiDistributionConfiguration` in the synthesized should be generated with title case (e.g., `TargetAccountIds`).

### Current Behavior

Properties of `AmiDistributionConfiguration` in the synthesized are generated with title case (e.g., `targetAccountIds`) which not only triggers `cfn-lint` but also leads to some non-fatal problems while deploying, as shown below

![screenshot](https://github.com/aws/aws-cdk/assets/112000617/0427c9e6-5d79-4e2b-94cc-a62150068d92).

### Reproduction Steps

MWE for a Python CDK app with a distribution configuration that illustrates the issue:

```python
from constructs import Construct
import aws_cdk as cdk

class TestStack(cdk.Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        ami_dist_conf_prop = cdk.aws_imagebuilder.CfnDistributionConfiguration.AmiDistributionConfigurationProperty(
            name="Test-{{ imagebuilder:buildDate }}",
            description="My test AMI",
            ami_tags={
                "Key": "Value"
            },
            target_account_ids=[
                "111111111111",
                "222222222222",
                "333333333333",
            ]
        )
        dist_prop = cdk.aws_imagebuilder.CfnDistributionConfiguration.DistributionProperty(
            region="eu-central-1",
            ami_distribution_configuration=ami_dist_conf_prop,
        )
        cdk.aws_imagebuilder.CfnDistributionConfiguration(
            self,
            "DistributionConfiguration",
            name="DistributionConfiguration",
            description="Distribution for the AMI",
            distributions=[dist_prop],
        )


app = cdk.App()
env = cdk.Environment(account="444444444444", region="eu-central-1")
TestStack(app, "TestStack", env=env)
app.synth()
```

This is the resource after synthesized:

```yaml
Resources:
  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Description: Distribution for the AMI
      Distributions:
        - AmiDistributionConfiguration:
            amiTags:
              Key: Value
            description: My test AMI
            name: Test-{{ imagebuilder:buildDate }}
            targetAccountIds:
              - "111111111111"
              - "222222222222"
              - "333333333333"
          Region: eu-central-1
      Name: DistributionConfiguration
    Metadata:
      aws:cdk:path: TestStack/DistributionConfiguration
```

As it can be seen the properties `amiTags`, `description`, `name`, and `targetAccountIds` are wrongly cased. This can be further illustrated by linting the resulting template:

```
$ cdk synth TestStack | cfn-lint -

E3002 Invalid Property Resources/DistributionConfiguration/Properties/Distributions/0/AmiDistributionConfiguration/amiTags. Did you mean AmiTags?
-:8:13

E3002 Invalid Property Resources/DistributionConfiguration/Properties/Distributions/0/AmiDistributionConfiguration/description. Did you mean Description?
-:10:13

E3002 Invalid Property Resources/DistributionConfiguration/Properties/Distributions/0/AmiDistributionConfiguration/name
-:11:13

E3002 Invalid Property Resources/DistributionConfiguration/Properties/Distributions/0/AmiDistributionConfiguration/targetAccountIds. Did you mean TargetAccountIds?
-:12:13
```

### CDK CLI Version

2.93.0

### Node.js Version

18.16.1

### OS

Ubuntu 22.04

### Language

Python

### Language Version

3.11.5
