### ISSUE TITLE
IAM:  Role Trust Relationships cannot be extended with multiple principals 

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#27006]
### Describe the bug

The Trust Relationships of a Role cannot be extended with multiple principals.  As example I included this configuration (which is possible from AWS-console)

![image](https://github.com/aws/aws-cdk/assets/26426283/a40ee520-a0c7-4b1c-b062-1673eb205999)

### Expected Behavior

The Trust Relationships can contain multiple principals 

### Current Behavior

While Deployment I'm getting this errors:

" A PolicyStatement used in an identity-based policy cannot specify any IAM principals" and "A PolicyStatement used in an identity-based policy must specify at least one resource"

### Reproduction Steps

see this code as example:

![image](https://github.com/aws/aws-cdk/assets/26426283/f7db3d2d-9308-4c88-b046-75383aab8c88)

### CDK CLI Version

aws-cli/2.13.12 Python/3.11.4 Windows/10 exe/AMD64 prompt/off

### Node.js Version

9.5.1

### OS

Windows

### Language

Java

### Language Version

Java 17

**Comment by wz2b** [comment]
I have this same exact problem.  I'm trying to create a function that will be called by cloudfront.  According to [this document](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-permissions.html) you need to allow the role to be assumed by two principles.  Currently, the assumedBy doesn't accept an array.

```
const fnRole = new iam.Role(this, "redirect-function-role-id", {
    roleName: "redirect-function-role",
    assumedBy: new iam.ServicePrincipal('edgelambda.amazonaws.com')
})
```

As a workaround, I thought I could just add another principal to the trust policy like this:

```
 fnRole.grantAssumeRole(new iam.ServicePrincipal('lambda.amazonaws.com'))
```

but the messed up thing is that just silently did nothing - no error, it just didn't work.  The output of the two things above generated this:

```yaml
  redirectfunctionroleid9F482E14:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: edgelambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: redirect-function-role
```

I think that is related to https://github.com/aws/aws-cdk/issues/24507 ...

**Comment by peterwoodworth** [comment]
`grantAssumeRole` doesn't add to the Role's trust policy - it grants the other principal permissions in their policy statement. Does `addToPrincipalPolicy` not work? https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#addwbrtowbrprincipalwbrpolicystatement

**Comment by ttais2017** [comment]
I tried this:
![image](https://github.com/aws/aws-cdk/assets/26426283/2502521d-29d7-4895-8fce-eba1721ae441)


but I get deploy errors:
![image](https://github.com/aws/aws-cdk/assets/26426283/0045567d-6e5c-4833-a53d-8db97e9cf3ef)

**Comment by ttais2017** [comment]
I dont still understand why this method does not work.  @peterwoodworth: "grantAssumeRole doesn't add to the Role's trust polic" ?
![image](https://github.com/aws/aws-cdk/assets/26426283/9d1ef062-cf64-4db1-bf10-7845c0bb7ad7)

**Comment by wz2b** [comment]
> I dont still understand why this method does not work. @peterwoodworth 

I don't, either.  The name pretty strongly implies that you're granting some principal authority to assume the role.

**Comment by peterwoodworth** [comment]
From our [README](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam-readme.html#iam-principals), try `CompositePrincipal`. This works for me

```ts
    const role = new iam.Role(this, 'Role', {
      assumedBy: new iam.CompositePrincipal(
        new iam.ServicePrincipal('lambda.amazonaws.com'),
        new iam.ServicePrincipal('apigateway.amazonaws.com'),
      ),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonSagemakerFullAccess'),
        iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonS3FullAccess')
      ],
      inlinePolicies: {
        policy: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              actions: ['lakeformation:*'],
              resources: ['*'],
              effect: iam.Effect.ALLOW,
            })
          ]
        })
      }
    })
```

Regarding the confusion over `grantAssumeRole`, it states:

> Grant permissions to the given principal to assume this role.

I'm not really sure how this can be made more clear in the docstring. It's stating that it's granting permission to the principal, it doesn't state anything about adding to its own trust policy. If you have any suggestions on how to make this more clear, let me know. 

Aside from the docstring, we should at the least document a use case of `grantAssumeRole()`, `addToPrincipalPolicy()`, and `assumeRolePolicy`

**Comment by wz2b** [comment]
> I'm not really sure how this can be made more clear in the docstring.

I'm not sure, either.  I have a feeling I'm missing something fundamental.  As an experiment I tried doing this:

```
const fnRole = new iam.Role(this, "redirect-function-role-id", {
    roleName: "redirect-function-role",
    assumedBy: new iam.ServicePrincipal('edgelambda.amazonaws.com')
})
```

then did a cdk synth > file1.json.  Then I added this:

```
 fnRole.grantAssumeRole(new iam.ServicePrincipal('lambda.amazonaws.com'))
```

then did cdk synth > file2.json.  Then I diffed them, and they were the same:

```
  craproleid58ADBD94:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: edgelambda.amazonaws.com
        Version: "2012-10-17"
      RoleName: redirect-function-role
```

What I expected it to do was to add a second principal under the AssumeRolePolicyDocument.  It didn't change the role at all, unless it somehow changed it outside of the role definition in the template.
