### ISSUE TITLE
(@aws-cdk/aws-batch-alpha): (unable to update maxVcpus)

### ISSUE THREAD

**Issue by bhargav265** [aws/aws-cdk#27054]
### Describe the bug

We are using Fargate compute environment and we are unable to update the max vcpus on CFN. 
We get the error 
```
The following parameters can\'t be updated for Fargate compute environment: allocationStrategy, bidPercentage, ec2Configuration, ec2KeyPair, imageId, instanceRole, instanceTypes, launchTemplate, placementGroup, tags, type, updatePolicy, updateToLatestImageVersion. (Service: Batch, Status Code: 400, Request ID: 5bf1284d-eefb-42c1-921a-41e6d0b44565)
```

### Expected Behavior

Should update the maxVcpus directly

### Current Behavior

Throws the error
```
The following parameters can\'t be updated for Fargate compute environment: allocationStrategy, bidPercentage, ec2Configuration, ec2KeyPair, imageId, instanceRole, instanceTypes, launchTemplate, placementGroup, tags, type, updatePolicy, updateToLatestImageVersion. (Service: Batch, Status Code: 400, Request ID: 5bf1284d-eefb-42c1-921a-41e6d0b44565)
```

### Reproduction Steps

1. Make a Compute environment with some vcpu setting something like:
```
 new FargateComputeEnvironment(this, batchComputeEnvironmentName, {
            enabled: true,
            maxvCpus: 512,
            vpc: props.vpc,
            computeEnvironmentName: batchComputeEnvironmentName,
        });
```

2. Deploy this to an AWS account
3. Change the maxVcpu value to be 2048 or something different.
4. Deploy again.

### CDK CLI Version

V2

### Node.js Version

18.16.1

### OS

Linux

### Language

Typescript

**Comment by comcalvi** [comment]
root cause, provided by an internal engineer:

The CFN handler first calls `createComputeEnvironment`, and `updateToLatestImageVersion` is not passed in. Then the handler calls `UpdateComputeEnvironment`, which does pass this value in. Batch sees this as changing this value on an already-created CE, resulting in this error.

Fix: don't pass this value in by default anywhere.

**Comment by polamjag** [comment]
https://github.com/aws/aws-cdk/pull/27059 seems to be included in [v2.96.0 release](https://github.com/aws/aws-cdk/releases/tag/v2.96.0), but I'm still experiencing same error message as https://github.com/aws/aws-cdk/issues/27054#issue-1886568702 in v2.96.2.

**Comment by dschulz-aam** [comment]
I still seem to be having this issue, I changed the number of maxv_cpus from 5 to 8 for the following compute environment definition:

```
fargate_compute = batch.FargateComputeEnvironment(
    self,
    "FargateComputeEnv",
    compute_environment_name="FargateEnv",
    vpc=vpc,
    maxv_cpus=8,
)
```
 I get this error:
 
 ```
 "The following parameters can\'t be updated for Fargate compute environment: allocationStrategy, bidPercentage, ec2Configuration, ec2KeyPair, imageId, instanceRole, instanceTypes, launchTemplate, placementGroup, tags, type, updatePolicy, updateToLatestImageVersion. (Service: Batch, Status Code: 400, Request ID: 6e88dfba-ac1a-4e34-8b43-7c74f2270c14)" (RequestToken: e63bbbad-2be2-0b81-2714-30cd9f04437c, HandlerErrorCode: InvalidRequest)
 ```

**Comment by wafuwafu13** [comment]
In CFn, I reproduce it when `ReplaceComputeEnvironment` is `false`.
In CFn, the default value is `true`, but `false` in CDK.

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-batch-computeenvironment.html#aws-resource-batch-computeenvironment-properties
>ReplaceComputeEnvironment
Specifies whether the compute environment is replaced if an update is made that requires replacing the instances in the compute environment. The default value is true. 


https://github.com/aws/aws-cdk/blob/3196733466c925721e978fd73bfcef4b8629d2e7/packages/aws-cdk-lib/aws-batch/lib/managed-compute-environment.ts#L221

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: "issue27054"
      ComputeResources:
        Type: "FARGATE"
        MaxvCpus: 128
        SecurityGroupIds:
          - sg-xxx
        Subnets:
          - subnet-xxx
          - subnet-xxx
      Type: "MANAGED"
```

=> CREATE_COMPLETE


```yaml
MaxvCpus: 256
```

=> UPDATE_COMPLETE



```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: "issue27054"
      ComputeResources:
        Type: "FARGATE"
        MaxvCpus: 128
        SecurityGroupIds:
          - sg-xxx
        Subnets:
          - subnet-xxx
          - subnet-xxx
      Type: "MANAGED"
      ReplaceComputeEnvironment: false
```


=> CREATE_COMPLETE


```yaml
MaxvCpus: 256
```

=> UPDATE_FAILED

```
Resource handler returned message: "The following parameters can\'t be updated for Fargate compute environment: allocationStrategy, bidPercentage, ec2Configuration, ec2KeyPair, imageId, instanceRole, instanceTypes, launchTemplate, placementGroup, tags, type, updatePolicy, updateToLatestImageVersion. (Service: Batch, Status Code: 400, Request ID: ab21a9fb-d652-486b-9645-d1ee7fba66da)" (RequestToken: e4ae8882-9f00-90a0-e271-f1a7e0428ee1, HandlerErrorCode: InvalidRequest)
```
