### ISSUE TITLE
Amazon.CDK.AWS.Apigatewayv2.Alpha: Support "AWS" as the IntegrationType for WebSockets

### ISSUE THREAD

**Issue by JobaDiniz** [aws/aws-cdk#27164]
### Describe the feature

Currently, `Amazon.CDK.AWS.Apigatewayv2.Alpha` lacks support for `AWS` option as the [IntegrationType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationtype) for **WebSocket** Apigateway.

The quote from the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationtype):
>`AWS`: for integrating the route or method request with an AWS service action, including the Lambda function-invoking action. With the Lambda function-invoking action, this is referred to as the Lambda custom integration. With any other AWS service action, this is known as AWS integration. Supported only for WebSocket APIs.

The important part is:
>With any other AWS service action, this is known as AWS integration. Supported only for WebSocket APIs.

That is, you can create a WebSocket Apigateway that calls **directly** other AWS services **without** a Lambda function middleware.

### Use Case

Ability to create a CDK for WebSocket Apigateway where I can define a direct integration to another AWS service.

For example, WebSocket route integration that triggers a AWS Step Function directly.

This use case is supported using CloudFormation and SAM as follows:
```yaml
  ApiAuthenticateRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BrokerRobotSocketApi
      IntegrationType: AWS
      IntegrationMethod: POST
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:states:action/StartExecution"
      CredentialsArn: !Sub "${ApiAuthenticateIntegrationStateMachineExecutionRole.Arn}" 
      TemplateSelectionExpression: \$default
      RequestTemplates: # see: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html
        "$default" : 
          Fn::Sub: >
            #set($statesInput=$util.escapeJavaScript($input.json('$.data')).replaceAll("\\'","'"))
            { 
              "input": "{\"data\":$statesInput, \"metadata\": {\"requestId\":\"$context.requestId\",\"connectionId\":\"$context.connectionId\",\"domainName\":\"$context.domainName\",\"stage\":\"$context.stage\"}}",
              "stateMachineArn": "${BrokerAuthenticatorStateMachine}"
            }
```

### Proposed Solution

From dotnet world, the solution requires the creation of another class that inherits from [`WebSocketRouteIntegration`](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.Apigatewayv2.Alpha.WebSocketRouteIntegration.html) to expose the specific props needed for IntegrationType as AWS.

I propose a class named `WebSocketAwsIntegration`, following the convention for the other integrations types already implemented: [WebSocketMockIntegration](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.Apigatewayv2.Integrations.Alpha.WebSocketMockIntegration.html), [WebSocketLambdaIntegration](https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.Apigatewayv2.Integrations.Alpha.WebSocketLambdaIntegration.html).

**Alternatively**, we could be even more specific and create classes such as `WebSocketStepFunctionIntegration`, however, this would require considerably more work because we would need to create several classes for _every_ AWS service that is supported with this construct.

In any case, this would require the following changes - _looking briefly at the code_:

### [`WebSocketRouteIntegrationConfig`](https://github.com/aws/aws-cdk/blob/dc87d28110403f6223ed2ee506c35bc79fc7835e/packages/%40aws-cdk/aws-apigatewayv2-alpha/lib/websocket/integration.ts#L130)

Adding the following missing properties:  [IntegrationMethod](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationmethod), [RequestTemplates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-requesttemplates), [CredentialsArn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-credentialsarn), [TemplateSelectionExpression](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-templateselectionexpression), and probably others depending on the AWS service you want to integrate.

### [`WebSocketIntegrationType`](https://github.com/aws/aws-cdk/blob/dc87d28110403f6223ed2ee506c35bc79fc7835e/packages/%40aws-cdk/aws-apigatewayv2-alpha/lib/websocket/integration.ts#L19)

Adding the following option to the enum: `AWS`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

Windows 11
