### ISSUE TITLE
(@aws-cdk/aws-dlm): Policy type is not synthesized when using CfnLifecyclePolicy construct

### ISSUE THREAD

**Issue by khushail** [aws/aws-cdk#27817]
### Describe the bug

CX is using the construct CfnLifecyclePolicy with Policy_type with the given code snippet. After synth, the policy_type details are msising from the template.

Synthesized template -
```
Resources:
  lifecyclepolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties:
      Description: EC2 Backup Policy
      ExecutionRoleArn: arn:aws:iam::404890032397:role/AWSDataLifecycleManagerDefaultRole
      PolicyDetails:
        ResourceTypes:
          - INSTANCE
        Schedules:
          - CopyTags: true
            CreateRule:
              CronExpression: cron(0 2 * * ? *)
              Interval: 2
              IntervalUnit: HOURS
            Name: DailyBackup
            RetainRule:
              Count: 12
            TagsToAdd:
              - Key: Purpose
                Value: Backup
        TargetTags:
          - Key: altci
            Value: ServiceNowDiscovery
      State: ENABLED
```

Additionally Cx mentions that they observe life cycle manager PolicyType to "EBS snapshot policy", instead of "EBS-backed AMI policy".

### Expected Behavior

Synthesized template should include the policy_type property.

### Current Behavior

Property is missing from the template

### Reproduction Steps

dlm.CfnLifecyclePolicy(
                self,
                id="lifecyclepolicy",
                description="EC2 Backup Policy",
                state='ENABLED',
                execution_role_arn='',
                policy_details={
                    'policy_type' : 'IMAGE_MANAGEMENT',
                    'resourceTypes': ['INSTANCE'],
                    'targetTags': [{
                        'key': 'altci',
                        'value': 'ServiceNowDiscovery'
                    }],
                    'schedules': [{
                        'name': 'DailyBackup',
                        'createRule': {
                            'interval': 2,
                            'intervalUnit': 'HOURS',
                            'cronExpression': 'cron(0 2 * * ? *)'
                        },
                        'retainRule': {
                            'count':12
                        },
                        'copyTags': True,  
                        'tagsToAdd': [{'key': 'Purpose', 'value': 'Backup'}] 
                        
                    }]
                }
            )

### CDK CLI Version

2.103.1

### Node.js Version

v18.15.0

### OS

Mac

### Language

Python
