### ISSUE TITLE
CDK Bootstrap: PermissionBoundary not applied to all roles

### ISSUE THREAD

**Issue by dverdonschot** [aws/aws-cdk#28453]
### Describe the feature

PermissionBoundary is only applied to Cloudformation Execution Role when bootstrapping with option --custom-permission-boundary

```bash
cdk bootstrap --custom-permissions-boundary PermissionBoundary
```

The following roles currently do not get the PermissionBoundary when the Bootstrap is done with the command above:

DeploymentActionRole
FilePublishingRole
ImagePublishingRole
LookupRole

### Use Case

The organisation I work for has a PermissionBoundary that enforces all roles to also be created with the PermissionBoundary.

```json
        {
            "Sid": "RestrictRoleCreation",
            "Effect": "Deny",
            "Action": [
                "iam:CreateRole",
                "iam:UpdateRole",
                "iam:PutRolePermissionsBoundary"
            ],
            "Resource": "*",
            "Condition": {
                "StringNotLike": {
                    "iam:PermissionsBoundary": [
                        "arn:aws:iam::*:policy/PermissionBoundary"
                    ]
                }
            }
        },
```
Currently we have to bootstrap CDK using a custom bootstrap-template.yaml that applies the PermissionBoundary on all other roles.
But sometimes this causes issues if someone later on runs cdk bootstrap without the template, and resources are updated without PermissionBoundary again...

### Proposed Solution

Add below code to all roles created by bootstrap-template.yaml

```yaml
      PermissionsBoundary:
        Fn::If:
          - PermissionsBoundarySet
          - Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${InputPermissionsBoundary}'
          - Ref: AWS::NoValue
```
I can make a PR for this if needed.

### Other Information

Currently bootstrap-template.yaml only applies the below code for attaching the PermissionBoundary on CloudFormationExecutionRole:

```yaml
      PermissionsBoundary:
        Fn::If:
          - PermissionsBoundarySet
          - Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${InputPermissionsBoundary}'
          - Ref: AWS::NoValue
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.114.0

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by tim-finnigan** [comment]
Thanks for reaching out. It looks like this is a duplicate of https://github.com/aws/aws-cdk/issues/12207. Can you confirm or highlight any differences between these issues?

**Comment by dverdonschot** [comment]
Sorry for responding this late, should have opened this issue after the holidays.

In the mentioned issue #12207 it shows that you can set the permissionBoundary with --custom-permissions-boundary only for the execution role. 
You can also use the cdk.json option to apply the permissionBoundary to all stacks in all resources.

But the problem is that cdk bootstrap is not performed from the stack with cdk.json, but from the cdk bootstrap command.
CDK Bootstrap will still create the other roles, like the lookup role, without the permissionBoundary.

In the company that I work there is a PermissionBoundary that has a policy to only allow IAM Role creation if that role also uses the PermissionBoundary.

We can solve it currently by using a custom bootstrap-template.yml with the permissionBoundary added to the other roles.

```yaml
      PermissionsBoundary:
        Fn::If:
          - PermissionsBoundarySet
          - Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${InputPermissionsBoundary}'
          - Ref: AWS::NoValue
```

But then we always need to use that template to bootstrap CDK.

Sometimes the existing CDK bootstrap get's broken or overwritten by a user, and then the user gets stuck creating a new bootstrap when they don't have the template, because the permissionBoundary is not applied to the other roles.

If we can just get the PermissionsBoundary code snippet applied to all roles by default, then we can bootstrap with 1 command and have the permissionBoundary attached to every role.

**Comment by kswanny** [comment]
+1 same issue

**Comment by bill-bryan-bp** [comment]
+1 same issue, had to create a custom template to include as mentioned by @dverdonschot.  Any chance of this being resolved, I have had to describe this fix to multiple customers at this point and it really should be a simple fix.

**Comment by shivkonaje** [comment]
+1 Same issue

**Comment by adminy** [comment]
+1 same issue.

**Comment by pahud** [comment]
## Current Behavior vs Expected Behavior

```mermaid
graph TB
    subgraph "Current Behavior"
        CB["cdk bootstrap --custom-permissions-boundary PermPolicy"]
        CB --> CFE["CloudFormationExecutionRole"]
        CFE --> PB1["✅ PermissionsBoundary Applied"]
        CB --> FP["FilePublishingRole"]
        FP --> PB2["❌ No PermissionsBoundary"]
        CB --> IP["ImagePublishingRole"]
        IP --> PB3["❌ No PermissionsBoundary"]
        CB --> LR["LookupRole"]
        LR --> PB4["❌ No PermissionsBoundary"]
        CB --> DAR["DeploymentActionRole"]
        DAR --> PB5["❌ No PermissionsBoundary"]
    end
    
    CtoE["vs"]
    
    subgraph "Expected Behavior"
        EB["cdk bootstrap --custom-permissions-boundary PermPolicy"]
        EB --> ECFE["CloudFormationExecutionRole"]
        ECFE --> EPB1["✅ PermissionsBoundary Applied"]
        EB --> EFP["FilePublishingRole"]
        EFP --> EPB2["✅ PermissionsBoundary Applied"]
        EB --> EIP["ImagePublishingRole"]
        EIP --> EPB3["✅ PermissionsBoundary Applied"]
        EB --> ELR["LookupRole"]
        ELR --> EPB4["✅ PermissionsBoundary Applied"]
        EB --> EDAR["DeploymentActionRole"]
        EDAR --> EPB5["✅ PermissionsBoundary Applied"]
    end


```


- Current Behavior: Only the CloudFormationExecutionRole gets the permissions boundary applied
- Expected Behavior: All roles created during bootstrap would have the permissions boundary applied


##Root Cause Analysis

After examining the bootstrap template at node_modules/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml, I found:

The template defines a parameter InputPermissionsBoundary that's set when using the --custom-permissions-boundary option.

The template includes a condition `PermissionsBoundarySet` that checks if this parameter has been provided.
`
However, the PermissionsBoundary` property is only applied to the `CloudFormationExecutionRole`:

```yaml
CloudFormationExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    # Other properties...
    PermissionsBoundary:
      Fn::If:
        - PermissionsBoundarySet
        - Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${InputPermissionsBoundary}'
        - Ref: AWS::NoValue
```

4. The other roles created during bootstrap don't have this property set:
- FilePublishingRole
- ImagePublishingRole
- LookupRole
- DeploymentActionRole


## Is it supposed to apply to all roles?
Based on my analysis:

1. There's no documentation explicitly stating that --custom-permissions-boundary should apply to all roles.

2. The implementation only applies it to the CloudFormationExecutionRole.

3. However, the parameter name InputPermissionsBoundary and condition name PermissionsBoundarySet are generic, suggesting it could be intended for broader use.

4. The issue submitter's organization has a policy that requires all IAM roles to have a permissions boundary, which is a common security practice in many organizations.

5. The submitter's proposed solution of adding the same permission boundary configuration to all roles is technically straightforward and consistent with the existing implementation for the CloudFormationExecutionRole.

## Conclusion

We need clarification from the team and should make it clear in the document as well.
