### ISSUE TITLE
wafv2: add_override does not obey Action key

### ISSUE THREAD

**Issue by Rondineli** [aws/aws-cdk#29165]
### Describe the bug

Trying to add a rule to an specific key breaks as Action is not added:

```python
waf_acl = wafv2.CfnWebACL(self, 'id', **params)
# Assuming above we would have only one rule
new_rule = {
    "Action": {
        "Block": {}
    },
    "Name": "Deny_regex",
    "Priority": 1,
    "Statement": {
        "RegexPatternSetReferenceStatement": {
            "Arn": {
                "Fn::ImportValue": "my-regex-arn"
            },
            "FieldToMatch": {
                "SingleHeader": {
                    "Name": "my-header"
                }
            },
            "TextTransformations": [
                {
                    "Priority": 0,
                    "Type": "NONE"
                }
            ]
        }
    },
    "VisibilityConfig": {
        "CloudWatchMetricsEnabled": true,
        "MetricName": "Deny_regex",
        "SampledRequestsEnabled": true
    }
}
waf_acl.add_override('Properties.Rules.1', new_rule)

```

At the final template, the `Action` block is not present:
```json
{
    "Name": "Deny_regex",
    "Priority": 1,
    "Statement": {
        "RegexPatternSetReferenceStatement": {
            "Arn": {
                "Fn::ImportValue": "my-regex-arn"
            },
            "FieldToMatch": {
                "SingleHeader": {
                    "Name": "my-header"
                }
            },
            "TextTransformations": [
                {
                    "Priority": 0,
                    "Type": "NONE"
                }
            ]
        }
    },
    "VisibilityConfig": {
        "CloudWatchMetricsEnabled": true,
        "MetricName": "Deny_regex",
        "SampledRequestsEnabled": true
    }
}
```

### Expected Behavior

Expected the rule json output to have the `Action` block

### Current Behavior

Somehow, the Action json block is not being added to the final template

### Reproduction Steps

Create a waf, and try to use add_override with a plain json rule on wafv2

### Possible Solution

Add Action to the jsii interface mappings? Somehow Action is missing.

### CDK CLI Version

2.127.0 (build 6c90efc)

### Node.js Version

v18.17.0

### OS

MacOs

### Language

Python

### Language Version

Python 3.9.6

**Comment by pahud** [comment]
I guess you should just use `Rules`

This works for me in ts

```ts

export class DummyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const new_rule = {
      "Action": {
          "Block": {}
      },
      "Name": "Deny_regex",
      "Priority": 1,
      "Statement": {
          "RegexPatternSetReferenceStatement": {
              "Arn": {
                  "Fn::ImportValue": "my-regex-arn"
              },
              "FieldToMatch": {
                  "SingleHeader": {
                      "Name": "my-header"
                  }
              },
              "TextTransformations": [
                  {
                      "Priority": 0,
                      "Type": "NONE"
                  }
              ]
          }
      },
      "VisibilityConfig": {
          "CloudWatchMetricsEnabled": "True",
          "MetricName": "Deny_regex",
          "SampledRequestsEnabled": "True"
      }
  }

    const cfnwebacl = new wafv2.CfnWebACL(this, 'WebACL', {
      defaultAction: {},
      scope: 'CLOUDFRONT',
      visibilityConfig: {
        cloudWatchMetricsEnabled: true,
        metricName: 'foo',
        sampledRequestsEnabled: true,
      }
    });
    cfnwebacl.addPropertyOverride('Rules', [ new_rule ])
  }
}
```

synth output

```yaml
Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction: {}
      Rules:
        - Action:
            Block: {}
          Name: Deny_regex
          Priority: 1
          Statement:
            RegexPatternSetReferenceStatement:
              Arn:
                Fn::ImportValue: my-regex-arn
              FieldToMatch:
                SingleHeader:
                  Name: my-header
              TextTransformations:
                - Priority: 0
                  Type: NONE
          VisibilityConfig:
            CloudWatchMetricsEnabled: "True"
            MetricName: Deny_regex
            SampledRequestsEnabled: "True"
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: foo
        SampledRequestsEnabled: true
```
