### ISSUE TITLE
sam: cdk synth is missing prop for CfnFunction

### ISSUE THREAD

**Issue by AmazingDreams** [aws/aws-cdk#29297]
### Description:

I am trying to setup an SQS event handler with ReportBatchItemFailures enabled. I am using CDK. However, the option will still be disabled.

### Steps to reproduce:

I am using this in CDK template:

```
        new sam.CfnFunction(this, 'some-function', {
            events: {
                sqs: {
                    type: 'SQS',
                    properties: {
                        queue: this.queue.queueArn,
                        batchSize: 10,
                        functionResponseTypes: [ 'ReportBatchItemFailures' ],
                    }
                }
            }
        });
```

### Observed result:

The function response types are not inserted into the generated template:

```
  somefunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: somefunction
      Events:
        sqs:
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - somequeue
              - Arn
          Type: SQS
```

### Expected result:

I expect the ReportBatchItemFailures to be injected into the generated template:

```
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - somequeue
              - Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`:
3. AWS region: eu-west-1

```
{
  "version": "1.109.0",
  "system": {
    "python": "3.11.7",
    "os": "Windows-10-10.0.22631-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "1.7.3"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by pahud** [comment]
Yes I can reproduce this issue

```ts
    new sam.CfnFunction(this, 'some-function', {
      events: {
          sqs: {
              type: 'SQS',
              properties: {
                  queue: 'dummyArn',
                  batchSize: 10,
                  functionResponseTypes: ['foo'],
              }
          }
      }
    });
```

would synthesize into

```yaml
  somefunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        sqs:
          Properties:
            BatchSize: 10
            Queue: dummyArn
          Type: SQS
```

And `functionResponseTypes` is missing in the template.
