### ISSUE TITLE
imagebuilder.CfnImagePipeline: AWS::ImageBuilder::ImagePipeline WorkflowConfiguration

### ISSUE THREAD

**Issue by include** [aws/aws-cdk#29910]
### Describe the bug

I am defining a default Amazon-managed AMI build workflow (arn:aws:imagebuilder:eu-west-1:aws:workflow/build/build-image/1.0.1/1) but it breaks.

The snippet of code I am using: (reduced to the essential):

```
    const pipeline = new imagebuilder.CfnImagePipeline(this, 'Pipeline', {
      name: this.stackName + '-pipeline',
      // (...)
      workflows: [
        {
          onFailure: 'ABORT',
          workflowArn: 'arn:aws:imagebuilder:eu-west-1:aws:workflow/build/build-image/1.0.1/1',
        },
      ],
    });
```

### Expected Behavior

Build a image pipeline using a standard workflow.

### Current Behavior

```
12:40:45 AM | CREATE_FAILED        | AWS::ImageBuilder::ImagePipeline               | Pipeline
Resource handler returned message: "The value supplied for parameter 'workflows' is not valid. AWS managed workflows must have latest version 'x.x.x' for '{workflow_arn_str}' (Service:
Imagebuilder, Status Code: 400, Request ID: c02cd8e3-1ecd-4ddf-ae0a-3c3ca29ee39a)" (RequestToken: e006e4e0-8450-41c7-93ed-5fb154cb1950, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

As show above, the deployment of the following resource; using workflows.

```
    const pipeline = new imagebuilder.CfnImagePipeline(this, 'Pipeline', {
      name: this.stackName + '-pipeline',
      description: 'Image pipeline',
      distributionConfigurationArn: euAllDistribution.attrArn,
      enhancedImageMetadataEnabled: true,
      executionRole: iamRoleforimageBuilder.roleArn,
      imageRecipeArn: baseRecipe.attrArn,
      imageScanningConfiguration: {
        imageScanningEnabled: imageScanningEnabled,
      },
      imageTestsConfiguration: {
        imageTestsEnabled: false,
        timeoutMinutes: 60,
      },
      infrastructureConfigurationArn: infraConfig.attrArn,
      schedule: {
        pipelineExecutionStartCondition: 'EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE',
        scheduleExpression: 'cron(0 0 * * ? *)',
      },
      status: status,
      tags: tags,
      workflows: [
        {
          onFailure: 'ABORT',
          parallelGroup: '1',
          workflowArn: 'arn:aws:imagebuilder:eu-west-1:aws:workflow/build/build-image/1.0.1/1',
        },
      ],
    });
```

### Additional Information/Context

The official CloudFormation page https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-imagebuilder-imagepipeline-workflowconfiguration.html#cfn-imagebuilder-imagepipeline-workflowconfiguration-workflowarn points out the correct regexp for this parameter:

```
WorkflowArn
The Amazon Resource Name (ARN) of the workflow resource.

Required: No

Type: String

Pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws):workflow/(build|test|distribution)/[a-z0-9-_]+/(?:(?:([0-9]+|x)\.([0-9]+|x)\.([0-9]+|x))|(?:[0-9]+\.[0-9]+\.[0-9]+/[0-9]+))$
```

In the meantime just for testing the pattern I've used in TS, (using https://regex101.com/ to test the regexp), I had to escape all "/" like following bellow to get it working; in any case the deployment failed.

````

/^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws):workflow\/(build|test|distribution)\/[a-z0-9-_]+\/(?:(?:([0-9]+|x)\.([0-9]+|x)\.([0-9]+|x))|(?:[0-9]+\.[0-9]+\.[0-9]+\/[0-9]+))$/gm
```

### CDK CLI Version

2.138.0

### Framework Version

_No response_

### Node.js Version

v20.0.0

### OS

mac 14.4.1

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

**Comment by pahud** [comment]
This seems to be an issue of CFN not CDK. Can you share the synthesized CFN template of this resource?

**Comment by include** [comment]
Hi @pahud thank you for picking up this.

Here it goes that synth section which looks fine to me.

```yaml
  Pipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Description: Image pipeline
      DistributionConfigurationArn:
        Fn::GetAtt:
          - euAllDistribution
          - Arn
      EnhancedImageMetadataEnabled: true
      ExecutionRole:
        Fn::GetAtt:
          - EC2InstanceProfileForImageBuilderA043DE9F
          - Arn
      ImageRecipeArn:
        Fn::GetAtt:
          - BaseRecipe
          - Arn
      ImageScanningConfiguration:
        ImageScanningEnabled: false
      ImageTestsConfiguration:
        ImageTestsEnabled: false
        TimeoutMinutes: 60
      InfrastructureConfigurationArn:
        Fn::GetAtt:
          - infraConfig
          - Arn
      Name: pipe-img-builder-x-pipeline
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE
        ScheduleExpression: cron(0 0 * * ? *)
      Status: ENABLED
      Tags:
        Name: pipe-img-builder
        Release: live
        Version: 0.1.0
      Workflows:
        - OnFailure: ABORT
          WorkflowArn: arn:aws:imagebuilder:eu-west-1:aws:workflow/build/build-image/1.0.1
    Metadata:
      aws:cdk:path: PipeImgBuilderStack/Pipeline
```

I've noted that in the main page (AWS Console) / EC2 Image Builder / Image workflows: the 'build-image' has the following "Arn: arn:aws:imagebuilder:eu-west-1:aws:workflow/build/build-image/1.0.1", but if you click "build-image" to see its details, the Arn is: "arn:aws:imagebuilder:eu-west-1:aws:workflow/build/build-image/1.0.1/1". Not much a difference and in fact I've tested both; returns the same error.

PS: I can ship the entire synth if you need.

Thank you in advance,
F
