### ISSUE TITLE
Glue::CfnTable: Not able to create a table by providing schema_name and registry_name

### ISSUE THREAD

**Issue by mehdimld** [aws/aws-cdk#30076]
### Describe the bug

I've encountered an issue while trying to create a Glue table using the aws_glue.CfnTable construct in the AWS CDK Python library. According to the [documentation](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_glue/CfnTable.html#aws_cdk.aws_glue.CfnTable.SchemaReferenceProperty), I should be able to specify the schema_reference using registry_name and schema_name. However, when I attempt to deploy this configuration, the deployment fails with an error indicating that these pieces of information are not being provided. Below is a screenshot of the code snippet I use and the error I get at deployment. 

<img width="1476" alt="Screenshot 2024-05-06 at 17 09 52" src="https://github.com/aws/aws-cdk/assets/38988556/84f27504-8b6b-4260-935f-9757ae9de520">

<img width="1493" alt="Screenshot 2024-05-06 at 17 15 32" src="https://github.com/aws/aws-cdk/assets/38988556/a2f61ffb-6689-49df-9ead-2e8e941ae644">

### Expected Behavior

The table should be created with the schema referenced, as I provided both registry and schema name.

### Current Behavior

Table creation fails

### Reproduction Steps

Try to create a glue table using aws_glue.CfnTable, reference a schema and a registry. 

### CDK CLI Version

2.132.1

### Node.js Version

20.10.0

### OS

Windows

### Language

Python

### Language Version

3.11

**Comment by ashishdhingra** [comment]
@mehdimld Good morning. Thanks for opening the issue. The above error is returned by CloudFormation when the synthesized CF template is deployed. Could you please share the following:
- Minimal reproduction code for your CDK stack to reproduce the issue.
- Have you tried latest version of `aws-cdk-lib`?
- Share the output CloudFormation template of `cdk synth` command.

I tried reproducing the issue using CDK stack written both in TypeScript and Python. The properties `RegistryName` and `SchemaName` both appear to be set in output CFN template when executing `cdk synth`.

<details>

<summary>TypeScript</summary>

## CDK stack
```TypeScript
import * as cdk from 'aws-cdk-lib';
import * as glue from 'aws-cdk-lib/aws-glue';
import { Construct } from 'constructs';

export class TypescriptStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const cfnTable = new glue.CfnTable(this, 'MyCfnTable', {
      catalogId: 'testcatalogid',
      databaseName: 'testdatabasename',
      tableInput: {
        description: 'description',
        tableType: 'EXTERNAL_TABLE',
        name: 'testtablename',
        partitionKeys: [{
          name: 'name',

          // the properties below are optional
          comment: 'comment',
          type: 'type',
        }],
        storageDescriptor: {
          location: 's3://testbucket/',
          schemaReference: {
            schemaId: {
              registryName: 'testregistryName',
              schemaName: 'testschemaName',
            }
          }
        },
      }
    });
  }
}
```
## `cdk synth` output
```YAML
Resources:
  MyCfnTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: testcatalogid
      DatabaseName: testdatabasename
      TableInput:
        Description: description
        Name: testtablename
        PartitionKeys:
          - Comment: comment
            Name: name
            Type: type
        StorageDescriptor:
          Location: s3://testbucket/
          SchemaReference:
            SchemaId:
              RegistryName: testregistryName
              SchemaName: testschemaName
        TableType: EXTERNAL_TABLE
    Metadata:
      aws:cdk:path: TypescriptStack/MyCfnTable
  CDKMetadata:
    Type: AWS::CDK::Metadata
...
...
```
</details>

<details>

<summary>Python</summary>

## CDK stack
```Python
from aws_cdk import (
    # Duration,
    Stack,
    aws_glue as glue,
)
from constructs import Construct

class PythonStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # The code that defines your stack goes here

        # example resource
        cfnTable = glue.CfnTable(
            self, "MyCfnTable",
            catalog_id="testcatalogid",
            database_name="testdatabasename",
            table_input=glue.CfnTable.TableInputProperty(
                description="description",
                table_type="EXTERNAL_TABLE",
                name="testtablename",
                partition_keys=[glue.CfnTable.ColumnProperty(name="name", comment="comment", type="type")],
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    location="s3://testbucket/",
                    schema_reference=glue.CfnTable.SchemaReferenceProperty(
                        schema_id=glue.CfnTable.SchemaIdProperty(
                            registry_name="testregistryName",
                            schema_name="testschemaName"
                        )
                    )
                )
            )
        )
```
## `cdk synth` output
```YAML
Resources:
  MyCfnTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: testcatalogid
      DatabaseName: testdatabasename
      TableInput:
        Description: description
        Name: testtablename
        PartitionKeys:
          - Comment: comment
            Name: name
            Type: type
        StorageDescriptor:
          Location: s3://testbucket/
          SchemaReference:
            SchemaId:
              RegistryName: testregistryName
              SchemaName: testschemaName
        TableType: EXTERNAL_TABLE
    Metadata:
      aws:cdk:path: PythonStack/MyCfnTable
  CDKMetadata:
    Type: AWS::CDK::Metadata
...
...
```
</details>

Thanks,
Ashish
