### ISSUE TITLE
(Lambda): Lambda environment variables that reference updated "parameters" are not updated when redeploying the stack

### ISSUE THREAD

**Issue by AllanOricil** [aws/aws-cdk#30101]
### Describe the bug

I have a lambda full of env variables referencing a "parameter", like the one shown below

<img width="1328" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/402332d8-fe1b-48d0-b7d0-507c90b3fe79">

> **INFO**: pay attention that I'm loading the right .env file as shown in the above image. I always set NODE_ENV before I ran any cdk command. And I print the .env path to make sure the right one was selected when building things locally.

<img width="1347" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/1e43907b-5369-452b-b5af-966bc4e5f3d0">

The above screenshots show a template that was synthesized by CDK after I changed the .env file that provide values to my parameters.  However, even after deploying this new stack, CDK did not change my env variable values in my lambda functions. In the image below you can see that "ALLOWED_ORIGINS" was not updated.

<img width="1407" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/66366b22-79e9-466c-b62a-a2317afad89b">

Another weird thing is the CDK doesnt even realize that this change will happen. Below you can see the output of `cdk diff` for the same stack.

### Expected Behavior

CDK must update Lambda Env Variables values that reference parameters whenever they are changed.

### Current Behavior

CDK does not update Lambda Env Variables values when they reference parameters that have changed

### Reproduction Steps

1. create a construct with one lambda
2. create a cfn parameter that is loaded with values from a .env file. You can use dotenv. like I did.
<img width="588" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/6646813b-f9d1-4d56-9060-461682888a2c">
<img width="560" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/2d389371-a8e4-443b-bcdd-3b5840765a81">

4. add an env variable to your lambda, and fill its value with the value from the parameter.

<img width="521" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/06cdae43-8126-4b21-b751-8bb038e27c13">

5. synth and deploy it. Open the synthesized template and verify the parameter value is the same one from your .env.
6. change the .env value 
7. synth. Again verify the synthesized template and verify that it has changed, and it again matches the one from your .env.
8. deploy it and  verify that the value was not changed in AWS
10. conclude it is a bug

### Possible Solution

Couldn't find any woraround

### CDK CLI Version

2.138.0

### Node.js Version

node 18

### OS

macos latest

### Language

TypeScript

### Language Version

typescript@v5.2.2

**Comment by AllanOricil** [comment]
I also deleted ALL env variables in one of my functions, redeployed the stack, and the env variables were not added back. There were a bunch of other env variables there that are just gone.

<img width="1637" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/d70c2970-ecba-4e3a-99fe-1acbe24d7726">

**Comment by AllanOricil** [comment]
I had to invest around 1 hour to destroy and recreate my stack in order to have env variables updated

<img width="1419" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/ae036b68-89f6-453b-84e9-f671a02a5f2d">

**Comment by AllanOricil** [comment]
Please, create a dedicated flag in cdk that "updates env variables only".

`--update-lambda-env-variables-only`


Look at this! 28min to deploy + the time to destroy the stack + the time I now have to invest to update the API url in some other stacks

<img width="1132" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/8b932ac4-7cf9-406f-af7b-ed2f1ad9812b">

**Comment by ashishdhingra** [comment]
@AllanOricil Somehow I'm unable to reproduce the issue with CDK version `2.140.0`. Used the code below:
**TypescriptStack.ts**
```TypeScript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as dotenv from 'dotenv';

export class TypescriptStack extends cdk.Stack {
  private readonly allowedOrigins: cdk.CfnParameter;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    dotenv.config();
    console.log("ALLOWED_ORIGINS: " + this.getEnvVar("ALLOWED_ORIGINS"));

    this.allowedOrigins = new cdk.CfnParameter(this, "allowedOrigins", {
      type: "String",
      noEcho: true,
      default: this.getEnvVar("ALLOWED_ORIGINS")
    });

    const lambdaFunction = new lambda.Function(this, 'testLambda', {
      runtime: lambda.Runtime.NODEJS_20_X,
      code: lambda.Code.fromAsset('lambda'),
      handler: 'hello.handler',
      environment: {
         ALLOWED_ORIGINS: this.getEnvVar("ALLOWED_ORIGINS")
      }
    });
  }

  getEnvVar(envVarName: string): string {
    return process.env.ALLOWED_ORIGINS ?? "";
  }
}
```
**lambda\hello.js**
```JavaScript
exports.handler = async function(event) {
    console.log("request:", JSON.stringify(event, undefined, 2));
    return {
      statusCode: 200,
      headers: { "Content-Type": "text/plain" },
      body: `Hello, CDK! You've hit ${event.path}\n`
    };
  };
```
**.env** (on 1st deploy)
```
ALLOWED_ORIGINS=http://localhost:8080,http://testdomain.com
```
**.env** (on 2nd deploy)
```
ALLOWED_ORIGINS=http://localhost:8080,http://testdomain.com,http://makemydomain.com
```
**package.json**
```JSON
{
  "name": "typescript",
  "version": "0.1.0",
  "bin": {
    "typescript": "bin/typescript.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/jest": "^29.5.12",
    "@types/node": "20.12.7",
    "aws-cdk": "2.140.0",
    "jest": "^29.7.0",
    "ts-jest": "^29.1.2",
    "ts-node": "^10.9.2",
    "typescript": "~5.4.5"
  },
  "dependencies": {
    "aws-cdk-lib": "2.140.0",
    "constructs": "^10.0.0",
    "dotenv": "^16.4.5",
    "source-map-support": "^0.5.21"
  }
}
```

Executing `cdk diff` before 2nd deployment gave the below output:
```
Parameters
[~] Parameter allowedOrigins allowedOrigins: {"Type":"String","Default":"http://localhost:8080,http://testdomain.com","NoEcho":true} to {"Type":"String","Default":"http://localhost:8080,http://testdomain.com,http://makemydomain.com","NoEcho":true}

Resources
[~] AWS::Lambda::Function testLambda testLambdaC13632F6 
 └─ [~] Environment
     └─ [~] .Variables:
         └─ [~] .ALLOWED_ORIGINS:
             ├─ [-] http://localhost:8080,http://testdomain.com
             └─ [+] http://localhost:8080,http://testdomain.com,http://makemydomain.com
```

Executing `cdk deploy` updated the environment variable in Lambda function.

Thanks,
Ashish

**Comment by AllanOricil** [comment]
Ok, my hypothesis is that CDK breaks when the template is too big? So, a simpler example isn't enought? The one I shared above is part of a huge stack I have.

**Comment by ashishdhingra** [comment]
> @ashishdhingra your lambda is not using the value from the parameter. It is using the env variable. Your rendered template must have a Ref pointing to the parameter.

@AllanOricil Thanks for pointing it out. I modified the code to below and the issue is now reproducible:
```TypeScript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as dotenv from 'dotenv';

export class TypescriptStack extends cdk.Stack {
  private readonly allowedOrigins: cdk.CfnParameter;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    dotenv.config();
    console.log("ALLOWED_ORIGINS: " + this.getEnvVar("ALLOWED_ORIGINS"));

    this.allowedOrigins = new cdk.CfnParameter(this, "allowedOrigins", {
      type: "String",
      noEcho: true,
      default: this.getEnvVar("ALLOWED_ORIGINS")
    });

    const lambdaFunction = new lambda.Function(this, 'testLambda', {
      runtime: lambda.Runtime.NODEJS_20_X,
      code: lambda.Code.fromAsset('lambda'),
      handler: 'hello.handler',
      environment: {
         ALLOWED_ORIGINS: this.allowedOrigins.value.toString()
      }
    });
  }

  getEnvVar(envVarName: string): string {
    return process.env.ALLOWED_ORIGINS ?? "";
  }
}
```
It produces below CloudFormation template (as an example), with environment variable as `Ref` to `allowedOrigins` parameter:
```
Parameters:
  allowedOrigins:
    Type: String
    Default: http://localhost:8080,http://testdomain.com,http://makemydomain.com
    NoEcho: true
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  testLambdaServiceRole955E2289:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TypescriptStack/testLambda/ServiceRole/Resource
  testLambdaC13632F6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: b12b4d45960ea908338c4544bcac8039b13736e6d6af9e8a85ef57f538e29706.zip
      Environment:
        Variables:
          ALLOWED_ORIGINS:
            Ref: allowedOrigins
      Handler: hello.handler
      Role:
        Fn::GetAtt:
          - testLambdaServiceRole955E2289
          - Arn
      Runtime: nodejs20.x
    DependsOn:
      - testLambdaServiceRole955E2289
    Metadata:
      aws:cdk:path: TypescriptStack/testLambda/Resource
      aws:asset:path: asset.b12b4d45960ea908338c4544bcac8039b13736e6d6af9e8a85ef57f538e29706
      aws:asset:is-bundled: false
      aws:asset:property: Code
...
...
```
Running `cdk diff` (before 2nd deployment), produces the following output:
```
ALLOWED_ORIGINS: http://localhost:8080,http://testdomain.com,http://makemydomain.com
Stack TypescriptStack
Hold on while we create a read-only change set to get a diff with accurate replacement information (use --no-change-set to use a less accurate but faster template-only diff)
Parameters
[~] Parameter allowedOrigins allowedOrigins: {"Type":"String","Default":"http://localhost:8080,http://testdomain.com","NoEcho":true} to {"Type":"String","Default":"http://localhost:8080,http://testdomain.com,http://makemydomain.com","NoEcho":true}


✨  Number of stacks with differences: 1
```

I'm unsure though if this is a CDK issue or CloudFormation issue since the synthesized template is handled by CloudFormation, and CloudFormation allows declaring parameters.

Need to discuss this with team.

Thanks,
Ashish

**Comment by AllanOricil** [comment]
@ashishdhingra keep us updated
Thank you!

**Comment by pahud** [comment]
Looks like `cdk diff` would not notice the default value change of the same CfnParameter.

**Comment by AllanOricil** [comment]
guys, just found another bug related to env variables.

I added a new env variables to my Build Project for a Codepipeline pipeline, and CDK is also not seeing the difference.

<img width="777" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/ee4b911d-b0a9-4cdf-9af1-783e906ac351">

<img width="777" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/e2daed00-4e47-41cc-9b69-3443ca3aae17">

I synth, then diff, then deployed, and again no changes to Env variables. It seems a generalized issue related to env variables that many parts of cloudformation or cdk cant see.

<img width="777" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/4786c1c2-7fe9-45ab-97db-9c45e049b3cc">

**Comment by AllanOricil** [comment]
Sorry, I thought I had found another related issue. But I confused an execution record with a config record.

**Comment by skinny85** [comment]
@AllanOricil why do you need to use a Parameter at all? In general, CloudFormation Parameters are discouraged when using CDK.

**Comment by AllanOricil** [comment]
In this scenario I can remove it. I did it because I wanted to be able to override an env variable in case It comes from somewhere else that isn't in the env where cdk is being built. With a parameter like that, I can deploy my stack as so:


```bash
DYNAMIC_VARIABLE=$(...)
cdk synth stack-name -e --parameters $DYNAMIC_VARIABLE
```

**Comment by skinny85** [comment]
@AllanOricil No worries! A few thoughts:

1. There's no reason to use CloudFormation Parameters if all you need is to read an environment variable. You can always just read an environment variable directly in your CDK code:

    ```ts
    const dynamicVariable = process.env.DYNAMIC_VARIABLE ?? 'DEFAULT_VALUE';
    // use dynamicVariable in your code...
    ```

2. The [CDK Context](https://docs.aws.amazon.com/cdk/v2/guide/context.html) is a good mechanism if you need to reference something outside your code.

In general, the results of synthesizing your CDK app should be deterministic, and avoid things like external environment variables as much as possible.

Do you need to use environment variables perhaps because you are using the same CDK `Stack` instance for multiple deployed Stacks in CloudFormation? [That's not the best practice when using CDK](https://www.endoflineblog.com/cdk-tips-05-have-a-stack-instance-per-deployed-stack).

Let me know if this makes sense!

**Comment by ashishdhingra** [comment]
For testing purposes, without using CDK:
- Deployed the below CloudFormation stack from AWS console (manually uploaded the lambda code ZIP file to S3 bucket):
```YAML
Parameters:
  allowedOrigins:
    Type: String
    Default: http://localhost:8080,http://testdomain.com
    NoEcho: true
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  testLambdaServiceRole955E2289:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  testLambdaC13632F6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: testbucket-issue1880
        S3Key: b12b4d45960ea908338c4544bcac8039b13736e6d6af9e8a85ef57f538e29706.zip
      Environment:
        Variables:
          ALLOWED_ORIGINS:
            Ref: allowedOrigins
      Handler: hello.handler
      Role:
        Fn::GetAtt:
          - testLambdaServiceRole955E2289
          - Arn
      Runtime: nodejs20.x
    DependsOn:
      - testLambdaServiceRole955E2289
```
This created Lambda along with environment variable `ALLOWED_ORIGINS` having value `http://localhost:8080,http://testdomain.com`.

- Modified the value of CloudFormation parameter `allowedOrigins` to `http://localhost:8080,http://testdomain.com,http://makemydomain.com`. Deployed the below template (updated CloudFormation stack to use a new template):
```YAML
Parameters:
  allowedOrigins:
    Type: String
    Default: http://localhost:8080,http://testdomain.com,http://makemydomain.com
    NoEcho: true
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  testLambdaServiceRole955E2289:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  testLambdaC13632F6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: testbucket-issue1880
        S3Key: b12b4d45960ea908338c4544bcac8039b13736e6d6af9e8a85ef57f538e29706.zip
      Environment:
        Variables:
          ALLOWED_ORIGINS:
            Ref: allowedOrigins
      Handler: hello.handler
      Role:
        Fn::GetAtt:
          - testLambdaServiceRole955E2289
          - Arn
      Runtime: nodejs20.x
    DependsOn:
      - testLambdaServiceRole955E2289
``` 
  - During AWS console workflow, in **Specify stack details** step showing there was a checkbox `Use previous value` in `Parameters` section. By default, this checkbox was checked. In the last step **Review testlambdastack**, it displayed message `No updates are to be performed.`.

  - Went back to **Specify stack details** step and unchecked the checkbox `Use previous value`. Unchecking the checkbox blanked out the value (could be a UI issue since it should have read updated value from uploaded YAML file). Hence, manually specified value ` http://localhost:8080,http://testdomain.com,http://makemydomain.com` for `allowedOrigins` parameter.
  - Going to last **Review testlambdastack** now displayed Lambda function to be modified in `Change set preview` section.
  - Submitting the changes updated the Lambda function with environment variable `ALLOWED_ORIGINS` changed to `http://localhost:8080,http://testdomain.com,http://makemydomain.com `.

So, by default, any changes to CloudFormation parameter are not used (based on observation in AWS console UI).

If we look at the CDK guide [Deploying with parameters](https://docs.aws.amazon.com/cdk/v2/guide/parameters.html), is explicitly specifies that `By default, the AWS CDK retains values of parameters from previous deployments and uses them in subsequent deployments if they are not specified explicitly. Use the --no-previous-parameters flag to require all parameters to be specified.` (this may be due to limitation of CloudFormation).

Going with the above understanding, using `cdk deploy --no-previous-parameters` on 2nd deployment updated the value of environment variable in Lambda configuration.

@AllanOricil Please use `cdk deploy --no-previous-parameters` to use the updated value of CloudFormation parameter.

Thanks,
Ashish
