### ISSUE TITLE
Changing ssm parameter from string -> securestring throws me an cdk deployment error

### ISSUE THREAD

**Issue by maddyexplore** [aws/aws-cdk#30129]
### Describe the bug

I was trying to secure all strings in ssm parameter group and I found the cdk-bootstrap version there and I changed it into securestring, after that any deployment with cdk fails with error

`AutomationStack: SSM parameter /cdk-bootstrap/<blabla>/version not a number`

### Expected Behavior

it should sense and decrypt with the km kwy

### Current Behavior

throws me error

### Reproduction Steps

secure all strings in ssm parameter group and I found the cdk-bootstrap version there and I changed it into securestring, after that any deployment with cdk fails

### CDK CLI Version

2.124.0

### Node.js Version

v21.6.1

### OS

Windows

### Language

Python

### Language Version

python 3.10

**Comment by ashishdhingra** [comment]
Bootstrap version SSM parameter is defined as `DEFAULT_BOOTSTRAP_STACK_VERSION_SSM_PARAMETER` [here](https://github.com/aws/aws-cdk/blob/f9f3681be9fc6a0c998cd26119053c5832ef9806/packages/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.ts#L289). During [synthesize()](https://github.com/aws/aws-cdk/blob/f9f3681be9fc6a0c998cd26119053c5832ef9806/packages/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.ts#L423C10-L423C20) operation, `CheckBootstrapVersion` rule would be added in the generated CloudFormation template along with the `CfnParameter` named `BootstrapVersion` as shown in example below:
```YAML
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
...
...
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
``` 

As per description `Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store.` of `BootstrapVersion` parameter in the generated CloudFormation template, the value for this parameter is automatically retrieved from SSM Parameter Store. The CDK deployment is essentially a CloudFormation deployment and is handled by the CloudFormation service.

Per [CDK Bootstrapping](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) documentation, 
- AWS CDK's built-in stack synthesizers is called `DefaultStackSynthesizer` (refer [Stack synthesizers](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-synthesizers))
- During initialization of a stack, it is possible to specify a synthesizer as per below example in the above documentation:
  ```TypeScript
  new MyStack(this, 'MyStack', {
    // stack properties
    synthesizer: new DefaultStackSynthesizer({
      // synthesizer properties
    }),
  });
  ```
- Here it is possible to override certain properties (as mentioned in [Customizing synthesis](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-custom-synth) section)
  - The property `generateBootstrapVersionRule` could be set to `false` and as per logic [here](https://github.com/aws/aws-cdk/blob/f9f3681be9fc6a0c998cd26119053c5832ef9806/packages/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.ts#L431), it should not emit `BootstrapVersion` CfnParameter and `CheckBootstrapVersion` CfnRule (these are added [here](https://github.com/aws/aws-cdk/blob/f9f3681be9fc6a0c998cd26119053c5832ef9806/packages/aws-cdk-lib/core/lib/stack-synthesizers/stack-synthesizer.ts#L312)).
  **Unsure if this should be used since bootstrap version should always be validated.**
  - Per **Roles** section at [The bootstrapping template contract](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-contract), the `DefaultStackSynthesizer` requires five IAM roles for five different purposes. For your use case, since the issue happens during deployment process, in your AWS environment, you could add necessary IAM permissions to the `cloudFormationExecutionRole`, which per above documentation is `ARN of the role passed to CloudFormation to execute the deployments.` and has format like `arn:${AWS::Partition}:iam::${AWS::AccountId}:role/cdk-${Qualifier}-cfn-exec-role-${AWS::AccountId}-${AWS::Region}` (here the default value for `${Qualifier}` is `hnb659fds`) deployment role created by CDK bootstrapping process. You could refer [IAM permissions for using AWS default keys and customer managed keys](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html#ps-kms-permissions) for example policy.
 
I would rather go with 2nd option to add necessary IAM permissions. Hope it unblocks you.

Thanks,
Ashish
