### ISSUE TITLE
aws_ecs_patterns: default listener rule cannot be changed

### ISSUE THREAD

**Issue by kcong7714** [aws/aws-cdk#30412]
### Describe the bug

I have a `my_service` instantiated from `aws_ecs_patterns.ApplicationLoadBalancedFargateService()`.

I need a custom listener rule with a host header condition so that all other traffic will not be forwarded to the container. This can be added without issue, but the default listener rule does not change despite explicitly defining it, rendering the added custom rule pointless.

### Expected Behavior

Default listener rule returns HTTP 503 Service Unavailable.

### Current Behavior

Default listener rule is forwarding to target group `my_service.target_group`.

### Reproduction Steps

`my_service` is instantiated from `aws_ecs_patterns.ApplicationLoadBalancedFargateService()`.

A custom listener rule is added:
```
aws_elbv2.ApplicationListenerRule(
    self, 'my-rule',
    listener=my_service.listener,
    priority=1,
    conditions=[aws_elbv2.ListenerCondition.host_headers([MY_DOMAIN_NAME])],
    action=elbv2.ListenerAction.forward(target_groups=[my_service.target_group]),
)
```

An attempt to change the default listener rule:
```
my_service.listener.default_action = elbv2.ListenerAction.fixed_response(
    status_code=503,
    content_type='text/plain',
    message_body='Service Unavailable',
)
```

### Additional Information/Context

`cdk synth` sample output:
```
  MyServiceLBPublicListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: MyServiceLBPublicListenerECSGroup
          Type: forward
```

### CDK CLI Version

2.144.0 (build 5fb15bc)

### Node.js Version

v20.11.1

### OS

Ubuntu 22.04.4 LTS

### Language

Python

### Language Version

3.10.12

**Comment by kcong7714** [comment]
Sorry, my bad, it's not a bug. The right way to do this is:

```
my_service.listener.add_action(
    'DefaultAction',
    action=elbv2.ListenerAction.fixed_response(
        status_code=503,
        content_type='text/plain',
        message_body='Service Unavailable',
    )
)
```

When `priority` is not specified, it becomes the default action.

`cdk synth` output:
```
  MyServiceLBPublicListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - FixedResponseConfig:
            ContentType: text/plain
            MessageBody: Service Unavailable
            StatusCode: "503"
          Type: fixed-response
```
