### ISSUE TITLE
cdk migrate: FooBarStack could not be generated because VpcId is not a valid property for resource EC2NatGatewayNNN of type AWS::EC2::NatGateway

### ISSUE THREAD

**Issue by paolo-galati** [aws/aws-cdk#30872]
### Describe the bug

Attempting to migrate some deployed resources, the command returns the error:

`Migrate failed for 'FooBar': FooBarStack could not be generated because VpcId is not a valid property for resource EC2NatGatewayNNN of type AWS::EC2::NatGateway.`

The command executed is as follows:

`cdk migrate -n FooBar -l java --from-scan new --ignore-errors`

### Expected Behavior

Generate a CDK stack

### Current Behavior

Migrate failed with message:

`Migrate failed for 'FooBar': FooBarStack could not be generated because VpcId is not a valid property for resource EC2NatGatewayXXX of type AWS::EC2::NatGateway.`

### Reproduction Steps

Run `cdk migrate -n FooBar -l java --from-scan new --ignore-errors` on an account where a NAT gateway is present.

### Possible Solution

No workaround found.

### CDK CLI Version

2.149.0 (build c8e5924)

### Node.js Version

v20.15.1

### OS

macOS 14.5

### Language

Java

### Language Version

Java (21)

**Comment by richardgavel-ordinaryexperts** [comment]
@paolo-galati When you look at your stack's template in AWS console, does it actually have a property VpcId?

**Comment by paolo-galati** [comment]
Hi @richardgavel-ordinaryexperts .

I currently don't have a CloudFormation stack, I only have deployed resources. For this reason, I would like to use CDK migrate to create a new AWS CDK project. In fact, I used the `--from-scan` flag to create the project from deployed resources."

**Comment by aantia** [comment]
I am experiencing an identical issue, and can answer @richardgavel-ordinaryexperts 's question. I can confirm that the CloudFormation template does actually have a property VpcId (values censored): 
```
EC2NatGateway00natfoo:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EC2::NatGateway"
    DeletionPolicy: "Retain"
    Properties:
      PrivateIpAddress: "10.X.X.X"
      ConnectivityType: "public"
      VpcId: "vpc-foo"
      EniId: "eni-foo"
      AllocationId:
        Fn::GetAtt:
        - "EC2EIP0034foo"
        - "AllocationId"
      SubnetId:
        Ref: "EC2Subnet00subnet0foo"
      Tags:
      - Value: "MyOldStack/MyResource/Subnet3"
        Key: "Name"
```

This was generated in the CloudFormation console from existing resources, imported by the import tool. It may be irrelevant, but the resource itself was originally created as part of a CDK stack ('MyOldStack'), which I deleted after setting all the resources to `DeletionPolicy: "Retain"` as part of a large refactor. Another potentially relevant note is that I'm doing this in such a fiddly way because the `cdk import` command failed (with message `FAILED, Internal Failure`) with these resources - I wonder if it was generating this template internally with VpcId and EniId?

As a workaround, I deleted the VpcId and EniId from my template and deployed that to my existing stack before running cdk migrate (the same error was triggered for EniId). This doesn't _seem_ to have broken anything, but it hasn't been tested properly yet.

This could be a bug in CloudFormation rather than CDK, depending on whether those properties are actually supposed to be there.
