### ISSUE TITLE
aws_s3.Bucket.from_bucket_name : returns _BaseBucketProxy object instead of IBucket

### ISSUE THREAD

**Issue by kamari-swami** [aws/aws-cdk#30885]
### Describe the bug

existing_bucket_name = "test_bucket"

get_bucket = Bucket.from_bucket_name(scope, id, existing_bucket_name)

cloudformation_distro = Distribution(....., log_bucket=get_bucket,)

Error:
```
    test = MeteredDistribution(
  File "/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/.venv/lib/python3.10/site-packages/aws_cdk/aws_lambda_event_sources/__init__.py", line 1147, in __init__
    check_type(argname="argument bucket", value=bucket, expected_type=type_hints["bucket"])
  File "/.venv/lib/python3.10/site-packages/typeguard/__init__.py", line 785, in check_type
    raise TypeError(
TypeError: type of argument bucket must be aws_cdk.aws_s3.Bucket; got aws_cdk.aws_s3._BucketBaseProxy instead
```

### Expected Behavior

Bucket.from_bucket_name should return IBucket object as per the definition of the method:

```
def from_bucket_name(
        cls,
        scope: _constructs_77d1e7e8.Construct,
        id: builtins.str,
        bucket_name: builtins.str,
    ) -> IBucket:

```

### Current Behavior

Returns `aws_cdk.aws_s3._BucketBaseProxy` instead

### Reproduction Steps

as above

### Possible Solution

Not known

### CDK CLI Version

2.147.1 (build d3695d4)

### Node.js Version

v20.11.0

### OS

Ubuntu v22

### Language

Python

### Language Version

Python 3.10.12

**Comment by ashishdhingra** [comment]
Hi @kamari-swami,

Good morning. Thanks for opening the issue. Could you please share minimal self reproduction CDK code to troubleshoot the issue. Using AWS CDK version `2.149.0 (build c8e5924)`, the below Python CDK code:
```Python
from aws_cdk import (
    Stack,
    aws_s3 as s3,
    aws_cloudfront as cloudfront,
    aws_cloudfront_origins as cloudfrontOrigins
)
from constructs import Construct

class Issue30885Stack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        bucket = s3.Bucket.from_bucket_name(
            self, 
            id="MyBucket",
            bucket_name="testbucket-someissue"
        )

        cloudfrontDistribution = cloudfront.Distribution(
            self,
            id="MyCloudfrontDistribution",
            default_behavior=cloudfront.BehaviorOptions(
                allowed_methods=cloudfront.AllowedMethods.ALLOW_ALL,
                origin=cloudfrontOrigins.S3Origin(
                    bucket=bucket,
                    origin_path="/"
                )
            ),
            log_bucket=bucket
        )
```
successfully synthesizes to the below CloudFormation template:
```YAML
Resources:
  MyCloudfrontDistributionOrigin1S3OriginF5116CA8:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for Issue30885StackMyCloudfrontDistributionOrigin1D7159771
    Metadata:
      aws:cdk:path: Issue30885Stack/MyCloudfrontDistribution/Origin1/S3Origin/Resource
  MyCloudfrontDistribution7D54D3CA:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: Issue30885StackMyCloudfrontDistributionOrigin1D7159771
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Logging:
          Bucket:
            Fn::Join:
              - ""
              - - testbucket-someissue.s3.
                - Ref: AWS::Region
                - "."
                - Ref: AWS::URLSuffix
        Origins:
          - DomainName:
              Fn::Join:
                - ""
                - - testbucket-someissue.s3.
                  - Ref: AWS::Region
                  - "."
                  - Ref: AWS::URLSuffix
            Id: Issue30885StackMyCloudfrontDistributionOrigin1D7159771
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: MyCloudfrontDistributionOrigin1S3OriginF5116CA8
...
...
```

Thanks,
Ashish
