### ISSUE TITLE
aws-cdk-lib: Arn.split cannot parse AWS Batch Job queue ARN

### ISSUE THREAD

**Issue by kcrimson** [aws/aws-cdk#30927]
### Describe the bug

I am trying to create a CloudWatch Alarm for AWS Batch queues. CDK synth produces the following CloudFormation template:

```
BatchWatchdogBatchWatchdogAlertsworkerm6gdlargeAlarm7BA82391:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: false
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: BatchJobQueue
          Value:
            Fn::Select:
              - 2
              - Fn::Split:
                  - /
                  - Fn::Select:
                      - 5
                      - Fn::Split:
                          - ":"
                          - Fn::Select:
                              - 1
                              - Fn::Split:
                                  - /
                                  - Fn::Select:
                                      - 5
                                      - Fn::Split:
                                          - ":"
                                          - Fn::GetAtt:
                                              - workerm6gdlargeJobQueue4AFBF4B1
                                              - JobQueueArn
      EvaluationPeriods: 5
      MetricName: TimeInQueue
      Namespace: benchmarking
      Period: 300
      Statistic: Average
      Tags:
        - Key: owner
          Value: benchmark
        - Key: project
          Value: benchmarking-batch-infrastructure
        - Key: stage
          Value: staging
      Threshold: 3600
      Unit: Seconds

```

### Expected Behavior

What is expected is to set the value of the Alarm dimension to the AWS batch job queue name.

When I run this code as a code snippet, it extracts the resource name properly, but it generates an invalid CF template

```
|  Welcome to JShell -- Version 11.0.8
|  For an introduction type: /help intro

jshell> import software.amazon.awscdk.Arn;

jshell> import software.amazon.awscdk.ArnFormat

jshell> Arn.split("arn:aws:batch:us-east-1:111122223333:job-queue/JobQueueName",ArnFormat.SLASH_RESOURCE_SLASH_RESOURCE_NAME).getResourceName();
$3 ==> "JobQueueName"

```

### Current Behavior

When I deploy this stack, I get the following error:

```
Failed resources:
benchmarking-batch-infrastructure-staging-eu-central-1 | 4:11:00 PM | CREATE_FAILED        | AWS::CloudWatch::Alarm         | BatchWatchdog/BatchWatchdogAlerts/worker-m6gd.large-Alarm (BatchWatchdogBatchWatchdogAlertsworkerm6gdlargeAlarm7BA82391) Template error: Fn::Select  cannot select nonexistent value at index 5

```

### Reproduction Steps

The Java code which creates CloudWatch alarms, looks like this:

```
private void createAlarm(BatchJobQueue batchJobQueue) {
        var resourceName = Arn.split(batchJobQueue.getJobQueueName(), ArnFormat.SLASH_RESOURCE_SLASH_RESOURCE_NAME)
                .getResourceName();
        Alarm.Builder.create(this, batchJobQueue.getNode().getId() + "-Alarm")
                .actionsEnabled(false)
                .metric(Metric.Builder.create()
                        .namespace(BatchWatchDog.BENCHMARKING_METRIC_NAMESPACE)
                        .metricName(BatchWatchDog.TIME_IN_QUEUE_METRIC_NAME)
                        .dimensionsMap(Map.of(BatchWatchDog.BATCH_JOB_QUEUE_DIMENSION, resourceName))
                        .period(software.amazon.awscdk.Duration.minutes(5))
                        .unit(Unit.SECONDS)
                        .statistic(Stats.AVERAGE)
                        .build())
                .evaluationPeriods(5)
                .datapointsToAlarm(3)
                .threshold(Duration.ofHours(1).toSeconds())
                .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD)
                .build();
    }
```
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.149.0

### Framework Version

_No response_

### Node.js Version

v20.15.1

### OS

Ubuntu  24.04 LTS

### Language

Java

### Language Version

Java 11

### Other information

_No response_
