### ISSUE TITLE
CfnAssociation outputs invalid CloudFormation

### ISSUE THREAD

**Issue by kuhnboy** [aws/aws-cdk#3092]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
When creating a CfnAssociation parameter:

```cs
Parameters = new Dictionary<string, Amazon.CDK.AWS.SSM.CfnAssociation.ParameterValuesProperty>
{ 
  {
    "Operation", new Amazon.CDK.AWS.SSM.CfnAssociation.ParameterValuesProperty
    { 
      ParameterValues = new[] { "Scan" } 
    }
  }
}
```

The output appears to be correct, but cloud formation reports the following error: "Value of {Parameters} must be a map where each value is a list of {String}"

Looking at the documentation, it appears from the sample yaml it should be:

```yam
Parameters:
      Directory: ["myWorkSpace"]
```

but what is emitted from the code above is:

```yaml
Parameters:
  Operation:
    ParameterValues:
      - Scan
```

* **What is the expected behavior (or behavior of feature suggested)?**

Would expect the association to be created with the correct parameters and values.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Would like to have CfnAssociation working.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.28.0
  - Module Version: 0.28.0
  - OS: Windows 10
  - Language: CSharp

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by skinny85** [comment]
@kuhnboy according to the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-association.html#cfn-ssm-association-parameters), the first YAML you posted is actually correct... can you tell us what is the error you get from CloudFormation when trying to deploy this?

Thanks,
Adam

**Comment by tgmedia-nz** [comment]
I've got the same problem, this is my synth template:

```
SSMAssociationApplyPatchBaseline:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-RunPatchBaseline
      AssociationName: Apply-Patch-Baseline
      Parameters:
        Operations:
          ParameterValues:
            - Install
      Targets:
        - Key: tag:Patching
          Values:
            - enabled
```

Using python, I build it (bit retarted tbh, why not just accept dict / array lol):

```
params = _ssm.CfnAssociation.ParameterValuesProperty(parameter_values = ['Install'])

ssm.CfnAssociation(...
parameters = {"Operations": params})
```

If I deploy a manually adjusted cfn like this:

```
      Parameters:
        Operation:
        - Install
```

CF is deploying it all fine - maybe there is a problem with the AWS documentation?

**Comment by tgmedia-nz** [comment]
Btw I've submitted feedback to AWS about the documentation being either confusing or wrong :)

**Comment by tgmedia-nz** [comment]
I've received confirmation from AWS that their documentation is wrong and they will update it:

> Thanks for sending along the feedback about the association parametervalues documentation. We’ll get this updated
> 
> Best wishes,
> -Jim
> Jim Brotherton
> 
> Amazon Web Services
> Senior Technical Writer
> AWS Systems Manager

**Comment by bo67192** [comment]
I'm hitting this today with this version

`"@aws-cdk/aws-ssm": "^1.19.0",`

I have this snippet of CDK code

```
    new ssm.CfnAssociation(this, 'config-gateway', {
      associationName: 'HC-TSP-Config-Gateway',
      name: 'AWS-RunPowerShellScript',
      scheduleExpression: 'rate(30 minutes)',
      targets: [{key: 'SSM_Association', values: [this.gtw_ssm_assoc]}],
      parameters: {
        commands: {parameterValues: ['return c:\\docutap\\util\\tsp\\Run-GatewayConfig.ps1']}
      }
    })
```

And I get this cloudformation yaml

```
  configgateway:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-RunPowerShellScript
      AssociationName: HC-TSP-Config-Gateway
      Parameters:
        commands:
          ParameterValues:
            - return c:\docutap\util\tsp\Run-GatewayConfig.ps1
      ScheduleExpression: rate(30 minutes)
      Targets:
        - Key: SSM_Association
          Values:
            - PHI-tspgtw-prod
    Metadata:
      aws:cdk:path: tsplus-prod/config-gateway
```

And the same error about the contents of the parameter field as above.

I'm going to try flipping to an `IResolvable` produced by this class: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Lazy.html
