### ISSUE TITLE
aws_apigateway: apigateway.LambdaIntegration Integration timeout must be between 50 milliseconds and 29 seconds.

### ISSUE THREAD

**Issue by schaetay** [aws/aws-cdk#31063]
### Describe the bug

The default integration for API Gateway is 29 seconds. After requesting an increase for the account/region I am unable to update the lambda integration timeout beyond the default 29 second timeout via the CDK however I am able to update the timeout beyond the default in the AWS Console.

### Expected Behavior

The Lambda integration timeout should be updated to the specified value beyond the default 29 seconds when deploying via CDK.

### Current Behavior

The Lambda integration timeout remains at the default 29-second limit even after deployment, despite the requested increase being successfully applied in the AWS Console.

### Reproduction Steps

```typescript
const api = new apigateway.RestApi(this, 'api', {
  restApiName: 'api',
  deploy: true,
  endpointConfiguration: {
    types: [ apigateway.EndpointType.REGIONAL ]
  },
});

const fn = new PythonFunction(this, 'fn', {
  functionName: 'lambda-function',
  entry: '../dir/lambda',
  runtime: lambda.Runtime.PYTHON_3_11,
  timeout: cdk.Duration.minutes(2),
});

new apigateway.LambdaIntegration(fn, {
  requestTemplates: { "application/json": '{ "statusCode": "200" }' },
  timeout: cdk.Duration.seconds(31)
});
    
```

### CDK CLI Version

2.151.0 (build b8289e2)

### Node.js Version

v18.18.0

### OS

Windows 11 Version 23H2

### Language

TypeScript

### Language Version

TypeScript 5.3.3

**Comment by pahud** [comment]
Yes according to this, we probably should unblock the limitation
https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-api-gateway-integration-timeout-limit-29-seconds/

https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-apigateway/lib/integration.ts#L83-L95

and

https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-apigatewayv2/lib/http/integration.ts#L260-L262

As there's no way to work it around, I am making it a p1 and we welcome pull requests.

**Comment by godwingrs22** [comment]
Hi @schaetay,  I tried to reproduce the bug with the following code in cdk v2.151.0 but I was able to synth and deploy successfully after increasing the limit in my account/region. Based on checking further, seems this issue is already addressed in this PR #30547. It is available from CDK [#v2.147.0](https://github.com/aws/aws-cdk/releases/tag/v2.147.0).

```
 // Define the Lambda function with inline code
    const lambdaFunction = new lambda.Function(this, 'MyLambdaFunction', {
      runtime: lambda.Runtime.NODEJS_18_X, // Choose your Lambda runtime
      handler: 'index.handler',
      code: lambda.Code.fromInline(`
        exports.handler = async function(event) {
          console.log('Received event:', JSON.stringify(event, null, 2));
          return {
            statusCode: 200,
            body: JSON.stringify({ message: 'Hello, World!' }),
          };
        };
      `),
    });

    // Define the API Gateway
    const api = new apigateway.RestApi(this, 'MyApi', {
      restApiName: 'MyService',
      description: 'This service serves Lambda functions.',
      deploy: true,
      endpointConfiguration: {
        types: [apigateway.EndpointType.REGIONAL]
      },
    });

    // Create a new Lambda integration
    const lambdaIntegration = new apigateway.LambdaIntegration(lambdaFunction, { timeout: cdk.Duration.seconds(31) });

    // Create a new resource and method
    api.root.addMethod('GET', lambdaIntegration);
```

![image](https://github.com/user-attachments/assets/c95ea69f-f474-4a9c-bb79-b0b7c0ffea93)

Could you please let us know which CDK version are you using as there is possibility if the version < v2.147.0, then you might get a validation error during synth or deploy

**Comment by pahud** [comment]
Thank you @godwingrs22 I will look into this issue again.

**Comment by pahud** [comment]
Hi @godwingrs22 

I tried again and yes I can reproduced this with 2.151.0

```ts
export class DummyStack2 extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const api = new apigateway.RestApi(this, 'api', {
      restApiName: 'api',
      deploy: true,
      endpointConfiguration: {
        types: [ apigateway.EndpointType.REGIONAL ]
      },
    });
    
    // dummy function
    const fn = new lambda.Function(this, 'dummy-function', {
      code: lambda.Code.fromInline('dummy'),
      runtime: lambda.Runtime.NODEJS_LATEST,
      handler: 'index.handler',
    })
    
  
    const lambdaIntegration = new apigateway.LambdaIntegration(fn, {
      timeout: cdk.Duration.seconds(31)
    });

    api.root.addMethod('GET', lambdaIntegration); 

  }
}
```


dummy-stack2: creating CloudFormation changeset...
4:34:37 PM | CREATE_FAILED        | AWS::ApiGateway::Method     | apiGETECF0BD67
Resource handler returned message: "Timeout should be between 50 ms and 29000 ms (Service: ApiGateway, Status Code: 400, Request ID: 1a9107c3-3c62-4e05
-9f0c-80f6174b1285)" (RequestToken: 4921f340-9655-87e0-6eee-5bad38b11a1b, HandlerErrorCode: InvalidRequest)


`cdk synth` is actually good but cloudformation would return error.

I see this on `cdk synth`

```
 Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        TimeoutInMillis: 31000 <-----HERE
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - dummyfunction8EE12489
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      RestApiId:
        Ref: apiC8550315
```
