### ISSUE TITLE
aws-cloudfront: cache policy comment length is not validated

### ISSUE THREAD

**Issue by floriangosse** [aws/aws-cdk#31248]
### Describe the bug

CloudFront cache policy have a maximum comment length of 128 but is currently not validated by CDK.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

CDK validates the comment's length.

### Current Behavior

CDK doesn't validate the comment's length.

### Reproduction Steps

```ts
const stack = new cdk.Stack();
new cloudfront.CachePolicy(stack, 'MyCachePolicy', {
	comment: "a".repeat(129)
});
```

### CDK CLI Version

2.37.1

### Node.js Version

20

### OS

macOS

### Language

TypeScript

### Language Version

TypeScript 5

**Comment by ashishdhingra** [comment]
Reproducible using latest version of CDK (`2.154.1 (build febce9d)`).

Running `cdk synth` generated the following CFN template:
```YAML
Resources:
  MyCachePolicyAB35B4E5:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        Name: CdktestStackMyCachePolicy7DA6ED29-us-east-2
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
    Metadata:
      aws:cdk:path: CdktestStack/MyCachePolicy/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzQ10TNUTCwv1k1OydbNyUzSqw4uSUzO1gEKxSfn5JempBXl55XoVTsnJmekBuTnZCZX6jin5SFxa0H8oNTi/NKi5NRanbz8lFS9rGL9MiMjPXM9A8Ws4sxM3aLSvJLM3FS9IAgNAIOR5994AAAA
    Metadata:
      aws:cdk:path: CdktestStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
```
Running `cdk deploy` fails with the following error:
```
✨  Synthesis time: 4.26s

CdktestStack:  start: Building 50549a994e849e12bd404078424773d04a8b39084521c478d0e4b8372886c375:139480602983-us-east-2
CdktestStack:  success: Built 50549a994e849e12bd404078424773d04a8b39084521c478d0e4b8372886c375:139480602983-us-east-2
CdktestStack:  start: Publishing 50549a994e849e12bd404078424773d04a8b39084521c478d0e4b8372886c375:139480602983-us-east-2
CdktestStack:  success: Published 50549a994e849e12bd404078424773d04a8b39084521c478d0e4b8372886c375:139480602983-us-east-2
CdktestStack: deploying... [1/1]
CdktestStack: creating CloudFormation changeset...
[███████████████████▎······································] (1/3)
10:38:09 AM | CREATE_FAILED        | AWS::CloudFront::CachePolicy | MyCachePolicyAB35B4E5
Resource handler returned message: "Invalid request provided: AWS::CloudFront::CachePolicy: The parameter Comment is too big. (Service: CloudFront, Status Code: 4
00, Request ID: ba45e8f8-146f-46f5-8956-e7809f86a121)" (RequestToken: 17de6002-6f1b-f8b3-9f27-6838f1763a89, HandlerErrorCode: InvalidRequest)


 ❌  CdktestStack failed: Error: The stack named CdktestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CloudFront::CachePolicy: The parameter Comment is too big. (Service: CloudFront, Status Code: 400, Request ID: ba45e8f8-146f-46f5-8956-e7809f86a121)" (RequestToken: 17de6002-6f1b-f8b3-9f27-6838f1763a89, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:447:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:450:200276)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:450:181698

 ❌ Deployment failed: Error: The stack named CdktestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CloudFront::CachePolicy: The parameter Comment is too big. (Service: CloudFront, Status Code: 400, Request ID: ba45e8f8-146f-46f5-8956-e7809f86a121)" (RequestToken: 17de6002-6f1b-f8b3-9f27-6838f1763a89, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:447:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:450:200276)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:450:181698

The stack named CdktestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CloudFront::CachePolicy: The parameter Comment is too big. (Service: CloudFront, Status Code: 400, Request ID: ba45e8f8-146f-46f5-8956-e7809f86a121)" (RequestToken: 17de6002-6f1b-f8b3-9f27-6838f1763a89, HandlerErrorCode: InvalidRequest)
```

Per [AWS CloudFront > CreateCachePolicy](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateCachePolicy.html), comment cannot be longer than 128 characters.

@floriangosse Thanks for your PR contribution.
