### ISSUE TITLE
s3-notifications: Unable to update the s3 event notifications on an existing S3 bucket.

### ISSUE THREAD

**Issue by satanupa** [aws/aws-cdk#31303]
### Describe the bug

I am facing an error when trying to update the s3 event notification configuration on an existing S3 bucket using CDK.
Created a stack to add s3 event notification on an existing s3 bucket. Create operation goes through successfully.
When I update the cdk stack to add event notifications on the same s3 bucket, the Update operation fails with below error.

**Error**:
```
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.. See the details in CloudWatch Log Stream:
```

Here the [lambda code](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py#L41) backing the BucketNotifications custom resource is unable to identify that the existing event notifications were also managed by the same cdk stack thereby creating duplicate notifications resulting in error.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Should be able to add additional notification configuration on the existing s3 bucket.

### Current Behavior

**Issue**
Created a cdk stack and added an event notification on an existing s3 bucket. Create operation is successful.
Updated the same stack to add a new event notification along with the existing ones. The update operation fails with below error.

**Error**:
```
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.. See the details in CloudWatch Log Stream:
```

### Reproduction Steps

Steps:
    1. Create a stack by commenting out the 2nd event notification (notificationfilter2)
    2. once stack is created, update the stack after uncommenting the 2nd event notification.
```


 my_lambda = _lambda.Function(
          self, 'HelloHandler',
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset('lambda'),
            handler='hello.handler',
        )  


        bucket = _s3.Bucket.from_bucket_name(self, "Bucket", "bucketname")
        notification = _s3_notify.LambdaDestination(my_lambda)

        notificationfilter1 = _s3.NotificationKeyFilter(prefix="foo/", suffix="bar/")
        bucket.add_event_notification(_s3.EventType.OBJECT_CREATED, notification, notificationfilter1
        )

       # notificationfilter2 = _s3.NotificationKeyFilter(prefix="fo1/",suffix="ba1/",)
      # bucket.add_event_notification(_s3.EventType.OBJECT_CREATED, notification, notificationfilter2
      #  )
```

### Possible Solution

**Analysis details**:
Create a cdk stack to add below event notification to an existing s3 bucket. The Create operation is successful.
```
'Events': ['s3:ObjectCreated:*'], 'Filter': {'Key': {'FilterRules': [{'Name': 'Prefix', 'Value': 'bar/'}, {'Name': 'Suffix', 'Value': 'foo/'}]}}}
```
In the [ notifications-resource-handler](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py#L41) code

For unmanaged buckets, there is a get_id function used to evaluate the hash for each event notification to confirm if this is created by the stack or is an existing external configuration:
```
def get_id(n):
    n['Id'] = ''
    strToHash=json.dumps(n, sort_keys=True).replace('"Name": "prefix"', '"Name": "Prefix"').replace('"Name": "suffix"', '"Name": "Suffix"')
    return f"{stack_id}-{hash(strToHash)}"
```
During creation, this goes fine as it treats all existing configurations as external.
Then it appends incoming + external and creates the final notification configuration as expected.

During an update operation, the lambda code will first get the existing event notifications on the s3 bucket.
Then it validates if the existing event notifications matches the notification in the incoming request from Cloudformation.
It does this by evaluating the hash for each existing event notification and validating if this matches with the hash of the incoming event notifications from Cloudformation. 
When there is a match, it identifies this existing event configuration as managed by the stack. 
This helps in eliminating the duplicates.

There is an issue with this hash evaluation, due to a change in order of the prefix and suffix within the filter rules between the existing notification and the notification coming from Cloudformation.

Sample event notification from Cloudformation request
```
{
    "Events": [
        "s3:ObjectCreated:*"
    ],
    "Filter": {
        "Key": {
            "FilterRules": [
                {
                    "Name": "Suffix",
                    "Value": "foo/"
                },
                {
                    "Name": "Prefix",
                    "Value": "bar/"
                }
            ]
        }
    },
    "Id": "",
    "LambdaFunctionArn": "arn:aws:lambda:<aws-region>:<aws-account-id>:function:<FunctionName>"
}
```

Sample existing S3 event notification:
```
    "Events": [
        "s3:ObjectCreated:*"
    ],
    "Filter": {
        "Key": {
            "FilterRules": [
                {
                    "Name": "Prefix",
                    "Value": "bar/"
                },
                {
                    "Name": "Suffix",
                    "Value": "foo/"
                }
            ]
        }
    },
    "Id": "",
    "LambdaFunctionArn": "arn:aws:lambda:<aws-region>:<aws-account-id>:function:<FunctionName>"
}
```

Note: Even though the content of the above jsons are the same, the order of the filter rules (prefix and suffix) are different. 
Due to this, the hash evaluated will also be different. So, it is unable to identify that the existing configuration was also added by the stack itself.
This ends up in a configuration which includes the duplicates (existing configurations on s3 + incoming event configuration from Cloudformation stack)
resulting in below error:
```
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.
```
This can be workaround by changing the order of filters in the cdk synthesized stack template, by passing the prefix first and then suffix within the filter rules array.

### CDK CLI Version

2.152.0

### Node.js Version

v20.16.0

### OS

Linux

### Language

Python

**Comment by pahud** [comment]
Yes this is reproducible.

```py
class IssueTriagePyStack(Stack):
  def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
    super().__init__(scope, construct_id, **kwargs)
  
    my_lambda = _lambda.Function(
          self, 'HelloHandler',
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset('lambda'),
            handler='hello.handler',
    )    
  
    bucket = s3.Bucket.from_bucket_name(self, "Bucket", "my-existing-bucket-name")
    notification = s3_notify.LambdaDestination(my_lambda)

    notificationfilter1 = s3.NotificationKeyFilter(prefix="foo/", suffix="bar/")
    bucket.add_event_notification(s3.EventType.OBJECT_CREATED, notification, notificationfilter1)

    notificationfilter2 = s3.NotificationKeyFilter(prefix="fo1/",suffix="ba1/",)
    bucket.add_event_notification(s3.EventType.OBJECT_CREATED, notification, notificationfilter2)
```

On `cdk deploy` to update the stack:


```
issue-triage: creating CloudFormation changeset...
10:35:14 PM | UPDATE_FAILED        | Custom::S3BucketNotifications | BucketNotifications8F2E257D
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificati
onConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the sa
me event type.. See the details in CloudWatch Log Stream: 2024/09/04/[$LATEST]ff56425363ce4d8db0b594f6d560320a (RequestId: 9b4cb9c7-2141-4e7b-ba02-b4a880
70d580)

10:35:18 PM | UPDATE_FAILED        | Custom::S3BucketNotifications | BucketNotifications8F2E257D
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificati
onConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the sa
me event type.. See the details in CloudWatch Log Stream: 2024/09/04/[$LATEST]ff56425363ce4d8db0b594f6d560320a (RequestId: dc73fb2a-5abc-48d6-b0dd-da0625
2e55bc)
```

As I can't figure out any workaround. Making this a p1 bug.

**Comment by stefanopallicca-imagicle** [comment]
Facing the same issue: I previously defined two notifications, one with
prefix: person/upload
suffix: .csv

another with
prefix: car/upload
suffix: .csv

This configuration worked with 2.146.0, results in same issue by simply updating cdk to 2.155.0

**Comment by satanupa** [comment]
One workaround I tested was to force the order of filters in the synthesized  stack template, by passing the prefix first and then suffix within the filter rules array.

```
class IssueTriagePyStack(Stack):
  def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
    super().__init__(scope, construct_id, **kwargs)
  
    my_lambda = _lambda.Function(
          self, 'HelloHandler',
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset('lambda'),
            handler='hello.handler',
    )    
    
#input filter rules
    filterRules = [{ "prefix": "foo/", "suffix": "bar/"}, { "prefix": "foo1/", "suffix": "bar1/"},{ "prefix": "foo2/", "suffix": "bar2/"}]

    bucket = s3.Bucket.from_bucket_name(self, "Bucket", "my-existing-bucket-name")
    notification = s3_notify.LambdaDestination(my_lambda)

    for filter_item in filterRules:
            print(filter_item["prefix"], filter_item["suffix"])
            notificationfilter = s3.NotificationKeyFilter(prefix=filter_item["prefix"],suffix=filter_item["suffix"])
            bucket.add_event_notification(s3.EventType.OBJECT_CREATED, notification, notificationfilter)
   
#Additional code for getting the custom resource node to override the filter rules property.
        cfn_resource = bucket.node.find_child('Notifications').node.default_child

# Creating formatted_filter_rules to override the "FilterRules" property. 
# Note we are just changing the order of the prefix and suffix within filter rules, there will not be any change in data.

        for index, filter_item in enumerate(filterRules):
                formatted_filter_rules = {
                    "FilterRules": [
                        {
                            "Name": "prefix",
                            "Value": filter_item["prefix"]
                        },
                        {
                            "Name": "suffix",
                            "Value": filter_item["suffix"]
                        }
                    ]
                }
                property_to_override = "NotificationConfiguration.LambdaFunctionConfigurations."+ str(index) + ".Filter.Key"
                cfn_resource.add_property_override(property_to_override, formatted_filter_rules)
````

Final synthesized template:
```
NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: prefix
                    Value: foo/
                  - Name: suffix
                    Value: bar/
            LambdaFunctionArn:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: prefix
                    Value: foo1/
                  - Name: suffix
                    Value: bar1/
            LambdaFunctionArn:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: prefix
                    Value: foo2/
                  - Name: suffix
                    Value: bar2/
            LambdaFunctionArn:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
```

**Comment by satanupa** [comment]
One workaround I tested was to force the order of filters in the synthesized stack template, by passing the prefix first and then suffix within the filter rules array.

```
class IssueTriagePyStack(Stack):
  def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
    super().__init__(scope, construct_id, **kwargs)
  
    my_lambda = _lambda.Function(
          self, 'HelloHandler',
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset('lambda'),
            handler='hello.handler',
    )    
    
#input filter rules
    filterRules = [{ "prefix": "foo/", "suffix": "bar/"}, { "prefix": "foo1/", "suffix": "bar1/"},{ "prefix": "foo2/", "suffix": "bar2/"}]

    bucket = s3.Bucket.from_bucket_name(self, "Bucket", "my-existing-bucket-name")
    notification = s3_notify.LambdaDestination(my_lambda)

    for filter_item in filterRules:
            print(filter_item["prefix"], filter_item["suffix"])
            notificationfilter = s3.NotificationKeyFilter(prefix=filter_item["prefix"],suffix=filter_item["suffix"])
            bucket.add_event_notification(s3.EventType.OBJECT_CREATED, notification, notificationfilter)
   
#Additional code for getting the custom resource node to override the filter rules property.
        cfn_resource = bucket.node.find_child('Notifications').node.default_child

# Creating formatted_filter_rules to override the "FilterRules" property. 
# Note we are just changing the order of the prefix and suffix within filter rules, there will not be any change in data.

        for index, filter_item in enumerate(filterRules):
                formatted_filter_rules = {
                    "FilterRules": [
                        {
                            "Name": "prefix",
                            "Value": filter_item["prefix"]
                        },
                        {
                            "Name": "suffix",
                            "Value": filter_item["suffix"]
                        }
                    ]
                }
                property_to_override = "NotificationConfiguration.LambdaFunctionConfigurations."+ str(index) + ".Filter.Key"
                cfn_resource.add_property_override(property_to_override, formatted_filter_rules)
```

Final synthesized template:
```
NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: prefix
                    Value: foo/
                  - Name: suffix
                    Value: bar/
            LambdaFunctionArn:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: prefix
                    Value: foo1/
                  - Name: suffix
                    Value: bar1/
            LambdaFunctionArn:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: prefix
                    Value: foo2/
                  - Name: suffix
                    Value: bar2/
            LambdaFunctionArn:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
```
