### ISSUE TITLE
aws-lambda: FilterRule.null() returns empty array

### ISSUE THREAD

**Issue by ujjwol05** [aws/aws-cdk#31458]
### Describe the bug

According to the documentation [here](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-syntax), the FilterPattern should be [null]. However, the function FilterRule.null() currently returns an empty array [] instead.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The filter pattern for null should be
`
{
  "eventName": [
    "INSERT"
  ],
  "dynamodb": {
    "NewImage": {
      "test": {
        "S": [ null ]
      }
    }
  }
}
`

### Current Behavior

The filter pattern currently being returned is 
`
{
  "eventName": [
    "INSERT"
  ],
  "dynamodb": {
    "NewImage": {
      "test": {
        "S": []
      }
    }
  }
}
`

### Reproduction Steps

Construct an EventSourceMapping
```
new lambda.EventSourceMapping(
            this,
            `${stackPrefix}-lambda-event-source-mapping`,
            {
                startingPosition: StartingPosition.TRIM_HORIZON,
                target:XXXX,
                eventSourceArn: XXXX,
                reportBatchItemFailures: true,
                filters: [
                    lambda.FilterCriteria.filter({
                        eventName: lambda.FilterRule.isEqual('INSERT'),
                        dynamodb: {
                            NewImage: {
                                test: { S: lambda.FilterRule.exists() },
                            },
                        },
                    }),
                ],
            }
        );
```

### CDK CLI Version

2.155.0

### Node.js Version

v20.11.0

### OS

Sonoma

### Language

TypeScript

**Comment by pahud** [comment]
Yes

```ts
    new lambda.EventSourceMapping(
      this,
      'demo',
      {
          startingPosition: lambda.StartingPosition.TRIM_HORIZON,
          target: func,
          eventSourceArn: 'mock',
          reportBatchItemFailures: true,
          filters: [
              lambda.FilterCriteria.filter({
                  eventName: lambda.FilterRule.isEqual('INSERT'),
                  dynamodb: {
                      NewImage: {
                          test: { S: lambda.FilterRule.null() },
                      },
                  },
              }),
          ],
      }
  );
```

would synth to 
```yaml
 demo9A46DC86:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: mock
      FilterCriteria:
        Filters:
          - Pattern: '{"eventName":["INSERT"],"dynamodb":{"NewImage":{"test":{"S":[]}}}}'
      FunctionName:
        Ref: MyFunction3BAA72D1
      FunctionResponseTypes:
        - ReportBatchItemFailures
      StartingPosition: TRIM_HORIZON
```

which appears to be incorrect per [doc](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-syntax).
