### ISSUE TITLE
aws_logs: add NINE_MONTH retention

### ISSUE THREAD

**Issue by mrgum** [aws/aws-cdk#31573]
### Describe the feature

I'd like to add NINE_MONTHS to the RetentionDays Enum

### Use Case

I'm often asked to keep logs for NINE_MONTHS and this feature would make that clearer

### Proposed Solution

add NINE_MONTHS = 270,
to
./packages/@aws-cdk/aws-logs/lib/log-group.ts

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.159.1 (build c66f4e3)

### Environment details (OS name and version, etc.)

macos 15.0

**Comment by ashishdhingra** [comment]
@mrgum Good morning. Thanks for opening the feature request. Upon looking at the issue, looks like values supported by [RetentionDays](https://github.com/aws/aws-cdk/blob/4b00ffeb86b3ebb9a0190c2842bd36ebb4043f52/packages/aws-cdk-lib/aws-logs/lib/log-group.ts#L351) enum conform to the values supported by CloudFormation resource [AWS::Logs::LogGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html) where it lists allowed values for `RetentionInDays` as `1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1096, 1827, 2192, 2557, 2922, 3288, and 3653`. In CDK construct, it might appear to support [RetentionDays.INFINITE](https://github.com/aws/aws-cdk/blob/4b00ffeb86b3ebb9a0190c2842bd36ebb4043f52/packages/aws-cdk-lib/aws-logs/lib/log-group.ts#L465), but setting this value resets it to `undefined` value [here](https://github.com/aws/aws-cdk/blob/4b00ffeb86b3ebb9a0190c2842bd36ebb4043f52/packages/aws-cdk-lib/aws-logs/lib/log-group.ts#L612C61-L612C83) which is passed to [CfnLogGroup](https://github.com/aws/aws-cdk/blob/4b00ffeb86b3ebb9a0190c2842bd36ebb4043f52/packages/aws-cdk-lib/aws-logs/lib/log-group.ts#L629) constructor.

For testing purposes, I tried setting `RetentionDays` to `270` via escape hatch:
```TypeScript
import * as cdk from 'aws-cdk-lib';
import * as logs from 'aws-cdk-lib/aws-logs';

export class CdktestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const logGroup = new logs.LogGroup(this, 'TestLogGroup', {
      logGroupName: 'TestLogGroup',
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      retention: logs.RetentionDays.INFINITE
    });

    const cfnLogGroup = logGroup.node.defaultChild as logs.CfnLogGroup;
    cfnLogGroup.retentionInDays = 270;
  }
}
```
This synthesized into below CloudFormation template:
```YAML
Resources:
  TestLogGroup4EEF7AD4:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: TestLogGroup
      RetentionInDays: 270
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdktestStack/TestLogGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzQz0DNQTCwv1k1OydbNyUzSqw4uSUzO1gEKxefkpxfrVfvkp7sX5ZcW6Din5cHYtSBOUGpxfmlRcmqtTl5+SqpeVrF+mZGRnjnQvKzizEzdotK8kszcVL0gCA0AjNZMsmwAAAA=
    Metadata:
      aws:cdk:path: CdktestStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
```
Running `cdk deploy` resulted in below error from CloudFormation:
```
9:20:08 AM | CREATE_FAILED        | AWS::Logs::LogGroup | TestLogGroup4EEF7AD4
Resource handler returned message: "Model validation failed (#/RetentionInDays: #: only 1 subschema matches out of 2)
#/RetentionInDays: failed validation constraint for keyword [enum] (#/RetentionInDays)" (RequestToken: cdf4251e-b6e7-fa1
a-a6c7-775f44c86029, HandlerErrorCode: InvalidRequest)


 ❌  CdktestStack failed: Error: The stack named CdktestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Model validation failed (#/RetentionInDays: #: only 1 subschema matches out of 2)
#/RetentionInDays: failed validation constraint for keyword [enum] (#/RetentionInDays)" (RequestToken: cdf4251e-b6e7-fa1a-a6c7-775f44c86029, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:468:10828)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:471:200792)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:471:182091

 ❌ Deployment failed: Error: The stack named CdktestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Model validation failed (#/RetentionInDays: #: only 1 subschema matches out of 2)
#/RetentionInDays: failed validation constraint for keyword [enum] (#/RetentionInDays)" (RequestToken: cdf4251e-b6e7-fa1a-a6c7-775f44c86029, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:468:10828)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:471:200792)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:471:182091

The stack named CdktestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Model validation failed (#/RetentionInDays: #: only 1 subschema matches out of 2)
#/RetentionInDays: failed validation constraint for keyword [enum] (#/RetentionInDays)" (RequestToken: cdf4251e-b6e7-fa1a-a6c7-775f44c86029, HandlerErrorCode: InvalidRequest)
```

Hence, `NINE_MONTHS = 270` in `RetentionDays` could not be supported since the allowed values are limited by CloudFormation.

Thanks,
Ashish
