### ISSUE TITLE
aws_docdb - CfnDBInstance

### ISSUE THREAD

**Issue by bsnyder74** [aws/aws-cdk#31722]
### Describe the bug

Documented Construct Property `caCertificateIdentifier` does not exist for the CfnDBInstance & CfnDBInstanceProps in the aws-cdk-lib\aws_docdb type.  CDK version 2.161.1 and 2.162.0 tested, likely other versions will see this too.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_docdb.CfnDBInstance.html#construct-props

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Synth renders a template with a valid resource using the documented properties without error.

### Current Behavior

Error:
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
          ^
TSError: ⨯ Unable to compile TypeScript:
infrastructure/lib/docdb-cluster.ts:88:7 - error TS2345: Argument of type '{ dbInstanceIdentifier: string; dbInstanceClass: string; availabilityZone: string; enablePerformanceInsights: false; preferredMaintenanceWindow: string; autoMinorVersionUpgrade: true; dbClusterIdentifier: string; caCertificateIdentifier: string; certificateRotationRestart: boolean; }' is not assignable to parameter of type 'CfnDBInstanceProps'.
 Object literal may only specify known properties, and 'caCertificateIdentifier' does not exist in type 'CfnDBInstanceProps'.

caCertificateIdentifier: 'rds-ca-rsa4096-g1'

### Reproduction Steps

Steps to reproduce:

- Add a `caCertificateIdentifier` property to the CfnDBInstance construct to the type, as documented.
- Run cdk synth (or any cdk command that will validate the code).

### CDK CLI Version

2.161.1

### Node.js Version

v18.18.0

### OS

MacOS 15.0.1

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@bsnyder74 Good morning. Somehow, I'm unable to reproduce the issue using CDK version `2.161.1 (build 0a606c9)`. Below code (as an example):
```TypeScript
import * as cdk from 'aws-cdk-lib';
import * as docdb from 'aws-cdk-lib/aws-docdb';

export class CdktestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const docDBInstance = new docdb.CfnDBInstance(this, 'MyDocDB', {
      dbInstanceClass: 'test',
      dbClusterIdentifier: 'test',
      caCertificateIdentifier: 'test'
    });
  }
}
```
synthesizes successfully to CFN template:
```YAML
Resources:
  MyDocDB:
    Type: AWS::DocDB::DBInstance
    Properties:
      CACertificateIdentifier: test
      DBClusterIdentifier: test
      DBInstanceClass: test
    Metadata:
      aws:cdk:path: CdktestStack/MyDocDB
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/yXFvQ5AMBAA4Gext0dFxIzFygNIXU9SP9fEFYN4d4Nv+XIwpQGT2Fs0ulVvfoJniBZXZW8ZXUA3QTNzW3cs0TKSambuScJ5IL2KgyNYJL1MBXkGRbKI9/o4OfqdoP//APYAJH1lAAAA
    Metadata:
      aws:cdk:path: CdktestStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
```

I'm unsure what is missing at your end. Could you please check the `aws-cdk-lib` version in your `package.json`?

Thanks,
Ashish
