### ISSUE TITLE
Message from CloudFormation about DNS zone mapping not using `lazy: true`.

### ISSUE THREAD

**Issue by nomike** [aws/aws-cdk#31918]
### Describe the bug

Using this [python class](https://github.com/user-attachments/files/17543370/route53.py.gz) and these 
[parameters](https://github.com/user-attachments/files/17543446/parameters.json.gz) results in this 
[synthesized CloudFormation script](https://github.com/user-attachments/files/17543479/use1-pr-customer-api-public-route53-aliasrecord.yaml.gz).

The noteworthy parts are:

```yaml
        HostedZoneId:
          Fn::FindInMap:
            - MappingCopyAWSCloudFrontPartitionHostedZoneIdMapc88b0307188360f6083c72a2a857503f8678fb10e7
            - Ref: AWS::Partition
            - zoneId
```

and

```yaml
Mappings:
  MappingCopyAWSCloudFrontPartitionHostedZoneIdMapc88b0307188360f6083c72a2a857503f8678fb10e7:
    aws:
      zoneId: Z2FDTNDATAQYW2
    aws-cn:
      zoneId: Z3RFFRIM2A3IF5
```

According to this [CloudFormation user guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-aliastarget.html), alias records pointing to CloudFront distributions need to use `Z2FDTNDATAQYW2` as a hosted zone ID. From the variable naming I assume the mapping is included for a china specific workaround.

The problem with this is that it leads to the following message from CloudFormation:

```plaintext
[Info at /use1-pr-customer-api-public-route53-aliasrecord/MappingCopy-AWSCloudFrontPartitionHostedZoneIdMap-c88b0307188360f6083c72a2a857503f8678fb10e7] Consider making this CfnMapping a lazy mapping by providing `lazy: true`: either no findInMap was called or every findInMap could be immediately resolved without using Fn::FindInMap
```

Normally it would be clear what to do, but as the affected code is auto-generated and not written by me, it is not possible for me to provide that flag.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I would either expect CDK to provide `lazy: true` or at least the message not to be shown. As there is nothing I can do to get rid of it the message is just spam and doesn't help me at all.

### Current Behavior

CloudFormation shows the message I quoted above and there is nothing that can be done about it.

### Reproduction Steps

Create two stacks in different regions. Once defining a CloudFront distribution and the other defining a route53 alias record pointing to that distribution.

### Possible Solution

It should be evaluated whether providing the `lazy: true` option would have any negative side effects and if not, it should just be added.

If it's not possible to add this, a more sophisticated approach might be needed.

### CDK CLI Version

2.164.1 (build bb9275c)

### Node.js Version

v20.5.1

### OS

Ubuntu 24.04 LTS

### Language

Python

### Language Version

Does not apply
