### ISSUE TITLE
AWS::ECR::Repository LifecyclePolicy:  extraneous key [lifecyclePolicyText] is not permitted

### ISSUE THREAD

**Issue by iMilad** [aws/aws-cdk#32001]
### Describe the bug

CloudFormation template, generated by CDK contains camel case property (`lifecyclePolicyText`) which is not permitted! base on the Documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-repository-lifecyclepolicy.html it has to be capitalized. 

Error log report:
> Resource template validation failed for resource EcrRepository as the template has invalid properties. Please refer to the resource documentation to fix the template. Properties validation failed for resource EcrRepository with message: #/LifecyclePolicy: extraneous key [lifecyclePolicyText] is not permitted

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.165.0

### Expected Behavior

CloudFormation template validation should pass!

### Current Behavior

Resource template validation failed for resource EcrRepository as the template has invalid properties. Please refer to the resource documentation to fix the template. Properties validation failed for resource EcrRepository with message: #/LifecyclePolicy: extraneous key [lifecyclePolicyText] is not permitted

### Reproduction Steps

```
CfnRepository(
    self,
    "construct-id",
    image_tag_mutability=immutable.value_as_string,
    image_scanning_configuration=CfnRepository.ImageScanningConfigurationProperty(
        scan_on_push=True
    ),
    empty_on_delete=True,
    lifecycle_policy=Fn.condition_if(
        delete_untagged_images_condition.logical_id,
        CfnRepository.LifecyclePolicyProperty(
            lifecycle_policy_text=Fn.join(
                "",
                [
                    '{"rules":[{"rulePriority":1,"description": "delete untagged images '
                    'older than X days since push","selection":{"tagStatus":"untagged",'
                    '"countType":"sinceImagePushed","countNumber":',
                    delete_untagged_images.value_as_string,
                    ',"countUnit":"days"},"action":{"type":"expire"}}]}"',
                ],
            ),
        ),
    ),
)
```

### Possible Solution

rename `lifecyclePolicyText` to `LifecyclePolicyText`

### CDK CLI Version

2.165.0

### Node.js Version

v18.19.1

### OS

Ubuntu 24.04.1

### Language

Python

### Language Version

3.12.3

**Comment by pahud** [comment]
Yes I noticed that.

when the code is:

```py
        ecr.CfnRepository(
            self,
            "construct-id",
            lifecycle_policy=ecr.CfnRepository.LifecyclePolicyProperty(
              lifecycle_policy_text="lifecyclePolicyText",
            )
```

The synth is good:

```yaml
Resources:
  constructid:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: lifecyclePolicyText
```

But if the code

```py
        ecr.CfnRepository(
            self,
            "construct-id",
            lifecycle_policy=Fn.condition_if(
                always_true,
                ecr.CfnRepository.LifecyclePolicyProperty(
                    lifecycle_policy_text=Fn.join(
                        "",
                        ['foo', 'bar'],
                    ),
                ),
                None,
            ),
        )
```

synth

```yaml
 constructid:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        Fn::If:
          - alwaystruecond
          - lifecyclePolicyText: foobar  <------ Incorrect here
```

The workaround is

```py
ecr.CfnRepository(
            self,
            "construct-id",
            lifecycle_policy=Fn.condition_if(
                always_true,
                { 
                  "LifecyclePolicyText": Fn.join("", ['foo', 'bar'])
                },
                None,
            ),
        )
```

which synthesizes to

```yaml
Resources:
  constructid:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        Fn::If:
          - alwaystruecond
          - LifecyclePolicyText: foobar
```


I will bring this up to the team for further inputs.
