### ISSUE TITLE
aws-lambda: Function.grantInvoke() not applying permissions for older versions of lambda function

### ISSUE THREAD

**Issue by michaellasmanis** [aws/aws-cdk#32455]
### Describe the bug

when using Function.grantInvoke(), permission for function:Invoke is applied to the unqualified function arn but not to any of the older versions. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Per the documentation here: https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/services/lambda/package-summary.html#resource-based-policies-heading

and the GitHub PR here: https://github.com/aws/aws-cdk/pull/19318

I would expect that both the unqualified [FunctionArn] and [Function.Arn].* to have the permissions applied.

### Current Behavior

Invoke permission only seem to be applied to the unqualified function arn.

cdk synth produces the following snippet:

```
  HelloWorldFunctionInvokeFcyXBRX02EWa52GlFECQiCzDt0fdRUDi4mo4foC5aU2283F0E1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloWorldFunctionB2AB6E79
          - Arn
      Principal: apigateway.amazonaws.com

```

which just enabled the unqualified ARN

### Reproduction Steps

if you have a stack containing such:

```
    // Define the Lambda function resource
    const myFunction = new lambda.Function(this, "HelloWorldFunction", {
      runtime: lambda.Runtime.NODEJS_20_X, // Provide any supported Node.js runtime
      handler: "index.handler",
      code: lambda.Code.fromInline(`
        exports.handler = async function(event) {
          return {
            statusCode: 200,
            body: JSON.stringify('Hello World on ` + new Date().toLocaleString() + `!'),
          };
        };
      `),
    });

    const myVersion = new lambda.Version(this, "HelloWorldFunction" + new Date().getTime()/1000,
    {
      lambda: myFunction,
      removalPolicy: cdk.RemovalPolicy.RETAIN_ON_UPDATE_OR_DELETE
    });

    myFunction.grantInvoke(new iam.ServicePrincipal('apigateway.amazonaws.com'));
```

you will notice after the second (or subsequent) deploy that the permissions from the non-$LATEST versions are removed as part of the cdk deploy.
 

### CDK CLI Version

2.172.0

### Node.js Version

v23.3.0

### OS

macOS

### Language

Java

### Language Version

java 17
