### ISSUE TITLE
EC2::VPCEndpoint: 2.174.0 adds unsupported Tags

### ISSUE THREAD

**Issue by LArkema** [aws/aws-cdk#32782]
### Describe the bug

Starting in version 2.174.0, the cdk.Tags.of(stack) function adds tags to VPC Endpoints that are rejected during deployment and cause deployments to fail.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.173.4

### Expected Behavior

Context: Stack A with Gateway Endpoint:

```
ec2.CfnVPCEndpoint(self, 'Stack A S3 Gateway Endpoint',
  service_name='com.amazonaws.'+self.region+'.s3',
  vpc_endpoint_type='Gateway',
  vpc_id=self.vpc.vpc_id,
  route_table_ids=[self.route_table.attr_route_table_id]
) 
```

And an app that applies a dictionary of tags to each stack in the app:

```
for stack in constant_stacks:
  for key,value in tags.items():
      cdk.Tags.of(stack).add(key=key,value=value,apply_to_launched_instances=True)
```

Should synthesize to a CloudFormation object without Tags and deploy successfully:

`cdk synth StackA` > 
```
StackAS3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint 
    Properties:
      RouteTableIds:
        - Fn::GetAtt:
            - StackASubnetsRouteTable
            - RouteTableId
      ServiceName: com.amazonaws.us-gov-west-1.s3
      VpcEndpointType: Gateway
      VpcId:
        Ref: StackAVPCRef
    Metadata:
      aws:cdk:path: StackA/ S3 Gateway Endpoint
NextComponent: ...
```

`cdk deploy StackA` > 
```
✨  Synthesis time: Xs

StackA: deploying... [1/1]

 ✅  StackA (no changes)

✨  Deployment time: Ys
```

### Current Behavior

However, starting in 2.174.0, Tags are added during synthesis which causes deployments to break (even though Tags are ostensibly supported in the [CFN L1 Construct](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-tags))

`cdk synth StackA` >
```
StackAS3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint 
    Properties:
      RouteTableIds:
        - Fn::GetAtt:
            - StackASubnetsRouteTable
            - RouteTableId
      ServiceName: com.amazonaws.us-gov-west-1.s3
      Tags:
        - Key: <key>
          Value: <value>
        - Key: <key>
          Value: <value>
      VpcEndpointType: Gateway
      VpcId:
        Ref: StackAVPCRef
    Metadata:
      aws:cdk:path: StackA/ S3 Gateway Endpoint
```

`cdk deploy StackA` >
```
✨  Synthesis time: Xs

StackA: deploying... [1/1]
StackA: creating CloudFormation changeset...
StackA | 0/4 | 11:33:10 AM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack            | StackA User Initiated
StackA | 0/4 | 11:33:15 AM | UPDATE_FAILED        | AWS::EC2::VPCEndpoint                 | Stack A S3 Gateway Endpoint (StackAS3GatewayEndpoint) Encountered unsupported property Tags
...
```

However, diffing does not show the addition of new Tags:
`cdk diff StackA` >
```
There were no differences
✨  Number of stacks with differences: 0
```

### Reproduction Steps

Stack A with Gateway Endpoint:

```
ec2.CfnVPCEndpoint(self, 'Stack A S3 Gateway Endpoint',
  service_name='com.amazonaws.'+self.region+'.s3',
  vpc_endpoint_type='Gateway',
  vpc_id=self.vpc.vpc_id,
  route_table_ids=[self.route_table.attr_route_table_id]
) 
```

And an app that applies a dictionary of tags to each stack in the app:

```
for stack in constant_stacks:
  for key,value in tags.items():
      cdk.Tags.of(stack).add(key=key,value=value,apply_to_launched_instances=True)
```

### Possible Solution

Looking at the diff between 2.173.4 and 2.174.0, nothing stood out as the obvious source of the bug. Ideally, the tags would be applied to the endpoints and not be rejected during deployment.

### CDK CLI Version

2.174.1

### Node.js Version

20.11.1

### OS

MacOS

### Language

Python

### Language Version

Python 3.9.6

**Comment by pahud** [comment]
Taking a look. Off the top of my head 2.174.0 might have CFN spec update that add Tags props to `AWS::EC2::VPCEndpoint` which could still unsupported in your region(`us-gov-west-1`?)

**Comment by pahud** [comment]
OK I noticed https://github.com/aws/aws-cdk/pull/32582 introduced the change:

```
│    └[~] resource AWS::EC2::VPCEndpoint
│      ├  - tagInformation: undefined
│      │  + tagInformation: {"tagPropertyName":"Tags","variant":"standard"}
```
which is supported in CFN doc
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-tags

But I guess it's not supported yet in your deploying region and that could be the cause of your error. You probably want to remove the `cdk.Tags.of(stack).add(key=key,value=value,apply_to_launched_instances=True)` statement?

Let me know if this works for you and we probably need to figure out a better design to avoid this discrepancy. I'll bring this up to the team for visibility.

**Comment by ashishdhingra** [comment]
@LArkema Good morning. Thanks for opening the issue. I'm unsure what's happening at your end, however, using similar code below (CDK CLI/Lib version `2.174.0`), the issue is not reproducible:
**TypeScript**
```TypeScript:
import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

export class CdktestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);


    const vpc = ec2.Vpc.fromLookup(this, 'MyVpc', { isDefault: true });

    new ec2.CfnVPCEndpoint(this, 'Stack A S3 Gateway Endpoint 1', {
      serviceName: 'com.amazonaws.'+this.region+'.s3',
      vpcEndpointType: 'Gateway',
      vpcId: vpc.vpcId
    });
  
    vpc.addGatewayEndpoint('Stack A S3 Gateway Endpoint 2', {
      service: ec2.GatewayVpcEndpointAwsService.S3
    });
  }
}

const app = new cdk.App();

const cdkteststack = new CdktestStack(app, 'CdktestStack', {
  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },
});

cdk.Tags.of(cdkteststack).add('testkey', 'testvalue', { applyToLaunchedInstances: true });

app.synth();
```

**Python**
```Python
from aws_cdk import (
    # Duration,
    Stack,
    aws_ec2 as ec2,
)
from constructs import Construct

class CdktestpythonStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        vpc = ec2.Vpc.from_lookup(
            self, 
            'MyVpc', 
            is_default=True
        )
        
        ec2.CfnVPCEndpoint(
            self, 
            'Stack A S3 Gateway Endpoint',
            service_name='com.amazonaws.'+self.region+'.s3',
            vpc_endpoint_type='Gateway',
            vpc_id=vpc.vpc_id
        )
        
        vpc.add_gateway_endpoint(
            'Stack A S3 Gateway Endpoint 2',
            service=ec2.GatewayVpcEndpointAwsService.S3
        )


app = cdk.App()
cdkteststack = CdktestpythonStack(app, "CdktestpythonStack",
    env=cdk.Environment(account=os.getenv('CDK_DEFAULT_ACCOUNT'), region=os.getenv('CDK_DEFAULT_REGION')),
    )

cdk.Tags.of(cdkteststack).add('testkey', 'testvalue', apply_to_launched_instances=True)

app.synth()
```
This synthesizes successfully to below CFN template:
```YML
Resources:
  MyVpcStackAS3GatewayEndpoint2E769D7E4:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - rtb-0034d376967729a9c
      ServiceName:
        Fn::Join:
          - ""
          - - com.amazonaws.
            - Ref: AWS::Region
            - .s3
      Tags:
        - Key: testkey
          Value: testvalue
      VpcEndpointType: Gateway
      VpcId: vpc-0bcd157c9276f648b
    Metadata:
      aws:cdk:path: CdktestStack/MyVpc/Stack A S3 Gateway Endpoint 2/Resource
  StackAS3GatewayEndpoint1:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-2.s3
      Tags:
        - Key: testkey
          Value: testvalue
      VpcEndpointType: Gateway
      VpcId: vpc-0bcd157c9276f648b
    Metadata:
      aws:cdk:path: CdktestStack/Stack A S3 Gateway Endpoint 1
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzQ30TNQTCwv1k1OydbNyUzSqw4uSUzO1glKLc4vLUpO1UksL45PTTbSq3ZPLEktT6wMK0h2zUspyM/MK9FxTssLC3CGcWtBfJi+Wp28/JRUvaxi/TJDCz0jAz0TxazizEzdotK8kszcVL0gCA0AEQNmQ4IAAAA=
    Metadata:
      aws:cdk:path: CdktestStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
```

Kindly note that I tested this in non-Gov-Cloud region.

Please see if you are using the same CDK CLI and Lib versions.

Thanks,
Ashish
