### ISSUE TITLE
CLI: does not support cross-account calls

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#3322]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Use case: someone using CodeBuild in one account to "cdk deploy" to a stack in a different account.

Even though the account may have permission to touch the stack in another account, we do a check to see if the "current credentials's account" and the target account are the same, and we will fail that use case.

* **What is the expected behavior (or behavior of feature suggested)?**

Not sure. We should think about this.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Already described.

**Comment by floydding** [comment]
@rix0rrr Thanks for creating the issue. I got this to work assume-role'ing. here is part of my build spec for the reference

NOTE: I used `jq` for extracting from json blob but `grep` works as well
```
pre_build:
    commands:
    - assumed_role_credentials=$(aws sts assume-role --role-arn *** --role-session-name ***)

    - aws_access_key_id=$(echo $assumed_role_credentials | jq .Credentials.AccessKeyId | tr -d '"')
    - aws_secret_access_key=$(echo $assumed_role_credentials | jq .Credentials.SecretAccessKey | tr -d '"')
    - aws_session_token=$(echo $assumed_role_credentials | jq .Credentials.SessionToken | tr -d '"')

    - export AWS_ACCESS_KEY_ID=$aws_access_key_id
    - export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
    - export AWS_SESSION_TOKEN=$aws_session_token

    - npm run build
    - npm run cdk synth ${STACK_NAME}
  build:
    commands:
    - npm run cdk -- -v deploy ${STACK_NAME}
```
