### ISSUE TITLE
(eks): EKS ALB Controller cannot provision ALB with OIDC configuration

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#33223]
### Describe the bug

AlbController cannot provision ALB with OIDC configuration: `User "system:serviceaccount:kube-system:aws-load-balancer-controller" cannot get resource "secrets" in API group`.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

ALB Controller can be used to provision ALB's

### Current Behavior

```json
    "log": "{\"level\":\"error\",\"ts\":\"2025-01-29T08:26:18Z\",\"msg\":\"Reconciler error\",\"controller\":\"ingress\",\"object\":{\"name\":\"app-name.domain-name-ingress\",\"namespace\":\"namespace-name\"},\"namespace\":\"namespace-name\",\"name\":\"app-name.domain-name-ingress\",\"reconcileID\":\"cba15a83-4c7c-4c6a-8827-010514fc27da\",\"error\":\"ingress: namespace-name/app-name.domain-name-ingress: secrets \\\"golinks-okta-secret\\\" is forbidden: User \\\"system:serviceaccount:kube-system:aws-load-balancer-controller\\\" cannot get resource \\\"secrets\\\" in API group \\\"\\\" in the namespace \\\"namespace-name\\\"\"}",
```

### Reproduction Steps

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://sso.supercell.com","authorizationEndpoint":"https://okta/oauth2/v1/authorize","tokenEndpoint":"https://okta/oauth2/v1/token","userInfoEndpoint":"https://okta/oauth2/v1/userinfo","secretName":"app-name-okta-secret"}'
    

```

### Possible Solution

Please add the required permissions for it to work :) Is there any workaround for this?

### CDK CLI Version

2.177.0 (build b396961)

### Node.js Version

v22.13.0

### OS

Mac

### Language

TypeScript

**Comment by pahud** [comment]
Hi @markusl 

Can you share your minimal CDK code? Looks like we'll need to grant secret read privileges and I am not sure if aws-eks L2 should handle that. Having the visibility of your CDK code snippet would help.

**Comment by pahud** [comment]
Thank you. 

https://github.com/aws/aws-cdk/blob/6fa1d059140e32dbe48a4251fb0ce54eea12c463/packages/aws-cdk-lib/aws-eks/lib/alb-controller.ts#L315-L330

Sounds like we need to account the serviceAccount to access that secret but I am not pretty sure what is the best action we need to do from CDK. Can you find any document about how to install the alb controller with OIDC support without using CDK? I guess we need to first find out what's the correct steps before we could figure out what CDK can do here.

**Comment by markusl** [comment]
@pahud it turns something like this can be used as a workaround:

```
# secrets-access.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: app-namespace
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-access-binding
  namespace: app-namespace
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller
    namespace: kube-system
roleRef:
  kind: Role
  name: secrets-access
  apiGroup: rbac.authorization.k8s.io
```

If it turns out to be difficult to implement, at least the limitation should be documented in AlbController, and preferably a convenience method could be added to easily attach the required resources if user is using ALB + OIDC.

Thank you!
