### ISSUE TITLE
aws_stepfunctions: catcher output property not generated

### ISSUE THREAD

**Issue by guillaume-alliander** [aws/aws-cdk#33374]
### Describe the bug

When generating a state with cdk, the `outputs` of a catcher, although syntactically present in `aws_cdk`, are not generated. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

In the template created by `synth`,  have the `output` field present. 

### Current Behavior

This is the subset of the yaml template printed out after `synth`:

```yaml
  StatemachineDEF8448E:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Start_job","States":{"Start_job":{"QueryLanguage":"JSONata","End":true,"Catch":[{"ErrorEquals":["States.ALL"],"Next":"boom"}],"Type":"Task","Arguments":{"JobName":"{% $states.input %}","NotificationProperty":null},"Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::glue:startJobRun"},"boom":{"Type":"Fail","QueryLanguage":"JSONata"}},"QueryLanguage":"JSONPath"}
```

### Reproduction Steps

```python
import aws_cdk as core
from aws_cdk import aws_stepfunctions_tasks as tasks
from aws_cdk import aws_stepfunctions as sfn


class StateMachine(core.Stack):
    def __init__(self, scope: core.App, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        states = tasks.GlueStartJobRun.jsonata(  # actual type does not matter, this is just to have something to add a catcher to
            self,
            "Start_job",
            glue_job_name="{% $states.input %}",
        ).add_catch(
            sfn.Fail.jsonata(self, "boom"),
            errors=["States.ALL"],
            outputs="a string",  # Not appearing!
        )

        sfn.StateMachine(
            self,
            "State_machine",
            query_language=sfn.QueryLanguage.JSON_PATH,
            definition_body=sfn.ChainDefinitionBody.from_chainable(states),
        )


app = core.App()
StateMachine(app, "StateMachineStack")
app.synth()

```

### Additional Information/Context

I tried with different types of outputs, and `jsonata` vs `jsonpath`, to no avail. 
I wonder as well why the `comment` field of the catcher is not valid. 

### CDK CLI Version

2.178.1 (build ae342cb)

### Node.js Version

22.9.0

### OS

MacOs Sequoi 15.3

### Language

Python

### Language Version

3.12.8

**Comment by pahud** [comment]
Looking at the [renderCatch](https://github.com/aws/aws-cdk/blob/fdd451c69ee647419cc4e37c767ad495ddd54b6a/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L748) function, we can see that the outputs property is only included in the rendered ASL (Amazon States Language) when using JSONata query language.

The issue is that when using JSONPath (which is the default query language), the outputs property is not included in the rendered catch block at all. This explains why in the user's code.

The fix would involve:

1. Modifying the renderCatch function to include the Output property regardless of the query language being used
2. Ensuring that the output is properly formatted according to the query language being used

**Comment by guillaume-alliander** [comment]
I think this makes sense, `outputs` is only [valid for jsonata](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_stepfunctions_tasks/GlueStartJobRun.html#aws_cdk.aws_stepfunctions_tasks.GlueStartJobRun.add_catch). 

That said, in my example, I had explicitly declared a jsonata glue step `tasks.GlueStartJobRun.jsonata(..)`. The same example, with having `jsonata` even for the state machine itself (`query_language=sfn.QueryLanguage.JSONATA`) gives the same error. 


```python
import aws_cdk as core
from aws_cdk import aws_stepfunctions_tasks as tasks
from aws_cdk import aws_stepfunctions as sfn

class StateMachine(core.Stack):
    def __init__(self, scope: core.App, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        states = tasks.GlueStartJobRun.jsonata(  # actual type does not matter, this is just have something to catch errors on
            self,
            "start_job",
            glue_job_name="{% $states.input %}",
        ).add_catch(
            sfn.Fail.jsonata(self, "boom"),
            errors=["States.ALL"],
            outputs="a string",  # Not appearing!
        )

        sfn.StateMachine(
            self,
            "machine",
            state_machine_name="HELLOTHERE",
            query_language=sfn.QueryLanguage.JSONATA,
            definition_body=sfn.ChainDefinitionBody.from_chainable(states),
        )

app = core.App()
StateMachine(app, "StateMachineStack")
app.synth()
```

I end up with the same yaml definition string, without the outpus:

```yaml
DefinitionString:
    Fn::Join:
        - ""
        - - '{"StartAt":"start_job","States":{"start_job":{"End":true,"Catch":[{"ErrorEquals":["States.ALL"],"Next":"boom"}],"Type":"Task","Arguments":{"JobName":"{% $states.input %}","NotificationProperty":null},"Resource":"arn:'
        - Ref: AWS::Partition
        - :states:::glue:startJobRun"},"boom":{"Type":"Fail"}},"QueryLanguage":"JSONata"}
 ```
