### ISSUE TITLE
Amazon.CDK.AWS.Lex: Error when creating a bot using CfnBot class. (.net 8)

### ISSUE THREAD

**Issue by jordialemany** [aws/aws-cdk#33710]
### Describe the bug

It seems that there is a PascalCase / camelCase issue when deploying a new Lex Bot using the CfnBot class. There is a mandatory property called "DataPrivacy". This property must be of type "CfnBot.DataPrivacyProperty", which also contains a mandatory property called "ChildDirected". Even this property has been set to "true", when deploying the stack it throws an error like this: 

UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource MyResourceA629FA55 with message:
[#/DataPrivacy: extraneous key [childDirected] is not permitted]

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

It should deploy the Lex bot without any issues.

### Current Behavior

The deployment of the Lex bot is failing, so the entire changeset gets rolled back.

### Reproduction Steps

Define a CfnBot like this:

                var bot = new CfnBot(this, $"{id}-{botName}", new CfnBotProps
                {
                    Name = $"{botName}",
                    RoleArn = lexRole.RoleArn,
                    **DataPrivacy = new CfnBot.DataPrivacyProperty
                    {
                        ChildDirected = false
                    },**
                    IdleSessionTtlInSeconds = 300, // 5 minutes
                    Description = $"Bot for the {id} application.",
                    BotFileS3Location = new CfnBot.S3LocationProperty
                    {
                        S3Bucket = importBucket.BucketName,
                        S3ObjectKey = botKey,
                    }
                });

### Possible Solution

Fix the JsiiProperty attribute of the property ChildDirected of the class Amazon.CDK.AWS.Lex.CfnBot.DataPrivacyProperty by changing its name from "childDirected" to "ChildDirected".

### CDK CLI Version

2.1003.0 (build b242c23)

### Framework Version

.net 8

### Node.js Version

v20.9.0

### OS

Windows 11 23H2

### Language

.NET

**Comment by ashishdhingra** [comment]
Reproducible. It synthesizes into below CFN template (for example):
```YAML
Resources:
  CdktestDotnetStackTestBot:
    Type: AWS::Lex::Bot
    Properties:
      BotFileS3Location:
        S3Bucket: testbucket
        S3ObjectKey: testkey
      DataPrivacy:
        childDirected: false
      Description: Bot for the CdktestDotnetStack application.
      IdleSessionTTLInSeconds: 300
      Name: TestBot
      RoleArn: arn:aws:iam::139480602983:role/TestEC2ReadOnlyRole
    Metadata:
      aws:cdk:path: CdktestDotnetStack/CdktestDotnetStack-TestBot
...
```
Refer [AWS::Lex::Bot DataPrivacy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lex-bot-dataprivacy.html), there is a casing difference.

This appears to be JSII issue.
