### ISSUE TITLE
aws-cdk-lib: `idpInitiated` prop on UserPoolIdentityProviderSamlProps is ignored

### ISSUE THREAD

**Issue by nateq314** [aws/aws-cdk#33806]
### Describe the bug

I set this option to `true`, but the SAML IDP in Cognito is still being created with

```
Require SP-initiated SAML assertions
```

as the set option, not the intended

```
Accept SP-initiated and IdP-initiated SAML assertions
```

As a result it has to be manually set in AWS console after deploy.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Expected `Accept SP-initiated and IdP-initiated SAML assertions` to be the set option after deploy finished.

### Current Behavior

The option set on the SAML IdP was `Require SP-initiated SAML assertions`

### Reproduction Steps

see description

### CDK CLI Version

2.149.0

### Node.js Version

18.20.4

### OS

MacOS

### Language

TypeScript

### Language Version

Typescript

**Comment by ashishdhingra** [comment]
@nateq314 Good afternoon. Could you please elaborate how the `idpInitiated` property is ignored. Using below code with current latest `aws-cdk-lib` version `2.184.1`:
```TypeScript
import * as cdk from 'aws-cdk-lib';
import * as cognito from 'aws-cdk-lib/aws-cognito';

export class CdktestStackNew extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const userpool = new cognito.UserPool(this, 'Pool');
    new cognito.UserPoolIdentityProviderSaml(this, 'userpoolIdpFile', {
      userPool: userpool,
      metadata: cognito.UserPoolIdentityProviderSamlMetadata.url('https://my-metadata-url.com'),
      encryptedResponses: true,
      requestSigningAlgorithm: cognito.SigningAlgorithm.RSA_SHA256,
      idpInitiated: true,
    });
  }
}
```
successfully synthesizes into the following template:
```YAML
Resources:
  PoolD3F588B8:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      SmsVerificationMessage: The verification code to your new account is {####}
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdktestStackNew/Pool/Resource
  userpoolIdpFileD25C533A:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderDetails:
        IDPSignout: false
        MetadataURL: https://my-metadata-url.com
        EncryptedResponses: true
        RequestSigningAlgorithm: rsa-sha256
        IDPInit: true
      ProviderName: CdktestStackrpoolIdpFileB949FAA5
      ProviderType: SAML
      UserPoolId:
        Ref: PoolD3F588B8
    Metadata:
      aws:cdk:path: CdktestStackNew/userpoolIdpFile/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSM7Qw0TNUTCwv1k1OydbNyUzSqw4uSUzO1kksL45Pzk/PyyzJ16sOLU4tCsjPz9FxTsuDs2EMz5TUvJLMksqAovyyzJTUouDEXBSF6PK1tTp5+SmpelnF+mWGFnpGBnomilnFmZm6RaV5JZm5qXpBEBoAjYFvzJ0AAAA=
    Metadata:
      aws:cdk:path: CdktestStackNew/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
```

Notice that `IDPInit` is set to `true` as expected in the CloudFormation template. Once you run `cdk deploy`, it's the CloudFormation that takes over.

Could you please share the following using the latest `aws-cdk-lib` version:
- Sample CDK app and stack.
- Output of `cdk synth` in your stack.
- Do you see different behavior when you directly deploy using CloudFormation console, instead of running `cdk deploy`?

Thanks,
Ashish
