### ISSUE TITLE
cdk init java issues

### ISSUE THREAD

**Issue by jlhood** [aws/aws-cdk#339]
cdk version: 0.7.3-beta (build eb3f31a)
Env: Macbook Pro running 10.11.6 (El Capitan)

Found 2 issues with cdk init of a java app:

1. app.sh doesn't have execute permissions. Causes `cdk ls` to fail with "spawn EACCES" error immediately after `cdk init` completes. Workaround is to `chmod +x app.sh`.
1. .gitignore isn't getting copied over from the appropriate init-template folder. This causes files like .classpath.txt and all files in the target folder to be included in the initial commit.

Steps to Reproduce:

1. `mkdir init-test`
1. `cd init-test`
1. `cdk init --language java`
1. `cdk ls`

Expected Output:

```
-
    name: hello-cdk-1
    environment:
        name: 277187709615/us-east-1
        account: '277187709615'
        region: us-east-1
-
    name: hello-cdk-2
    environment:
        name: 277187709615/us-east-1
        account: '277187709615'
        region: us-east-1
```

Actual Output:
```
spawn EACCES
```

1. git log --stat

Expected .classpath.txt to not be part of initial commit but it is because .gitignore wasn't copied over.
