### ISSUE TITLE
ec2: aws go cdk ommit Throughput parameter for EBS block devices

### ISSUE THREAD

**Issue by binglius** [aws/aws-cdk#34033]
### Describe the bug

I encounter an issue, When running cdk synth, the generated CloudFormation template lacks the Throughput parameter for EBS block devices, even though it is explicitly configured in the code. For example, the template should include:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            Iops: 10000
            Throughput: 500 -->>> is missing. 
            VolumeSize: 500
            VolumeType: gp3
      EbsOptimized: false
Here, my code.
    ebsOptions := &awsec2.EbsDeviceOptions{
        VolumeType: ebsVolumeType,
        Throughput: jsii.Number(throughput),
        Iops:      jsii.Number(iops),
    }

The source file indicates it's supported. 
https://github.com/aws/aws-cdk-go/blob/awscdk/v2.187.0/awscdk/awsec2/EbsDeviceOptions.go#L33

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Create EC2 with specified EBS throughput.

### Current Behavior

The EBS Size/IOPS are correct, but the throughput stays at 125M/s, the default value. 

### Reproduction Steps

Create ec2 with blockdevices and ebsOptions below. 
```
    ebsOptions := &awsec2.EbsDeviceOptions{
        VolumeType: ebsVolumeType,
        Throughput: jsii.Number(throughput),
        Iops:      jsii.Number(iops),
    }

....

awsec2.NewInstance(stack, jsii.String(xxxxxxxxx), &awsec2.InstanceProps {
       ...
       BlockDevices: &blockDevices,
       ...
    }


```

### CDK CLI Version

2.1007.0

### Node.js Version

v22.14.0

### OS

MacOS/Gentoo Linux/Amazon Linux

### Language

Go

**Comment by binglius** [comment]
Here is demo to reproduce this issue:

```
package main

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"
)

type EC2StackProps struct {
	awscdk.StackProps
	// Custom properties for EBS configuration
	DiskSizeGb int
	Iops       int
	Throughput int
}

func NewEC2Stack(scope constructs.Construct, id string, props *EC2StackProps) awscdk.Stack {
	var sprops awscdk.StackProps
	if props != nil {
		sprops = props.StackProps
	}
	stack := awscdk.NewStack(scope, &id, &sprops)

	// Create VPC
	vpc := awsec2.NewVpc(stack, jsii.String("VPC"), &awsec2.VpcProps{
		MaxAzs: jsii.Number(2),
	})

	// Define EC2 instance parameters
	instanceType := awsec2.InstanceType_Of(awsec2.InstanceClass_COMPUTE5, awsec2.InstanceSize_LARGE)
	
	// Get the latest Amazon Linux AMI
	ami := awsec2.NewAmazonLinuxImage(&awsec2.AmazonLinuxImageProps{
		Generation: awsec2.AmazonLinuxGeneration_AMAZON_LINUX_2,
	})

	// Create block device with EBS configuration
	blockDevice := awsec2.BlockDevice{
		DeviceName: jsii.String("/dev/xvda"),
		Volume: awsec2.BlockDeviceVolume_Ebs(jsii.Number(float64(props.DiskSizeGb)), &awsec2.EbsDeviceOptions{
			VolumeType:          awsec2.EbsDeviceVolumeType_GP3,
			Iops:                jsii.Number(float64(props.Iops)),
			Throughput:          jsii.Number(float64(props.Throughput)),
			DeleteOnTermination: jsii.Bool(true),
		}),
	}

	// Create a slice of pointers to BlockDevice
	blockDevices := []*awsec2.BlockDevice{&blockDevice}

	// Create EC2 instance
	awsec2.NewInstance(stack, jsii.String("EC2Instance"), &awsec2.InstanceProps{
		Vpc:          vpc,
		InstanceType: instanceType,
		MachineImage: ami,
		BlockDevices: &blockDevices, // Pass pointer to the slice
	})

	return stack
}

func main() {
	app := awscdk.NewApp(nil)

	NewEC2Stack(app, "EC2WithConfigurableEBSStack", &EC2StackProps{
		// Configurable EBS parameters
		DiskSizeGb: 100,  // 100 GB disk size
		Iops:       6000, // 6000 IOPS
		Throughput: 300,  // 300 MB/s throughput
	})

	app.Synth(nil)
}
```

**Comment by ykethan** [comment]
Hey @binglius, thank you for reaching out. I was able to reproduce the issue using the following reproduction steps. 

### Reproduction Steps

#### TypeScript Implementation:
```typescript
blockDevices: [
  {
    deviceName: "/dev/xvda",
    volume: cdk.aws_ec2.BlockDeviceVolume.ebs(500, {
      volumeType: cdk.aws_ec2.EbsDeviceVolumeType.GP3,
      iops: 10000,
      throughput: 500  // property
    })
  }
]
```

Run `cdk synth`
Observe that the throughput parameter is missing in the generated CloudFormation template

#### Generated CloudFormation:
```yaml
BlockDeviceMappings:
  - DeviceName: /dev/xvda
    Ebs:
      Iops: 10000
      VolumeSize: 500
      VolumeType: gp3
      # Throughput parameter is missing
```

### Workaround
As a workaround, i was able to override the `Throughput` property

```
const cfnInstance = testInstance.node
      .defaultChild as cdk.aws_ec2.CfnInstance;
    cfnInstance.addOverride(
      "Properties.BlockDeviceMappings.0.Ebs.Throughput",
      500
    );
```

#### Generated CloudFormation:
```yaml
   BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            Iops: 10000
            VolumeSize: 500
            VolumeType: gp3
            Throughput: 500
```


Marking this as bug.

**Comment by pahud** [comment]
minimal reproducible code

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

export class Issue34033ReproStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create VPC
    const vpc = new ec2.Vpc(this, 'VPC', {
      maxAzs: 2, // Default is 3, match Go example
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'Public',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: 'Private',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        }
      ]
    });

    // Define EC2 instance type
    const instanceType = ec2.InstanceType.of(ec2.InstanceClass.C5, ec2.InstanceSize.LARGE);

    // Get the latest Amazon Linux 2 AMI
    const ami = new ec2.AmazonLinuxImage({
      generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
    });

    // Define the root block device with specific GP3 settings
    const rootBlockDevice: ec2.BlockDevice = {
      deviceName: '/dev/xvda', // Standard root device name for Linux AMIs
      volume: ec2.BlockDeviceVolume.ebs(100, { // 100 GB size
        volumeType: ec2.EbsDeviceVolumeType.GP3,
        iops: 6000, // Specific IOPS
        throughput: 300, // Specific Throughput (MiB/s)
        deleteOnTermination: true,
      }),
    };

    // Create EC2 instance
    new ec2.Instance(this, 'EC2Instance', {
      vpc: vpc,
      instanceType: instanceType,
      machineImage: ami,
      blockDevices: [rootBlockDevice], // Pass the configured block device
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC, // Place instance in a public subnet for simplicity
      },
    });
  }
}
```

on `cdk synth`

```yaml
 EC2Instance770AAE32:
    Type: AWS::EC2::Instance
    Properties:
      # ... other properties ...
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Iops: 6000             # Correctly set
            VolumeSize: 100          # Correctly set
            VolumeType: gp3          # Correctly set
            # Throughput: 300  <-- This property is MISSING
      # ... other properties ...
    Metadata:
      aws:cdk:path: Issue34033ReproStack/EC2Instance/Resource
```

Interesting I don't see `Throughput` in the `AWS::EC2::Instance` `Ebs` prop

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-ebs.html

But CDK does have this prop in the interface.
https://github.com/aws/aws-cdk/blob/74a14b303d4391bdbfc28d8cf836eb5eac9425d5/packages/aws-cdk-lib/aws-ec2/lib/volume.ts#L44-L88

Looks like L1 `CfnInstance.EbsProperty` actually does not support that thus being ignored. I can't find out the root cause for now. Requesting further input from the team.
