### ISSUE TITLE
ECS CDK: fluentd-async-connect is deprecated since Docker 20.04

### ISSUE THREAD

**Issue by michaelxuao** [aws/aws-cdk#34055]
### Describe the bug

https://github.com/moby/moby/pull/46114

`fluentd-async` should be used instead as it has existed since docker 20.04

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Docker launches the ECS container as expected.

### Current Behavior

Deprecated setting has been removed in Docker v28 and now containers relying on Fluentd Log Driver will crash

```
level=error time=[REDACTED] msg="Error transitioning container" error="Error response from daemon: unknown log opt 'fluentd-async-connect' for fluentd log driver" task="[REDACTED]" container="[REDACTED]" runtimeID="" nextState="CREATED"
```

https://docs.docker.com/engine/release-notes/28/

### Reproduction Steps

Install docker-ce-28 and try to run ECS container with fluentd driver.

### Possible Solution

default config to use `fluentd-async` with `fluentd-async-connect` left as a legacy option

### CDK CLI Version

2.136.0

### Node.js Version

20

### OS

MacOS

### Language

TypeScript

**Comment by michaelxuao** [comment]
https://github.com/aws/aws-cdk/blob/994e95289b589596179553a5b9d7201155bd9ed1/packages/aws-cdk-lib/aws-ecs/lib/log-drivers/fluentd-log-driver.ts#L81

**Comment by pahud** [comment]
## Reproduction

```ts
import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import { Construct } from 'constructs';

export class Issue34055ReproStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create a VPC
    const vpc = new ec2.Vpc(this, 'ReproVpc', {
      maxAzs: 2,
      natGateways: 1,
    });

    // Create an ECS Cluster
    const cluster = new ecs.Cluster(this, 'ReproCluster', {
      vpc: vpc,
    });

    // Define a Fargate Task Definition
    const taskDefinition = new ecs.FargateTaskDefinition(this, 'ReproTaskDef', {
      memoryLimitMiB: 512,
      cpu: 256,
    });

    // Add a container using the Fluentd log driver
    taskDefinition.addContainer('NginxContainer', {
      image: ecs.ContainerImage.fromRegistry('nginx:latest'),
      portMappings: [{ containerPort: 80 }],
      logging: ecs.LogDrivers.fluentd({
        // Using fluentd driver triggers the deprecated 'fluentd-async-connect' option
        address: 'tcp://127.0.0.1:24224', // Dummy address for demonstration
        tag: 'nginx.access',
        asyncConnect: true, // Explicitly set to true to ensure the option is included
        // Note: The 'asyncConnect' property defaults to true, which maps to 'fluentd-async-connect'
      }),
    });

    // Output the Task Definition ARN
    new cdk.CfnOutput(this, 'TaskDefinitionArn', {
      value: taskDefinition.taskDefinitionArn,
    });
  }
}
```

cdk synth


```yaml
  ReproTaskDefD3A03199:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: nginx:latest
          LogConfiguration:
            LogDriver: fluentd
            Options:
              fluentd-address: tcp://127.0.0.1:24224
              fluentd-async-connect: "true"  # <-- Deprecated option is present
              tag: nginx.access
          Name: NginxContainer
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
      # ... other properties
```

Reproducible. Making this a p1.


## Reference

https://docs.docker.com/engine/deprecated/
https://docs.docker.com/engine/release-notes/20.10/
https://docs.docker.com/engine/release-notes/28/
