### ISSUE TITLE
Unable to use AWS code build webhook scope configuration for GitLab

### ISSUE THREAD

**Issue by Navya0510** [aws/aws-cdk#34146]
### Describe the feature

CreateWebhook [1] in CodeBuild API provides a way to configure scope and domain in scopeConfiguration object. Valid Values of scope are : GITHUB_ORGANIZATION | GITHUB_GLOBAL | GITLAB_GROUP as per [2]. However when I try to create a CodeBuild project using CDK with scope value set, I see an error. If no scope value is set, it defaults to GITHUB_ORGANIZATION for my GITLAB configuration and the update fails.

[1] https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateWebhook.html
[2] https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ScopeConfiguration.html#CodeBuild-Type-ScopeConfiguration-scope

### Use Case

Create a GitLab Runner Project via CDK

### Proposed Solution

Update the scope configuration property

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.CfnProject.ScopeConfigurationProperty.html 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.189.0

### Environment details (OS name and version, etc.)

Linux, windows

**Comment by Navya0510** [comment]
Added the issue in https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues 

https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2300

**Comment by SimonCMoore** [comment]
CFN added those two properties and the CDK L1s were updated last week and merged in https://github.com/aws/aws-cdk/pull/34164


service aws-codebuild
resource AWS::CodeBuild::Project
type ScopeConfiguration
│            └ properties
│               ├[+] Domain: string
│               └[+] Scope: string


Please try the latest release of CDK Library (v2.191.0)

**Comment by pahud** [comment]
Hi @Navya0510 

Just confirmed in `2.193.0` you can have that either using L2 Project with `addPropertyOverride` or `CfnProject`.

## Option 1

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as codebuild from 'aws-cdk-lib/aws-codebuild'; // Corrected import path

export class GitlabScopeOverrideDemoStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Define a dummy source - Using BitBucketSource as a placeholder L2 source
    // The actual type and location will be overridden below.
    // IMPORTANT: Ensure webhook: true is set or filters are provided
    // to make the L2 construct generate the 'Triggers' property.
    const placeholderSource = codebuild.Source.bitBucket({
      owner: 'placeholder', // Value doesn't matter, will be overridden
      repo: 'placeholder',   // Value doesn't matter, will be overridden
      reportBuildStatus: true, // Keep this if needed
      webhook: true, // Explicitly enable webhook to ensure Triggers generation
    });

    // Create the L2 CodeBuild Project
    const project = new codebuild.Project(this, 'MyGitLabProjectL2OverrideAll', {
      projectName: 'gitlab-l2-override-all-project',
      source: placeholderSource, // Use the placeholder source
      environment: {
        buildImage: codebuild.LinuxBuildImage.STANDARD_7_0,
      },
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          build: {
            commands: [
              'echo "Hello from CodeBuild!"',
            ],
          },
        },
      }),
    });

    // --- Escape Hatch: addPropertyOverride for Multiple Properties ---
    // Get the underlying CfnProject L1 construct
    const cfnProject = project.node.defaultChild as codebuild.CfnProject;

    // 1. Override Source Type
    cfnProject.addPropertyOverride('Source.Type', 'GITLAB');

    // 2. Override Source Location (Required for ScopeConfiguration)
    cfnProject.addPropertyOverride('Source.Location', 'CODEBUILD_DEFAULT_WEBHOOK_SOURCE_LOCATION');

    // 3. Override ScopeConfiguration Scope
    cfnProject.addPropertyOverride('Triggers.ScopeConfiguration.Scope', 'GITLAB_GROUP');

    // 4. Override ScopeConfiguration Name (Required by CloudFormation)
    // Replace 'your-gitlab-group-name' with the actual group name.
    cfnProject.addPropertyOverride('Triggers.ScopeConfiguration.Name', 'your-gitlab-group-name');

    // Optional: Override ScopeConfiguration Domain if needed
    // cfnProject.addPropertyOverride('Triggers.ScopeConfiguration.Domain', 'your.gitlab.domain.com');

    // Optional: Remove properties set by the L2 placeholder source that are not applicable to GitLab
    // For example, BitBucketSource might add 'Auth', which might conflict or be unnecessary
    // cfnProject.addPropertyDeletionOverride('Source.Auth'); // Example if Auth was added by L2

  }
}

```

And on `cdk synth` you get this

```yaml
  MyGitLabProjectL2OverrideAll19DB3E56:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name: gitlab-l2-override-all-project
      ServiceRole:
        Fn::GetAtt:
          - MyGitLabProjectL2OverrideAllRole12CFDE90
          - Arn
      Source:
        BuildSpec: |-
          {
            "version": "0.2",
            "phases": {
              "build": {
                "commands": [
                  "echo \"Hello from CodeBuild!\""
                ]
              }
            }
          }
        Location: CODEBUILD_DEFAULT_WEBHOOK_SOURCE_LOCATION
        ReportBuildStatus: true
        Type: GITLAB
      Triggers:
        ScopeConfiguration:
          Scope: GITLAB_GROUP
          Name: your-gitlab-group-name
        Webhook: true
```

## Option 2(Using CfnProject)

```ts
    new codebuild.CfnProject(this, 'MyGitLabProjectL1', {
      name: 'gitlab-l1-demo-project',
      serviceRole: codeBuildRole.roleArn,

      // Define Source (replace placeholder values)
      source: {
        type: 'GITLAB', // Specify GitLab type directly
        location: 'https://gitlab.com/your-gitlab-group-or-user/your-gitlab-repo.git', // Replace with actual GitLab repo URL
        // auth: { type: 'OAUTH' }, // Add authentication if needed
        reportBuildStatus: true, // Optional: report status back to GitLab
        // buildSpec: '...', // Optional: define buildspec inline or path
      },

      // Define Artifacts (e.g., NO_ARTIFACTS or S3)
      artifacts: {
        type: 'NO_ARTIFACTS',
      },

      // Define Environment
      environment: {
        type: 'LINUX_CONTAINER',
        computeType: 'BUILD_GENERAL1_SMALL',
        image: 'aws/codebuild/standard:7.0',
        // privilegedMode: false, // Default
        // imagePullCredentialsType: 'CODEBUILD', // Default
      },

      // Define Triggers with ScopeConfiguration for GitLab
      triggers: {
        webhook: true, // Enable webhook
        // filterGroups: [ ... ], // Optional: Add webhook filters if needed
        // Use type assertion 'as any' to bypass TypeScript error for 'scope'
        scopeConfiguration: {
          scope: 'GITLAB_GROUP', // Set the desired scope (CloudFormation supports this)
          name: 'your-gitlab-group-name', // Provide the required group name
          // domain: 'your.gitlab.domain.com', // Add if using GitLab Self-Managed
        },
      },

      // Optional: Add other properties like cache, vpcConfig, etc.
      // cache: { type: 'NO_CACHE' }, // Default
    });
```

`cdk synth`

```yaml
  MyGitLabProjectL1:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Name: gitlab-l1-demo-project
      ServiceRole:
        Fn::GetAtt:
          - MyGitLabProjectRoleL100CFAD7F
          - Arn
      Source:
        Location: https://gitlab.com/your-gitlab-group-or-user/your-gitlab-repo.git
        ReportBuildStatus: true
        Type: GITLAB
      Triggers:
        ScopeConfiguration:
          Name: your-gitlab-group-name
          Scope: GITLAB_GROUP
        Webhook: true
```


While option 2 gives you full control from L1 perspective, option 1 would be my recommended approach.

For the long-term solution to address this, the `@aws-cdk/aws-codebuild` module should be enhanced by adding dedicated L2/L3 source constructs, specifically `codebuild.Source.gitLab()` and potentially `codebuild.Source.gitLabSelfManaged()`. These constructs would provide a type-safe interface for GitLab integration, automatically handling the correct `Source.Type`, `Source.Location` (using `CODEBUILD_DEFAULT_WEBHOOK_SOURCE_LOCATION` when needed), and properly formatting the `Triggers.ScopeConfiguration` to include `scope: 'GITLAB_GROUP'` based on user input. This aligns with existing CDK patterns and eliminates the need for L1 constructs or property overrides for this common use case.

As workaround should be available, I am making this issue to p2 feature request now.

Please confirm if this workaround resolves the error. If not, kindly provide the full error message for further analysis.
