### ISSUE TITLE
Userdata not populated properly in CfnInstance

### ISSUE THREAD

**Issue by salovan** [aws/aws-cdk#3419]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
I'm attempting to create EC2 instances with userdata to handle post-init configuration using the CfnInstance class.  The userdata object is being created via the aws_ec2.UserData constructor.

```python
from aws_cdk import (
    core,
    aws_ec2
)
class ConnectSmtpRouteStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        shellCommands = aws_ec2.UserData.for_linux()
        shellCommands.add_commands("command1")
        shellCommands.add_commands("command2")

        ec2Instance1 = CfnInstance(self, 'ec2Instance1',
            image_id='ami-3ecc8f46',
            instance_type='t3.large',
            availability_zone='us-west-2b',
            user_data=shellCommands.render()
        )
```
The generated CloudFormation code fails with "Invalid BASE64 encoding of user data" error.  The relevant YAML output looks like:
```yaml
  ec2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2b
      ImageId: ami-3ecc8f46
      InstanceType: t3.large
      UserData: >-
        #!/bin/bash

        command1

        command2

```

* **What is the expected behavior (or behavior of feature suggested)?**
I would expect the generated UserData stanza to include the relevant Base64 encoding blocks.  Something like:
```yaml
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash
           command1
           command2
```

* **What is the motivation / use case for changing the behavior or adding this feature?**
Immediately, I want to create an EC2 instance with additional data volumes which are partitioned, formatted, and mounted when the instance is initialized.  There are other post-init workflows that I would like to build later

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0 (build 1a11e96)
  - Module Version: aws-cdk=1.1.0,@aws-cdk/aws-cloudwatch=1.1.0,@aws-cdk/aws-ec2=1.1.0,@aws-cdk/aws-iam=1.1.0,@aws-cdk/aws-ssm=1.1.0,@aws-cdk/core=1.1.0,@aws-cdk/cx-api=1.1.0,@aws-cdk/region-info=1.1.0,jsii-runtime=Python/3.6.8
  - OS: Ubuntu 18.04
  - Language: Python

**Comment by alokito** [comment]
I have a related issue, I am trying to embed the IP address of another ec2 instance in the user data of a second ec2 instance with (apologies for the typescript vs python):

```
    const ec2Instance2 = new ec2.CfnInstance(this, 'ec2Instance2', {
          imageId: 'ami-3ecc8f46',
          instanceType:'t3.large',
          availabilityZone:'us-west-2b',
          userData:`export CDK_IP='${ec2Instance1.attrPrivateIp}'`
    });
```
This produces
```
  ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2b
      ImageId: ami-3ecc8f46
      InstanceType: t3.large
      UserData:
        Fn::Join:
          - ""
          - - export CDK_IP='
            - Fn::GetAtt:
                - ec2Instance1
                - PrivateIp
            - "'"
```

This fails with a similar error due to lack of `"Fn::Base64":`
