### ISSUE TITLE
aws-lambda: Unsupported Lambda runtime for '${Token[TOKEN.833]}': FROM_IMAGE

### ISSUE THREAD

**Issue by fzlrhmn** [aws/aws-cdk#34343]
### Describe the bug

Trying to build lambda function with `awslambda.NewDockerImageFunction` that takes handler from AWS ECR. But it throws following error. 

```
Error: Unsupported Lambda runtime for '${Token[TOKEN.832]}': FROM_IMAGE
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Should be working as expected where function with Docker Image taken from ECR.

### Current Behavior

It throws an error

```
panic: Error: Unsupported Lambda runtime for '${Token[TOKEN.832]}': FROM_IMAGE
```

### Reproduction Steps

In my code, following lines are being used in construct library. It uses `NewDockerImageFunction` to build function and `DockerImageCode_FromEcr` to specify the code.

```go
repo := awsecr.Repository_FromRepositoryName(scope, jsii.String(id+"tax-verification-ecr"), jsii.String(props.LambdaImageRepo))
function := awslambda.NewDockerImageFunction(scope, jsii.String(id+"-tax-verification-lambda"), &awslambda.DockerImageFunctionProps{
		FunctionName: jsii.String(props.LambdaFunctionName),
		Description:  jsii.String(props.LambdaDescription),
		Architecture: awslambda.Architecture_X86_64(),
		Code:         awslambda.DockerImageCode_FromEcr(repo, nil),
		MemorySize:   jsii.Number(256),
		Timeout:      awscdk.Duration_Seconds(jsii.Number(60)),
		Role:         lambdaRole,
		Environment:  &envs,
})
```

### CDK CLI Version

2.1013.0 (build 054afef)

### Node.js Version

v20.18.1

### OS

Mac OS

### Language

Go

### Language Version

go version go1.24.0 darwin/arm64

**Comment by pahud** [comment]
Hi @fzlrhmn 

I was able to `cdk synth` using the code below:


```go
package main

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsecr"
	"github.com/aws/aws-cdk-go/awscdk/v2/awslambda"

	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"
)

type Issue34343ReproStackProps struct {
	awscdk.StackProps
}

func NewIssue34343ReproStack(scope constructs.Construct, id string, props *Issue34343ReproStackProps) awscdk.Stack {
	var sprops awscdk.StackProps
	if props != nil {
		sprops = props.StackProps
	}
	stack := awscdk.NewStack(scope, &id, &sprops)


	repo := awsecr.Repository_FromRepositoryName(stack, jsii.String("ImportedRepo"), jsii.String("mock-repo-name"))

	awslambda.NewDockerImageFunction(stack, jsii.String("MyDockerImageFunction"), &awslambda.DockerImageFunctionProps{
		FunctionName: jsii.String("issue-34343-repro-function"),
		Code:         awslambda.DockerImageCode_FromEcr(repo, nil), // Reference the dummy repo
	})

	return stack
}

func main() {
	defer jsii.Close()

	app := awscdk.NewApp(nil)

	NewIssue34343ReproStack(app, "Issue34343ReproStack", &Issue34343ReproStackProps{
		awscdk.StackProps{
			Env: env(),
		},
	})

	app.Synth(nil)
}

func env() *awscdk.Environment {
	return nil
}
```

and `go.mod` is like

```
module issue-34343-repro

go 1.23.0

toolchain go1.23.3

require (
	github.com/aws/aws-cdk-go/awscdk/v2 v2.186.0
	github.com/aws/constructs-go/constructs/v10 v10.4.2 // Keep constructs version or let tidy adjust
	github.com/aws/jsii-runtime-go v1.109.0 // Keep jsii version or let tidy adjust
)

require (
	github.com/Masterminds/semver/v3 v3.3.1 // indirect
	github.com/cdklabs/awscdk-asset-awscli-go/awscliv1/v2 v2.2.227 // indirect
	github.com/cdklabs/awscdk-asset-node-proxy-agent-go/nodeproxyagentv6/v2 v2.1.0 // indirect
	github.com/cdklabs/cloud-assembly-schema-go/awscdkcloudassemblyschema/v40 v40.7.0 // indirect
	github.com/fatih/color v1.18.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/yuin/goldmark v1.4.13 // indirect
	golang.org/x/lint v0.0.0-20210508222113-6edffad5e616 // indirect
	golang.org/x/mod v0.24.0 // indirect
	golang.org/x/sync v0.12.0 // indirect
	golang.org/x/sys v0.31.0 // indirect
	golang.org/x/tools v0.31.0 // indirect
)
```

synth output


```yaml
Resources:
  MyDockerImageFunctionServiceRoleE1D00006:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Issue34343ReproStack/MyDockerImageFunction/ServiceRole/Resource
  MyDockerImageFunction36744589:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          Fn::Join:
            - ""
            - - Ref: AWS::AccountId
              - .dkr.ecr.
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
              - /mock-repo-name:latest
      FunctionName: issue-34343-repro-function
      PackageType: Image
      Role:
        Fn::GetAtt:
          - MyDockerImageFunctionServiceRoleE1D00006
          - Arn
    DependsOn:
      - MyDockerImageFunctionServiceRoleE1D00006
```

Can you make sure to use the latest awscdk version and try again? Let me know if it works for you.
