### ISSUE TITLE
(aws-cloudformation) What is wrong with my code?

### ISSUE THREAD

**Issue by dentistfrankchen** [aws/aws-cdk#34445]
### Describe the bug

Here's my yaml file.
The stack cannot be created. 
It says [Failure] reason
Properties validation failed for resource EC2Instance with message: [#: extraneous key [InstanceMarketOptions] is not permitted]

[WindowsServer2019-NICE-DCV.yaml.txt](https://github.com/user-attachments/files/20187356/WindowsServer2019-NICE-DCV.yaml.txt)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The stack should be created.

### Current Behavior

CREATE_ERROR

### Reproduction Steps

use the yaml to create stacks.

### AWS CDK Library version (aws-cdk-lib)

...

### AWS CDK CLI version

...

### Node.js Version

...

### OS

...

### Language

Python

**Comment by ykethan** [comment]
Hey @dentistfrankchen, thank you for reaching out. Wanted to get some additional information on the use case. was the CloudFormation template generated using AWS CDK or are you currently importing an existing template into CDK?

But on diving into the provided CloudFormation template and the error message. From the CloudFormation documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-instancemarketoptions.html 

it appears the `InstanceMarketOptions` is a property of the [AWS::EC2::LaunchTemplate LaunchTemplateData](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html). The error occurs because `InstanceMarketOptions` cannot be used directly with an `AWS::EC2::Instance` resource. This property is only valid within a Launch Template configuration.

According to AWS CloudFormation documentation, to create a Spot Instance, you need to:

1. Create a Launch Template that includes your Spot configuration
2. Reference that Launch Template from your EC2 Instance resource

while i have not deployed these changes, the changes on the template for example may require:

1. Create a new Launch Template resource with your Spot configuration:

```yaml
SpotLaunchTemplate:
  Type: AWS::EC2::LaunchTemplate
  Properties:
    LaunchTemplateName: !Sub "${AWS::StackName}-spot-template"
    LaunchTemplateData:
      # All your instance configuration goes here
      ImageId: !FindInMap [AMIRegionMap, !Ref "AWS::Region", NICEDCVAMI]
      InstanceType: !Ref InstanceType
      # Other properties...
      InstanceMarketOptions:
        MarketType: spot
        SpotOptions:
          MaxPrice: !Ref SpotPrice
          InstanceInterruptionBehavior: stop
```

2. Modify your EC2 Instance to reference the template:

```yaml
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    LaunchTemplate:
      LaunchTemplateId: !Ref SpotLaunchTemplate
      Version: !GetAtt SpotLaunchTemplate.LatestVersionNumber
    SubnetId: !Ref PublicSubnet
# Other properties that can stay at EC2 Instance level...

```
