### ISSUE TITLE
Issue with conditions, intrinsic functions and CDK's construct non-string properties

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#3615]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
I believe the issue I'm describing is a general issue related to how CloudFormation conditions, intrinsic functions and CDK construct non-string properties interact. I will, however, give example code snippets related to one use case I recently ran into and that is trying to set a principals of a policy statement conditionally based on the value of a CloudFormation parameter.

```typescript
const parameter = new CfnParameter(this, 'Parameter', {type: 'String', default: ''});
const condition = new CfnCondition(this, 'ConditionLogicalId', { expression: Fn.conditionEquals(stageParameter, 'someValue') });
.
.
const policyStatement = new PolicyStatement({
    effect: Effect.ALLOW,
    actions: ['sns:Subscribe'],
    resources: ['*'],
    principals: Fn.conditionIf(condition.logicalId, conditionTruePrincipals, conditionFalsePrincipals) // This wouldn’t work due to type mistmatch as the principals property expects IPrincipal[] while Fn.condition at best can return a string representation of the condition using .toString() which wouldn't work in this case
});
```

* **What is the expected behavior (or behavior of feature suggested)?**
Construct properties should accept conditional intrinsic functions non-string values

* **What is the motivation / use case for changing the behavior or adding this feature?**
Using raw CloudFormation, one could've easily modelled e.g.

```
        Statement:
        - Action: ["sns:Subscribe"]
          Effect: Allow
          Principal:
            AWS:
              Fn::If:
              - ConditionLogicalId
              - - trueConditionPrincipal1ARN
                - trueConditionPrincipal2ARN
              - - falseConditionPrincipal1ARN
```

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - Module Version: 1.2.0
  - OS: [all]
  - Language: [TypeScript]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)
