### ISSUE TITLE
[dynamodb] Automatically generate attributeDefinitions for partition key/sort key

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#3690]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

I see the private property `attributeDefinitions` on the `Table` class but `attributeDefinitions` are not generated automatically.

### Proposed Solution

Usage:

```typescript
import dynamodb = require('@aws-cdk/aws-dynamodb');

const table = new dynamodb.Table(this, 'OrdersTable', {
  partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
  sortKey: { name: 'orderDate', type: dynamodb.AttributeType.STRING }
});
```

The above should generate the attribute definitions under the hood.

```
OrdersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: orders
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: orderDate
        AttributeType: S
```

### Environment

  - **CDK CLI Version:** 1.4.0
  - **Module Version:** 1.4.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript
