### ISSUE TITLE
applyRemovalPolicy applies to all resource in stack not just the specified resource 

### ISSUE THREAD

**Issue by NetaNir** [aws/aws-cdk#3701]
### What is the problem?
Hi CDK team! 

When using applyRemovalPolicy on a single resource the synthesized template results in the same removal policy attached to all the resources in the stack 

```typescript
    const bucket = new s3.Bucket(this, 'CoolBucket');
    (bucket.node.defaultChild as CfnBucket).applyRemovalPolicy(RemovalPolicy.RETAIN);
    bucket2 = new s3.Bucket(this, 'NotCoolBucket');
```
Synthesized template: 

```yml
Resources:
  CoolBucketAE6B717C:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
 NotCoolBucket6CD7397B:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```
### Environment

  - **CDK CLI Version:** 1.3.0
  - **Module Version:** 1.3.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript
