### ISSUE TITLE
CodePipeline policy with LambdaInvokeAction wrongly assumes that ImportValue of a Lambda is the ARN but it is the logical ID

### ISSUE THREAD

**Issue by khornberg** [aws/aws-cdk#3876]
:bug: Bug Report

### What is the problem?
A CodePipeline with a [LambdaInvokeAction](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.LambdaInvokeAction.html) wrongly assumes that [ImportValue of a Lambda is the ARN but it is the logical ID](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#aws-resource-lambda-function-return-values). The pipeline policy also wrongly assumes the import value.

### Reproduction Steps
Clone https://github.com/khornberg/cdk-bugs
Install pip packages (assuming one has the npm package already)
Run `cdk synth --path-metadata false --version-reporting false --app "python3 pipeline-lambda-invoke-action-bug.py"`

### Verbose Log
https://github.com/khornberg/cdk-bugs/blob/master/output.yaml

*Pipeline action*
Lines 78-82 are wrong and will fail
```
                  Fn::Select:
                    - 6
                    - Fn::Split:
                        - ":"
                        - Fn::ImportValue: SomeFunction
```

*Policy*
Lines 135-138
```
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::ImportValue: SomeFunction
```

The action is created thus
```
                LambdaInvokeAction(
                    action_name="LambdaInvokeAction",
                    run_order=1,
                    lambda_=Function.from_function_arn(
                        self, "function", core.Fn.import_value("SomeFunction")
                    ),
                )
```

### Environment

  - **CDK CLI Version:** 1.5.0 (build c020efa)
  - **Module Version:** 1.6.1
  - **OS:** OSX Mojave
  - **Language:** Python

**Comment by khornberg** [comment]
If I do something like `Function.from_function_arn(self, 'x', core.Fn.get_att("SomeFunction", "Arn"))` I get a synth error like `jsii.errors.JSIIError: Expected Scalar, got {"$jsii.byref":"@aws-cdk/core.Intrinsic@10015"}`

**Comment by rhboyd** [comment]
Where are you exporting the lambda’s logical ID that this stack is importing?

**Comment by rhboyd** [comment]
Okay. There’s a few things here. Fn.get_att(“someFunction”, “Arn”) would throw an error if you didn’t have a function with the logical ID of “someFunction” in the same stack (which is highly unlikely in a CDK stack).

Fn.Import_value(“SomeFunction”) will look for a CFN Export in the same account/region.

My assumption is that you hate exporting a Lambda’s logical ID in a different stack when you should probably be exporting the Lambda’s Arn instead.

Happy to walk you though it if you can share your CDK or YAML

**Comment by khornberg** [comment]
You are correct that the import value is in a different stack.
```
Outputs:
  ValidateVersionBump:
    Value:
      Ref: ValidateVersionBumpLambdaFunction
    Description: Name of the lambda function used in CodePipeline to disable ServiceCatalog updates
    Export:
      Name: ValidateVersionBumpLambda
```

I have a working CF template that defines the CodePipeline. I am trying recreate it using CDK.

This actions works and it also part of a separate stack.
```
            Actions:
              - Name: Validate-Version-Bump
                RunOrder: 1
                ActionTypeId:
                  Category: Invoke
                  Owner: AWS
                  Provider: Lambda
                  Version: '1'
                InputArtifacts:
                  - Name: Artifact
                Configuration:
                  FunctionName:
                    Fn::ImportValue: ValidateVersionBumpLambda
```

I have monkey patched the CDK output to fix the perceived errors above and the stack works. I guess I am expecting a fairly similar mapping of concepts between CloudFormation and CDK. If I am able to import the logical id of a function and it works in CF, then I expect to be able to do the same in CDK.

Given what you have said, is there a way to get the arn from a logical id import in CDK?
