### ISSUE TITLE
Tags not applied to Cognito UserPools

### ISSUE THREAD

**Issue by johncrn** [aws/aws-cdk#3882]
### What is the problem?
In short, Cognito User Pool resources generated by the CDK do not have their parent Stack's Tags applied to them.

It's perhaps a bit of a stretch to call this a bug with the CDK. The problem appears to be that the CloudFormation syntax for defining tags on a Cognito User Pool resource differs from the norm. This may be breaking whatever convention the CDK uses to apply tags to resources.

For User Pools, Tags must be supplied as a property called UserPoolTags and follow a JSON structure, see more here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-userpooltags

### Reproduction Steps

```
class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // just to confirm tags are propagating, create a resource where the stack level tags are applied.
    new dynamodb.Table(this, "TablesGetTagsNoProblems", {
      partitionKey: { name: "pk", type: AttributeType.STRING },
      sortKey: { name: "sk", type: AttributeType.STRING },
      billingMode: BillingMode.PAY_PER_REQUEST
    });

    const testUserPool = new cognito.UserPool(this, "TestUserPool");

    testUserPool;

    // Here's a workaround
    /*
    const cfnPool = testUserPool.node.defaultChild as cognito.CfnUserPool;

    cfnPool.userPoolTags = {
      TagAppliedDirect: "TestTagValue",
      AnotherTagAppliedDirect: "TestTagValue2"
    };
    */
  }
}

const testStack = new TestStack(app, "TestStack");

Tag.add(testStack, "TestTag", "TestTagValue"); // this is applied to the DDB Table but not the Cognito User Pool
```

### Verbose Log
Here's the CloudFormation output when I use the workaround above, note the differences in how tags are applied to the resources

```
Resources:
  TablesGetTagsNoProblems170A1452:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: TestTag
          Value: TestTagValue
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: TestStack/TablesGetTagsNoProblems/Resource
  TestUserPool83C2ABD0:
    Type: AWS::Cognito::UserPool
    Properties:
      LambdaConfig: {}
      UserPoolTags:
        TagAppliedDirect: TestTagValue
        AnotherTagAppliedDirect: TestTagValue2
    Metadata:
      aws:cdk:path: TestStack/TestUserPool/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.6.1,@aws-cdk/assets=1.6.1,@aws-cdk/aws-apigateway=1.6.1,@aws-cdk/aws-applicationautoscaling=1.6.1,@aws-cdk/aws-autoscaling-common=1.6.1,@aws-cdk/aws-cloudwatch=1.6.1,@aws-cdk/aws-cognito=1.6.1,@aws-cdk/aws-dynamodb=1.6.1,@aws-cdk/aws-ec2=1.6.1,@aws-cdk/aws-events=1.6.1,@aws-cdk/aws-iam=1.6.1,@aws-cdk/aws-kms=1.6.1,@aws-cdk/aws-lambda=1.6.1,@aws-cdk/aws-lambda-event-sources=1.6.1,@aws-cdk/aws-logs=1.6.1,@aws-cdk/aws-s3=1.6.1,@aws-cdk/aws-s3-assets=1.6.1,@aws-cdk/aws-s3-notifications=1.6.1,@aws-cdk/aws-sns=1.6.1,@aws-cdk/aws-sns-subscriptions=1.6.1,@aws-cdk/aws-sqs=1.6.1,@aws-cdk/aws-ssm=1.6.1,@aws-cdk/core=1.6.1,@aws-cdk/cx-api=1.6.1,@aws-cdk/region-info=1.6.1,jsii-runtime=node.js/v10.16.0
```

### Environment

  - **CDK CLI Version:** 1.6.1
  - **Module Version:** 1.6.1
  - **OS:** all
  - **Language:** TypeScript 

### Other information
I brought this up in the Gitter channel and it was suggested I raise an issue for it to be investigated: https://gitter.im/awslabs/aws-cdk?at=5d68b4392efeca1df51cb710
