### ISSUE TITLE
Firelens taskDefinition with custom-resources got "logConfiguration.options['auto_create_group'] to be a string" error

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#3933]
## :question: General Issue

I was trying to create a Fargate task definition with the Firelens support with `@aws-cdk/custom-resources`. When I deploy it I got the following error:

```
Failed to update resource. Expected params.containerDefinitions[1].logConfiguration.options['auto_create_group'] to be a string
```

I am not sure if this is a bug related to AWS CDK or AWS Javascript SDK.

### The Question

```js
import cdk = require('@aws-cdk/core');
import { Vpc } from '@aws-cdk/aws-ec2';
import ecs = require('@aws-cdk/aws-ecs');
import customresources = require('@aws-cdk/custom-resources');

export class AwsFireLensStack extends cdk.Stack {
  public taskArn: string
  public FirelensEnabledTask: any

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = Vpc.fromLookup(this, 'VPC', {
      isDefault: true
    })

    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc: vpc
    })

    this.FirelensEnabledTask = new customresources.AwsCustomResource(this, 'FirelensEnabledTask', {
      onUpdate: { // will also be called for a CREATE event
        service: 'ECS',
        action: 'registerTaskDefinition',
        parameters: {
          "requiresCompatibilities": ["FARGATE"],
          "networkMode": "awsvpc",
          "family": "firelens-demo",
          "cpu": "1024",
          "memory": "2048",
          "containerDefinitions": [
            {
              "essential": true,
              "image": "amazon/aws-for-fluent-bit:latest",
              "name": "log_router",
              "firelensConfiguration": {
                "type": "fluentbit"
              },
              "memory": 25
            },
            {
              "essential": true,
              "image": "nginx",
              "name": "app",
              "portMappings": [
                {
                  "hostPort": 80,
                  "protocol": "tcp",
                  "containerPort": 80
                }],
              "logConfiguration": {
                "logDriver": "awsfirelens",
                "options": {
                  "Name": "cloudwatch",
                  "region": `${this.region}`,
                  "auto_create_group": "true",
                  "log_group_name": "firelens-testing-fluent-bit",
                  "log_stream_prefix": "from-fluent-bit"
                }
              },
              "memory": 100
            }
          ]
        },
        physicalResourceId: Date.now().toString()
      },

    })
    new cdk.CfnOutput(this, 'NewTaskArn', {
      value: this.FirelensEnabledTask.getData('taskDefinition.taskDefinitionArn')
    })
  }
}
```
when I `cdk deploy` I got this error:

<img width="1252" alt="圖片" src="https://user-images.githubusercontent.com/278432/64252766-5d3a2080-cf4e-11e9-8339-e780e521ed12.png">

If I check the custom resource in cloudformation generated from `cdk synth` I got `auto_create_group: "true"` in the YAML. And it looks like the custom-resources provider fails to validate it as a string.

```yaml
  FirelensEnabledTask266C2132:
    Type: Custom::AWS
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
      Create:
        service: ECS
        action: registerTaskDefinition
        parameters:
          requiresCompatibilities:
            - FARGATE
          networkMode: awsvpc
          family: firelens-demo
          cpu: "1024"
          memory: "2048"
          containerDefinitions:
            - essential: true
              image: amazon/aws-for-fluent-bit:latest
              name: log_router
              firelensConfiguration:
                type: fluentbit
              memory: 25
            - essential: true
              image: nginx
              name: app
              portMappings:
                - hostPort: 80
                  protocol: tcp
                  containerPort: 80
              logConfiguration:
                logDriver: awsfirelens
                options:
                  Name: cloudwatch
                  region: ap-northeast-1
                  auto_create_group: "true"
                  log_group_name: firelens-testing-fluent-bit
                  log_stream_prefix: from-fluent-bit
              memory: 100
        physicalResourceId: "1567598358544"
      Update:
        service: ECS
        action: registerTaskDefinition
        parameters:
          requiresCompatibilities:
            - FARGATE
          networkMode: awsvpc
          family: firelens-demo
          cpu: "1024"
          memory: "2048"
          containerDefinitions:
            - essential: true
              image: amazon/aws-for-fluent-bit:latest
              name: log_router
              firelensConfiguration:
                type: fluentbit
              memory: 25
            - essential: true
              image: nginx
              name: app
              portMappings:
                - hostPort: 80
                  protocol: tcp
                  containerPort: 80
              logConfiguration:
                logDriver: awsfirelens
                options:
                  Name: cloudwatch
                  region: ap-northeast-1
                  auto_create_group: "true"
                  log_group_name: firelens-testing-fluent-bit
                  log_stream_prefix: from-fluent-bit
              memory: 100
        physicalResourceId: "1567598358544"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: awsFireLensDemo1/FirelensEnabledTask/Resource/Default
```

### Environment

  - **CDK CLI Version:** 1.6.1 (build a09203a)
  - **Module Version:** 1.6.1
  - **OS:** OSX Mojave
  - **Language:** TypeScript

### Other information

My Firelens sample configuration is from [here](https://github.com/aws/containers-roadmap/blob/7bda4999601c66aa024c96c6ad95ffba60aed0b1/preview-programs/firelens/cloudwatch_task_definition.json#L23)
