### ISSUE TITLE
Docker Volume ?

### ISSUE THREAD

**Issue by alexisgunst** [aws/aws-cdk#4048]
Hello there,

I can't succeed in using Docker volumes with CDK.
My goal is to reproduce the following :

```
version: '3'
volumes:  
  app_volume:

services:  
  app:    
    image: my-app:latest
    expose:      
      - 9292
    volumes:
      - app_volume:/app

  nginx:
    image: nginx:alpine
    depends_on:      
      - app    
    volumes:
      - app_volume:/app
    ports:      
      - 8080:80
    command: /bin/sh -c "cp /app/config/nginx/server.conf /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
```

I'm on it for 3h without success.
Do you have any idea ?

Thanks
