### ISSUE TITLE
Make `stack.partition` concrete if `region` is concrete

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#4092]
### Description

If users specify `env.region` when they define a `Stack`, we should be able to return a concrete value for `stack.partition` instead of `{ "Ref": "AWS::Partition" }`

### Proposed Solution

Create a map from region to partition in `region-info`.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by rix0rrr** [comment]
We can, but what's the advantage?

**Comment by hlascelles** [comment]
For me, cleaner, smaller and easier to read stack diffs. eg, what is simpler to scan here:

```
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :iam::123456789876:root
```
or
```
            Principal:
              AWS: "arn:aws:iam::123456789876:root"

```
