### ISSUE TITLE
Crossacount role for pipeline issue

### ISSUE THREAD

**Issue by amwill04** [aws/aws-cdk#4125]
Unsure if this is a bug or intended and I am misusing something. Unavble to to set up cross account pipeline role. This seems referenced in #49 but I ham unable to get any of the 'hacks` to work and it seems closed.

given the following `roles` on `accountB`  with relevant `policies`

- `arn:aws:iam::accountB:role/deployer`
- `arn:aws:iam::accountB:role/crossaccount`

on the `pipeline` `action` on `acccountA`

```
const deployerRole = Role.fromRoleArn(
    this,
    'DeployerAccount',
    `arn:aws:iam::accountB:role/deployer`
);

const crossAccountRole = Role.fromRoleArn(
    this,
    'CrossAccount',
    `arn:aws:iam::accountB:role/deployer`
);

// Pipeline action
new CloudFormationCreateUpdateStackAction({
    ...,
    deploymentRole: deployerRole,
    role: crossAccountRole
})
```

will produce the following `template` which will fail as it is creating a `policy` and attaching a `role` that does not exist.

```
  CrossAccountPolicy76F2CBCC:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: iam:PassRole
            Effect: Allow
            Resource: arn:aws:iam::accountB:role/deployer-policy
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::ticker-services-journey-artifacts
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::ticker-services-journey-artifacts/*
          - Action:
              - cloudformation:CreateStack
              - cloudformation:DescribeStack*
              - cloudformation:GetStackPolicy
              - cloudformation:GetTemplate*
              - cloudformation:SetStackPolicy
              - cloudformation:UpdateStack
              - cloudformation:ValidateTemplate
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":cloudformation:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :stack/services-journey-lambda-stack/*
        Version: "2012-10-17"
      PolicyName: CrossAccountPolicy76F2CBCC
      Roles:
        - crossaccount // This line here causes the issue
```

It is creating a `policy` with a role that does not exist.
