### ISSUE TITLE
Supply Setter for ServiceLinkedRoleARN in @aws-cdk/aws-autoscaling.AutoScalingGroup

### ISSUE THREAD

**Issue by coding-jj** [aws/aws-cdk#4467]
Please supply a way to set  `ServiceLinkedRoleARN` in Cloudfromation `AWS::AutoScaling::AutoScalingGroup`.

### Use Case

Currently you can only use the default Service Linked Role `role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling` this is created if it doesn't exits.

If you are using multiple KMS CMK Keys, there is no way to have multiple Service Linked Roles with each having it's own access to a KMS CMK Key.

### Proposed Solution

Just add `ServiceLinkedRoleARN` in `interface CommonAutoScalingGroupProps` and add this Parameter to the generated Stack:

``` yaml
Type: AWS::AutoScaling::AutoScalingGroup
Properties: 
  ServiceLinkedRoleARN: String
```
