### ISSUE TITLE
Update Getting Started in Dev Guide to set removalPolicy on S3 bucket so destroy will clean it up

### ISSUE THREAD

**Issue by rajinder-yadav** [aws/aws-cdk#4503]
Follow CDK Hello world here: https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html

When I did the "cdk destroy" my S3 bucket was not deleted. I tried again with same result.

### Environment

  - **CLI Version      :1.12.0 (build 923055e)
  - **OS               :Linux
  - **Language         :TypeScript

```json
{
  "name": "aws-cdk",
  "version": "0.1.0",
  "bin": {
    "aws-cdk": "bin/aws-cdk.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "^1.12.0",
    "@types/jest": "^24.0.18",
    "jest": "^24.9.0",
    "ts-jest": "^24.0.2",
    "aws-cdk": "^1.12.0",
    "ts-node": "^8.1.0",
    "typescript": "~3.6.2"
  },
  "dependencies": {
    "@aws-cdk/aws-s3": "^1.12.0",
    "@aws-cdk/core": "^1.12.0",
    "source-map-support": "^0.5.9"
  }
}
```

**Comment by shivlaks** [comment]
hey @rajinder-yadav 

CloudFormation does not delete S3 buckets that are non-empty.

> You can only delete empty buckets. Deletion fails for buckets that have contents.

Here's the relevant [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html).

**Comment by rajinder-yadav** [comment]
The bucket is empty, still not being destroyed.

**Comment by SomayaB** [comment]
> The bucket is empty, still not being destroyed.

@shivlaks

**Comment by shivlaks** [comment]
@rajinder-yadav oh I see that you're using the `aws-s3` module. The buckets are created with a default retention policy of `Retain`

you can see this in your output from `cdk synth`

```yml
Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```

you can change this by accessing the CloudFormation resource and setting the property there:

```typescript
    const resource = bucket.node.defaultChild as cdk.CfnResource;
    resource.applyRemovalPolicy(cdk.RemovalPolicy.DESTROY);
```

after that, your `cdk synth` should show something like


```yml
Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
```
