### ISSUE TITLE
Wrong policy action when create an AwsCustomResource

### ISSUE THREAD

**Issue by jagu-sayan** [aws/aws-cdk#4533]
Hello,
When I try to create the `AwsCustomResource` show as example in the documentation : https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html, I got a cloudformation error.

### Reproduction Steps

```javascript
import { AwsCustomResource } from "@aws-cdk/custom-resources";
const app = new App();
const verifyDomainIdentity = new AwsCustomResource(app, 'VerifyDomainIdentity', {
  onCreate: {
    service: 'SES',
    action: 'verifyDomainIdentity',
    parameters: {
      Domain: 'example.com'
    },
    physicalResourceIdPath: 'VerificationToken' // Use the token returned by the call as physical id
  }
});
```

### Error Log

```log
Failed to create resource. User: arn:aws:sts::***:assumed-role/***-***/***-***-*** is not authorized to perform: ses:VerifyDomainIdentity
```

### Environment

  - **CLI Version      :** 1.13.0 (build 250a270)
  - **Framework Version:** 1.13.0
  - **OS               :** Debian
  - **Language         :** javascript

### Other

When I look the cloudformation created by cdk, the `Action` property is wrong. I got ``"Action": "email:VerifyDomainIdentity"` instead of `"Action": "ses:VerifyDomainIdentity"`

I think mapping define [here](https://github.com/aws/aws-cdk/blob/67b07263fe84ff1b73d66c1efaf1961b62f68b15/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource.ts#L192-L203) is not correct for all services.

### Workaround

```javascript
import { AwsCustomResource } from "@aws-cdk/custom-resources";
const app = new App();
const verifyDomainIdentity = new AwsCustomResource(app, 'VerifyDomainIdentity', {
  onCreate: {
    service: 'SES',
    action: 'verifyDomainIdentity',
    parameters: {
      Domain: 'example.com'
    },
    physicalResourceIdPath: 'VerificationToken' // Use the token returned by the call as physical id
  },
  policyStatements : [
    new PolicyStatement({
      resources : ['*'],
      actions   : ['ses:VerifyDomainIdentity'],
    }),
  ],
});
```

--- 

This is :bug: Bug Report

**Comment by svenrienstra** [comment]
The problem seems to originate in the SDK, the prefix used comes from this file: https://github.com/aws/aws-sdk-js/blob/master/apis/metadata.json

In there the prefix for SES is defined as `email`.  Not sure what this prefix is used for in the SDK, but it might need fixing in the SDK instead of CDK.

**Comment by SomayaB** [comment]
Thanks for reporting this! We are looking into it. Someone will update when there is movement.

**Comment by vipingoel** [comment]
This issue is present for some more APIs of node js sdk. 

We are trying to create inventory configuration on s3 using AwsCustomResource with policy statements fromSdkCalls.
It needs "s3:PutInventoryConfiguration" action but fromSdkCalls generates "s3:putBucketInventoryConfiguration".

Same is the case for s3:CreateJob (IAM action) vs s3control:CreateJob (sdk method).

I guess this is dumb to just use the sdk method. There should be a sort of mapping between the two or sdk methods should exactly map with the actions.

**Comment by rrrix** [comment]
Is there an open ticket in the AWS Javascript SDK GitHub repository for this issue? I don't see one linked above.

I just happened to need to Verify both an SES domain and SES Email Identity, so I thought I would use the handy dandy example for `AwsCustomResource` in the documentation: https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#examples-1 

```typescript
const verifyDomainIdentity = new AwsCustomResource(this, 'VerifyDomainIdentity', {
  onCreate: {
    service: 'SES',
    action: 'verifyDomainIdentity',
    parameters: {
      Domain: 'example.com'
    },
    physicalResourceId: PhysicalResourceId.fromResponse('VerificationToken') // Use the token returned by the call as physical id
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({resources: AwsCustomResourcePolicy.ANY_RESOURCE})
});

new route53.TxtRecord(this, 'SESVerificationRecord', {
  zone,
  recordName: `_amazonses.example.com`,
  values: [verifyDomainIdentity.getResponseField('VerificationToken')]
});
```

It's funny because the example in the docs for `AwsCustomResource` is broken (but generally works for almost all other services and actions I've tried). 

Turns out the generated SDK metadata file is completely wrong for SES. It generates the following IAM Policy:

```yaml
  AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: email:VerifyDomainIdentity
            Effect: Allow
            Resource: "*"
          - Action: email:VerifyEmailIdentity
            Effect: Allow
            Resource: "*"
          - Action: email:DeleteIdentity
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
```

That should obviously be `ses:VerifyDomainIdentity`, `ses:VerifyEmailIdentity` and `ses:DeleteIdentity` ("email" is not an AWS Service 😄 )

If the AWS JS SDK is going to continue to be wrong, and it's too difficult to get the appropriate fixes applied to the AWS JS SDK (which admittedly is a total beast and has a zillion moving parts), then perhaps the AWS CDK needs some sort of "custom override" mapping for known issues (like SES, and @vipingoel's example)? 

Also, this is probably something which should have [more tests](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/test/aws-custom-resource/integ.aws-custom-resource.expected.json) for scenarios like this.
