### ISSUE TITLE
vpc_subnets prop in aws_elasticloadbalancingv2.ApplicationLoadBalancer is not set correctly

### ISSUE THREAD

**Issue by cheney-yan** [aws/aws-cdk#4627]
### Reproduction Steps

Given python code:
```
from aws_cdk import core, aws_ec2, aws_elasticloadbalancingv2 as alb

class VPC(core.Stack):

  def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
    super().__init__(scope, id, **kwargs)

    # The code that defines your stack goes here
    vpc = aws_ec2.Vpc(self, "VPC",
                      cidr="10.0.0.0/16",
                      enable_dns_support=True,
                      subnet_configuration=[
                          aws_ec2.SubnetConfiguration(
                              name='private',
                              subnet_type=aws_ec2.SubnetType.PRIVATE,
                              cidr_mask=20,
                          ),
                          aws_ec2.SubnetConfiguration(
                              name='data',
                              subnet_type=aws_ec2.SubnetType.PRIVATE,
                              cidr_mask=20,
                          ),
                          aws_ec2.SubnetConfiguration(
                              name='public',
                              subnet_type=aws_ec2.SubnetType.PUBLIC,
                              cidr_mask=20,
                          ),
                      ],
                      max_azs=3,
                      nat_gateways=3,
                      )
    subnets=(vpc.select_subnets(subnet_group_name='private'))
    print((subnets)) # here the subnets are three, which is correct
    private_lb = alb.ApplicationLoadBalancer(
        self, 'PrivateLB',
        # internet_facing=True,
        vpc=vpc,
        vpc_subnets=subnets,
    )
```
In the above code I defined two groups of private subnets, with name "private" and "data" each. And I expect the load balancer to be deployed to "private" subnets only.
So totally there are 6 PrivateSubnets and I am expecting the ALB deployed in three of them.
However, when using `cdk synth`, the result is:
```
  PrivateLBCA1142AB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - Fn::GetAtt:
            - PrivateLBSecurityGroupC3B0B048
            - GroupId
      Subnets:
        - Ref: VPCprivateSubnet1SubnetE522290D
        - Ref: VPCprivateSubnet2Subnet2F4D9530
        - Ref: VPCprivateSubnet3Subnet3C29037E
        - Ref: VPCdataSubnet1Subnet282C8337
        - Ref: VPCdataSubnet2SubnetC7C0AEAC
        - Ref: VPCdataSubnet3Subnet6BA7044F
```
Meaning the vpc_subnet is respected

### Environment

  - **CLI Version      :1.13.1**
  - **Framework Version: ALL 1.13.1**
  - **OS               :OSX**
  - **Language         : Python**

### Other

If I am trying to put any arbitrary object to vpc_subnets, like 
```
    private_lb = alb.ApplicationLoadBalancer(
        self, 'PrivateLB',
        internet_facing=True,
        vpc=vpc,
        vpc_subnets={'a':' b'},
    )
```

The output is still shows all six private subnets, seems the vpc_subnets parameter is not correctly processed. Even if i specify `internet_facing=True`, it still collects all the six private subnets.

----

This is :bug: Bug Report
