### ISSUE TITLE
Cannot add multiple s3 event notifications to lambda

### ISSUE THREAD

**Issue by hedrall** [aws/aws-cdk#4648]
I'd like to add multiple s3 event notification to a Lambda function, but no notifications has created.

### Reproduction Steps

```ts
lambda.addEventSource(
      new S3EventSource( s3Bucket, {
        events: [s3.EventType.OBJECT_CREATED],
        filters: [
          { prefix: 'a/', suffix: '.zip' },
        ]
      } )
    );
lambda.addEventSource(
      new S3EventSource( s3Bucket, {
        events: [s3.EventType.OBJECT_CREATED],
        filters: [
          { prefix: 'a/', suffix: '.txt' },
        ]
      } )
    );
```

### Environment

  - **CLI Version      :*1.14.0*
  - **Framework Version:*1.14.0*
  - **OS               :*mac*

--- 

This is :bug: Bug Report

**Comment by hedrall** [comment]
This problem seems to have been solved.

There are two events in output.

```yml
testbucketNotifications794B1DC4:
    Type: Custom::S3BucketNotifications
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691
          - Arn
      BucketName:
        Ref: testbucketE6E05ABE
      NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: suffix
                    Value: .zip
                  - Name: prefix
                    Value: a/
            LambdaFunctionArn:
              Fn::GetAtt:
                - testfunctions94507C2C
                - Arn
          - Events:
              - s3:ObjectCreated:*
            Filter:
              Key:
                FilterRules:
                  - Name: suffix
                    Value: .txt
                  - Name: prefix
                    Value: a/
            LambdaFunctionArn:
              Fn::GetAtt:
                - testfunctions94507C2C
                - Arn
```
