### ISSUE TITLE
cannot use Refs in Fargate task definition memory / cpu limit

### ISSUE THREAD

**Issue by ndchelsea** [aws/aws-cdk#4656]
It's not possible to use refs in Fargate task definitions. They get synthesized to "[object object]"

### Reproduction Steps

```
    const number = new CfnParameter(this, 'Number', {
      type: 'Number',
    })
    const taskDefinition = new FargateTaskDefinition(this, 'TaskDefinition', {
      memoryLimitMiB: number.value,
      cpu: number.value,
    })
```

This results in:

```
  TaskDefinitionB36D86D9:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Cpu: '[object Object]'
      Family: TaskDefinition
      Memory: '[object Object]'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        'Fn::GetAtt':
          - TaskDefinitionTaskRoleFD40A61D
          - Arn
```

The expected result is:

```
  TaskDefinitionB36D86D9:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Cpu:
        Ref: Number
      Family: TaskDefinition
      Memory:
        Ref: Number
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        'Fn::GetAtt':
          - TaskDefinitionTaskRoleFD40A61D
          - Arn
```

### Error Log

N/A

### Environment

  - **CLI Version      : (npm?) 6.11.3
  - **Framework Version: 1.14.0
  - **OS               : mac os 10.14.5
  - **Language         : javascript

--- 

This is :bug: Bug Report
