### ISSUE TITLE
Is it possible to pass CfnParameter as the container name for ContainerDefinition

### ISSUE THREAD

**Issue by bryan0515** [aws/aws-cdk#4817]
### The Question

I'm creating a CFN stack using **Java CDK**, and I would like to pass a CfnParameter as the container name like following. However, I cannot find an easy way to do that, as the name of the container is specified by its ID in CDK. Could you please advise any solution?

```
Parameters:
  ServiceContainerName:
    Default: 'default-container'
    Type: String
Resources:
   Task:
     Type: 'AWS::ECS::TaskDefinition'
     Properties:
       ContainerDefinitions:
         - Name:
             Ref: ServiceContainerName
           .
           .
           .
```
### Environment

  - **CDK CLI Version:**  1.15.0 (build bdbe3aa)
  - **Module Version:** v1.15.0
  - **Language:**  Java
