### ISSUE TITLE
[IAM] Ability to add conditions to AccountPrincipal

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#5855]
It'd be great if we can add conditions to `AccountPrincipal` when creating `iam.Role`. Currently, `AccountPrincipal` only accepts `accountId` param. We're creating an iam role for 3rd party SaaS and we need to provide a `Condition` property.

### Other

Current workaround is using `addPropertyOverride`.

```typescript
const role = new iam.Role(this, "role", {
  assumedBy: new iam.AccountPrincipal('1234567890')
});

let roleRef = role.node.defaultChild as iam.CfnRole;
roleRef.addPropertyOverride("AssumeRolePolicyDocument.Statement.0.Condition.StringEquals.foo”,"baz");
```

```yaml
Resources:
  Role1EF426C6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :iam::1234567890:root
            Condition:
              StringEquals:
                foo: baz
        Version: "2012-10-17"
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
