### ISSUE TITLE
Secret Manager generateSecretString and generateStringKey must be specified together

### ISSUE THREAD

**Issue by pushthat** [aws/aws-cdk#5951]
Secret manager Secret creation in the cdk require to mention both generateSecretString and generateStringKey together.
This is not required in cloudformation.

I can help implementing if needed I just posted it not to forget.

### Reproduction Steps

```typescript
       import * as cdkSecret from '@aws-cdk/aws-secretsmanager';

        new cdkSecret.Secret(
          this, 'Secret' + instance, {
          generateSecretString: {
            secretStringTemplate: JSON.stringify({ 
              username: "hello-secret",
            }),
            // generateStringKey should't be required 
            generateStringKey: 'tmp'
          }
        });
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue, but I don't think you're correct here @pushthat .

Simple experiment:

```ts
        new secretsmanager.CfnSecret(this, 'Resource', {
            description: 'my description',
            generateSecretString: {
                secretStringTemplate: JSON.stringify({
                    username: "hello-secret",
                }),
            },
        });
```

```
$ cdk deploy
 1/7 | 11:25:44 AM | CREATE_FAILED        | AWS::SecretsManager::Secret | TestStack (Resource) SecretStringTemplate and GenerateStringKey must both be set or removed
        new TestStack (/Users/adamruka/workplace/cdk/my-example-cdk-app/src/test-stack.js:17:9)
        \_ Object.<anonymous> (/Users/adamruka/workplace/cdk/my-example-cdk-app/src/index.js:10:1)
        \_ Module._compile (internal/modules/cjs/loader.js:778:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        \_ Module.load (internal/modules/cjs/loader.js:653:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        \_ startup (internal/bootstrap/node.js:283:19)
        \_ bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by pushthat** [comment]
Hello @skinny85,

Thanks for your answer.

However this is the point :

We can't do it on cdk :

```typescript
        new secretsmanager.CfnSecret(this, 'Resource', {
            description: 'my description',
            generateSecretString: {
                secretStringTemplate: JSON.stringify({
                    username: "test",
                }),
            },
        });
```

But we can do it in cloudformation : 

```yaml
  Secret: 
    Type: AWS::SecretsManager::Secret 
    Properties: 
      Description: "my description" 
      Name:  "test"
      GenerateSecretString: 
        SecretStringTemplate: !Sub '{"username": "test"}' 
```

**Comment by jogold** [comment]
@pushthat and what would be the use case here? Why would you want to have a template without secret in it?

**Comment by pushthat** [comment]
You could for example aggregate multiple secrets from other secrets into one big.
I see what you sent in the documentation @jogold however this template is valid and deploy in cloudformation :

```yaml
  Secret: 
    Type: AWS::SecretsManager::Secret 
    Properties: 
      Description: "my description" 
      Name:  "test"
      GenerateSecretString: 
        SecretStringTemplate: !Sub '{"username": "test"}' 
```

There's an inconsistency between cdk and cloudformation.
