### ISSUE TITLE
Error response from daemon: failed to initialize logging driver

### ISSUE THREAD

**Issue by niranjan2020** [aws/aws-cdk#5954]
Hi I am creating ECS. I have below code to create ECS.

First I created Task definition role as below.

```
MWSECSTaskExecutionRole = iam.Role(self, 'MWSECSTaskExecutionRole',
        assumed_by=iam.ServicePrincipal('ecs-tasks.amazonaws.com'))
        MWSECSTaskExecutionRole.add_to_policy(iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            resources=["*"],
            actions=["ecr:GetAuthorizationToken","ecr:BatchCheckLayerAvailability","ecr:GetDownloadUrlForLayer","ecr:BatchGetImage"]
        ))
```

I created log group

`logDetails = logs.LogGroup(self, "MerchWebServicesLogGroup", log_group_name="/projects/merchwebserviceslog/apiservices", retention=logs.RetentionDays.SIX_MONTHS, removal_policy=core.RemovalPolicy.DESTROY)`

Then task definition and container definition as below

 ```
task_definition = ecs.Ec2TaskDefinition(
            self, "TaskDef", execution_role=MWSECSTaskExecutionRole
        )
        container = task_definition.add_container(
            "mw-service",
            image=ecs.ContainerImage.from_registry("123.dkr.ecr.us-southeast-2.amazonaws.com/location/location-service:latest"),
            memory_limit_mib=3072,
            logging = ecs.AwsLogDriver(stream_prefix='MerchServices', log_group=logDetails))
```

Which generates below cloud formation scripts

1.  Log Group
```
MerchWebServicesLogGroup94598F8F:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /projects/merchwebserviceslog/apiservices
      RetentionInDays: 180
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: location-agent-cdk/MerchWebServicesLogGroup/Resource
```

2. Task definition  role and its policy
```
MWSECSTaskExecutionRole40529A5B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: location-agent-cdk/MWSECSTaskExecutionRole/Resource
  MWSECSTaskExecutionRoleDefaultPolicyEDA68720:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Effect: Allow
            Resource: "*"
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - MerchWebServicesLogGroup94598F8F
                - Arn
        Version: "2012-10-17"
      PolicyName: MWSECSTaskExecutionRoleDefaultPolicyEDA68720
      Roles:
        - Ref: MWSECSTaskExecutionRole40529A5B
    Metadata:
      aws:cdk:path: location-agent-cdk/MWSECSTaskExecutionRole/DefaultPolicy/Resource
```

Here please note I have created policy for only 

              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage 

But policy also added below statement
```
- Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - MerchWebServicesLogGroup94598F8F
                - Arn

```

Then Finally  Task definition as below

```
TaskDef54694570:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: 123.dkr.ecr.us-southeast-2.amazonaws.com/location/location-service:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: MerchWebServicesLogGroup94598F8F
              awslogs-stream-prefix: MerchServices
              awslogs-region: ap-southeast-2
          Memory: 3072
          Name: mw-service
          PortMappings:
            - ContainerPort: 44319
              HostPort: 0
              Protocol: tcp
      ExecutionRoleArn:
        Fn::GetAtt:
          - MWSECSTaskExecutionRole40529A5B
          - Arn
      Family: locationagentcdkTaskDef1C411958
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      TaskRoleArn:
        Fn::GetAtt:
          - TaskDefTaskRole1EDB4A67
          - Arn
    Metadata:
      aws:cdk:path: location-agent-cdk/TaskDef/Resource

```
Whenever service tries to create task I start getting below error

`
Status reason | CannotStartContainerError: Error response from daemon: failed to initialize logging driver: failed to create Cloudwatch log stream: CredentialsEndpointError: failed to load credentials caused by: :`

Also please not that If I remove taskdefinitionrerole from taskdefinition task will start. I have two things here.

First I dont see any way to stop below policy getting created 
```

 - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - MerchWebServicesLogGroup94598F8F
                - Arn
```
I do not know why this policy is getting created. Fine If policy is there why I am getting the above mentioned error? struggling from long time to find out. Can any one help me in this? Thanks
