### ISSUE TITLE
Explicit dependencies provided during prepare are silently ignored

### ISSUE THREAD

**Issue by pierreis** [aws/aws-cdk#5967]
Dependencies provided using `construct.node.addDependency` are ignored silently when specified during the prepare phase.

### Reproduction Steps

```typescript
import path from 'path';

import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');
import dynamodb = require('@aws-cdk/aws-dynamodb');

class TestStack extends cdk.Stack {
  readonly table: dynamodb.Table;

  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    this.table = new dynamodb.Table(this, 'Table', {
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
    });
  }

  prepare() {
    super.prepare();

    const fn = new lambda.Function(this, 'MyFunction', {
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, 'lambda')),
    });

    fn.node.addDependency(this.table);  // <-- this dependency is ignored
  }
}

const app = new cdk.App();
new TestStack(app, 'Stack', {});
app.synth();
```

The above code runs with no error. It results in a template including the lambda function but omitting the explicit dependency (see synthesized template below).

### Error Log

No error message.

### Environment

  - **CLI Version      : 1.22.0 (build 309ac1b)**
  - **Framework Version: 1.22.0 (build 309ac1b)**
  - **OS               : OS X.15.2**
  - **Language         : TypeScript**

### Other

Synthesized template from the above code:

```yaml
Resources:
  TableCD117FA1:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Stack/Table/Resource
  MyFunctionServiceRole3C357FF2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Stack/MyFunction/ServiceRole/Resource
  MyFunction3BAA72D1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21cS3Bucket847A7624
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21cS3VersionKey6A23F9E3
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21cS3VersionKey6A23F9E3
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - MyFunctionServiceRole3C357FF2
          - Arn
      Runtime: nodejs10.x
    Metadata:
      aws:cdk:path: Stack/MyFunction/Resource
      aws:asset:path: asset.3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21c
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.22.0,@aws-cdk/assets=1.22.0,@aws-cdk/aws-applicationautoscaling=1.22.0,@aws-cdk/aws-autoscaling-common=1.22.0,@aws-cdk/aws-cloudwatch=1.22.0,@aws-cdk/aws-dynamodb=1.22.0,@aws-cdk/aws-ec2=1.22.0,@aws-cdk/aws-events=1.22.0,@aws-cdk/aws-iam=1.22.0,@aws-cdk/aws-kms=1.22.0,@aws-cdk/aws-lambda=1.22.0,@aws-cdk/aws-logs=1.22.0,@aws-cdk/aws-s3=1.22.0,@aws-cdk/aws-s3-assets=1.22.0,@aws-cdk/aws-sqs=1.22.0,@aws-cdk/aws-ssm=1.22.0,@aws-cdk/core=1.22.0,@aws-cdk/cx-api=1.22.0,@aws-cdk/region-info=1.22.0,jsii-runtime=node.js/v13.7.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21cS3Bucket847A7624:
    Type: String
    Description: S3 bucket for asset "3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21c"
  AssetParameters3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21cS3VersionKey6A23F9E3:
    Type: String
    Description: S3 key for asset version "3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21c"
  AssetParameters3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21cArtifactHashD63FCBCE:
    Type: String
    Description: Artifact hash for asset "3a8cd29213a24ff016e4d93741fe62256fae4250164601010ee30192314ef21c"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```

--- 

This is :bug: Bug Report
