### ISSUE TITLE
How to adress multiple VPC´s in one Stack?

### ISSUE THREAD

**Issue by githubnoobieme** [aws/aws-cdk#6024]
Hello there,

I have a Scenario where I want to make changes to a bunch of VPC´s in my Account. As I understand the VPC "from_lookup" only adresses one VPC. How would I create a Stack that for example adding endpoints for more than one VPC? The only way I see, is to create different stacks for each VPC or does someone know how to include that in one Stack?

I was thinking of something like that for example
```
class CdkStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        VPCID1='vpc-0fa05fcb898a245c2'
        vpc = ec2.Vpc.from_lookup(self, "VPC", is_default=False, vpc_id=VPCID1)

        VPCID2='vpc-0bb4a05bd79caa712'
        vpc = ec2.Vpc.from_lookup(self, "VPC2", is_default=False, vpc_id=VPCID2)

        s3_endpoint = vpc.add_gateway_endpoint('S3Endpoint',
                                               service=ec2.GatewayVpcEndpointAwsService('s3'))
```

But this only shows one VPC when I run ckd synth

```
PS C:\Projekt\cdk> cdk synth

Resources:
  VPC2S3EndpointCC881F4D:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName:
        Fn::Join:
          - ""
          - - com.amazonaws.
            - Ref: AWS::Region
            - .s3
      VpcId: vpc-0bb4a05bd79caa712
      RouteTableIds:
        - rtb-006b8fabe4cd144e9
      VpcEndpointType: Gateway
    Metadata:
      aws:cdk:path: cdk/VPC2/S3Endpoint/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.22.0,@aws-cdk/aws-cloudwatch=1.22.0,@aws-cdk/aws-ec2=1.22.0,@aws-cdk/aws-iam=1.22.0,@aws-cdk/aws-kms=1.22.0,@aws-cdk/aws-ssm=1.22.0,@aws-cdk/core=1.22.0,@aws-cdk/cx-api=1.22.0,@aws-cdk/region-info=1.22.0,jsii-runtime=Python/3.7.6
```
