### ISSUE TITLE
CloudFrontWebDistribution doesn't complete ViewerCertificate entry correctly

### ISSUE THREAD

**Issue by markingram** [aws/aws-cdk#6035]
I am attempting to create a CloudFrontWebDistribution fronting an S3 bucket. I'm specifying an ACM certificate by ARN. However, the YAML that's output disagrees with [the AWS documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ViewerCertificate.html) and errors out with:
```
Exactly one of [AcmCertificateArn,CloudFrontDefaultCertificate,IamCertificateId] needs to be specified
        new CloudFrontWebDistribution (/Users/mark/dev/screencloud-js-player/deploy/cdk/node_modules/@aws-cdk/aws-cloudfront/lib/web_distribution.ts:821:26)
.. continues...
```

### Reproduction Steps

```typescript
const deploymentBucket = new Bucket(this, ...); // nothing fancy

const certificate = Certificate.fromCertificateArn(
    this,
    'certificate',
    props.cloudFrontSslCertificateArn
);

const distro = new cf.CloudFrontWebDistribution(this, 'cfWebDistribution', {
  originConfigs: [
    {
      s3OriginSource: {
        s3BucketSource: deploymentBucket
      },
      behaviors: [{
        isDefaultBehavior: true
      }]
    }
  ],
  enableIpV6: false,
  defaultRootObject: "index.html",
  httpVersion: cf.HttpVersion.HTTP1_1,
  viewerProtocolPolicy: cf.ViewerProtocolPolicy.ALLOW_ALL,
  viewerCertificate: cf.ViewerCertificate.fromAcmCertificate(
    certificate,
    {
      aliases: [props.cname],
      securityPolicy: cf.SecurityPolicyProtocol.TLS_V1,
      sslMethod: cf.SSLMethod.SNI
    }
  ),
  priceClass: cf.PriceClass.PRICE_CLASS_ALL,
});
```
Then run a `cdk deploy`.

### Error Log

```
<stack-name>: deploying...
<stack-name>: creating CloudFormation changeset...
 0/4 | 9:58:44 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata            | CDKMetadata 
 0/4 | 9:58:44 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket               | deploymentBucket (deploymentBucket1F89110B) 
 0/4 | 9:58:45 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket               | deploymentBucket (deploymentBucket1F89110B) Resource creation Initiated
 0/4 | 9:58:46 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata            | CDKMetadata Resource creation Initiated
 1/4 | 9:58:46 PM | CREATE_COMPLETE      | AWS::CDK::Metadata            | CDKMetadata 
 2/4 | 9:59:07 PM | CREATE_COMPLETE      | AWS::S3::Bucket               | deploymentBucket (deploymentBucket1F89110B) 
 2/4 | 9:59:08 PM | CREATE_IN_PROGRESS   | AWS::CloudFront::Distribution | cfWebDistribution/CFDistribution (cfWebDistributionCFDistributionAC8B7B11) 
 3/4 | 9:59:10 PM | CREATE_FAILED        | AWS::CloudFront::Distribution | cfWebDistribution/CFDistribution (cfWebDistributionCFDistributionAC8B7B11) Exactly one of [AcmCertificateArn,CloudFrontDefaultCertificate,IamCertificateId] needs to be specified
        new CloudFrontWebDistribution (/...path to project root redacted.../deploy/cdk/node_modules/@aws-cdk/aws-cloudfront/lib/web_distribution.ts:821:26)
        ... remainder of stack trace elided...
```

### Environment

  - **CLI Version      : 1.22.0 (build 309ac1b)**
  - **Framework Version:**
  - **OS               : macOS Catalina 10.15.2**
  - **Language         : TypeScript**

### Other
Here is a snippet of the YAML output from a `cdk synth`:
```yaml
...
        Origins:
          - DomainName:
              Fn::GetAtt:
                - deploymentBucket1F89110B
                - RegionalDomainName
            Id: origin1
            S3OriginConfig: {}
        PriceClass: PriceClass_All
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
    Metadata:
      aws:cdk:path: <stack-name>/cfWebDistribution/CFDistribution
  CDKMetadata:
...
```
Notice the `ViewerCertificate` is missing `AcmCertificateArn` in my context.

--- 

This is :bug: Bug Report
