### ISSUE TITLE
AWS Cdk Custom Resource Creation

### ISSUE THREAD

**Issue by VinayRana5674** [aws/aws-cdk#6044]
Can anyone please help me, I have been trying this thing for 5 days. I have a custom resource in AWS YAML format, which I want to create in AWS CDK. I am able to add condition and ServiceToken using AWS CDK CfnCustomResource but I can't add properties. Please help me to find out the solution.

YAML Template

```
LookupAmi:
Condition: UseGI
Properties:
  ServiceToken:
      Fn::ImportValue: !Join ['', [!If [ MyProd, '', 'qa-'], Prod-LookupAmiFunction]]
  AMI: {Ref: AMI}      
  appId: {Ref: AppId}
  envType: {Ref: EnvType}
  osType: {Ref: OSType}
Type: Custom::AmiLookup
```

Corresponding AWS CDK typescript code which is working.

```
const LookupAmi = new cfn.CfnCustomResource(this, 'LookupAmi', {
  serviceToken : "DSDS"  # Just a random value but it is working



});LookupAmi.cfnOptions.condition = UseGI
```

I want to add properties of YAML template, how could I do it. Please help me........
