### ISSUE TITLE
Tagging of single resource

### ISSUE THREAD

**Issue by ben0ler** [aws/aws-cdk#6121]
Having read https://docs.aws.amazon.com/cdk/latest/guide/tagging.html, it seems that with CDK it is only possible to tag a set of resources in a construct (e.g. all the EC2 instances or all S3 buckets).

### Use Case

In addition to be able to globally set tags for a construct or a set of resources I would like to overwrite or add a tag to a specific resource (e.g. a single S3 bucket) to cover for individual differences in resource declarations. Some resources in a set possibly need to be assigned a different cost allocation tags than others.

### Proposed Solution

Keep global tagging available:
`(Tag.add(my_construct, "key", "value")`

Add optional paramter to resources, e.g.:
`aws_s3.Bucket(self, "mys3bucket", tags=[{"key": "value", "key": "value"}])`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by aripalo** [comment]
You can add tags to individual resource by:
```ts
const bucket = new s3.Bucket(this, "MyBucket");
cdk.Tag.add(bucket, "MyKey", "MyValue");
```

This will result in:
```yaml
Resources:
  MyBucketF68F3FF0:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: MyKey
          Value: MyValue
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```

Resources in CDK are constructs too! In your example S3 case this is because `s3.Bucket` extends a class `s3.BucketBase` which extends a class `Resource extends Construct`.
