### ISSUE TITLE
ec2: VPC Flow Logs' logGroupOptions property appears to be ignored

### ISSUE THREAD

**Issue by kaylanm** [aws/aws-cdk#6316]
When creating a flow log using the new/experimental flow log construct, the `FlowLogOptions.logGroupOptions` property is ignored.

### Reproduction Steps

```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as logs from '@aws-cdk/aws-logs';

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'VPC', {});

    vpc.addFlowLog('FlowLog', {
      logGroupOptions: {
        retention: logs.RetentionDays.INFINITE,
      },
    });
  }
}

```

Output includes:

```
  VPCFlowLogLogGroup03CD7A70:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 731
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: TestStack/VPC/FlowLog/LogGroup/Resource
```

No `RetentionInDays` property should be emitted.

### Environment

  - **CLI Version      :** 1.24.0
  - **Framework Version:** 1.24.0
  - **OS               :** macOS 10.15.3
  - **Language         :** TypeScript

### Other

Possible fix: move `logGroupOptions` into `FlowLogDestinationConfig` and expose it as an argument of `FlowLogDestination.toCloudWatchLogs()` since this is related to the destination itself and not the FlowLog.

cc: @corymhall
