### ISSUE TITLE
Python: cfn_options.metadata cannot be mutated

### ISSUE THREAD

**Issue by elruwen** [aws/aws-cdk#6379]
Hi!

When I set metadata via the cfn_options, it does not end up in the final template.

Additionally, the metadata field is `None` if I run `cdk synth --path-metadata=false --version-reporting=false --asset-metadata=false` instead of just `cdk synth`

### Reproduction Steps
```
from aws_cdk import core
from aws_cdk.aws_elasticloadbalancingv2 import CfnTargetGroup
from aws_cdk.core import Fn


class MetadataStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        target_group_nlb = CfnTargetGroup(self, 'mytg', health_check_interval_seconds=30,
                                          health_check_port="8080",
                                          health_check_protocol="TCP", healthy_threshold_count=10,
                                          port=8080, protocol="TCP", unhealthy_threshold_count=10,
                                          vpc_id=Fn.import_value(shared_value_to_import='vpc-id'))

        target_group_nlb.cfn_options.metadata['Comment'] = "this is missing"
```

Result:
```
Resources:
  mytg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: "8080"
      HealthCheckProtocol: TCP
      HealthyThresholdCount: 10
      Port: 8080
      Protocol: TCP
      UnhealthyThresholdCount: 10
      VpcId:
        Fn::ImportValue: vpc-id
    Metadata:
      aws:cdk:path: metadata/mytg
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.23.0,@aws-cdk/assets=1.23.0,@aws-cdk/aws-certificatemanager=1.23.0,@aws-cdk/aws-cloudformation=1.23.0,@aws-cdk/aws-cloudwatch=1.23.0,@aws-cdk/aws-ec2=1.23.0,@aws-cdk/aws-elasticloadbalancingv2=1.23.0,@aws-cdk/aws-events=1.23.0,@aws-cdk/aws-iam=1.23.0,@aws-cdk/aws-kms=1.23.0,@aws-cdk/aws-lambda=1.23.0,@aws-cdk/aws-logs=1.23.0,@aws-cdk/aws-route53=1.23.0,@aws-cdk/aws-s3=1.23.0,@aws-cdk/aws-s3-assets=1.23.0,@aws-cdk/aws-sns=1.23.0,@aws-cdk/aws-sqs=1.23.0,@aws-cdk/aws-ssm=1.23.0,@aws-cdk/core=1.23.0,@aws-cdk/cx-api=1.23.0,@aws-cdk/region-info=1.23.0,jsii-runtime=Python/3.7.3
    Condition: CDKMetadataAvailable

```

Expected result:
```
Resources:
  mytg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: "8080"
      HealthCheckProtocol: TCP
      HealthyThresholdCount: 10
      Port: 8080
      Protocol: TCP
      UnhealthyThresholdCount: 10
      VpcId:
        Fn::ImportValue: vpc-id
    Metadata:
      aws:cdk:path: metadata/mytg
      Comment: 'this is missing'
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.23.0,@aws-cdk/assets=1.23.0,@aws-cdk/aws-certificatemanager=1.23.0,@aws-cdk/aws-cloudformation=1.23.0,@aws-cdk/aws-cloudwatch=1.23.0,@aws-cdk/aws-ec2=1.23.0,@aws-cdk/aws-elasticloadbalancingv2=1.23.0,@aws-cdk/aws-events=1.23.0,@aws-cdk/aws-iam=1.23.0,@aws-cdk/aws-kms=1.23.0,@aws-cdk/aws-lambda=1.23.0,@aws-cdk/aws-logs=1.23.0,@aws-cdk/aws-route53=1.23.0,@aws-cdk/aws-s3=1.23.0,@aws-cdk/aws-s3-assets=1.23.0,@aws-cdk/aws-sns=1.23.0,@aws-cdk/aws-sqs=1.23.0,@aws-cdk/aws-ssm=1.23.0,@aws-cdk/core=1.23.0,@aws-cdk/cx-api=1.23.0,@aws-cdk/region-info=1.23.0,jsii-runtime=Python/3.7.3
    Condition: CDKMetadataAvailable
```
### Error Log
This error only shows up if I use `cdk synth --path-metadata=false --version-reporting=false --asset-metadata=false`

```
cdk synth --path-metadata=false --version-reporting=false --asset-metadata=false
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    MetadataStack(app, "metadata")
  File "/home/ruwen/src/cdk-bugreport/metadata/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ruwen/src/cdk-bugreport/metadata/metadata/metadata_stack.py", line 17, in __init__
    target_group_nlb.cfn_options.metadata['Comment'] = "this is missing"
TypeError: 'NoneType' object does not support item assignment
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.23.0 (build 01f326e)
  - **Framework Version:** 1.23.0
  - **OS               :** Linux
  - **Language         :** Python

### Other

This might be related to https://github.com/aws/aws-cdk/issues/1958, but I struggled to follow that bug report 100%.

--- 

This is :bug: Bug Report
