### ISSUE TITLE
VPC: allow users to change setting of NAT instances SecurityGroup

### ISSUE THREAD

**Issue by nobrooklyn** [aws/aws-cdk#6382]
When I create NAT instance, its security group setting is set to allow any IPv4 address and TCP port.
I want it to be able to configure them by myself.

### Use Case

Below is the code when I created NAT instance by using NatProvider from VPC.Builder.

My Java code:
```java
...
List<SubnetConfiguration> subnetConfs = Arrays.asList(
  SubnetConfiguration.builder().name("pub").cidrMask(24)
    .subnetType(SubnetType.PUBLIC).build(),
  SubnetConfiguration.builder().name("pri").cidrMask(24)
    .subnetType(SubnetType.PRIVATE).build());

NatInstanceProps props = NatInstanceProps.builder()
    .instanceType(
      InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.NANO))
    .build();

NatProvider nat = NatProvider.instance(props);

Vpc.Builder.create(scope, id).cidr(cidr)
  .enableDnsHostnames(true).enableDnsSupport(true)
  .maxAzs(1)
  .subnetConfiguration(subnetConfs)
  .natGatewayProvider(nat)
  .natGateways(1).build();
...
```

Generated(cdk synth):
```yaml
...
Type: AWS::EC2::SecurityGroup
Properties:
  GroupDescription: Security Group for NAT instances
  SecurityGroupEgress:
    - CidrIp: 0.0.0.0/0
      Description: Allow all outbound traffic by default
      IpProtocol: "-1"
  SecurityGroupIngress:
    - CidrIp: 0.0.0.0/0
      Description: from 0.0.0.0/0:ALL PORTS
      FromPort: 0
      IpProtocol: tcp
      ToPort: 65535
  Tags:
...
```

I think nat.ts sets this.

```ts
...
class NatInstance extends NatProvider {
  ...
  public configureNat(options: ConfigureNatOptions) {
    ...
    const sg = new SecurityGroup(options.vpc, 'NatSecurityGroup', {
      vpc: options.vpc,
      description: 'Security Group for NAT instances',
    });
    sg.connections.allowFromAnyIpv4(Port.allTcp());
    ...
```

I think it's better to only allow private subnet access.
[Creating the NATSG Security Group](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html#NATSG)

### Proposed Solution

For example, allow users to add and configure SecurityGroup to NatInstanceProps and allow users to change the default SecurityGroup settings.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
