### ISSUE TITLE
Not possible to disable elbv2.ApplicationTargetGroup healthcheck

### ISSUE THREAD

**Issue by httpdigest** [aws/aws-cdk#6397]
Currently, with a [elasticloadbalancingv2.ApplicationTargetGroup](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationTargetGroup.html) it is impossible to disable ELB health checks when creating the target group.

While CloudFormation does support disabling it via the [HealthCheckEnabled](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-healthcheckenabled) property, CDK does not expose this ability.

When leaving out the [healthCheck property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationTargetGroup.html#healthcheck) in the properties object of the constructor, the documentation indicates that the health check will be "None" which is INCORRECT, as indicated by the CloudFormation template being generated for it also leaving out the HealthCheck CloudFormation property instead of setting it to False.

This results in a default ALB health check configuration being added to the ELB TargetGroup, which currently is:
```
Protocol: HTTP
Path: /
Port: traffic port
Healthy threshold: 5
Unhealthy threshold: 2
Timeout: 5
Interval: 30
Success codes: 200
```

### Reproduction Steps

TypeScript stack definition:
```typescript
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';
export class ElbStack extends cdk.Stack {
  constructor(scope: cdk.Construct) {
    super(scope, 'test');
    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { vpcId: 'vpc-45e1212f' });
    new elbv2.ApplicationTargetGroup(this, 'TargetGroup', {
      port: 80,
      targetType: elbv2.TargetType.IP,
      vpc: vpc,
    });
  }
}
```
Generated CloudFormation template:
```yaml
Resources:
  TargetGroup3D7CD9B8:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: vpc-45e1212f
    Metadata:
      aws:cdk:path: test/TargetGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.25.0, ...
```

### Environment

  - **CLI Version      :** 1.25.0 (build 5ced526)
  - **Framework Version:** 1.25.0
  - **OS               :** Windows 10 x64
  - **Language         :** typescript

This is :bug: Bug Report
