### ISSUE TITLE
How to use FnImportValue where CDK wants a string or list of string?

### ISSUE THREAD

**Issue by dsilvasc** [aws/aws-cdk#674]
Hi,

I'm trying to import a VPC from an existing (non-cdk) stack, following the examples in:
https://gist.github.com/mipearson/aeaf303b0770c25f8b5f6e360594cfbf
https://github.com/awslabs/aws-cdk/issues/603
https://github.com/awslabs/aws-cdk/issues/506

I added exports in my existing stack for the VPC ID, CIDR block, availability zones, and subnets.

In order to call `VpcNetworkRef.import_`, I need to pass it VpcNetworkRefProps, and the builder for the props wants a list of strings for AZs.

None of these type check as arguments to `VpcNetworkRefProps.builder().withVpcId(id).withAvailabilityZones`:

- `new FnImportValue("other-stack-AZs")` where `other-stack-AZs` is a comma-separated export (`Fn::Join` on the other stack's cloudformation template)
- `new FnSplit(",", new FnImportValue("other-stack-AZs"))`
- `[new FnImportValue("other-stack-AZ1"), new FnImportValue("other-stack-AZ2"), new FnImportValue("other-stack-AZ3")]`

How can I import availability zones from another stack?

And more generally, how should we use FnImportValue where CDK wants a string or a list of strings?

**Comment by eladb** [comment]
CDK tokens, such as `FnImportValue` can be represented as strings, so you should be able to just do `[ new FnImportValue("other-stack-az1").toString(), new FnImportValue("other-stack-az2").toString(), ... ]`. Can't say that's super elegant but that should work.

Would that work for your use case?

**Comment by dsilvasc** [comment]
Thank you -- that would work.

How about in places where CloudFormation accepted `Fn::Split` but CDK wants a list?  For example:

```yaml
Resources:
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets: !Split [ ",", !ImportValue shared-infra-PublicSubnetIDs ]
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier: !Split [ ",", !ImportValue shared-infra-PrivateSubnetIDs ]
```
