### ISSUE TITLE
AppSync: support for AWS_IAM authorization type

### ISSUE THREAD

**Issue by oleh-kolinko** [aws/aws-cdk#6772]
Currently, there is no support for AWS_IAM authorization type for AppSync, only API_KEY & AMAZON_COGNITO_USER_POOLS available

### Use Case

In my application, I use User Pool authorization but I also need additional authorization for backend and internal processes and the best approach is to use IAM_AUTH as stated in [here](https://aws.amazon.com/blogs/mobile/supporting-backend-and-internal-processes-with-aws-appsync-multiple-authorization-types/)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by 0xdevalias** [comment]
According to CloudFormation, there doesn't appear to be any other configuration options required when using IAM, just a matter of setting the appropriate `AuthenticationType` keys to `AWS_IAM`:

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-authenticationtype
  - > Security configuration for your GraphQL API. For allowed values (such as API_KEY, AWS_IAM, or AMAZON_COGNITO_USER_POOLS, OPENID_CONNECT),
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-additionalauthenticationproviders.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-additionalauthenticationprovider.html#cfn-appsync-graphqlapi-additionalauthenticationprovider-authenticationtype
  - > API key, AWS IAM, OIDC, or Amazon Cognito user pools.

**Comment by kastork** [comment]
I'm trying to accomplish something similar to this by modeling my CDK stack after the templates generated by Amplify.  Here's what Amplify produces as a CF Template when trying to use IAM as a way to provide both authenticated and unauthenticated access to appsync.
```
  IdentityPool:
  # Always created
    Type: AWS::Cognito::IdentityPool
    Properties: 
      IdentityPoolName: !If [ShouldNotCreateEnvResources, 'ngc35ff4b0e_identitypool_35ff4b0e', !Join ['',['ngc35ff4b0e_identitypool_35ff4b0e', '__', !Ref env]]]
      
      CognitoIdentityProviders:
        - ClientId:  !Ref UserPoolClient
          ProviderName: !Sub
            - cognito-idp.${region}.amazonaws.com/${client}
            - { region: !Ref "AWS::Region",  client: !Ref UserPool}
        - ClientId:  !Ref UserPoolClientWeb
          ProviderName: !Sub
            - cognito-idp.${region}.amazonaws.com/${client}
            - { region: !Ref "AWS::Region",  client: !Ref UserPool}
            
      AllowUnauthenticatedIdentities: !Ref allowUnauthenticatedIdentities
       
       
    DependsOn: UserPoolClientInputs 
    
  
  IdentityPoolRoleMap:
  # Created to map Auth and Unauth roles to the identity pool
  # Depends on Identity Pool for ID ref
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties: 
      IdentityPoolId: !Ref IdentityPool
      Roles:
          unauthenticated: !Ref unauthRoleArn
          authenticated: !Ref authRoleArn
    DependsOn: IdentityPool

```

I can't seem to replicate this with `CfnIdentityPoolRoleAttachment`

because this...
(I'm leaving out the definitions for `AuthRole` and `UnAuthRole` since this is already long enough)

```
// This is kotlin code with the java cdk.
	val identityPool: CfnIdentityPool = CfnIdentityPool.Builder.create(this, "idp")
			.allowUnauthenticatedIdentities(true)
			.cognitoIdentityProviders(listOf(webClientIdp, appClientIdp))
			.build()

	val roleMappings = CfnIdentityPoolRoleAttachment.Builder.create(this, "IdentityPoolRoleMap")
			.identityPoolId(identityPool.logicalId)
			.roles(mapOf(
					"authenticated" to authRole.attrArn,
					"unauthenticated" to unAuthRole.attrArn
			))
			.build()
```
produces this
```
    "idp": {
      "Type": "AWS::Cognito::IdentityPool",
      "Properties": {
        "AllowUnauthenticatedIdentities": true,
        "CognitoIdentityProviders": [
          {
            "ClientId": {
              "Ref": "UserPoolClientWebAA099225"
            },
            "ProviderName": {
              "Fn::ImportValue": "ngsuserpoolFD3AC84D:userpoolExportsOutputFnGetAttpool056F3F7EProviderNameFE989B1F"
            }
          },
          {
            "ClientId": {
              "Ref": "UserPoolClientAppE719858A"
            },
            "ProviderName": {
              "Fn::ImportValue": "ngsuserpoolFD3AC84D:userpoolExportsOutputFnGetAttpool056F3F7EProviderNameFE989B1F"
            }
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "ngs/user-authn/idp"
      }
    },

    "IdentityPoolRoleMap": {
      "Type": "AWS::Cognito::IdentityPoolRoleAttachment",
      "Properties": {
        "IdentityPoolId": "idp",
        "Roles": {
          "authenticated": {
            "Fn::GetAtt": [
              "AuthRole",
              "Arn"
            ]
          },
          "unauthenticated": {
            "Fn::GetAtt": [
              "UnAuthRole",
              "Arn"
            ]
          }
        }
      },
      "DependsOn": [
        "AuthRole",
        "idp",
        "UnAuthRole"
      ],
      "Metadata": {
        "aws:cdk:path": "ngs/user-authn/IdentityPoolRoleMap"
      }
    }
```

The problem is on the line

```
      "Properties": {
        "IdentityPoolId": "idp",
```
Which I think should instead be
```
      "Properties": {
        "IdentityPoolId": {
             "Ref": "idp"
        },
```
