### ISSUE TITLE
Missing RDS subnet group and scaling configuration

### ISSUE THREAD

**Issue by davidlbailey11** [aws/aws-cdk#6817]
Trying to deploy Aurora serverless DB cluster with a specific subnet group and scaling configuration.  Both are missing from the CloudFormation generated by cdk synth, and the resulting db cluster is placed in the default VPC instead.

### Reproduction Steps

        # RDS Aurora Serverless DB

        subnet_ids = ['subnet-04abd2be57a886b3f', 'subnet-0a6d1f5b4f545ac1c', 'subnet-0c59a1dff2750a4d4']

        db_subnet_group = rds.CfnDBSubnetGroup(self, 'AuroraSubnetGroup',
                                                db_subnet_group_description='Subnets for Aurora Serverless DB',
                                                subnet_ids=subnet_ids)

        aurora_db = rds.CfnDBCluster(self, 'AuroraServerlessDB',
                                     engine='aurora',
                                     engine_mode='serverless',
                                     database_name='ArcDmgAssessDB',
                                     db_cluster_identifier='arc-aurora-serverless',
                                     master_username='master_user',
                                     master_user_password='replace_this_password!',
                                     port=3306,
                                     db_subnet_group_name=db_subnet_group.db_subnet_group_name,
                                     scaling_configuration={
                                         'AutoPause': True,
                                         'MaxCapacity': 2,
                                         'MinCapacity': 1,
                                         'SecondsUntilAutoPause': 3600
                                     })

        aurora_db.add_depends_on(db_subnet_group)

### Error Log

No error message, just missing information in the resulting CloudFormation: 

```
  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for Aurora Serverless DB
      SubnetIds:
        - subnet-04abd2be57a886b3f
        - subnet-0a6d1f5b4f545ac1c
        - subnet-0c59a1dff2750a4d4
    Metadata:
      aws:cdk:path: arc/AuroraSubnetGroup
  AuroraServerlessDB:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      DatabaseName: ArcDmgAssessDB
      DBClusterIdentifier: arc-aurora-serverless
      EngineMode: serverless
      MasterUsername: master_user
      MasterUserPassword: replace_this_password!
      Port: 3306
      ScalingConfiguration: {}
    DependsOn:
      - AuroraSubnetGroup
    Metadata:
      aws:cdk:path: arc/AuroraServerlessDB
  CDKMetadata:
    Type: AWS::CDK::Metadata
```

### Environment

  - **CLI Version      : 1.17.9
  - **Framework Version: cdk 1.23.0, 1.28.0
  - **OS               : macOS Mojave version 10.14.6
  - **Language    : Python 3.7

### Other

--- 

This is :bug: Bug Report
