### ISSUE TITLE
ApiGateway DomainName - A certificate was not provided for the endpoint type EDGE (types/local validation issue)

### ISSUE THREAD

**Issue by 0xdevalias** [aws/aws-cdk#6962]
Attempting to create a new Api Gateway with a custom domain name and type 'edge' fails:

```
AWS::ApiGateway::DomainName A certificate was not provided for the endpoint type EDGE. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: a68f64af-b52d-462d-8e70-74e6464208c4)
```

### Reproduction Steps

```javascript
const zone = route53.HostedZone.fromLookup(this, 'Zone', {
  domainName: 'example.com',
})

const certificate = new acm.DnsValidatedCertificate(
  this,
  'ApiCertificate',
  {
    domainName: 'api.example.com',
    hostedZone: zone,
    region: 'us-east-1',
  }
)

const api = new apigateway.RestApi(this, 'ApiGateway', {
  endpointConfiguration: {
    types: [apigateway.EndpointType.EDGE],
  },
})

api.addDomainName('ApiGatewayDomain', {
  domainName: 'api.example.com',
  certificate: certificate.certificateArn,
  endpointType: apigateway.EndpointType.EDGE,
})
```

Looking at the synthesised CloudFormation, when I pass the `certificate.certificateArn` (`string`), I end up with this (which is breaking):

```yaml
ApiGatewayApiGatewayDomain9044B73E:
  Type: AWS::ApiGateway::DomainName
  Properties:
    DomainName: api.example.com
    EndpointConfiguration:
      Types:
        - EDGE
  Metadata:
    aws:cdk:path: REDACTED/ApiGateway/ApiGatewayDomain/Resource
```

Yet when I just pass the `certificate` (`ICertificate`) directly, I get the following (which works):

```yaml
ApiGatewayApiGatewayDomain9044B73E:
  Type: AWS::ApiGateway::DomainName
  Properties:
    DomainName: api.example.com
    CertificateArn:
      Fn::GetAtt:
        - ApiCertificateCertificateRequestorResource57CB3F69
        - Arn
    EndpointConfiguration:
      Types:
        - EDGE
  Metadata:
    aws:cdk:path: REDACTED/ApiGateway/ApiGatewayDomain/Resource
```

Based on the documentation, I am meant to pass the `certificate` (`ICertificate`), but I would have expected to get a validation error and/or type hints telling me that using the ARN string was wrong (wich I didn't), before the stack failing with a less obvious error.

- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.DomainName.html
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.DomainNameProps.html#certificate
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-certificatemanager.ICertificate.html

### Error Log

```
1/20 | 1:27:38 PM | CREATE_FAILED        | AWS::ApiGateway::DomainName         | ApiGateway/ApiGatewayDomain (ApiGatewayApiGatewayDomain9044B73E) A certificate was not provided for the endpoint type EDGE. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: a68f64af-b52d-462d-8e70-74e6464208c4)
	new DomainName (/Users/devalias/dev/REDACTED/node_modules/@aws-cdk/aws-apigateway/lib/domain-name.js:22:26)
	\_ RestApi.addDomainName (/Users/devalias/dev/REDACTED/node_modules/@aws-cdk/aws-apigateway/lib/restapi.js:103:28)
	\_ new REDACTEDApiStack (/Users/devalias/dev/REDACTED/lib/REDACTED-api-stack.js:92:9)
	\_ Object.<anonymous> (/Users/devalias/dev/REDACTED/bin/REDACTED.js:41:3)
	\_ Module._compile (internal/modules/cjs/loader.js:955:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	\_ Module.load (internal/modules/cjs/loader.js:811:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:723:14)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
	\_ internal/main/run_main_module.js:17:11
```

### Environment

  - **CLI Version      :** 1.30.0 (build 4f54ff7)
  - **Framework Version:** 1.30.0
  - **OS               :** macOS Catalina 10.15.3
  - **Language         :** JavaScript

### Other

N/A

--- 

This is :bug: Bug Report
