### ISSUE TITLE
LambdaFunction does not implement IRuleTarget

### ISSUE THREAD

**Issue by alexmv** [aws/aws-cdk#7143]
In the Python CDK, attempting to pass `aws_events_targets.LambdaFunction` as the target of an `events.Rule` fails to typecheck:

```
$ mypy test.py
test.py:19: error: List item 0 has incompatible type "LambdaFunction"; expected "IRuleTarget"
test.py:19: note: 'LambdaFunction' is missing following 'IRuleTarget' protocol member:
test.py:19: note:     __jsii_proxy_class__
Found 1 error in 1 file (checked 1 source file)
```

It does _run_ perfectly fine, however -- this is purely an error in the typesystem.

### Reproduction Steps

```python:test.py
from aws_cdk import aws_events, aws_events_targets, aws_lambda, core

class Example(core.Construct):
    def __init__(self, scope: core.Construct):
        super().__init__(scope, "some-name")
        some_lambda = aws_lambda.Function(
            self,
            "some-handler",
            runtime=aws_lambda.Runtime.PYTHON_3_8,
            code=aws_lambda.AssetCode("some/path"),
            handler="some_package.handler",
            retry_attempts=0,
        )
        aws_events.Rule(
            self,
            "some-rule",
            schedule=aws_events.Schedule.cron(minute="*/5"),
            targets=[aws_events_targets.LambdaFunction(some_lambda)],
        )
```

`pip install mypy && mypy test.py`

### Error Log

```
test.py:19: note: 'LambdaFunction' is missing following 'IRuleTarget' protocol member:
test.py:19: note:     __jsii_proxy_class__
```

### Environment

  - **CLI Version:** 1.17.13
  - **Framework Version:** 1.31.0
  - **OS:**  OS X 10.14.6
  - **Language:** Python 3.8.0 / mypy 0.770

### Other

It is also possible this is a bug in mypy.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are supposed to use this integration class to glue them together: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events-targets.LambdaFunction.html

We use this pattern in many places.

**Comment by alexmv** [comment]
Please re-read the code I posted.  I _am_ using the `aws_cdk.aws_events_targets.LambdaFunction` class.  The bug that `LambdaFunction` does not implement `IRuleTarget` as it is documented to because it's missing a `__jsii_proxy_class__` method.

Which appears to be accurate.  Looking at this more closely, `IRuleTarget` is a protocol which defines the non-abstract static method `__jsii_proxy_class__`, as well as `bind`.  Because both are part of the protocol's definition, it means that `LambdaFunction` must itself define a static `__jsii_proxy_class__` method to be an `IRuleTarget`, which it doesn't currently:

```
$ python
Python 3.8.0 (default, Mar 18 2020, 12:21:22)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aws_cdk import aws_events, aws_events_targets
>>> aws_events_targets.LambdaFunction.__jsii_proxy_class__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'LambdaFunction' has no attribute '__jsii_proxy_class__'
```

**Comment by alexmv** [comment]
Heya -- I believe this bug was closed in error; see my post from a few days ago.  Can it be re-opened?

**Comment by skinny85** [comment]
Sorry about that @alexmv !

I just tried with the following code:

```python
some_lambda = aws_lambda.Function(
            self, "some-handler",
            runtime=aws_lambda.Runtime.PYTHON_3_8,
            code=aws_lambda.CfnParametersCode(),
            handler="some_package.handler",
            retry_attempts=0,
        )
        aws_events.Rule(
            self, "some-rule",
            schedule=aws_events.Schedule.cron(minute="*/5"),
            targets=[aws_events_targets.LambdaFunction(some_lambda)],
        )
```

and I got the following template:

```yaml
Resources:
  ServiceCatalogPipelinesomehandlerServiceRoleEC8BC838:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: hello-cdk-1/ServiceCatalogPipeline/some-handler/ServiceRole/Resource
  ServiceCatalogPipelinesomehandler9B981751:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: ServiceCatalogPipelinesomehandlerLambdaSourceBucketNameParameter56C9663D
        S3Key:
          Ref: ServiceCatalogPipelinesomehandlerLambdaSourceObjectKeyParameter5B5EE148
      Handler: some_package.handler
      Role:
        Fn::GetAtt:
          - ServiceCatalogPipelinesomehandlerServiceRoleEC8BC838
          - Arn
      Runtime: python3.8
    DependsOn:
      - ServiceCatalogPipelinesomehandlerServiceRoleEC8BC838
    Metadata:
      aws:cdk:path: hello-cdk-1/ServiceCatalogPipeline/some-handler/Resource
  ServiceCatalogPipelinesomehandlerEventInvokeConfig36490DD4:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName:
        Ref: ServiceCatalogPipelinesomehandler9B981751
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
    Metadata:
      aws:cdk:path: hello-cdk-1/ServiceCatalogPipeline/some-handler/EventInvokeConfig/Resource
  ServiceCatalogPipelinesomehandlerAllowEventRulehellocdk1ServiceCatalogPipelinesomerule0752F509CACFF320:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ServiceCatalogPipelinesomehandler9B981751
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - ServiceCatalogPipelinesomeruleE4CCF127
          - Arn
    Metadata:
      aws:cdk:path: hello-cdk-1/ServiceCatalogPipeline/some-handler/AllowEventRulehellocdk1ServiceCatalogPipelinesomerule0752F509
  ServiceCatalogPipelinesomeruleE4CCF127:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(*/5 * * * ? *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - ServiceCatalogPipelinesomehandler9B981751
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: hello-cdk-1/ServiceCatalogPipeline/some-rule/Resource
Parameters:
  ServiceCatalogPipelinesomehandlerLambdaSourceBucketNameParameter56C9663D:
    Type: String
  ServiceCatalogPipelinesomehandlerLambdaSourceObjectKeyParameter5B5EE148:
    Type: String
```

So `cdk synth` works, however I do get a warning in my IDE that `aws_events_targets.LambdaFunction` does not implement `IRuleTarget` - so there is definitely something to be improved here!
