### ISSUE TITLE
Example: AWS SAM

### ISSUE THREAD

**Issue by 0xdevalias** [aws/aws-cdk#716]
I think it could be useful to have a basic canonical example of how to use [SAM](https://github.com/awslabs/aws-sam-cli) from CDK (See also: #703, https://github.com/awslabs/aws-sam-cli/issues/663)

If it would be useful, I could probably knock together what I figured out here into a PR to examples? If so.. what would be the best naming/etc for it? Potentially could choose one of the simpler examples from the following and translate it to CDK:

* https://github.com/awslabs/serverless-application-model/tree/master/examples

I found the following, so should be doable:
* https://github.com/awslabs/aws-cdk/tree/master/packages/%40aws-cdk/aws-sam

But when I was exploring the docs, it didn't look like I could do much without dropping into the `cloudformation` namespace (which is probably fine, as this is 'lower level/direct mapping'):

* https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-sam.html

So I decided to try and make a basic function example from that, just to see how it would work. It took me a little while to figure the intricacies of the types used and their interrelations:

```typescript
import sam = require('@aws-cdk/aws-serverless');
```
```typescript
const helloWorld = new sam.cloudformation.FunctionResource(this, "HelloWorld", {
            functionName: "HelloWorld",
            description: "Greeting the world",
            codeUri: "./target",
            handler: "hello-world",
            runtime: lambda.Runtime.Go1x.name,
            tracing: "active",
            events: {
                CatchAll: {
                    type: "Api",
                    properties: {
                        path: "/{proxy+}",
                        method: "ANY",
                        // restApiId: ""
                    }
                }
            }
        });
```

Which synthesises to:

```yaml
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    HelloWorld:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: ./target
            Handler: hello-world
            Runtime: go1.x
            Description: 'Greeting the world'
            Events:
                CatchAll:
                    Properties:
                        Method: ANY
                        Path: '/{proxy+}'
                    Type: Api
            FunctionName: HelloWorld
            Tracing: active
    CDKMetadata:
        Type: 'AWS::CDK::Metadata'
        Properties:
            Modules: '@aws-cdk/assets=0.9.0,@aws-cdk/aws-cloudwatch=0.9.0,@aws-cdk/aws-codepipeline-api=0.9.0,@aws-cdk/aws-ec2=0.9.0,@aws-cdk/aws-elasticloadbalancing=0.9.0,@aws-cdk/aws-events=0.9.0,@aws-cdk/aws-iam=0.9.0,@aws-cdk/aws-kms=0.9.0,@aws-cdk/aws-lambda=0.9.0,@aws-cdk/aws-s3=0.9.0,@aws-cdk/aws-s3-notifications=0.9.0,@aws-cdk/aws-serverless=0.9.0,@aws-cdk/aws-sqs=0.9.0,@aws-cdk/cdk=0.9.0,@aws-cdk/cx-api=0.9.0,js-base64=2.4.5,poc-aws-cdk=0.1.0'
```

**CDK References:**

* https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-sam.html#functionresource
* https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-sam.html#functionresourceprops-interface
* https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-sam.html#@aws-cdk/aws-sam.cloudformation.FunctionResource.ApiEventProperty

**SAM References:**

* https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
* https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types
* https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-object
* https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
