### ISSUE TITLE
SplunkLogDriverProps adds splunk-token to logging options instead of secretoptions

### ISSUE THREAD

**Issue by lockan** [aws/aws-cdk#7264]
### Bug Description
When creating a Task Definition and adding a SplunkLogDriver, a `token` property can be provided. The `token` is a secret value. In our case, we're providing the token from SecretsManager as a SecretValue per the cdk API spec. 

In Cloudformation this would be provided to the Task Definition through `secretOptions` rather than `options`, and the secret would be hidden from the user in the ECS Console UI. 
(See docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)

When doing the same through CDK, the token is added to the `Options` property, and so the secret is resolved from Secrets Manager as expected, but then is plainly displayed as a string in the ECS console UI. This can also be confirmed by examining the output cloudformation 

### Reproduction Steps

Sample CDK code to reproduce the issue:
```
const splunkSecretArn = "arn:aws:secretsmanager:{region}:{accountno}:secret:{secretsmanagerkey}"

...

this.splunkSecretParam = new cdk.CfnParameter(this,
    'SplunkSecretArn', {
    type: 'String',
    description: "Secret manager ARN for the splunk HEC token",
    default: splunkSecretArn
})

...

this.logDriverConfig = new ecs.SplunkLogDriver({
    url: this.parameters.splunkUrl.valueAsString,
    index: this.parameters.splunkIndex.valueAsString,
    token: cdk.SecretValue.secretsManager(this.splunkSecretParam.valueAsString),
 })

this.fargateContainer = this.fargateTaskDefinition.addContainer("fg-containerdef", {
      image: ecs.ContainerImage.fromEcrRepository(this.ecrRepository, "latest"),
      logging: this.logDriverConfig
})

```
### Error Log

Excerpt from the output cloudformation template after doing `cdk synthesize`. Notice that the splunk-token appears under `Options`, not `SecretOptions`. 
```
...
LogConfiguration:
            LogDriver: splunk
            Options:
              splunk-token:
                'Fn::Join':
                  - ''
                  - - '{{resolve:secretsmanager:'
                    - Ref: ExternalSplunkSecretArn
                    - ':SecretString:::}}'
...
```

### Environment

  - **CLI Version      :** aws-cli/2.0.0dev0 Python/3.7.4 Darwin/17.7.0 botocore/2.0.0dev0
  - **Framework Version:** 1.31.0 (build 8f3ac79)
  - **OS               :** MacOS High Sierra 10.13.16
  - **Language         :** javascript / typescript

### Other

--- 

This is :bug: Bug Report
