### ISSUE TITLE
Invalid type for parameter computeResources.tags.props

### ISSUE THREAD

**Issue by cfriedline** [aws/aws-cdk#7350]
When adding a tag to Batch Compute Resources, the synth succeeds, but does not deploy. The messages written indicate the that parameter validation may be incorrect:

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html

#### Tag without properties

```
cr = batch.ComputeResources(
            vpc=vpc,
            ec2_key_pair=key_pair,
            compute_resources_tags=Tag("Name", tags[self.lims.env]["Name"]),
            ...
        )
```
Results in:

```
Invalid type for parameter computeResources.tags.props, value: {}, type: <type 'dict'>, valid types: <type 'basestring'>
```
Synth:
```
Tags:
          key: Name
          props: {}
          defaultPriority: 100
          value: debug-lims-assay-processor

```

#### Tag with properties

```
cr = batch.ComputeResources(
            vpc=vpc,
            ec2_key_pair=key_pair[self.lims.env],
            compute_resources_tags=Tag(
                "Name", tags[self.lims.env]["Name"], apply_to_launched_instances=True
            ),
...
```

Results in:

```
Invalid type for parameter computeResources.tags.props, value: {u'applyToLaunchedInstances': u'true'}, type: <type 'dict'>, valid types: <type 'basestring'>
```

Synth:
```
Tags:
          key: Name
          props:
            applyToLaunchedInstances: true
          defaultPriority: 100
          value: debug-lims-assay-processor
```
### Error Log

See above...

### Environment

  - **CLI Version      :** 1.32.2
  - **Framework Version:** 1.32.2
  - **OS               :** MacOS
  - **Language         :** Python

--- 

This is :bug: Bug Report
