### ISSUE TITLE
Support a "Region Filter" model

### ISSUE THREAD

**Issue by mindstorms6** [aws/aws-cdk#743]
AWS is lovely - and big!

Sometimes, there's uh, _differences_, depending on where you're running you're code. Some things are super obvious - like endpoints in the `aws-cn` partition. 

Some things are less obvious, like some AZs in some regions don't support NAT Gateway.

Some things are even more odd - in AWS-CN - Lambda env vars don't work. 

We should build a "filter" such that when you attempt to say, add a S3 VPC Endpoint in a region where it's not supported, it degrades gracefully, or the CDK fails to build

Historically, we've created a CloudFormation mapping that has entries like

```
Conditions:
  HasCloudWatchDashboards:
    Fn::Not:
      Fn::Or:
        - Fn::Equals:
          - Ref: AWS::Region
          - "some-region-etc"
```

etc

And added them to the templates we build. 

This is sort of similar to:

https://github.com/awslabs/aws-cdk/issues/326
