### ISSUE TITLE
Add ability to 'shallow synthesize' for snapshot testing

### ISSUE THREAD

**Issue by nihakue** [aws/aws-cdk#7566]
Our team maintains a CDK construct library which is used by multiple applications. Some of those apps are owned by us, but some might be owned by other teams. At the moment, teams would like to be able to use snapshot testing for their applications, but with normal snapshot/synthesis even non-breaking changes in the underlying construct library are breaking their tests.

In React land, we would reach for 'shallow rendering', where the implementation details of the component are abstracted away, and what gets tested is the component's interface. 

I'm imagining this would look something like:

```
expect(SynthUtils.toShallow(stack, {shallow: [SomeConstructFromLibrary]}).toMatchSnapshot()

...
ShallowConstructs:
 SomeConstructFromLibrary:
    Properties:
      ConstructProp1: foo
      ConstructProp2: bar
Resources:
  MyResourceFromMyConstructs:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: baz
  MyOtherResourceFromMyConstructs:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: MyQueue
```

I'm not sure how valuable it is to make the output look like a cloudformation template when it isn't one, but hopefully this helps illustrate what I'm talking about.

Now the application snapshots only break when the interface for the construct in the library changes. Of course I can still do a full synth + deploy integ test to be sure everything is working as advertised, but I've removed snapshot tests that depend on the implementation details of my dependencies.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
