### ISSUE TITLE
Permission resource is not created for imported lambda function

### ISSUE THREAD

**Issue by durja** [aws/aws-cdk#7588]
Resource Policy is not being created for Lambda when using Lambda version but is being created when using new Lambda. 

### Reproduction Steps:

* Create a new lambda function and publish a new version for it. 

* Create a new resource policy for the created lambda version. 

Example shows creating new resource policy for api gateway to invoke weatherFunction lambda version 13
```
_lambda.Version.from_version_attributes(self, id='stageVersion',lambda_=weatherFunction,version='13').add_permission(id='invokeweatherfnversion13',principal=iam.ServicePrincipal(service='apigateway.amazonaws.com'),
        action='lambda:InvokeFunction',source_arn=api.arn_for_execute_api(stage='dev', method='GET',path='/')
        )
```

### Error Log

No error message 

### Environment

  - **CLI Version      : 1.34.1
  - **Framework Version: 1.34.1
  - **OS               : Mac Mojave 10.14.6
  - **Language         :Python

### Other

--- 

This is :bug: Bug Report

**Comment by mbsimonovic** [comment]
this might be related, cdk fails to create a `AWS::Lambda::Permission` resource for an imported lambda function (but does generate it for in-the-stack lambdas):


Steps to reproduce:
```
  const importedLambda = lambda.Function.fromFunctionArn(
    stack,'shared lambda authorizer', 'some external arn'
  )
  const jwtAuthorizer = new apigateway.TokenAuthorizer(stack, 'api-authorizer', {
    handler: importedLambda,
    authorizerName: 'api-authorizer',
  })

importedLambda.addPermission('api gateway allow', {
    principal: new iam.ServicePrincipal('apigateway.amazonaws.com'),
    sourceArn: jwtAuthorizer.authorizerArn
  }) // this does NOT create AWS::Lambda::Permission
```
I expect something like this to be created:

```
somePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - importedLambda
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:<region>:<account>:"
            - Ref: APIGWSTAGE
            - /authorizers/
            - Ref: jwtAuthorizer
```


So is it possible (and how) and how to allow external lambdas to be invoked by the custom authorizer? GrantInvoke probably also doesn't work...
