### ISSUE TITLE
"UpdatePolicy" documentation for CfnAutoScalingGroup

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#7648]
I don't have found a way to create an **UpdatePolicy** for _autoscaling.CfnAutoScalingGroup_ with CDK.

I'm using **CfnAutoScalingGroup** because LaunchTemplates are not available by default when creating an ASG with CDK API.

**UpdatePolicy** is not available in _CfnAutoScalingGroup_ construct :
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.CfnAutoScalingGroup.html#construct-props

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnAutoScalingReplacingUpdate.html

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnAutoScalingRollingUpdate.html

So, how to create an **UpdatePolicy** for _autoscaling.CfnAutoScalingGroup_ like we can do with a simple Cfn YAML :
```
myASG: 
  UpdatePolicy: 
    AutoScalingRollingUpdate: 
      MinInstancesInService: "1"
      MaxBatchSize: "1"
      PauseTime: "PT12M5S"
      SuspendProcesses:
        - HealthCheck
        - ReplaceUnhealthy
        - AZRebalance
        - AlarmNotification
        - ScheduledActions
  Type: AWS::AutoScaling::AutoScalingGroup
```

---

This is a 📕 documentation issue
