### ISSUE TITLE
Be able to target SSM RunCommand with aws-events.Rule

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#7710]
Hello,

It seems that we can't target an SSM Run Command with Events > **class Rule (construct)**  : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.IRuleTarget.html

It's not obtainable from Ssm : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.RuleTargetConfig.html

### Use Case

I want to create scheduled Events Rule to Target an SSM RunCommand to call a Document, for example, to RunShellScript on my target(s) identified with Tags.

### Proposed Solution

Be able to configure SSM Run COmmand in Events.Rule, Yaml example : 

```
  TargetsProperties:
    - Arn: "arn:aws:ssm:{{environment_config.region}}::document/AWS-RunShellScript"
      Id: "1"
      Input: "{
      \"commands\":[ echo "Hello World" ]
      }"
      RoleArn: !stack_output ecs-host-cloudwatch-events-iam-role::RoleArn
      RunCommandParametersProperties:
        - Key: tag:UpdateECSAgent
          Values:
            - "true"

```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
