### ISSUE TITLE
RDS CfnDBInstance ignores DBSubnetGroupName 

### ISSUE THREAD

**Issue by IndikaUdagedara** [aws/aws-cdk#7771]
Same issue as in #3483. The previous issue has been closed as there's a workaround but it's not clear why it works. I'd expect the `Cfn` resource types would work without any surprises.

### Reproduction Steps

```ts
    const vpc = new ec2.Vpc(this, "Vpc", {
      maxAzs: 3,
      cidr: "10.1.0.0/16",
    });

   
    var dbSecurityGroup = new ec2.SecurityGroup(this, "DBSecurityGroup", {
      vpc: vpc,
      allowAllOutbound: true,
    });

   var masterPassword = 

    // using Cfn as highler level constructs are declared not stable
    const db = new rds.CfnDBInstance(this, "RDS", {
      dbInstanceClass: "db.t2.small",
      allocatedStorage: "100",
      storageType: "standard",
      storageEncrypted: true,
      engine: "sqlserver-web",
      masterUsername: "user",
      masterUserPassword: ssm.StringParameter.valueForSecureStringParameter(this, 'rds-password', 1);,
      vpcSecurityGroups: [dbSecurityGroup.securityGroupId],
      dbSubnetGroupName: dbSubnetGroup.dbSubnetGroupName,
    })
```

### Error Log

`cdk synth` doesn't include DBSubnetGroup 

```yaml
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.small
      AllocatedStorage: "100"
      Engine: sqlserver-web
      MasterUsername: "user"
      MasterUserPassword: "{{resolve:ssm-secure:rds-password:1}}"
      StorageEncrypted: true
      StorageType: standard
      VPCSecurityGroups:
        - Fn::GetAtt:
            - DBSecurityGroupE3B245A3
            - GroupId

```

### Environment

  - **CLI Version      :1.36.1 (build 4df7dac)**
  - **Framework Version: 1.36**
  - **OS               :Ubuntu**
  - **Language         : Typescript**

### Other

After changing

```ts
      dbSubnetGroupName: dbSubnetGroup.dbSubnetGroupName,
```

to

```ts
      dbSubnetGroupName: dbSubnetGroup.ref
```
it generates the correct Cloudformation but it's not clear why it does that. Not sure if this is an issue with Cloudformation itself as it seems to be expecting a resource Id instead of a name for `dbSubnetGroupName` (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbsubnetgroupname)

--- 

This is :bug: Bug Report
