### ISSUE TITLE
Elastic Fabric Adapter in AutoScalingGroup

### ISSUE THREAD

**Issue by indhub** [aws/aws-cdk#7928]
AutoScalingGroup must allow specifying NetworkInterfaces. This will enable creating instances with EFA adapter in autoscaling group.

### Use Case

I'm using CDK to create autoscaling groups for HPC use cases. EFA is required for performance reasons.

### Proposed Solution

Simplest solution is probably to add a property called 'networkInterfaceType'. If this property is set to 'efa', you can create EFA adapter. 

generated template will look like this:
```
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            InterfaceType: efa
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
