### ISSUE TITLE
Support Github Releases for CodePipeline Triggers

### ISSUE THREAD

**Issue by edwardofclt** [aws/aws-cdk#8111]
Add support for triggering CodePipeline using GitHub releases. 

### Use Case

My team currently deploys software using semantic versioning. Rather than solely relying on merging into branches, it would be great to trigger deployments using releases.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hi @edward-of-clt ,

is this functionality available in CodePipeline today? Or are you proposing creating something entirely new in the CDK?

Thanks,
Adam

**Comment by gskaplan** [comment]
Is this a possibility for a future release of CodePipeline? I would like to use Github Releases for triggering a pipeline.

**Comment by edwardofclt** [comment]
Apologies... I didn't see the notification of the comment, it's currently available in CodePipeline, though I don't believe it to be available in Cloudformation.

**Comment by gskaplan** [comment]
I can't see how to use it from the configuration page. It only seems to trigger a pipeline when a branch is changed. Is there a configuration setting somewhere that can cause a pipeline to be triggered when a new release is created?

**Comment by LeoLapworthKT** [comment]
https://stackoverflow.com/questions/52516087/trigger-aws-codepipeline-by-github-release-webhook seems to suggest it's possible - but not examples for CDK

Please reopen

**Comment by LeoLapworthKT** [comment]
I have made a solution that seems to work:

https://blog.cuckoo.org/aws-pipelines-with-github-release-trigger-in-cdk

**Comment by askkhan84** [comment]
@LeoLapworthKT - the link is no longer available

**Comment by LeoLapworthKT** [comment]
> @LeoLapworthKT - the link is no longer available

Umm... link is working... and I've just updated the post...

The latest version of CDK Pipeline (even in 1.x) doesn't support my work around.

We've ended up switching to a github action on release... which then pushes to a specific `release_to_production` branch which I have the pipeline triggered from, much simpler and no bespoke CDK code.

**Comment by makeitraina** [comment]
@LeoLapworthKT Looking to do a similar workflow and just wondering if there is a readily available action in the marketplace that you used to push to the release branch? Would appreciate if you can share your workflow file.

**Comment by yukinakanaka** [comment]
I'm using CDK v2. 
```
$ cdk --version                                              
2.47.0 (build 3528e3d)
```
Does anyone know a method of  triggering CodePipeline using GitHub releases?

**Comment by LeoLapworthKT** [comment]
> Does anyone know a method of triggering CodePipeline using GitHub releases?

Github work flow to push your release to a `release` branch - which then triggers the CodePipeline was the wasiest way

@makeitraina - missed this - there wasn't an action but it's not complicated:

```
name: Release to production
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push to release branch
        run: git push -f origin "HEAD:refs/heads/release"
```

Only down side is `release` can't easily be a protected branch - I managed to use API calls to GH to unprotect, push and reprotect but it was more faff than it was worth for our company so removed that

Hope that helps

**Comment by yukinakanaka** [comment]
@LeoLapworthKT 
Your solution helps us so much! GitHub action is the wisest way. 
We set the followings for release to Staging and Production.

**CodePipeline Setting**
  - Staging CodePipeline's target branch: `staging`
  - Production CodePipeline's target branch: `production`

**GitHub action for Staging**
- release to staging by GitHub `pre-release`
```
name: Release to Staging
on:
  release:
    types: [prereleased]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to staging branch
        run: git push -f origin "HEAD:refs/heads/staging"
```

**GitHub action for Production**
- release to production by GitHub `release`
```
name: Release to Production
on:
  release:
    types: [released]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to production branch
        run: git push -f origin "HEAD:refs/heads/production"
```
