### ISSUE TITLE
Add Support for adding Metadata to deal with 3rd party tools

### ISSUE THREAD

**Issue by Zirkonium88** [aws/aws-cdk#8336]
Hi ,thanks for your greate effort on  CDK development!

Please add the posssibillty to add custom meta data to Cloudformation templates via the CDK.

### Use Case

I would like to use [cfn_nag](https://github.com/stelligent/cfn_nag). This is security scanning CLI tool for Cloudformation templates. Not all rules apply to my organization. You can add metadata to Cloudformation which disables unnecessary rules of cfn_snag. 

### Proposed Solution

This snippet

```YAML
PublicAlbSecurityGroup:
  Properties:
    GroupDescription: 'Security group for a public Application Load Balancer'
    VpcId:
      Ref: vpc
  Type: AWS::EC2::SecurityGroup
PublicAlbSecurityGroupHttpIngress:
  Properties:
    CidrIp: 0.0.0.0/0
    FromPort: 80
    GroupId:
      Ref: PublicAlbSecurityGroup
    IpProtocol: tcp
    ToPort: 80
  Type: AWS::EC2::SecurityGroupIngress
```

shall be adapted to this

```YAML
PublicAlbSecurityGroup:
  Properties:
    GroupDescription: 'Security group for a public Application Load Balancer'
    VpcId:
      Ref: vpc
  Type: AWS::EC2::SecurityGroup
  Metadata:
    cfn_nag:
      rules_to_suppress:
        - id: W9
          reason: "This is a public facing ELB and ingress from the internet should be permitted."
        - id: W2
          reason: "This is a public facing ELB and ingress from the internet should be permitted."
PublicAlbSecurityGroupHttpIngress:
  Properties:
    CidrIp: 0.0.0.0/0
    FromPort: 80
    GroupId:
      Ref: PublicAlbSecurityGroup
    IpProtocol: tcp
    ToPort: 80
  Type: AWS::EC2::SecurityGroupIngress
```

My idea

```Python
alb_sg.node.add_metadata(
{
   "cfn_nag": {
      "rules_to_suppress": [
         {
            "id": "W9",
            "reason": "This is a public facing ELB and ingress from the internet should be permitted."
         },
         {
            "id": "W2",
            "reason": "This is a public facing ELB and ingress from the internet should be permitted."
         }
      ]
   }
}
)
```

### Other

Related #6379

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
