### ISSUE TITLE
CloudFormation parameter overrides and logRetention issues

### ISSUE THREAD

**Issue by thovden** [aws/aws-cdk#8519]
### The Question

I deploy CloudFormation changesets created with CDK from CodePipeline. I use `parameterOverrides` to achieve this: 

```
      const deployCommonProductionAction = new codepipelineActions.CloudFormationCreateUpdateStackAction({
            ...
            parameterOverrides: {
                ...lambdaCode.assign(serviceBuildOutput.s3Location),
            },
            extraInputs: [serviceBuildOutput],
        })
````

In the actual stack I get the lambda code parameters like this: 

```
this.lambdaCode = lambda.Code.fromCfnParameters()
```

This all works fine in the standard case. However, when setting `logRetention` on a lambda in the stack, CDK  [creates a Lambda which uses `Asset`](https://github.com/aws/aws-cdk/blob/986e2814e072f0334d8470a2d60ea73dcceadfe4/packages/%40aws-cdk/aws-lambda/lib/log-retention.ts#L48) and hence our stack becomes dependent on info about the logRetention lambda code location - e.g., `S3Bucket` and `S3VersionKey`. These do not exist when deploying with CloudFormation.

```
Parameters:
  monitoringLambdaSourceBucketNameParameterCA784686:
    Type: String
  monitoringLambdaSourceObjectKeyParameterA7543DF9:
    Type: String
  AssetParametersceefd938ac7ea929077f2e2f4cf09b5034ebdd14799216b1281f4b28427da40aS3BucketB030C8A8:
    Type: String
    Description: S3 bucket for asset "ceefd938ac7ea929077f2e2f4cf09b5034ebdd14799216b1281f4b28427da40a"
  AssetParametersceefd938ac7ea929077f2e2f4cf09b5034ebdd14799216b1281f4b28427da40aS3VersionKey6A2AABD7:
    Type: String
    Description: S3 key for asset version "ceefd938ac7ea929077f2e2f4cf09b5034ebdd14799216b1281f4b28427da40a"
  AssetParametersceefd938ac7ea929077f2e2f4cf09b5034ebdd14799216b1281f4b28427da40aArtifactHashEDC522F0:
    Type: String
    Description: Artifact hash for asset "ceefd938ac7ea929077f2e2f4cf09b5034ebdd14799216b1281f4b28427da40a
```

So either I need to be able to get hold of these parameters from the `logRetention` lambda code, or use some other escape hatch. 

I appreciate any thoughts on how to be able to use `logRetention` with `parameterOverrides`. 

### Environment

  - **CDK CLI Version:** 1.45.0
  - **Module Version:** 1.45.0
  - **Node.js Version:** 12.16.1
  - **OS:** OSX Catalina, Linux
  - **Language (Version):** Typescript 3.9.5
