### ISSUE TITLE
DynamoDB Retention Policy

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#8537]
Our docs say this for DynamoDB TableProps [RemovalPolicy](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.RemovalPolicy.html):
```text
DESTROY | This is the default removal policy.
```

Creating a Table with the Python CDK using the following command:
```python
self._client_db = ddb.Table(self, "ClientsTable", partition_key={"name":"client_id","type": ddb.AttributeType.STRING})
```

Yields the following CFN Template:
```yaml
Resources:
  ClientsTableC30D35A3:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: authorization-server/ClientsTable/Resource
```

### Reproduction Steps

provided above

### Error Log
N/A

### Environment

  - **CLI Version:**      1.44.0 (build 1cd832b)
  - **Framework Version:** 1.44.0 (build 1cd832b)
  - **Node.js Version:** v10.21.0
  - **OS               :** Amazon Linux 2012
  - **Language (Version):** Python 3.6

### Other

--- 

This is :bug: Bug Report
