### ISSUE TITLE
appsync - apiKeyConfig expires outputting incorrect format

### ISSUE THREAD

**Issue by m0rph13** [aws/aws-cdk#8698]
When specifying the attribute "expires" for apiKeyConfig, the rendered cloudformation gets a value of null.

### Reproduction Steps
```
const api = new GraphQLApi(this, 'api', {
            name: getResourceName('graphql'),
            authorizationConfig: {
                defaultAuthorization: {
                    authorizationType: AuthorizationType.API_KEY,
                    apiKeyConfig: {
                        name: "api-key",
                        description: "api-key",
                        expires: "1614164998"
                    }
                },    
            schemaDefinitionFile: 'schema.graphql',
        });
```

### Error Log

Synth gives:
```
 apiapikeyApiKeyXXXXXX:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt:
          - apiCXXXXXX
          - ApiId
      Description: api-key
      Expires: null
```

### Environment

  - **CLI Version      :** 1.46.0
  - **Framework Version:** 1.46.0
  - **Node.js Version:** v12.16.1 
  - **OS               :** OSX
  - **Language (Version):** 3.8.3 

### Other

--- 

This is :bug: Bug Report
