### ISSUE TITLE
[stepfunctions] CustomState loses explicit null fields from parsed JSON

### ISSUE THREAD

**Issue by erik-sab** [aws/aws-cdk#8754]
CustomState https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.CustomState.html 
looses explicit `null` fields from parsed JSON.

### Reproduction Steps

JSON provided bellow

```json
    "Enable_Termination_Protection": {
      "Type": "Task",
      "Resource": "arn:aws:states:::elasticmapreduce:setClusterTerminationProtection",
      "Parameters": {
        "ClusterId.$": "$.ClusterId",
        "TerminationProtected": true
      },
      "ResultPath": null,
      "Next": "rollup"
    },
```
generates next output parsed as CustomStep and added to the flow

```json
    "Enable_Termination_Protection": {
      "Next": "rollup",
      "Resource": "arn:aws:states:::elasticmapreduce:setClusterTerminationProtection",
      "Type": "Task",
      "Parameters": {
        "ClusterId.$": "$.ClusterId",
        "TerminationProtected": true
      }
```
**"ResultPath": null** is missing in the result

### Environment

  - **CLI Version      : 1.47.0**
  - **Framework Version: 1.47.0**
  - **Node.js Version: v12.18.1**
  - **OS               : Linux**
  - **Language (Version): Java 11**

### Other

Worarround for this particular case is to provide any fake result part, which is not null e.g. `$.devnull`

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@erik-telesoftas are you able to use the special value `DISCARD` as we would with other states?
I believe this concern of the null not translating to other languages did come up, I'll take a look at the Java experience and see what we can do to address this bug!

**Comment by erik-telesoftas** [comment]
Using `DISCARD` does not work either.

It creates `"ResultPath":"DISCARD"` and stack creation fails with an error:

```
6:00:19 AM | UPDATE_FAILED        | AWS::StepFunctions::StateMachine | Foo...ateMachineDC19C52A
Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Value is not a Reference Path: Reference path didn't start with '$' at /States/Enable_Termination_Protection/ResultPath, SCHEMA_VALIDATION_FAILED:
 Value is not a Reference Path: Reference path didn't start with '$' at /States/Disable_Termination_Protection/ResultPath' 
(Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 7ce1216a-0f91-4577-a5ce-f2a47071fe82; Proxy: null)
```

**Comment by cwensel** [comment]
I'm seeing the same behavior if I pull in a custom state machine json (rendered by SAM). 

The node tree passed to `CfnStateMachine.definition` does have a property with a null value, it just never makes it back out.

**Comment by jungle-gecko** [comment]
Same issue on following environment:
    CDK Version: 2.28.0 (build ba233f0)
    Python Version: v3.7.10
    OS : Amazon Linux 2

Looks like this issue in SFN Data Science SDK: https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/45

**Comment by jonathan5p** [comment]
Any updates on this issue?

**Comment by ANHPearce** [comment]
Bump

Not seeing any progress on this in 3 years and still having the issue. Also not seeing a lot of updates for Step Functions in general in CDK. 

You guys still working on this at all or should I be looking for a different deployment tool for my workflows?

**Comment by mrgrain** [comment]
@ANHPearce Can you post your code that is not working? Both using `null` and `JsonPath.DISCARD` works for me.
I think this was fixed in https://github.com/aws/aws-cdk/pull/24593

```ts
import * as cdk from 'aws-cdk-lib/core';
import * as sfn from 'aws-cdk-lib/aws-stepfunctions';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'StepFunctionsNullStack', {
  env: { region: 'eu-west-1' }
});

const customA = new sfn.CustomState(stack, "JsonPath.DISCARD", {
  stateJson: {
    Type: "Task",
    Resource:
      "arn:aws:states:::elasticmapreduce:setClusterTerminationProtection",
    Parameters: {
      "ClusterId.$": "$.ClusterId",
      TerminationProtected: true,
    },
    ResultPath: sfn.JsonPath.DISCARD,
    Next: "rollup",
  },
});
const customB = new sfn.CustomState(stack, "null", {
  stateJson: {
    Type: "Task",
    Resource:
      "arn:aws:states:::elasticmapreduce:setClusterTerminationProtection",
    Parameters: {
      "ClusterId.$": "$.ClusterId",
      TerminationProtected: true,
    },
    ResultPath: null,
    Next: "rollup",
  },
});

new sfn.StateMachine(stack, "StateMachine", {
  definition: sfn.Chain.start(customA).next(customB),
});
```

```yaml
StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: '{"StartAt":"JsonPath.DISCARD","States":{"JsonPath.DISCARD":{"Next":"rollup","Type":"Task","Resource":"arn:aws:states:::elasticmapreduce:setClusterTerminationProtection","Parameters":{"ClusterId.$":"$.ClusterId","TerminationProtected":true},"ResultPath":null},"null":{"End":true,"Type":"Task","Resource":"arn:aws:states:::elasticmapreduce:setClusterTerminationProtection","Parameters":{"ClusterId.$":"$.ClusterId","TerminationProtected":true},"ResultPath":null,"Next":"rollup"}}}'
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
    DependsOn:
      - StateMachineRoleB840431D
```
