### ISSUE TITLE
[EC2] make GenericMachineImage use CfnMapping in an agnostic stack

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#8759]
CDK demands AWS Region to be known at synth time when resolving IMachineImage for the EC2 Instance class, seemingly making it impossible to create a region-agnostic stack for launching an EC2 instance, while it's perfectly possible to defer region resolution in plain vanilla CFN to the run/deploy time.

### Use Case

I need a stack that can launch an EC2 in any region. CFN allows to do that via a Mapping that maps AMI Id to a region.

Consider this CFN snippet:
```yaml
Mappings:
  RegionMap:
    us-east-1: 
      AmiId: ami-XXXXXXXXXXX
    us-west-2: 
      AmiId: ami-YYYYYYYYYYY
...

Resources:
  ...
  InstanceMachine:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3a.large
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AmiId
```

This shows how specifying instance AMI Id can be made  region-agnostic.

When attempting to do this in CDK:
```cs
IMachineImage windowsAmi = MachineImage.GenericWindows(
    new Dictionary<string, string>
    { 
        ["us-east-1"] = "ami-XXXXXXXXXXX",
        ["eu-west-2"] = "ami-YYYYYYYYYYYY",
    }
);

var ec2Instance = new Instance_(this, "Instance", new InstanceProps {
    Vpc = vpc,
    InstanceType = InstanceType.Of(InstanceClass.BURSTABLE3_AMD, InstanceSize.XLARGE),
    MachineImage = windowsAmi,
    SecurityGroup = mySecurityGroup
});
```
... I am getting "Amazon.JSII.Runtime.JsiiException: Unable to determine AMI from AMI map since stack is region-agnostic" error.

### Proposed Solution

Instead of throwing an exception when AWS region is not specified at synth time, use region-AMI dictionary that CDK already requires to generate CFN Mapping, outputting the Mapping into generated template, so that whatever the Aws.REGION is at run time, that region value could be used.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
