### ISSUE TITLE
[glue] glue.CfnTriggeractions is empty

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-cdk#8797]
### The Question
I'm creating Glue job (worked well) and was adding job trigger but can't figure out how actions are populated

```
        glueTrigger = glue.CfnTrigger(
            self,
            'trigger',
            description='Trigger to execute job',
            type = 'ON_DEMAND',
            name = 'test',
            actions = [
                { 'JobName': "test" ,
                { 'JobName': "test1" }
            ],
            start_on_creation = False
        )
```

makes a resource with empty Actions

```
  trigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - {}
        - {}
      Type: ON_DEMAND
      Description: Trigger to execute job
      Name: test
      StartOnCreation: false
```

### Environment

  - **CDK CLI Version:** 1.47.0 (build c2b499a)
  - **Module Version:** aws-cdk.aws-glue 1.47.0
  - **Node.js Version:** v12.18.0
  - **OS:**  OSX Mojave
  - **Language (Version):**  python 3.7.0
