### ISSUE TITLE
[aws-rds] Incorrect output of the Engine version in OptionGroup

### ISSUE THREAD

**Issue by cp-k1nakayama** [aws/aws-cdk#9171]
If you specify a SQLServer engine when defining an OptionGroup, the MajorEngineVersion is not correct.

### Reproduction Steps

When you define an OptionGroup as shown below, the code output to CloudFormation will look like this

cdk code:
```python
        option_group = rds.OptionGroup(self, "OptionGroup",
                                       configurations=[
                                           rds.OptionConfiguration(
                                               name="SQLSERVER_BACKUP_RESTORE",
                                               settings={
                                                   "IAM_ROLE_ARN": backup_restore_role.role_arn
                                               }
                                           )
                                       ],
                                       engine=rds.DatabaseInstanceEngine.sql_server_web(
                                           version=rds.SqlServerEngineVersion.VER_11)
                                       )
```

output cloudformation:

```
  OptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: sqlserver-web
      MajorEngineVersion: "11.0"
      OptionConfigurations:
        - OptionName: SQLSERVER_BACKUP_RESTORE
          OptionSettings:
            - Name: IAM_ROLE_ARN
              Value:
                Fn::GetAtt:
                  - MSSqlServerBuckupRoleF4E03AFB
                  - Arn
```

As shown above, MajorEngineVersion is output as `11.0`, but the correct version is `11.00`.

### Error Log

When running a deployment in its current state, CloudFromation generates an error `Cannot find major version 11.0 for sqlserver-web`.

### Environment

  - **CLI Version      : aws-cli/2.0.12 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev16
  - **Framework Version: 1.53.0 (build 6c326cb)
  - **Node.js Version: v12.12.0
  - **OS               : MacOS 10.15.5
  - **Language (Version): Python (3.7.6)

--- 

This is :bug: Bug Report
