### ISSUE TITLE
[aws-events] concatenating event fields should produce an error

### ISSUE THREAD

**Issue by rirze** [aws/aws-cdk#9191]
Creating an input transformer for a Cloudwatch Rule results in questionable syntax in the Cloudformation output causing the stack to unsuccessfully deploy.

### Reproduction Steps

```python3
from aws_cdk import core
from aws_cdk import aws_events
from aws_cdk import aws_events_targets
from aws_cdk import aws_sns


class Scheduling(core.Construct):
    def __init__(self, scope: core.Construct, id: str):
        super().__init__(scope, id)

        topic = aws_sns.Topic(self, 'dummy_sns_topic')

        aws_events.Rule(self, 'test_rule',
                        description='test_rule',
                        schedule=aws_events.Schedule.rate(core.Duration.minutes(5)),
                        targets=[
                            aws_events_targets.SnsTopic(topic, message=aws_events.RuleTargetInput.from_object(
                                {
                                    'name': 'testing_at_' + aws_events.EventField.from_path('$.time')
                                }
                            ))
                        ])


class CdkTestRuleStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        Scheduling(self, 'test_rule')
```
This results in CFN output where I've trimmed some of the irrelevant parts:
```yaml
Resources:
  testruleB258B0E0:
    Type: AWS::Events::Rule
    Properties:
      Description: test_rule
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn:
            Ref: testruledummysnstopic5D840FE8
          Id: Target0
          InputTransformer:
            InputPathsMap:
              time: $.time
            InputTemplate: '{"name":"testing_at_<<${time>}'
    Metadata:
      aws:cdk:path: cdk-test-rule/test_rule/test_rule/Resource

```
I'm expecting ` InputTemplate: '{"name":"testing_at_<time>}'`. My question is, am I building this correctly or is this a bug?

### Error Log

```
11:46:48 AM | CREATE_FAILED        | AWS::Events::Rule     | testruleB258B0E0
Invalid InputTemplate for target Target0 : [Source: (String)"{"name":"testing_at_<<${time>}"; line: 1, column: 61]. (
Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: b09abd15-ff6b-4006-93
63-55b950ebf41d)

        new Rule (/tmp/jsii-kernel-R4yAYC/node_modules/@aws-cdk/aws-events/lib/rule.js:25:26)
        \_ ~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7836:49
        \_ Kernel._wrapSandboxCode (~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.
js:8296
:20)
        \_ Kernel._create (~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7836:2
6)
        \_ Kernel.create (~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7583:21
)
        \_ KernelHost.processRequest (~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtim
e.js:73
71:28)
        \_ KernelHost.run (~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7311:1
4)
        \_ Immediate._onImmediate (~/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.j
s:7314:
37)
        \_ processImmediate (internal/timers.js:456:21)


 ❌  cdk-test-rule failed: Error: The stack named cdk-test-rule failed creation, it may need to be manually deleted fr
om the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStack (~/.npm-packages/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:264:11
)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (~/.npm-packages/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:267:26)
    at CdkToolkit.deploy (~/.npm-packages/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (~/.npm-packages/lib/node_modules/aws-cdk/bin/cdk.ts:264:16)
    at initCommandLine (~/.npm-packages/lib/node_modules/aws-cdk/bin/cdk.ts:185:9)
The stack named cdk-test-rule failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

### Environment

  - **CLI Version      : 1.51.0 (build 8c2d53c)**
  - **Framework Version: 1.51.0**
  - **Node.js Version: v13.14.0** 
  - **OS               : Ubuntu 20.04 (WSL)**
  - **Language (Version): Python 3.7** 

### Other

--- 

This is :bug: Bug Report
