### ISSUE TITLE
[elasticloadbalancingv2] Support References or CfnParameters in priority

### ISSUE THREAD

**Issue by rachedanis** [aws/aws-cdk#9296]
It would be great to be able to set the value of the priority dynamically using a Reference : 
```
ApplicationListenerRule.Builder.create(stack, "ApplicationListenerRule")
                                .priority(token) // token.getValueAsNumber() does't work 
                                                 // since it generates a random number ( out of [0,50000] ) at synthesize stage
                                .build();
```

- Actually I want to deploy the same ressoures defined in a stack in new stacks by setting the generated template in the service catalog ( there is a CFN parameter that will be used for the path but it's not important ).
  Theses stacks uses the same ALB ( of another Stack ), and creates a new ALB Rule for the new ressources.

  I'm trying to recode this with CDK/java ( assuming I have a Lambda that generates the priority ) but it's seems to be impossible

```
AllocateAlbRulePriorityCustomResource:
    Type: Custom::AllocateAlbRulePriority
    [...]

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Priority: !GetAtt AllocateAlbRulePriorityCustomResource.Priority
      [...]
```

- Another use case is to set that priority as a `CfnParameter`, but when we call `getValueAsNumber()` it will generate a random number probably out of the allowed ranges.

### Proposed solution

- Add a new `priority` setter accepting Reference as argument.
- or/and Remove the check on priorityValue.

I vote for option 1.

---

This is a :rocket: Feature Request
