### ISSUE TITLE
[aws-s3-deployment] Broken permissions

### ISSUE THREAD

**Issue by Goldabj** [aws/aws-cdk#9298]
Lately my S3 bucket deployments have been failing due to `GetObject: Access Denied`. 

I believe this commit: 
https://github.com/aws/aws-cdk/commit/b2006c3efc4eab6a9b5d984a148586eb9fa7b410#diff-85982f660b9fcd1e9212d53d05253681

removed this line of code: 
https://github.com/aws/aws-cdk/commit/b2006c3efc4eab6a9b5d984a148586eb9fa7b410#diff-85982f660b9fcd1e9212d53d05253681L178

Now the custom lambda resource does not have permissions to read from my source bucket. 

### Reproduction Steps

```
const bucketDeploymentRole = new Role(scope, 'BucketDeploymentRole', {
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')]
    });

const uiDeployment = new BukcetDeployment(this, 'BucketDeployment', {
         sources: [Source.asset('build/website-ui.zip')],
         destinationBucket: uiAssetsBucket,
         distribution: cloudFrontDistribution,
         role: bucketDeploymentRole
      });
```

### Error Log

```
download failed: s3://deploymentbucket-4ce6b63f3f28bd9ad4d733dd2a4c7abb1028750b/pipelines_aggregate_transform_2246772/65bbbff2-ba4b-40b6-8e61-2cfc2ca44584_transform/cdk.out/asset.03674881224dfa30c00e6c63cd74f829d409d24a6cd78d51566c90ff2c2b28cf.zip to ../../tmp/tmp2a7zndrk/82d7a156-295b-4240-b327-85873c473829 An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

### Environment

  - **CLI Version**: 1.32.2
  - **Framework Version:**
  - **Node.js Version:** node-v12.18.2
  - **OS:** MacOS (darwin-x64)   
  - **Language (Version):** All (Typescript)

### Other

--- 

This is :bug: Bug Report

**Comment by voteblake** [comment]
Hi @Goldabj I ran in to this same issue today, but I see you closed this. Were you able to find a way forward? I'm also on CDK 1.32.2.

**Comment by Goldabj** [comment]
I can't exactly remember how I got rid of the issue, but I know it was a mistake on my end. I think I had manually deleted the S3 bucket from that account. I realized that Cloudformation operates based off change sets (what was in my CF template vs whats there now), instead of what the state of the resources in the account. So the CDK/CF wasn't recreating my S3 bucket. 

I just deleted the CF stack, then redeployed it.

**Comment by RafalWilinski** [comment]
I fixed that by adding `"@aws-cdk/core:newStyleStackSynthesis": true` to the `context` object in `cdk.json`.

**Comment by Goldabj** [comment]
My teammate is now running into this issue. (I was somehow able to resolve it). Looking at the diff in the CDK outputs we have, I have

```
BucketDeploymentRoleDefaultPolicyDC93C195:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: kms:Decrypt
            Effect: Allow
            Resource: arn:aws:kms:us-east-1:45570513164:key/*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::deploymentbucket-2343232432432
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::deploymentbucket-2343232432432/*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - FrontendUIAssetsBucketDABD6B9A
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - FrontendUIAssetsBucketDABD6B9A
                        - Arn
                    - /*
          - Action:
              - cloudfront:GetInvalidation
              - cloudfront:CreateInvalidation
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: BucketDeploymentRoleDefaultPolicyDC93C195
      Roles:
        - Ref: BucketDeploymentRoleB7087459
    Metadata:
      aws:cdk:path: FrontendUIStack-alpha-na/BucketDeploymentRole/DefaultPolicy/Resource
```

and he only has: 
```
BucketDeploymentRoleDefaultPolicyDC93C195:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: kms:Decrypt
            Effect: Allow
            Resource: arn:aws:kms:us-east-1:45570513164:key/*
        Version: "2012-10-17"
      PolicyName: BucketDeploymentRoleDefaultPolicyDC93C195
      Roles:
        - Ref: BucketDeploymentRoleB7087459
    Metadata:
      aws:cdk:path: FrontendUIStack-alpha-na/BucketDeploymentRole/DefaultPolicy/Resource
```

We are both on version 1.32.2, but didn't get to see his version in package-lock.json. He was able to get it to work eventually too after cleaning his node_modules folder.  So it looks like this may have been a bug in one of the releases of 1.3.2, but I think its fixed now?
