### ISSUE TITLE
[lambda] Is there any way to influence the parameter names synthesized for lambda assets? 

### ISSUE THREAD

**Issue by lestephane** [aws/aws-cdk#9425]
I have a strict requirement to keep our CICD pipeline free from nodejs, and to keep our templates in YAML format.

So what I do is call cdk synth, then convert the JSON templates into YAML templates, and I'm generally happy with the way the templates look.

However, the moment I start using lambda functions with Assets, the stack contains dynamically generated parameters (example below) that are very long, and which we'd have to search and replace to use our own predictable parameters names (after our pipeline has uploaded the assets, again, without CDK / cdk-assets / nodejs magic).

```yml
Parameters:
  AssetParameters8bf0b56607b5f99daaaa45896dcab8bc2b1b2287ed5ab9e36f9a8288ea85bfd7S3BucketEEABE56C:
    Type: String
    Description: S3 bucket for asset "8bf0b56607b5f99daaaa45896dcab8bc2b1b2287ed5ab9e36f9a8288ea85bfd7"
  AssetParameters8bf0b56607b5f99daaaa45896dcab8bc2b1b2287ed5ab9e36f9a8288ea85bfd7S3VersionKey82E46BBD:
    Type: String
    Description: S3 key for asset version "8bf0b56607b5f99daaaa45896dcab8bc2b1b2287ed5ab9e36f9a8288ea85bfd7"
  AssetParameters8bf0b56607b5f99daaaa45896dcab8bc2b1b2287ed5ab9e36f9a8288ea85bfd7ArtifactHash6236DCB4:
    Type: String
    Description: Artifact hash for asset "8bf0b56607b5f99daaaa45896dcab8bc2b1b2287ed5ab9e36f9a8288ea85bfd7"
```

Am I going about this the wrong way? I really cannot use CDK anywhere in the pipeline, but the devs love CDK for day to day work. The synth of the YML template would be the responsibility of the developers as part of their workflow. But if there is no way to influence these naming decisions, we may need to reassess. What I need is to understand if I can influence this naming scheme for lambda assets...

Any advice appreciated.
