### ISSUE TITLE
[aws-ec2] Unable to delete Ingress rule

### ISSUE THREAD

**Issue by wonjoonSeol** [aws/aws-cdk#9512]
Unable to remove created Ingress rules.

### Reproduction Steps

```
    class SecurityManager(Stack):
        def __init__(self, scope: Construct, id: str, **kwargs) -> None:
            super().__init__(scope, id, **kwargs)
            sg = SecurityGroup.from_security_group_id(
                self,
                id="security",
                security_group_id='ALREADY CREATED SECURITY GROUP ID',
                mutable=True,
            )
    
            sg.add_ingress_rule(
                Peer.ipv4('52.144.227.192/26'), Port.tcp(443), "THIS ADDS INBOUND RULE"
            )
```
Change the IPv4 52.144.227.192/26 to 52.219.60.0/23 and re-run `cdk deploy`

The terminal shows:
```
Security Group Changes
┌───┬──────────────────────┬─────┬──────────┬───────────────────┐
│   │ Group                │ Dir │ Protocol │ Peer              │
├───┼──────────────────────┼─────┼──────────┼───────────────────┤
│ - │ sg-12313213123123123 │ In  │ TCP 443  │ 52.144.227.192/26 │
├───┼──────────────────────┼─────┼──────────┼───────────────────┤
│ + │ sg-12313213123123123 │ In  │ TCP 443  │ 52.219.60.0/23    │
└───┴──────────────────────┴─────┴──────────┴───────────────────┘
```

However the IP ingress rule for 52.144.227.192/26 is not destroyed. 
It can be seen at the AWS console.

![Screenshot 2020-08-07 at 10 31 34 PM](https://user-images.githubusercontent.com/22602022/89650702-cadc9280-d8fd-11ea-8501-6cd14b52b2b5.png)
Both of them exist.

Destroying the stack SecurityManager does not remove the IP ingress rule neither.

### What did you expect to happen?

IP ingress rule for 52.144.227.192/26 should have been destroyed.

I was trying to add ingress rule to the existing security group that dev ops have created, and added Ingress rule to allow certain IP for an EC2 instance. 

The addition works fine, but the deletion does not work. As can be seen from above.

### What actually happened?

The old rule that should have been destroyed still exists.

### Environment

  - **CLI Version:**      : aws-cli/2.0.17 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev21
  - **Framework Version:** 1.56.0 (build c1c174d)
  - **Node.js Version:** v14.7.0
  - **OS:**               OSX Catalina 10.15.5
  - **Language (Version):** Python/3.7.4

--- 

This is :bug: Bug Report

**Comment by wonjoonSeol** [comment]
Hmm this is bizaare, I just created a new account and tried the above code, and it seems to delete fine.
But it doesn't work for my company's account - any reason why it may fail to delete. I wonder if it has to do with the owner of the security group? But there is no error message for failing to delete the security group.

![Screenshot 2020-08-09 at 1 16 09 AM](https://user-images.githubusercontent.com/22602022/89715054-e919bf80-d9dd-11ea-9676-1c73fe665a7c.png)

**Comment by wonjoonSeol** [comment]
CloudFormation logs:
![image](https://user-images.githubusercontent.com/22602022/89725338-6fb7b680-da49-11ea-94d1-36be45a85d71.png)

Template, After changing IP from  '52.144.227.192/26' to '52.219.60.0/23'.
But both IPs exists.

```
Resources:
  securityfrom{ID}:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 52.219.60.0/23
      Description: THIS ADDS INBOUND RULE
      FromPort: 443
      GroupId: {Security group ID}
      ToPort: 443
    Metadata:
      aws:cdk:path: cdk-playground/security/from 52.219.60.0_23:443
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.56.0,@aws-cdk/aws-cloudwatch=1.57.0,@aws-cdk/aws-ec2=1.57.0,@aws-cdk/aws-events=1.57.0,@aws-cdk/aws-iam=1.57.0,@aws-cdk/aws-kms=1.57.0,@aws-cdk/aws-logs=1.57.0,@aws-cdk/aws-s3=1.57.0,@aws-cdk/aws-ssm=1.57.0,@aws-cdk/cloud-assembly-schema=1.57.0,@aws-cdk/core=1.57.0,@aws-cdk/cx-api=1.57.0,@aws-cdk/region-info=1.57.0,jsii-runtime=Python/3.8.5
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```
