### ISSUE TITLE
[aws-kms] Key construct injects undesired root policy statement

### ISSUE THREAD

**Issue by Wenzil** [aws/aws-cdk#9618]
When creating a KMS Key with `trustAccountIdentities` set to false, CDK injects the following policy statement in the key policy.

```
Action:
    - kms:Create*
    - kms:Describe*
    - kms:Enable*
    - kms:List*
    - kms:Put*
    - kms:Update*
    - kms:Revoke*
    - kms:Disable*
    - kms:Get*
    - kms:Delete*
    - kms:ScheduleKeyDeletion
    - kms:CancelKeyDeletion
    - kms:GenerateDataKey
    - kms:TagResource
    - kms:UntagResource
Effect: Allow
Principal:
    AWS:
    Fn::Join:
        - ""
        - - "arn:"
        - Ref: AWS::Partition
        - :iam::${AWS::AccountId}:root
Resource: "*"
```

This is surprising because the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-kms.Key.html#trustaccountidentities) only mentions adding a similar statement when trustAccountIdentities is set to true.

### Reproduction Steps

```
new kms.Key(this, 'MyKey', {
    description: 'My Key',
    alias: 'MyKey',
    enableKeyRotation: true,
    enabled: true,
    policy: new iam.PolicyDocument({
        assignSids: true,
        trustAccountIdentities: false,
        statements: [
            new iam.PolicyStatement({
                actions: [
                    'kms:Encrypt',
                    'kms:Decrypt',
                    'kms:ReEncrypt*',
                    'kms:GenerateDataKey*',
                    'kms:DescribeKey',
                ],
                principals: [
                    new iam.ServicePrincipal('logs.amazonaws.com')
                ],
                resources: ['*'],
                effect: iam.Effect.ALLOW,
            }),
        ],
    }),
    removalPolicy: cdk.RemovalPolicy.DESTROY,
});
```

### What did you expect to happen?

I would expect the above key construct to generate no policy statement for the root principal, since none has been specified and `trustAccountIdentities` is `false`.

I understand this would make the key unmanageable, but that's fine as I would I supply my own policy statement (not shown).

### What actually happened?

CDK injected the above policy statement.

### Environment

  - **CLI Version      :** 1.54.0
  - **Framework Version:** 1.54.0
  - **Node.js Version:** 12.4.0
  - **OS               :** macOS Catalina
  - **Language (Version):** TypeScript (3.9.7)

This is :bug: Bug Report
