### ISSUE TITLE
[aws-kinesisanalytics] Duplicate tag key error after first successful deployment

### ISSUE THREAD

**Issue by moehlone** [aws/aws-cdk#9652]
When I tag a Kinesis Analytics Application (v2), the first deployment is successful with the tags set correctly. All subsequent deployments result in the error "The provided tag map contains duplicate tag key".

### Reproduction Steps

Implement a stack and inside the constructor do the following (no tags are passed):

```typescript
   import * as kda from "@aws-cdk/aws-kinesisanalytics";

    ...

    new kda.CfnApplicationV2(
      this,
      "MyKdaApp",
      {
        applicationName: "FancyAppName",
        runtimeEnvironment: "FLINK-1_8",
        serviceExecutionRole: kdaExecutionRoleArn,
        applicationConfiguration: {
          flinkApplicationConfiguration: {
            checkpointConfiguration: {
              configurationType: "CUSTOM",
              checkpointingEnabled: false,
              checkpointInterval: 60000,
              minPauseBetweenCheckpoints: 5000,
            },
            parallelismConfiguration: {
              configurationType: "CUSTOM",
              parallelism: 1,
              parallelismPerKpu: 1,
              autoScalingEnabled: false,
            },
          },
          applicationCodeConfiguration: {
            codeContentType: "ZIPFILE",
            codeContent: {
              s3ContentLocation: {
                bucketArn: artifactBucketArn,
                fileKey: artifactFileName,
              },
            },
          },
          applicationSnapshotConfiguration: {
            snapshotsEnabled: false,
          },
          environmentProperties: {
            propertyGroups,
          },
        },
      }
    );
```

In your app, create an instance and use the following:

```typescript
Tag.add(theStackInstance, "service", "foo");
Tag.add(theStackInstance, "appName", "bar");
```

Run `cdk deploy -a 'npx ts-node bin/app.ts'`

### What did you expect to happen?

Deploying a KinesisDataAnalyticsV2 instance that is tagged with `service: "foo"` and `appName: "bar"`. Subsequent deployments behave the same.

### What actually happened?

The first time I deploy this stack, everything works fine. Any subsequent deployment results always with the error "The provided tag map contains duplicate tag key". I must delete the stack to deploy any updates.

### Environment

  - **CLI Version      : 1.57.0**
  - **Framework Version: 1.57.0**
  - **Node.js Version: v14.7.0** 
  - **OS               : linux**
  - **Language (Version): TypeScript (3.9.7)** 

### Other

> Any sensitive information blacked out with `***`

Resulting stacktrace:

```
9:33:10 PM | UPDATE_FAILED        | AWS::KinesisAnalyticsV2::Application | ***
The provided tag map contains duplicate tag key

        new KinesisStack (/***/aws/lib/kinesisStack.ts:34:21)
        \_ /***/aws/bin/app.ts:85:24
        \_ processTicksAndRejections (internal/process/task_queues.js:93:5)


 ❌  *** failed: Error: The stack named *** failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/***/aws-cdk/1.57.0/libexec/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:294:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/***/aws-cdk/1.57.0/libexec/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:266:26)
    at CdkToolkit.deploy (/***/aws-cdk/1.57.0/libexec/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/***/aws-cdk/1.57.0/libexec/lib/node_modules/aws-cdk/bin/cdk.ts:268:16)
    at initCommandLine (/***/aws-cdk/1.57.0/libexec/lib/node_modules/aws-cdk/bin/cdk.ts:188:9)
The stack named *** failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

The synthesized template looks good to me (also no problems on further creations):

```yaml
Resources:
  ***KinesisDataAnalyticsAppV2:
    Type: AWS::KinesisAnalyticsV2::Application
    Properties:
      RuntimeEnvironment: FLINK-1_8
      ServiceExecutionRole: ***
      ApplicationConfiguration:
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: ***
              FileKey: ***
          CodeContentType: ZIPFILE
        ApplicationSnapshotConfiguration:
          SnapshotsEnabled: false
        EnvironmentProperties:
          PropertyGroups:
            ***
        FlinkApplicationConfiguration:
          CheckpointConfiguration:
            CheckpointInterval: 60000
            CheckpointingEnabled: false
            ConfigurationType: CUSTOM
            MinPauseBetweenCheckpoints: 5000
          ParallelismConfiguration:
            AutoScalingEnabled: false
            ConfigurationType: CUSTOM
            Parallelism: 1
            ParallelismPerKPU: 1
      ApplicationName: FancyAppName
      Tags:
        - Key: appName
          Value: bar
        - Key: service
          Value: foo
    Metadata:
      ***
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.57.0,@aws-cdk/aws-cloudwatch=1.57.0,@aws-cdk/aws-events=1.57.0,@aws-cdk/aws-iam=1.57.0,@aws-cdk/aws-kinesisanalytics=1.57.0,@aws-cdk/aws-kms=1.57.0,@aws-cdk/aws-logs=1.57.0,@aws-cdk/aws-msk=1.57.0,@aws-cdk/aws-s3=1.57.0,@aws-cdk/cloud-assembly-schema=1.57.0,@aws-cdk/core=1.57.0,@aws-cdk/cx-api=1.57.0,@aws-cdk/region-info=1.57.0,jsii-runtime=node.js/v14.7.0
```

I also tried passing the tags to the stack properties and even passed an empty tag array - same outcome.

--- 

This is :bug: Bug Report
