### ISSUE TITLE
[Core] Cross-stack attribute reference ignores cdk.fn

### ISSUE THREAD

**Issue by Project0** [aws/aws-cdk#9965]
When wiring up attributes between two stacks it usually creates a output export in one of the stacks and imports that in the other stack. However, if the referenced values is an token generated with cdk.fn.sub or cdk.fn.join it exports the underlying reference value instead of the prepared.

When creating a cfnOutput manually it works as expected.

### Reproduction Steps

```ts
// example resource
export class ElasticSearch extends cdk.Resource {
  public readonly domainEndpoint: string

  constructor(app: cdk.Construct, id: string, props: ServiceProps) {
    super(app, id)
    const domain = new es.CfnDomain(this, 'Resource', {})
    this.domainEndpoint = cdk.Fn.sub('https://${domain}', {
      domain: domain.attrDomainEndpoint,
    }) 
  }
}
```
Within the same stack it uses properly the substitution function. 

Referenced in a another stack it generates the following:
```yaml
#origin stack
  ExportsOutputFnGetAttElasticSearch3A9784B3DomainEndpoint15DC0619:
    Value:
      Fn::GetAtt:
        - ElasticSearch3A9784B3
        - DomainEndpoint
    Export:
      Name: service-catalog-cdk-es-importer-test:ExportsOutputFnGetAttElasticSearch3A9784B3DomainEndpoint15DC0619
```

### What did you expect to happen?

Export the value as it was provided with fn:sub. 

```yaml
#origin stack
  ExportsOutputFnGetAttElasticSearch3A9784B3DomainEndpoint15DC0619:
    Value:
      Fn::Sub:
        - https
        - domain:
            Fn::GetAtt:
              - ElasticSearch3A9784B3
              - DomainEndpoint
    Export:
      Name: service-catalog-cdk-es-importer-test:ExportsOutputFnGetAttElasticSearch3A9784B3DomainEndpoint15DC0619
```

### Environment

CDK version 1.60

--- 

This is :bug: Bug Report
