### ISSUE TITLE
[core] overriding availability_zones method in python seems no effect

### ISSUE THREAD

**Issue by SimonLau413** [aws/aws-cdk#9997]
Overriding the `availability_zones` method has no effect in Python

### Reproduction Steps
```
from aws_cdk import (
    aws_ec2 as ec2,
    core,
)
import typing

class TestStack(core.Stack):

    def availability_zones(self) -> typing.List[str]:
        return ["ap-east-1b", "ap-east-1c"]

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # The code that defines your stack goes here
        vpc = ec2.Vpc(
            self, "TestVpc",
            max_azs=2,
            cidr="10.0.0.0/16",
        )
```
### What did you expect to happen?
Run `cdk synth` should produce results that the subnets are in the specified availability zones.

### What actually happened?
Just part of the result
```
Resources:
  TestVpcE77CE678:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: TestStack/TestVpc
    Metadata:
      aws:cdk:path: TestStack/TestVpc/Resource
  TestVpcPublicSubnet1SubnetA7DB1EDF:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/18
      VpcId:
        Ref: TestVpcE77CE678
      AvailabilityZone: ap-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: TestStack/TestVpc/PublicSubnet1
    Metadata:
      aws:cdk:path: TestStack/TestVpc/PublicSubnet1/Subnet
```
### Environment

  - **CLI Version      :** 1.60 (build 8e3f53a)
  - **Framework Version:** 1.60
  - **Node.js Version:** v14.8.0
  - **OS               :** OSX 10.15.5
  - **Language (Version):** Python 3.8.5

--- 

This is :bug: Bug Report
